// Generated by tools/buildVirtualSources.js from src/simulation/flightPhysics/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { AIRCRAFT_GROUND_OFFSET } from '../data/worldData.js?v=202605070100';
import {
  A320NEO_CONFIG,
  DEG_TO_RAD,
  FT_PER_M,
  GRAVITY,
  KT_TO_MS,
  MS_TO_KT,
  airDensityForAltitude,
  clamp,
  flapConfigAt,
  ktToMS,
  moveToward,
  smoothstep,
  thrustFromN1,
  vlsForFlapPosition,
  vmaxForConfig
} from './aircraftConfig.js?v=202605061100';

const NORMAL_LAW = 'NORMAL_LAW';
const STALL_TRAINING = 'STALL_TRAINING';
const CONTROL_KEYS = ['KeyW', 'KeyA', 'KeyS', 'KeyD'];
const HOLD_SENSITIVITY_DELAY = 0.35;
const PITCH_HOLD_SENSITIVITY_RAMP_TIME = 1.8;
const TURN_HOLD_SENSITIVITY_RAMP_TIME = 2.15;
const MAX_PITCH_HOLD_SENSITIVITY = 1.34;
const MAX_TURN_HOLD_SENSITIVITY = 1.72;
const NORMAL_PITCH_LIMIT_UP = 30 * DEG_TO_RAD;
const NORMAL_PITCH_LIMIT_DOWN = -15 * DEG_TO_RAD;
const TRAINING_PITCH_LIMIT_UP = 42 * DEG_TO_RAD;
const TRAINING_PITCH_LIMIT_DOWN = -32 * DEG_TO_RAD;
const MAX_ROLL_NORMAL = 67 * DEG_TO_RAD;
const BANK_SOFT_LIMIT = 33 * DEG_TO_RAD;
const DEFAULT_GROUND_TRAVEL_SCALE = 1.4;
const DEFAULT_AIR_TRAVEL_SCALE = 1.5;
const MAX_WORLD_TRAVEL_SCALE = 1.8;
const Y_AXIS = new THREE.Vector3(0, 1, 0);
const Z_AXIS = new THREE.Vector3(0, 0, 1);

export function createFlightPhysics({ keys, state, forwardVec, terrainHeight, smoothstep: externalSmoothstep }) {
  const config = A320NEO_CONFIG;
  const massKg = clamp(Number(state.aircraftMassKg) || config.mass.defaultKg, config.mass.minKg, config.mass.maxKg);
  const keyHoldTimes = new Map();
  const previousKeys = new Set();
  const physicsVelocity = state.physicsVelocity?.isVector3 ? state.physicsVelocity : new THREE.Vector3();
  const worldVelocity = state.worldVelocity?.isVector3 ? state.worldVelocity : new THREE.Vector3();
  const attitudeForward = new THREE.Vector3();
  const bodyUpDirection = new THREE.Vector3();
  const velocityDirection = new THREE.Vector3();
  const liftDirection = new THREE.Vector3();
  const lateralAcceleration = new THREE.Vector3();
  const groundForward = new THREE.Vector3();
  const mechanisms = { collected: false, flaps: [], spoilers: [], gears: [] };
  let pitchRate = 0;
  let rollRate = 0;
  let smoothedPitchInput = 0;
  let flightPathPitch = 0;
  let stallFactor = state.stallFactor || 0;

  initAircraftState();

  function updateAircraft(dt, model) {
    const safeDt = clamp(dt, 0.001, 0.08);
    const wasGrounded = state.grounded === true;
    const radioAltFt = radioAltitudeFeet();
    const currentIAS = Math.max(0, Math.abs(state.currentIAS || state.speed * MS_TO_KT || 0));
    const brakeKeyPriority = wasGrounded && state.mainGearCompressed !== false;

    handleDiscreteSystemKeys(currentIAS);
    updateKeyHoldTimes(safeDt, brakeKeyPriority ? new Set(['KeyW']) : null);
    updateBrakeInputAndPressure(safeDt, wasGrounded, currentIAS, brakeKeyPriority);
    updateFlaps(safeDt);
    updateGear(safeDt, currentIAS);
    updateSpeedBrake(safeDt, currentIAS);
    updateGroundSpoilers(safeDt, wasGrounded);
    updateAttitude(safeDt, wasGrounded, brakeKeyPriority, currentIAS);
    publishAttitudeDirections();
    ensurePhysicsVelocity(wasGrounded);

    velocityDirection.copy(physicsVelocity);
    if (velocityDirection.lengthSq() > 0.0001) velocityDirection.normalize();
    else velocityDirection.copy(attitudeForward);
    flightPathPitch = wasGrounded ? 0 : Math.asin(clamp(velocityDirection.y, -1, 1));
    const angleOfAttack = computeAngleOfAttack();
    updateProtectionsAndStall(safeDt, angleOfAttack, currentIAS, wasGrounded);

    const previousY = state.position.y;
    if (wasGrounded) updateGroundVelocity(safeDt, currentIAS, radioAltFt);
    else updateAirVelocity(safeDt, currentIAS, radioAltFt, angleOfAttack);

    updateWorldPosition(safeDt, wasGrounded);
    resolveGroundContact(safeDt);
    publishPhysicsVelocity();
    state.verticalSpeed = ((state.position.y - previousY) / safeDt) * 196.85;
    updateWarnings(currentIAS);
    updateModel(model, safeDt);
    publishPreviousKeys();
  }

  function initAircraftState() {
    state.aircraftConfig = config;
    state.aircraftType = config.aircraftType;
    state.aircraftMassKg = massKg;
    state.physicsVelocity = physicsVelocity;
    state.worldVelocity = worldVelocity;
    state.visualPosition = state.visualPosition?.isVector3 ? state.visualPosition : state.position.clone();
    state.groundTravelScale = Number.isFinite(state.groundTravelScale) ? state.groundTravelScale : DEFAULT_GROUND_TRAVEL_SCALE;
    state.airTravelScale = Number.isFinite(state.airTravelScale) ? state.airTravelScale : DEFAULT_AIR_TRAVEL_SCALE;
    state.maxTravelScale = Number.isFinite(state.maxTravelScale) ? state.maxTravelScale : MAX_WORLD_TRAVEL_SCALE;
    state.flapTargetIndex = Number.isFinite(state.flapTargetIndex) ? state.flapTargetIndex : (state.grounded ? 2 : 0);
    state.flapPositionIndex = Number.isFinite(state.flapPositionIndex) ? state.flapPositionIndex : state.flapTargetIndex;
    state.gearCommand = Number.isFinite(state.gearCommand) ? state.gearCommand : (state.grounded ? 1 : 0);
    state.gearPosition = Number.isFinite(state.gearPosition) ? state.gearPosition : state.gearCommand;
    state.speedBrakeCommand = Number.isFinite(state.speedBrakeCommand) ? state.speedBrakeCommand : 0;
    state.speedBrakePosition = Number.isFinite(state.speedBrakePosition) ? state.speedBrakePosition : 0;
    state.speedBrakeOpenTime = 0;
    state.groundSpoilersArmed = state.groundSpoilersArmed !== false;
    state.groundSpoilerPosition = Number.isFinite(state.groundSpoilerPosition) ? state.groundSpoilerPosition : 0;
    state.mainGearCompressed = state.grounded;
    state.reverseAllowed = state.grounded && state.mainGearCompressed;
    state.differentialBrakeYawEnabled = false;
    state.leftBrakePressure = state.leftBrakePressure || 0;
    state.rightBrakePressure = state.rightBrakePressure || 0;
    state.totalBrakePressure = state.totalBrakePressure || 0;
    state.v1Kts = config.performance.v1Kts;
    state.vrKts = config.performance.vrKts;
    state.v2Kts = config.performance.v2Kts;
    publishConfigSpeeds();
    publishPhysicsVelocity();
  }

  function handleDiscreteSystemKeys(currentIAS) {
    if (justPressed('KeyX')) {
      state.speedBrakeCommand = state.speedBrakeCommand > 0.5 ? 0 : 1;
      state.audioCue = state.speedBrakeCommand ? 'SPEED BRK' : 'SPEED BRK RETRACT';
    }
    if (justPressed('KeyG')) {
      if (currentIAS > config.gear.vloKts + 5) {
        state.systemWarning = 'GEAR SPEED';
        state.audioCue = 'GEAR SPEED';
      }
      state.gearCommand = state.gearCommand > 0.5 ? 0 : 1;
    }
    if (justPressed('KeyY')) {
      state.groundSpoilersArmed = !state.groundSpoilersArmed;
      state.audioCue = state.groundSpoilersArmed ? 'GND SPLR ARM' : 'GND SPLR OFF';
    }
    if (justPressed('KeyC') || justPressed('BracketRight')) {
      const currentTarget = clamp(Math.round(state.flapTargetIndex || 0), 0, config.flaps.length - 1);
      const nextTarget = Math.min(config.flaps.length - 1, currentTarget + 1);
      const limitForNext = config.flaps[currentTarget]?.vfeNextKts ?? config.flaps[nextTarget]?.vfeKts ?? null;
      if (nextTarget > currentTarget && Number.isFinite(limitForNext) && currentIAS > limitForNext) {
        state.flapWarning = 'TOO FAST FOR FLAPS';
        state.flapWarningTimer = 2.8;
        state.audioCue = 'TOO FAST FOR FLAPS';
      } else {
        state.flapTargetIndex = nextTarget;
        state.audioCue = nextTarget !== currentTarget ? 'FLAPS' : '';
      }
    }
    if (justPressed('KeyZ') || justPressed('BracketLeft')) {
      state.flapTargetIndex = Math.max(0, Math.round(state.flapTargetIndex || 0) - 1);
      state.audioCue = 'FLAPS';
    }
  }

  function updateFlaps(dt) {
    if (state.flapWarningTimer > 0) {
      state.flapWarningTimer = Math.max(0, state.flapWarningTimer - dt);
      if (state.flapWarningTimer <= 0) state.flapWarning = '';
    }
    const target = clamp(Math.round(state.flapTargetIndex || 0), 0, config.flaps.length - 1);
    const current = clamp(Number(state.flapPositionIndex) || 0, 0, config.flaps.length - 1);
    const direction = Math.sign(target - current);
    if (direction !== 0) {
      const fromIndex = direction > 0 ? Math.floor(current) : Math.ceil(current);
      const segment = config.flaps[clamp(fromIndex, 0, config.flaps.length - 1)];
      const seconds = Math.max(0.5, segment.moveSecondsToNext || 4);
      state.flapPositionIndex = moveToward(current, target, dt / seconds);
    } else {
      state.flapPositionIndex = target;
    }
    state.flapTargetIndex = target;
    const flap = flapConfigAt(state.flapPositionIndex);
    const targetConfig = config.flaps[target];
    state.flapConfig = flap;
    state.selectedFlapIndex = target;
    state.selectedFlapConfig = targetConfig.key;
    state.flapHandle = targetConfig.shortLabel;
    state.flapLabel = flap.label;
    state.flapVfeKts = flap.vfeKts;
    state.vfeNextKts = targetConfig.vfeNextKts;
    state.flapLiftMultiplier = flap.liftMultiplier;
    state.flapDragAdder = flap.dragAdder;
    state.flapPitchMoment = flap.pitchMoment;
    state.stallSpeedKts = flap.stallSpeedKts;
    state.flapStatusText = `FLAPS ${targetConfig.shortLabel}`;
    state.actualSlatPosition = clamp(flap.slats, 0, 1);
    state.actualFlapPosition = clamp(flap.flaps, 0, 1);
    state.highLiftMoving = clamp(
      Math.abs((targetConfig.slats || 0) - state.actualSlatPosition) +
      Math.abs((targetConfig.flaps || 0) - state.actualFlapPosition),
      0,
      1
    );
    publishConfigSpeeds();
  }

  function updateGear(dt, currentIAS) {
    const target = state.gearCommand > 0.5 ? 1 : 0;
    const time = target > state.gearPosition ? config.gear.deployTimeSeconds : config.gear.retractTimeSeconds;
    state.gearPosition = moveToward(clamp(state.gearPosition || 0, 0, 1), target, dt / Math.max(0.5, time));
    state.gearState = state.gearPosition > 0.98 ? 'DOWN' : state.gearPosition < 0.02 ? 'UP' : target > 0 ? 'TRANSIT DOWN' : 'TRANSIT UP';
    state.gearStatusText = state.gearState === 'DOWN' ? 'GEAR DOWN' : state.gearState === 'UP' ? 'GEAR UP' : 'GEAR TRANSIT';
    state.gearWarning = currentIAS > (target > 0 ? config.gear.vloKts : config.gear.vleKts) && state.gearPosition > 0.05 ? 'GEAR SPEED' : '';
    publishConfigSpeeds();
  }

  function updateSpeedBrake(dt, currentIAS) {
    const requested = state.speedBrakeCommand > 0.5 && !state.grounded ? 1 : 0;
    const rate = requested > state.speedBrakePosition ? config.speedBrake.deployRatePerSecond : config.speedBrake.retractRatePerSecond;
    state.speedBrakePosition = moveToward(clamp(state.speedBrakePosition || 0, 0, 1), requested, rate * dt);
    if (state.speedBrakePosition > 0.02) state.speedBrakeOpenTime += dt;
    else state.speedBrakeOpenTime = 0;
    state.speedBrakeActive = state.speedBrakePosition > 0.04;
    state.actualSpeedBrakePosition = state.speedBrakePosition;
    state.speedBrakeBuffetIntensity = state.speedBrakePosition * smoothstep(
      config.speedBrake.buffetStartKts,
      config.speedBrake.buffetStrongKts,
      currentIAS
    );
    if (state.speedBrakeActive && currentIAS < state.vlsKts + 10) state.speedBrakeCaution = 'SPD BRK LOW SPD';
    else state.speedBrakeCaution = '';
    state.speedBrakeStatusText = state.speedBrakeActive ? `SPEED BRK ${Math.round(state.speedBrakePosition * 100)}%` : '';
  }

  function updateGroundSpoilers(dt, wasGrounded) {
    const leverIdleOrReverse = (state.leverPosition || 0) <= 0.02 || (state.reverse || 0) > 0.02;
    const shouldDeploy = wasGrounded && state.mainGearCompressed !== false && state.groundSpoilersArmed && leverIdleOrReverse;
    const target = shouldDeploy ? 1 : 0;
    const rate = target ? config.groundSpoilers.deployRatePerSecond : config.groundSpoilers.retractRatePerSecond;
    state.groundSpoilerPosition = moveToward(clamp(state.groundSpoilerPosition || 0, 0, 1), target, rate * dt);
    state.actualGroundSpoilerPosition = state.groundSpoilerPosition;
    state.groundSpoilersActive = state.groundSpoilerPosition > 0.05;
    if (state.groundSpoilersActive) state.speedBrakeStatusText = `GND SPLR ${Math.round(state.groundSpoilerPosition * 100)}%`;
    else if (!state.speedBrakeActive) state.speedBrakeStatusText = state.groundSpoilersArmed ? 'GND SPLR ARM' : 'SPLR OFF';
  }

  function updateAttitude(dt, wasGrounded, brakeKeyPriority, currentIAS) {
    const rawPitchInput = (keys.has('KeyS') ? 1 : 0) - (!brakeKeyPriority && keys.has('KeyW') ? 1 : 0);
    const rawTurnInput = (keys.has('KeyA') ? 1 : 0) - (keys.has('KeyD') ? 1 : 0);
    const rawYawInput = (!brakeKeyPriority && keys.has('KeyQ') ? 1 : 0) - (keys.has('KeyE') ? 1 : 0);
    const trainingLaw = state.lawMode === STALL_TRAINING;
    const normalLaw = !trainingLaw;
    const pitchInput = smoothPitchInput(rawPitchInput, dt, wasGrounded, trainingLaw);
    const turnInput = wasGrounded ? rawTurnInput : rawTurnInput * holdSensitivity(rawTurnInput, 'KeyA', 'KeyD', TURN_HOLD_SENSITIVITY_RAMP_TIME, MAX_TURN_HOLD_SENSITIVITY);
    state.controlInputPitch = pitchInput;
    state.controlInputRoll = turnInput;

    if (wasGrounded) {
      const rotateDemand = currentIAS >= config.performance.vrKts - 2 && pitchInput > 0.05;
      const targetPitch = rotateDemand ? clamp(pitchInput, 0, 1) * 11 * DEG_TO_RAD : 0;
      state.pitch = THREE.MathUtils.damp(state.pitch, targetPitch, rotateDemand ? 2.7 : 7.5, dt);
      pitchRate = THREE.MathUtils.damp(pitchRate, 0, 8, dt);
      state.yaw += turnInput * clamp((currentIAS * KT_TO_MS) / 42, 0.52, 1.35) * 1.18 * dt;
      state.roll = THREE.MathUtils.damp(state.roll, 0, 7, dt);
      rollRate = THREE.MathUtils.damp(rollRate, 0, 8, dt);
    } else {
      const authority = clamp(state.controlAuthority || 0.5, 0.18, 1.15);
      const limitUp = normalLaw ? NORMAL_PITCH_LIMIT_UP : TRAINING_PITCH_LIMIT_UP;
      const limitDown = normalLaw ? NORMAL_PITCH_LIMIT_DOWN : TRAINING_PITCH_LIMIT_DOWN;
      let pitchAccel = pitchInput * (normalLaw ? 21 : 27) * DEG_TO_RAD * authority;
      pitchAccel += ((state.flapPitchMoment || 0) + (state.actualSpeedBrakePosition || 0) * config.speedBrake.pitchMoment) * 18 * DEG_TO_RAD * authority;
      if (normalLaw && state.alphaProtActive) pitchAccel -= smoothstep(config.protections.alphaProtAoADeg, config.protections.alphaMaxAoADeg, state.angleOfAttackDeg || 0) * 18 * DEG_TO_RAD;
      if (normalLaw && state.overspeedProtectionActive) pitchAccel += smoothstep(config.performance.vmoKts, config.performance.vmoKts + 30, currentIAS) * 7 * DEG_TO_RAD;
      if (Math.abs(pitchInput) < 0.04) {
        const neutralPitch = normalLaw ? neutralNormalLawPitch(currentIAS) : 0;
        pitchAccel += (neutralPitch - state.pitch) * (normalLaw ? 0.34 : 0.045);
      }
      pitchRate = clamp((pitchRate + pitchAccel * dt) * Math.pow(normalLaw ? 0.965 : 0.975, dt * 60), -18 * DEG_TO_RAD, 18 * DEG_TO_RAD);
      state.pitch = clamp(state.pitch + pitchRate * dt, limitDown, limitUp);

      const rollAuthority = authority * (state.alphaProtActive ? 0.78 : 1);
      let rollCommand = turnInput * 0.38 * rollAuthority;
      if (normalLaw && rawTurnInput === 0 && Math.abs(state.roll) > BANK_SOFT_LIMIT) rollCommand += (Math.sign(state.roll) * BANK_SOFT_LIMIT - state.roll) * 1.15;
      else if (rawTurnInput === 0) rollCommand += -state.roll * (normalLaw ? 0.08 : 0.035);
      rollRate = THREE.MathUtils.damp(rollRate, rollCommand, 3.5, dt);
      state.roll = clamp(state.roll + rollRate * dt, normalLaw ? -MAX_ROLL_NORMAL : -1.28, normalLaw ? MAX_ROLL_NORMAL : 1.28);
      const speedMS = Math.max(physicsVelocity.length(), 45);
      const coordinatedTurnRate = Math.tan(state.roll) * GRAVITY / speedMS * 2.15 * (1 - stallFactor * 0.35);
      state.yaw += (coordinatedTurnRate + rawYawInput * 0.1 * authority + (state.thrustAsymmetry || 0) * 0.14) * dt;
    }

    attitudeForward.set(0, 0, -1).applyEuler(new THREE.Euler(state.pitch, state.yaw, 0, 'YXZ')).normalize();
    bodyUpDirection.set(0, 1, 0).applyEuler(new THREE.Euler(state.pitch, state.yaw, state.roll, 'YXZ')).normalize();
  }

  function updateProtectionsAndStall(dt, angleOfAttack, currentIAS, wasGrounded) {
    const aoaDeg = angleOfAttack / DEG_TO_RAD;
    const safeAoA = config.protections.safeAoADeg;
    const alphaProt = config.protections.alphaProtAoADeg;
    const criticalAoA = config.protections.criticalAoADeg;
    const alphaMax = config.protections.alphaMaxAoADeg;
    const normalLaw = state.lawMode !== STALL_TRAINING;
    const lowSpeedRisk = 1 - smoothstep(state.stallSpeedKts, state.stallSpeedKts + 30, currentIAS);
    const aoaRisk = smoothstep(safeAoA, criticalAoA, aoaDeg);
    const recoveryReady = currentIAS > state.stallSpeedKts + 25 && aoaDeg < safeAoA;
    const stallCondition = !wasGrounded && currentIAS < state.stallSpeedKts && aoaDeg > criticalAoA;
    const targetStall = !normalLaw && !recoveryReady ? Math.max(lowSpeedRisk * aoaRisk, stallCondition ? 0.75 : 0) : 0;
    stallFactor = THREE.MathUtils.damp(stallFactor, targetStall, targetStall > stallFactor ? 1.55 : 1.2, dt);
    if (normalLaw) stallFactor = THREE.MathUtils.damp(stallFactor, 0, 3.6, dt);
    state.angleOfAttack = angleOfAttack;
    state.angleOfAttackDeg = aoaDeg;
    state.flightPathPitch = flightPathPitch;
    state.stallFactor = stallFactor;
    state.alphaProtActive = normalLaw && aoaDeg >= alphaProt * 0.96;
    state.alphaMaxActive = normalLaw && aoaDeg >= alphaMax * 0.98;
    state.overspeedProtectionActive = normalLaw && currentIAS > config.performance.vmoKts;
    state.lowEnergy = !wasGrounded && currentIAS < state.vlsKts + 15 && aoaDeg > safeAoA * 0.8;
    const speedAuthority = clamp(currentIAS / 210, 0.25, 1);
    const alphaSoftening = state.alphaProtActive ? 0.68 : 1;
    const stallSoftening = 1 - stallFactor * (normalLaw ? 0.3 : 0.52);
    state.controlAuthority = clamp(speedAuthority * alphaSoftening * stallSoftening, 0.25, 1);
  }

  function updateGroundVelocity(dt, currentIAS, altitudeFeet) {
    const speedMs = Math.max(0, physicsVelocity.length());
    const density = airDensityForAltitude(altitudeFeet, config);
    const flap = state.flapConfig || flapConfigAt(state.flapPositionIndex);
    const speedBrake = speedBrakeEffect(currentIAS);
    const groundSpoiler = state.groundSpoilerPosition || 0;
    const cdTotal = config.aerodynamics.cdGroundBase +
      flap.dragAdder +
      config.gear.dragAdder * (state.gearPosition || 0) +
      speedBrake.cdAdder +
      config.groundSpoilers.dragAdder * groundSpoiler;
    const dragN = aerodynamicDrag(speedMs, density, cdTotal);
    const rollingResistanceN = massKg * GRAVITY * config.brakes.rollingResistanceCoefficient;
    const thrustN = thrustFromN1(state.engineN1Average || config.engines.idleN1, config);
    const reverseForceN = reverseForce(currentIAS);
    const wheelBrakeForceN = wheelBrakeForce(currentIAS);
    const parkingBrakeForceN = state.parkingBrake ? massKg * 2.2 : 0;
    const forwardThrustN = state.reverse > 0.02 ? 0 : thrustN;
    let netForceN = forwardThrustN - dragN - rollingResistanceN - reverseForceN - wheelBrakeForceN - parkingBrakeForceN;
    if (netForceN < 0) {
      const limitedDecel = Math.min(-netForceN / massKg, config.brakes.maxTotalGroundDecelerationMS2);
      netForceN = -limitedDecel * massKg;
    }
    let nextSpeed = speedMs + (netForceN / massKg) * dt;
    if (nextSpeed < 0.25 && netForceN <= 0) nextSpeed = 0;
    if (state.parkingBrake && forwardThrustN < rollingResistanceN + parkingBrakeForceN) nextSpeed = 0;
    groundForward.set(0, 0, -1).applyEuler(new THREE.Euler(0, state.yaw, 0, 'YXZ')).normalize();
    physicsVelocity.copy(groundForward).multiplyScalar(clamp(nextSpeed, 0, ktToMS(410)));
    physicsVelocity.y = 0;

    const rotateReady = currentIAS >= config.performance.vrKts && state.pitch > 4 * DEG_TO_RAD;
    const liftRatio = Math.pow(Math.max(nextSpeed, 1) / ktToMS(flap.stallSpeedKts), 2) * flap.liftMultiplier * (1 - groundSpoiler * config.groundSpoilers.liftLoss);
    if (rotateReady && liftRatio > 0.96 && state.gearPosition > 0.45) {
      physicsVelocity.y = Math.max(1.5, (liftRatio - 0.88) * 6.5 + state.pitch * 12);
    }

    publishForceState({
      netForceN,
      thrustN: forwardThrustN,
      dragN,
      reverseForceN,
      rollingResistanceN,
      wheelBrakeForceN,
      speedBrakeForceN: speedBrake.forceN,
      climbEnergyN: 0,
      diveEnergyN: 0,
      accelerationMS2: netForceN / massKg
    });
  }

  function updateAirVelocity(dt, currentIAS, altitudeFeet, angleOfAttack) {
    let speedMs = Math.max(physicsVelocity.length(), config.aerodynamics.minAirborneSpeedMS);
    velocityDirection.copy(physicsVelocity).normalize();
    if (velocityDirection.lengthSq() < 0.5) velocityDirection.copy(attitudeForward);

    const density = airDensityForAltitude(altitudeFeet, config);
    const flap = state.flapConfig || flapConfigAt(state.flapPositionIndex);
    const speedBrake = speedBrakeEffect(currentIAS);
    const aoaDeg = Math.abs(angleOfAttack / DEG_TO_RAD);
    const inducedDrag = config.aerodynamics.inducedDragScale * Math.pow(aoaDeg / config.protections.criticalAoADeg, 2);
    const maneuverDrag = Math.abs(state.roll) * 0.018 + Math.abs(state.controlInputPitch || 0) * 0.014 + stallFactor * 0.16;
    const cdTotal = config.aerodynamics.cdClean +
      flap.dragAdder +
      config.gear.dragAdder * (state.gearPosition || 0) +
      speedBrake.cdAdder +
      inducedDrag +
      maneuverDrag;
    const dragN = aerodynamicDrag(speedMs, density, cdTotal);
    const thrustN = thrustFromN1(state.engineN1Average || config.engines.idleN1, config) * altitudeThrustScale(altitudeFeet);
    const thrustAlongPathN = thrustN * clamp(attitudeForward.dot(velocityDirection), 0, 1);
    const climbFactor = clamp(velocityDirection.y, 0, 1);
    const diveFactor = clamp(-velocityDirection.y, 0, 1);
    const climbEnergyN = massKg * GRAVITY * climbFactor * config.aerodynamics.climbEnergyScale;
    const diveEnergyN = massKg * GRAVITY * diveFactor * config.aerodynamics.diveEnergyScale;
    const netForceN = thrustAlongPathN - dragN - speedBrake.forceN - climbEnergyN + diveEnergyN;
    const accelerationMS2 = netForceN / massKg;

    physicsVelocity.addScaledVector(velocityDirection, accelerationMS2 * dt);
    speedMs = Math.max(physicsVelocity.length(), config.aerodynamics.minAirborneSpeedMS);
    velocityDirection.copy(physicsVelocity).normalize();
    applyLiftAndGravity(dt, speedMs, density, flap, angleOfAttack, speedBrake);
    alignVelocityWithAttitude(dt);

    const maxSpeed = ktToMS(config.aerodynamics.maxDiveGameKts);
    const nextSpeed = clamp(physicsVelocity.length(), config.aerodynamics.minAirborneSpeedMS, maxSpeed);
    physicsVelocity.normalize().multiplyScalar(nextSpeed);
    publishForceState({
      netForceN,
      thrustN,
      dragN,
      reverseForceN: 0,
      rollingResistanceN: 0,
      wheelBrakeForceN: 0,
      speedBrakeForceN: speedBrake.forceN,
      climbEnergyN,
      diveEnergyN,
      accelerationMS2
    });
  }

  function applyLiftAndGravity(dt, speedMs, density, flap, angleOfAttack, speedBrake) {
    const liftProjection = bodyUpDirection.dot(velocityDirection);
    liftDirection.copy(bodyUpDirection).addScaledVector(velocityDirection, -liftProjection);
    if (liftDirection.lengthSq() < 0.001) liftDirection.set(0, 1, 0);
    liftDirection.normalize();
    const stallSpeedMS = ktToMS(flap.stallSpeedKts);
    const speedLiftFactor = clamp(Math.pow(speedMs / Math.max(stallSpeedMS, 1), 2), 0, 1.55);
    const positiveAoA = clamp((angleOfAttack + 4 * DEG_TO_RAD) / ((config.protections.safeAoADeg + 4) * DEG_TO_RAD), 0.05, 1.25);
    const alphaLiftLoss = smoothstep(config.protections.alphaProtAoADeg, config.protections.alphaMaxAoADeg * 1.1, Math.max(0, angleOfAttack / DEG_TO_RAD)) * 0.45;
    const bankLiftLoss = Math.abs(state.roll) * 0.16;
    const speedBrakeLiftLoss = speedBrake.position * config.speedBrake.liftLoss;
    const groundSpoilerLiftLoss = (state.groundSpoilerPosition || 0) * config.groundSpoilers.liftLoss;
    const liftFactor = speedLiftFactor * positiveAoA * flap.liftMultiplier *
      (1 - stallFactor * 0.88) *
      (1 - alphaLiftLoss) *
      (1 - bankLiftLoss) *
      (1 - speedBrakeLiftLoss) *
      (1 - groundSpoilerLiftLoss);
    const liftAcceleration = clamp(GRAVITY * liftFactor, 0, config.aerodynamics.maxLiftAccelerationMS2);
    lateralAcceleration.set(0, -GRAVITY, 0).addScaledVector(liftDirection, liftAcceleration);
    const alongPath = lateralAcceleration.dot(velocityDirection);
    lateralAcceleration.addScaledVector(velocityDirection, -alongPath);
    physicsVelocity.addScaledVector(lateralAcceleration, dt);
    state.liftAccelerationMS2 = liftAcceleration;
    state.liftDirection = state.liftDirection?.isVector3 ? state.liftDirection : new THREE.Vector3();
    state.liftDirection.copy(liftDirection);
  }

  function alignVelocityWithAttitude(dt) {
    const speedMs = Math.max(physicsVelocity.length(), config.aerodynamics.minAirborneSpeedMS);
    velocityDirection.copy(physicsVelocity).normalize();
    const alignmentRate = THREE.MathUtils.lerp(0.65, 1.75, smoothstep(120, 300, speedMs * MS_TO_KT));
    const alphaSeparation = smoothstep(config.protections.safeAoADeg, config.protections.criticalAoADeg * 1.45, Math.abs(state.angleOfAttackDeg || 0));
    const authority = clamp(state.controlAuthority || 0.5, 0.08, 1.2);
    slerpDirection(velocityDirection, attitudeForward, clamp(alignmentRate * authority * (1 - stallFactor * 0.82) * (1 - alphaSeparation * 0.45) * dt, 0, 0.38));
    physicsVelocity.copy(velocityDirection).multiplyScalar(speedMs);
  }

  function updateWorldPosition(dt, wasGrounded) {
    const activeTravelScale = activeWorldTravelScale(wasGrounded);
    worldVelocity.copy(physicsVelocity);
    worldVelocity.x *= activeTravelScale;
    worldVelocity.z *= activeTravelScale;
    state.worldTravelScale = activeTravelScale;
    state.visualMapSpeed = Math.hypot(worldVelocity.x, worldVelocity.z);
    state.position.addScaledVector(worldVelocity, dt);
    state.visualPosition.copy(state.position);
  }

  function resolveGroundContact(dt) {
    const ground = terrainHeight(state.position.x, state.position.z) + AIRCRAFT_GROUND_OFFSET;
    if (state.position.y <= ground) {
      state.position.y = ground;
      state.grounded = true;
      state.mainGearCompressed = state.gearPosition > 0.75;
      physicsVelocity.y = Math.max(0, physicsVelocity.y);
      const iasKts = physicsVelocity.length() * MS_TO_KT;
      const rotating = iasKts >= config.performance.vrKts - 5 && (state.controlInputPitch || 0) > 0.05;
      if (!rotating) state.pitch = THREE.MathUtils.damp(state.pitch, 0, 5.5, dt);
      else state.pitch = clamp(state.pitch, 0, 12 * DEG_TO_RAD);
      state.roll = THREE.MathUtils.damp(state.roll, 0, 7, dt);
    } else {
      state.grounded = false;
      state.mainGearCompressed = false;
    }
    state.reverseAllowed = state.grounded && state.mainGearCompressed;
  }

  function updateWarnings(currentIAS) {
    const normalLaw = state.lawMode !== STALL_TRAINING;
    let warning = '';
    if (state.flapWarning) warning = state.flapWarning;
    else if (currentIAS > state.vmaxKts + 1) warning = state.flapVfeKts && currentIAS > state.flapVfeKts ? 'FLAP OVERSPEED' : 'OVERSPEED';
    else if (state.gearWarning) warning = state.gearWarning;
    else if (!normalLaw && stallFactor > 0.55) warning = 'STALL';
    else if (!normalLaw && stallFactor > 0.18 && flightPathPitch < -5 * DEG_TO_RAD) warning = 'DIVE RECOVERY';
    else if (state.alphaMaxActive) warning = 'ALPHA MAX';
    else if (state.alphaProtActive) warning = 'ALPHA PROT';
    else if (state.lowEnergy) warning = 'LOW ENERGY';
    else if (state.speedBrakeCaution) warning = state.speedBrakeCaution;
    state.flightWarning = warning;
  }

  function updateModel(model, dt) {
    if (!model?.group) return;
    collectMechanisms(model.group);
    const rotating = state.grounded && (state.currentIAS || 0) >= config.performance.vrKts - 5 && (state.pitch || 0) > 0;
    const displayPitch = state.grounded && !rotating ? 0 : state.pitch;
    const displayRoll = state.grounded ? 0 : state.roll;
    model.group.position.copy(state.position);
    model.group.rotation.set(displayPitch, state.yaw, displayRoll, 'YXZ');
    updateControlSurfaces(model, dt);
    animateMechanisms(model, dt);
    if (model.fans) {
      const fanSpeed = 16 + (state.engineN1Average || 22) * 1.1 + (state.physicsSpeedMS || 0) * 0.24;
      for (const fan of model.fans) fan.rotation.z += fanSpeed * dt;
    }
  }

  function updateControlSurfaces(model, dt) {
    if (!model.controlSurfaces) return;
    const { aileronLeft, aileronRight, elevator, rudder } = model.controlSurfaces;
    const turnInput = state.controlInputRoll || 0;
    const pitchInput = state.controlInputPitch || 0;
    if (aileronLeft && aileronRight) {
      aileronLeft.rotation.x = THREE.MathUtils.damp(aileronLeft.rotation.x, turnInput * 0.28, 12, dt);
      aileronRight.rotation.x = THREE.MathUtils.damp(aileronRight.rotation.x, -turnInput * 0.28, 12, dt);
    }
    if (elevator) elevator.rotation.x = THREE.MathUtils.damp(elevator.rotation.x, -pitchInput * 0.26, 12, dt);
    if (rudder) rudder.rotation.y = THREE.MathUtils.damp(rudder.rotation.y, -turnInput * (state.grounded ? 0.46 : 0.18), 10, dt);
  }

  function collectMechanisms(root) {
    if (mechanisms.collected) return;
    root.traverse(object => {
      if (/flap/i.test(object.name)) mechanisms.flaps.push(object);
      if (/spoiler_panel/i.test(object.name)) mechanisms.spoilers.push(object);
      if (/landing_gear|main_gear|nose_gear/i.test(object.name) && object.isGroup) mechanisms.gears.push(object);
    });
    mechanisms.collected = true;
  }

  function animateMechanisms(model, dt) {
    const hasDetailedHighLift = Boolean(model?.highLiftSurfaces);
    if (hasDetailedHighLift) animateHighLiftSurfaces(model.highLiftSurfaces, dt);
    else {
      const flapAmount = clamp((state.flapPositionIndex || 0) / (config.flaps.length - 1), 0, 1);
      for (const flap of mechanisms.flaps) flap.rotation.x = THREE.MathUtils.damp(flap.rotation.x, -flapAmount * 0.48, 8, dt);
      const spoilerAmount = Math.max(state.speedBrakePosition || 0, state.groundSpoilerPosition || 0);
      for (const spoiler of mechanisms.spoilers) spoiler.rotation.x = THREE.MathUtils.damp(spoiler.rotation.x, -spoilerAmount * 0.55, 10, dt);
    }
    for (const gear of mechanisms.gears) gear.visible = (state.gearPosition || 0) > 0.04;
  }

  function animateHighLiftSurfaces(surfaces, dt) {
    const slatAmount = clamp(state.actualSlatPosition || 0, 0, 1), flapAmount = clamp(state.actualFlapPosition || 0, 0, 1);
    const airSpoilerAmount = clamp(state.actualSpeedBrakePosition || state.speedBrakePosition || 0, 0, 1), groundSpoilerAmount = clamp(state.actualGroundSpoilerPosition || state.groundSpoilerPosition || 0, 0, 1);
    const airSpoilers = new Set(surfaces.speedBrakeSpoilers || []);
    for (const slat of surfaces.slats || []) {
      const data = highLiftData(slat);
      slat.position.copy(data.basePosition).addScaledVector(Z_AXIS, (data.extendZ || 0) * slatAmount).addScaledVector(Y_AXIS, (data.dropY || 0) * slatAmount);
      slat.rotation.x = THREE.MathUtils.damp(slat.rotation.x, -(data.angle || 0.16) * slatAmount, 7, dt);
    }
    for (const flap of surfaces.flaps || []) {
      const data = highLiftData(flap);
      flap.position.copy(data.basePosition).addScaledVector(Z_AXIS, (data.slideZ || 0) * flapAmount).addScaledVector(Y_AXIS, (data.dropY || 0) * flapAmount);
      flap.rotation.x = THREE.MathUtils.damp(flap.rotation.x, -(data.angle || 0.48) * flapAmount, 7, dt);
    }
    for (const spoiler of surfaces.groundSpoilers || []) {
      const data = highLiftData(spoiler);
      const airAmount = airSpoilers.has(spoiler) ? airSpoilerAmount : 0;
      const airAngle = (data.airAngle ?? -config.speedBrake.visualAngleDeg * DEG_TO_RAD) * airAmount * (1 - groundSpoilerAmount);
      const groundAngle = (data.groundAngle ?? -config.groundSpoilers.visualAngleDeg * DEG_TO_RAD) * groundSpoilerAmount;
      spoiler.rotation.x = THREE.MathUtils.damp(spoiler.rotation.x, airAngle + groundAngle, 10, dt);
    }
  }

  function highLiftData(surface) {
    surface.userData.highLift = surface.userData.highLift || {};
    const data = surface.userData.highLift;
    if (!data.basePosition) data.basePosition = surface.position.clone();
    return data;
  }

  function updateBrakeInputAndPressure(dt, wasGrounded, currentIAS, brakeKeyPriority) {
    const brakesAvailable = wasGrounded && state.mainGearCompressed !== false;
    const leftBrakeInput = brakeKeyPriority && keys.has('KeyQ') ? 1 : 0;
    const rightBrakeInput = brakeKeyPriority && keys.has('KeyW') ? 1 : 0;
    state.leftBrakeInput = leftBrakeInput;
    state.rightBrakeInput = rightBrakeInput;
    state.brakesAvailable = brakesAvailable;
    state.leftBrakePressure = moveBrakePressure(state.leftBrakePressure || 0, brakesAvailable ? leftBrakeInput : 0, dt);
    state.rightBrakePressure = moveBrakePressure(state.rightBrakePressure || 0, brakesAvailable ? rightBrakeInput : 0, dt);
    state.totalBrakePressure = (state.leftBrakePressure + state.rightBrakePressure) * 0.5;
    state.brakeInput = (leftBrakeInput + rightBrakeInput) * 0.5;
    state.brakeYawMoment = 0;
    state.brakeStatusText = brakeStatusText(leftBrakeInput, rightBrakeInput, state.totalBrakePressure, currentIAS);
  }

  function wheelBrakeForce(currentIAS) {
    if (!state.brakesAvailable || state.totalBrakePressure <= 0.005) {
      state.brakeEfficiency = 0;
      state.antiSkidActive = false;
      return 0;
    }
    const wheelSpeedFactor = smoothstep(5, 45, currentIAS);
    const spoilerMultiplier = state.groundSpoilersActive ? config.groundSpoilers.brakeEfficiencyMultiplier : 1;
    let brakeEfficiency = wheelSpeedFactor * spoilerMultiplier;
    const requestedDecel = config.brakes.maxBrakeDecelerationMS2 * state.totalBrakePressure * brakeEfficiency;
    state.antiSkidActive = config.brakes.antiSkidEnabled && currentIAS > 15 && requestedDecel > 4.8;
    if (state.antiSkidActive) brakeEfficiency *= 0.78;
    const brakeDeceleration = config.brakes.maxBrakeDecelerationMS2 * state.totalBrakePressure * brakeEfficiency;
    state.brakeEfficiency = brakeEfficiency;
    state.wheelBrakeDecelerationMS2 = brakeDeceleration;
    return massKg * brakeDeceleration;
  }

  function reverseForce(currentIAS) {
    if (!state.grounded || !state.mainGearCompressed || state.reverse <= 0.02) return 0;
    const reverseLevel = clamp(state.reverse, 0, 1);
    const reverseEffectiveness = clamp(currentIAS / config.reverse.fullEffectKts, 0.25, 1);
    const reverseN1Power = clamp(((state.engineN1Average || config.engines.idleN1) - config.engines.idleN1) / (config.engines.maxReverseN1 - config.engines.idleN1), 0, 1);
    return config.engines.maxTotalThrustN * config.reverse.maxThrustRatio * reverseLevel * reverseEffectiveness * reverseN1Power;
  }

  function speedBrakeEffect(currentIAS) {
    const position = clamp(state.speedBrakePosition || 0, 0, 1);
    if (position <= 0.001) return { position: 0, cdAdder: 0, forceN: 0 };
    const speedFactor = smoothstep(config.speedBrake.minEffectiveKts, config.speedBrake.strongEffectKts, currentIAS);
    const timeFactor = Math.exp(-(state.speedBrakeOpenTime || 0) / config.speedBrake.decayTimeSeconds);
    let decayFactor = THREE.MathUtils.lerp(0.25, 1, timeFactor);
    if (currentIAS < config.speedBrake.terminalIasKts) decayFactor *= 0.15;
    if (currentIAS < state.vlsKts + 10) decayFactor *= 0.3;
    const equivalentDecel = config.speedBrake.initialDecelKtsPerSecond * KT_TO_MS * speedFactor * decayFactor * position;
    const cdAdder = config.speedBrake.cdMax * config.speedBrake.dragFactor * position * Math.max(0.18, speedFactor);
    return {
      position,
      cdAdder,
      forceN: massKg * equivalentDecel
    };
  }

  function brakeStatusText(leftInput, rightInput, totalPressure, currentIAS) {
    const brakePercent = Math.round(clamp(totalPressure, 0, 1) * 100);
    const reverseActive = state.reverse > 0.08;
    if (reverseActive && currentIAS < config.reverse.lowSpeedWeakKts) return 'REV LOW EFFECT';
    if (reverseActive && currentIAS < config.reverse.reduceReverseKts && brakePercent <= 4) return 'REDUCE REV';
    if (reverseActive && brakePercent > 0) return brakePercent >= 90 ? 'REV + BRAKE 100%' : `REV + BRK ${brakePercent}%`;
    if (totalPressure <= 0.04 && leftInput + rightInput === 0) return state.groundSpoilersActive ? 'GND SPLR' : '';
    if (state.longitudinalAccelerationMS2 < -3.2 && brakePercent <= 4) return 'DECEL';
    if (leftInput && rightInput) return `BRAKE ${brakePercent}%`;
    if (leftInput) return `LEFT BRK ${brakePercent}%`;
    if (rightInput) return `RIGHT BRK ${brakePercent}%`;
    return brakePercent > 0 ? `BRK ${brakePercent}%` : '';
  }

  function publishForceState(forces) {
    state.netForceN = forces.netForceN;
    state.engineThrustN = forces.thrustN;
    state.dragForceN = forces.dragN;
    state.reverseForceN = forces.reverseForceN;
    state.rollingResistanceN = forces.rollingResistanceN;
    state.wheelBrakeForceN = forces.wheelBrakeForceN;
    state.brakeForceN = forces.wheelBrakeForceN;
    state.speedBrakeForceN = forces.speedBrakeForceN;
    state.climbEnergyCostN = forces.climbEnergyN;
    state.diveEnergyGainN = forces.diveEnergyN;
    state.longitudinalAccelerationMS2 = forces.accelerationMS2;
    state.forwardAcceleration = forces.accelerationMS2;
  }

  function publishPhysicsVelocity() {
    const speedMS = Math.max(0, physicsVelocity.length());
    state.physicsSpeedMS = speedMS;
    state.indicatedSpeedMS = speedMS;
    state.currentIAS = speedMS * MS_TO_KT;
    state.groundSpeedKts = Math.hypot(physicsVelocity.x, physicsVelocity.z) * MS_TO_KT;
    state.wheelSpeedKts = state.grounded ? state.groundSpeedKts : 0;
    state.speed = speedMS;
    if (speedMS > 0.001) {
      state.velocityDirection = state.velocityDirection?.isVector3 ? state.velocityDirection : new THREE.Vector3();
      state.velocityDirection.copy(physicsVelocity).divideScalar(speedMS);
    }
    state.speedTrendKts = (state.longitudinalAccelerationMS2 || 0) * 10 * MS_TO_KT;
    publishConfigSpeeds();
  }

  function publishConfigSpeeds() {
    state.vlsKts = vlsForFlapPosition(state.flapPositionIndex || 0);
    state.vfeKts = state.flapVfeKts || null;
    state.vmaxKts = vmaxForConfig(state.flapPositionIndex || 0, state.gearPosition || 0);
    state.selectedSpeedKts = Number.isFinite(state.selectedSpeedKts) ? state.selectedSpeedKts : 250;
  }

  function ensurePhysicsVelocity(wasGrounded) {
    const speedMS = Math.max(Math.abs(state.speed || 0), wasGrounded ? 0 : config.aerodynamics.minAirborneSpeedMS);
    if (physicsVelocity.lengthSq() < 0.01 || !Number.isFinite(physicsVelocity.x + physicsVelocity.y + physicsVelocity.z)) {
      physicsVelocity.copy(attitudeForward).multiplyScalar(speedMS);
      if (wasGrounded) physicsVelocity.y = 0;
    }
  }

  function computeAngleOfAttack() {
    return clamp(state.pitch - flightPathPitch, -16 * DEG_TO_RAD, 32 * DEG_TO_RAD);
  }

  function publishAttitudeDirections() {
    state.forwardDirection = state.forwardDirection?.isVector3 ? state.forwardDirection : new THREE.Vector3();
    state.bodyUpDirection = state.bodyUpDirection?.isVector3 ? state.bodyUpDirection : new THREE.Vector3();
    state.forwardDirection.copy(attitudeForward);
    state.bodyUpDirection.copy(bodyUpDirection);
  }

  function aerodynamicDrag(speedMs, density, cd) {
    return 0.5 * density * speedMs * speedMs * config.dimensions.referenceWingAreaM2 * cd;
  }

  function altitudeThrustScale(altitudeFeet) {
    return clamp(1 - Math.pow(smoothstep(10000, 41000, altitudeFeet), 1.25), 0, 1);
  }

  function activeWorldTravelScale(wasGrounded) {
    const maxTravelScale = Number.isFinite(state.maxTravelScale) ? state.maxTravelScale : MAX_WORLD_TRAVEL_SCALE;
    const requestedScale = wasGrounded
      ? (Number.isFinite(state.groundTravelScale) ? state.groundTravelScale : DEFAULT_GROUND_TRAVEL_SCALE)
      : (Number.isFinite(state.airTravelScale) ? state.airTravelScale : DEFAULT_AIR_TRAVEL_SCALE);
    return clamp(requestedScale, 1, maxTravelScale);
  }

  function smoothPitchInput(rawPitchInput, dt, wasGrounded, trainingLaw) {
    const target = wasGrounded
      ? rawPitchInput
      : rawPitchInput * holdSensitivity(rawPitchInput, 'KeyS', 'KeyW', PITCH_HOLD_SENSITIVITY_RAMP_TIME, MAX_PITCH_HOLD_SENSITIVITY) * (trainingLaw ? 1.08 : 1);
    const rate = Math.abs(target) > Math.abs(smoothedPitchInput) ? 3 : 4;
    smoothedPitchInput = moveToward(smoothedPitchInput, target, rate * dt);
    return smoothedPitchInput;
  }

  function neutralNormalLawPitch(currentIAS) {
    const phase = state.flightPhase || '';
    const targetSpeed = Number.isFinite(state.targetSpeedKts) ? state.targetSpeedKts : config.performance.initialClimbIasKts;
    let targetDeg = 0;
    if (phase === 'TAKEOFF' || phase === 'INITIAL_CLIMB') {
      const accelerationProgress = smoothstep(config.performance.v2Kts + 8, config.performance.initialClimbIasKts, currentIAS);
      targetDeg = THREE.MathUtils.lerp(7.5, 9.5, accelerationProgress);
      if (currentIAS < config.performance.v2Kts + 5) targetDeg = 5.2;
    } else if (phase === 'CLIMB' || phase === 'GO_AROUND') {
      const speedMargin = currentIAS - targetSpeed;
      targetDeg = speedMargin < -18 ? 4.5 : speedMargin > 12 ? 8.2 : 6.4;
    } else if (phase === 'CRUISE') {
      targetDeg = 1.4;
    } else if (phase === 'DESCENT') {
      targetDeg = -1.8;
    } else if (phase === 'APPROACH') {
      targetDeg = 3.2;
    } else if (phase === 'FLARE' || phase === 'LANDING') {
      targetDeg = 2.4;
    }
    if (state.lowEnergy || state.alphaProtActive) targetDeg = Math.min(targetDeg, 2.5);
    if (state.overspeedProtectionActive) targetDeg = Math.max(targetDeg, 3.5);
    return targetDeg * DEG_TO_RAD;
  }

  function holdSensitivity(input, positiveCode, negativeCode, rampTime, maxSensitivity) {
    if (input === 0) return 1;
    const code = input > 0 ? positiveCode : negativeCode;
    const heldFor = keyHoldTimes.get(code) || 0;
    const ramp = smoothstep(HOLD_SENSITIVITY_DELAY, HOLD_SENSITIVITY_DELAY + rampTime, heldFor);
    return 1 + ramp * (maxSensitivity - 1);
  }

  function updateKeyHoldTimes(dt, suppressedCodes = null) {
    for (const code of CONTROL_KEYS) {
      keyHoldTimes.set(code, keys.has(code) && !suppressedCodes?.has(code) ? (keyHoldTimes.get(code) || 0) + dt : 0);
    }
  }

  function moveBrakePressure(current, target, dt) {
    const rate = target > current ? config.brakes.applyRatePerSecond : config.brakes.releaseRatePerSecond;
    return moveToward(current, target, rate * dt);
  }

  function justPressed(code) {
    return keys.has(code) && !previousKeys.has(code);
  }

  function publishPreviousKeys() {
    previousKeys.clear();
    for (const key of keys) previousKeys.add(key);
  }

  function slerpDirection(from, to, alpha) {
    const t = clamp(alpha, 0, 1);
    if (t <= 0) return from.normalize();
    const dot = clamp(from.dot(to), -1, 1);
    if (dot > 0.9995) return from.lerp(to, t).normalize();
    if (dot < -0.9995) return from.lerp(to, Math.min(t, 0.5)).normalize();
    const theta = Math.acos(dot);
    const sinTheta = Math.sin(theta);
    const fromScale = Math.sin((1 - t) * theta) / sinTheta;
    const toScale = Math.sin(t * theta) / sinTheta;
    return from.multiplyScalar(fromScale).addScaledVector(to, toScale).normalize();
  }

  function radioAltitudeFeet() {
    const ground = terrainHeight(state.position.x, state.position.z) + AIRCRAFT_GROUND_OFFSET;
    return Math.max(0, (state.position.y - ground) * FT_PER_M);
  }

  return { updateAircraft };
}
