// Generated by tools/buildVirtualSources.js from src/ui/hud/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import {
  AIRCRAFT_GROUND_OFFSET,
  AIRPORTS,
  BAYS,
  CITY_ZONES,
  LAKES,
  LANDMASSES,
  MAP_SIZE,
  RIVER_SYSTEMS
} from '../data/worldData.js?v=202605070100';
import { closestLandmass, waterBodyBoundaryPoint } from '../world/spatial.js?v=202605056000';

const NAV_MAP_UPDATE_INTERVAL_MS = 100;
const HUD_READOUT_UPDATE_INTERVAL_MS = 1000 / 30;

export function createHud({ ui, state, rootStyle, terrainHeight, airportWorld }) {
  let lastNavMapDraw = 0;
  let lastReadoutUpdate = 0;
  let displayedSpeedKts = null;
  let displayedAltitudeFt = null;
  let displayedN1Percent = null;
  let mapZoom = 1;
  let mapPanX = 0;
  let mapPanZ = 0;

  function updateHud() {
    const headingDeg = currentHeadingDeg();
    const now = performance.now();
  
    const visualPitch = Number.isFinite(state.visualPitch) ? state.visualPitch : state.pitch;
    const visualRoll = Number.isFinite(state.visualRoll) ? state.visualRoll : state.roll;
    rootStyle.setProperty('--roll', `${-visualRoll}rad`);
    rootStyle.setProperty('--pitch-offset', `${THREE.MathUtils.clamp(-visualPitch * 145, -52, 52)}px`);
    if (now - lastReadoutUpdate >= HUD_READOUT_UPDATE_INTERVAL_MS) {
      const readoutDt = lastReadoutUpdate > 0 ? THREE.MathUtils.clamp((now - lastReadoutUpdate) / 1000, 1 / 60, 0.12) : 1 / 30;
      updateReadouts(headingDeg, readoutDt);
      lastReadoutUpdate = now;
    }
    if (now - lastNavMapDraw >= NAV_MAP_UPDATE_INTERVAL_MS) {
      drawNavMap(headingDeg);
    }
  }

  function updateReadouts(headingDeg, readoutDt = 1 / 30) {
    const physicsSpeedMS = Number.isFinite(state.physicsSpeedMS) ? state.physicsSpeedMS : Math.abs(state.speed || 0);
    const indicatedKts = Number.isFinite(state.currentIAS) ? Math.abs(state.currentIAS) : physicsSpeedMS * 1.94384;
    const readoutPosition = state.visualPosition || state.position;
    const rawFeet = Math.max(0, (readoutPosition.y - terrainHeight(readoutPosition.x, readoutPosition.z) - AIRCRAFT_GROUND_OFFSET) * 3.28084);
    const rawN1Percent = state.engineN1Average || state.throttle * 100;
    displayedSpeedKts = dampReadout(displayedSpeedKts, indicatedKts, 14, readoutDt);
    displayedAltitudeFt = dampReadout(displayedAltitudeFt, rawFeet, 10, readoutDt);
    displayedN1Percent = dampReadout(displayedN1Percent, rawN1Percent, 12, readoutDt);
    const knots = Math.round(displayedSpeedKts);
    const feet = Math.max(0, Math.round(displayedAltitudeFt));
    const n1Percent = Math.round(displayedN1Percent);
    const reversePercent = Math.round(state.reverse * 100);
    const nearest = nearestAirport();
    const speedCalloutActive = Boolean(state.speedCallout) && performance.now() < (state.speedCalloutUntil || 0);
    const brakeText = state.brakeStatusText || '';
    const parkBrakeConflictText = state.parkBrakeWarningText
      ? (Math.floor(now / 850) % 2 === 0 ? (state.parkBrakeStatusText || 'PARK BRK ON') : state.parkBrakeWarningText)
      : '';
    const parkBrakeText = parkBrakeConflictText || state.parkBrakeStatusText || (state.parkingBrake ? (state.isParked ? 'PARKED' : 'PARK BRK') : '');
    const spoilerModeText = activeSpoilerModeText(state.speedBrakeStatusText);
    const gearModeText = state.gearStatusText === 'GEAR UP' ? '' : state.gearStatusText;
    const flapModeText = state.flapStatusText === 'FLAPS 0' ? '' : state.flapStatusText;
    const systemText = spoilerModeText || gearModeText || flapModeText || '';
    const modeText = state.thrustAlert || state.flightWarning || (speedCalloutActive ? state.speedCallout : '') ||
      (parkBrakeText || brakeText || (state.reverse > 0.08 ? 'REV' : systemText || (state.lawMode === 'STALL_TRAINING' ? 'STALL TRN' : 'NORMAL LAW')));

    setText(ui.speed, knots);
    setText(ui.altitude, feet);
    setText(ui.throttle, n1Percent);
    setText(ui.heading, headingDeg.toString().padStart(3, '0'));
    setWidth(ui.throttleBar, n1Percent);
    setWidth(ui.reverseBar, reversePercent);
    setText(ui.verticalSpeed, `${Math.round(state.verticalSpeed)} ft/min`);
    setText(ui.pitch, `${Math.round(THREE.MathUtils.radToDeg(state.pitch))} deg`);
    setText(ui.flapStatus, `${state.flapStatusText || 'FLAPS 0'} ${Math.round((state.actualSlatPosition || 0) * 100)}/${Math.round((state.actualFlapPosition || 0) * 100)}`);
    setText(ui.speedBrakeStatus, state.speedBrakeStatusText || 'SPLR OFF');
    setText(ui.vfeStatus, vfeReadout());
    setText(ui.vlsStatus, `${Math.round(state.vlsKts || 150)} kt`);
    setText(ui.nearestField, nearest.name);
    setText(ui.fieldDistance, `${nearest.distanceNm.toFixed(1)} nm`);
    setText(ui.mode, modeText);
    setText(ui.simClock, state.simClockText || '06:00');
    setText(ui.simClockSource, state.simClockSource || 'SERVER');
    ui.mode.classList.toggle('reverse-active', (state.reverse > 0.08 || brakeText || spoilerModeText || parkBrakeText) && !state.flightWarning && !state.thrustAlert);
    ui.mode.classList.toggle('warning-active', ['LOW ENERGY', 'OVERSPEED', 'STALL', 'REV LOCKED', 'LVR ASYM', 'FLAP OVERSPEED', 'TOO FAST FOR FLAPS', 'PARK BRK ON', 'RELEASE PARKING BRAKE'].includes(modeText));
    ui.mode.classList.toggle('protection-active', ['ALPHA PROT', 'ALPHA MAX', 'DIVE RECOVERY', 'A.FLOOR', 'TOGA LK', 'SPEED BRK', 'GND SPLR', 'PARK BRK', 'PARKED'].includes(modeText));
    ui.mode.classList.toggle('training-active', !state.flightWarning && !state.thrustAlert && state.lawMode === 'STALL_TRAINING');
    ui.mode.classList.toggle('speed-callout-active', speedCalloutActive && !state.flightWarning && !state.thrustAlert);
    updateFmaAndThrustPanel(knots);
    updateCompassStrip(headingDeg);
    setText(ui.mapMode, ui.mapOverlay.classList.contains('visible') ? 'FULL' : 'ALL');
  }

  function dampReadout(current, target, lambda, dt) {
    if (!Number.isFinite(current)) return target;
    if (!Number.isFinite(target)) return current;
    return THREE.MathUtils.damp(current, target, lambda, dt);
  }

  function updateFmaAndThrustPanel(knots) {
    if (!ui.fmaThrust) return;
    const speedTrend = Math.round(state.speedTrendKts || 0);
    const leftDetent = leverSideLabel('Left');
    const rightDetent = leverSideLabel('Right');
    const leverSummary = state.leverDetentLabel || (state.lvrAsym ? `L ${leftDetent} / R ${rightDetent}` : leftDetent);
    const detentDetail = state.leverDetentDetail || detentLabel(state.nearestDetent || state.thrustDetentLeft);
    const averageN1 = Math.round(state.engineN1Average || 0);
    const targetN1 = Math.round(state.targetN1Average || averageN1);
    const leftPct = leverPercent(state.thrustLeverLeft);
    const rightPct = leverPercent(state.thrustLeverRight);
    setText(ui.fmaThrust, state.fmaThrustMode || 'MAN THR');
    setText(ui.fmaVertical, state.fmaVerticalMode || 'OP CLB');
    setText(ui.fmaLateral, state.fmaLateralMode || 'HDG');
    setText(ui.athrStatus, `A/THR ${state.athrStatus || 'OFF'}`);
    setText(ui.targetSpeed, Math.round(state.targetSpeedKts || knots));
    setText(ui.speedMode, state.speedMode || 'MANAGED');
    setText(ui.speedTrend, `${speedTrend >= 0 ? '+' : ''}${speedTrend}`);
    setText(ui.leverDetent, leverSummary);
    setText(ui.leverDetentDetail, detentDetail);
    setText(ui.thrustModeSmall, state.fmaThrustMode || 'MAN THR');
    setText(ui.thrustIas, `${knots} kt`);
    setText(ui.thrustLimit, state.thrustLimitLabel || `${targetN1}%`);
    setText(ui.targetN1Readout, `${targetN1}%`);
    setText(ui.avgN1, `${averageN1}%`);
    setText(ui.leftDetent, leftDetent);
    setText(ui.rightDetent, rightDetent);
    setText(ui.leftN1, `${Math.round(state.engineN1Left || 0)}%`);
    setText(ui.rightN1, `${Math.round(state.engineN1Right || 0)}%`);
    setText(ui.detentToast, state.detentFlash || '');
    ui.detentToast.classList.toggle('visible', Boolean(state.detentFlash));
    ui.thrustPanel.classList.toggle('reverse-locked', !state.reverseAllowed);
    ui.thrustPanel.classList.toggle('reverse-active', state.reverse > 0.08);
    ui.thrustPanel.classList.toggle('thrust-asym', state.lvrAsym);
    ui.thrustPanel.classList.toggle('between-detents', state.isBetweenDetents);
    ui.thrustPanel.classList.toggle('soft-detent', Boolean(state.softDetentLeft || state.softDetentRight));
    ui.thrustPanel.classList.toggle('manual-fine', Boolean(state.manualFineTune));
    ui.thrustLeverLeft.classList.toggle('between-detents', Boolean(state.isBetweenDetentsLeft));
    ui.thrustLeverRight.classList.toggle('between-detents', Boolean(state.isBetweenDetentsRight));
    ui.thrustLeverLeft.style.bottom = `calc(${leftPct}% - 10px)`;
    ui.thrustLeverRight.style.bottom = `calc(${rightPct}% - 10px)`;
    for (const label of ui.detentLabels) {
      const detent = label.dataset.detentLabel;
      const active = detent === state.currentDetentLeft || detent === state.currentDetentRight;
      const soft = detent === state.softDetentLeft || detent === state.softDetentRight;
      const nearestBetween = state.isBetweenDetents && (detent === state.nearestDetentLeft || detent === state.nearestDetentRight);
      label.classList.toggle('active', active || soft);
      label.classList.toggle('soft', soft);
      label.classList.toggle('nearby', nearestBetween && !active && !soft);
    }
  }

  function vfeReadout() {
    const vfe = Number.isFinite(state.vfeKts) ? Math.round(state.vfeKts) : null;
    const next = Number.isFinite(state.vfeNextKts) ? Math.round(state.vfeNextKts) : null;
    if (vfe && next) return `${vfe} / N ${next}`;
    if (vfe) return `${vfe} kt`;
    if (next) return `NEXT ${next}`;
    return '---';
  }

  function activeSpoilerModeText(text) {
    if (!text || text === 'GND SPLR ARM' || text === 'SPLR OFF') return '';
    return text;
  }

  function leverPercent(position = 0) {
    return THREE.MathUtils.clamp((position + 0.3) / 1.3 * 100, 0, 100);
  }

  function detentLabel(name) {
    if (name === 'BETWEEN') return 'BETWEEN';
    if (name === 'LVR ASYM') return 'LVR ASYM';
    if (name === 'MAX_REV') return 'MAX REV';
    if (name === 'REV_IDLE') return 'REV IDLE';
    if (name === 'FLX_MCT') return 'FLX/MCT';
    return name || 'IDLE';
  }

  function leverSideLabel(sideName) {
    const current = state[`currentDetent${sideName}`];
    const position = state[`thrustLever${sideName}`] || 0;
    if (current && current !== 'BETWEEN') return detentLabel(current);
    if (position < 0) return `REV ${Math.round(THREE.MathUtils.clamp((0 - position) / 0.3, 0, 1) * 100)}%`;
    return `${Math.round(THREE.MathUtils.clamp(position, 0, 1) * 100)}%`;
  }

  function setText(element, value) {
    if (!element) return;
    const text = String(value);
    if (element.textContent !== text) element.textContent = text;
  }

  function setWidth(element, percent) {
    if (!element) return;
    const width = `${percent}%`;
    if (element.style.width !== width) element.style.width = width;
  }

  function drawNavMap(headingDeg = currentHeadingDeg()) {
    lastNavMapDraw = performance.now();
    drawNavMapCanvas(ui.navMap, headingDeg, false);
    if (ui.mapOverlay.classList.contains('visible')) {
      drawNavMapCanvas(ui.navMapOverlay, headingDeg, true);
    }
  }

  function updateCompassStrip(headingDeg) {
    const marks = [-90, -60, -30, 0, 30, 60, 90];
    for (let i = 0; i < marks.length; i++) {
      ui.compassStrip.children[i].textContent = compassLabel(headingDeg + marks[i]);
    }
  }

  function compassLabel(deg) {
    const heading = normalizeHeading(deg);
    if (heading === 0) return 'N';
    if (heading === 90) return 'E';
    if (heading === 180) return 'S';
    if (heading === 270) return 'W';
    return heading.toString().padStart(3, '0');
  }

  function drawNavMapCanvas(canvas, headingDeg, expanded) {
    const rect = canvas.getBoundingClientRect();
    if (rect.width < 2 || rect.height < 2) return;
  
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const pixelWidth = Math.max(1, Math.round(rect.width * dpr));
    const pixelHeight = Math.max(1, Math.round(rect.height * dpr));
    if (canvas.width !== pixelWidth || canvas.height !== pixelHeight) {
      canvas.width = pixelWidth;
      canvas.height = pixelHeight;
    }
  
    const ctx = canvas.getContext('2d');
    const width = rect.width;
    const height = rect.height;
    const pad = expanded ? 13 : 7;
    const size = Math.max(1, Math.min(width - pad * 2, height - pad * 2));
    const left = (width - size) / 2;
    const top = (height - size) / 2;
  
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = '#082531';
    ctx.fillRect(0, 0, width, height);
    ctx.fillStyle = '#17627d';
    ctx.fillRect(left - pad * 0.42, top - pad * 0.42, size + pad * 0.84, size + pad * 0.84);
  
    const viewSpan = expanded ? MAP_SIZE / mapZoom : MAP_SIZE;
    const centerX = expanded ? mapPanX : 0;
    const centerZ = expanded ? mapPanZ : 0;
    const worldToMap = (x, z) => {
      const nx = (x - centerX) / viewSpan + 0.5;
      const ny = (z - centerZ) / viewSpan + 0.5;
      return {
        x: left + (expanded ? nx : THREE.MathUtils.clamp(nx, 0, 1)) * size,
        y: top + (expanded ? ny : THREE.MathUtils.clamp(ny, 0, 1)) * size
      };
    };

    const drawWaterBody = (body, color, stroke) => {
      ctx.beginPath();
      const samples = body.shoreIrregularity ? (expanded ? 84 : 56) : 44;
      for (let i = 0; i <= samples; i++) {
        const angle = (i / samples) * Math.PI * 2;
        const boundary = waterBodyBoundaryPoint(body, angle, 1);
        const p = worldToMap(boundary.x, boundary.z);
        if (i === 0) ctx.moveTo(p.x, p.y);
        else ctx.lineTo(p.x, p.y);
      }
      ctx.closePath();
      ctx.fillStyle = color;
      ctx.fill();
      if (stroke) {
        ctx.strokeStyle = stroke;
        ctx.lineWidth = expanded ? 1.6 : 0.9;
        ctx.stroke();
      }
    };

    for (const land of LANDMASSES) drawWaterBody(land, '#3f7546', 'rgba(153, 181, 151, 0.58)');
    for (const bay of BAYS) drawWaterBody(bay, '#1f7b96', '#76d1e4');
    for (const lake of LAKES) drawWaterBody(lake, '#1f84a2', '#95dfef');
  
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.strokeStyle = 'rgba(120, 219, 238, 0.82)';
    ctx.lineWidth = expanded ? 3 : 1.6;
    for (const river of RIVER_SYSTEMS) {
      ctx.beginPath();
      for (let i = 0; i < river.length; i++) {
        const p = worldToMap(river[i].x, river[i].z);
        if (i === 0) ctx.moveTo(p.x, p.y);
        else ctx.lineTo(p.x, p.y);
      }
      ctx.stroke();
    }
  
    ctx.fillStyle = 'rgba(205, 211, 207, 0.26)';
    for (const zone of CITY_ZONES) {
      const p = worldToMap(zone.x, zone.z);
      ctx.beginPath();
      ctx.arc(p.x, p.y, zone.radius / MAP_SIZE * size, 0, Math.PI * 2);
      ctx.fill();
    }
  
    for (const airport of AIRPORTS) {
      const runwayLength = airport.runwayLength || 1320;
      const start = airportWorld(airport, 0, -runwayLength / 2);
      const end = airportWorld(airport, 0, runwayLength / 2);
      const a = worldToMap(start.x, start.z);
      const b = worldToMap(end.x, end.z);
      ctx.strokeStyle = '#e8edf2';
      ctx.lineWidth = airport.size > 1.05 ? (expanded ? 4.2 : 2.4) : (expanded ? 3.2 : 1.8);
      ctx.beginPath();
      ctx.moveTo(a.x, a.y);
      ctx.lineTo(b.x, b.y);
      ctx.stroke();
  
      const hiddenAirfield = airport.airportCategory === 'HIDDEN_REMOTE_AIRFIELD';
      if (expanded || hiddenAirfield) {
        const label = worldToMap(airport.x, airport.z);
        const classTag = airport.runwayClass || (airport.tier === 'international' ? 'A' : airport.tier === 'regional' ? 'B' : 'C');
        const a320Tag = airport.a320Recommended === false ? ' NO A320' : airport.a320Recommended === 'challenge' ? ' CHALLENGE' : '';
        const nightTag = airport.isNightCapable === false ? ' NO LIGHT' : '';
        const labelText = hiddenAirfield ? 'nothing there' : `${airport.short || airport.name} [${classTag}${a320Tag}${nightTag}]`;
        ctx.fillStyle = '#eff8ff';
        ctx.font = '700 10px ui-sans-serif, system-ui, sans-serif';
        ctx.fillText(labelText, label.x + 5, label.y - 5);
      }
    }
  
    const aircraftTargets = Array.isArray(state.multiplayerAircraft) && state.multiplayerAircraft.length
      ? state.multiplayerAircraft
      : [{
          aircraftCode: state.localAircraftCode || 'YOU',
          isSelf: true,
          position: { x: state.position.x, z: state.position.z },
          heading: headingDeg,
          altitude: Math.max(0, Math.round((state.position.y - terrainHeight(state.position.x, state.position.z) - AIRCRAFT_GROUND_OFFSET) * 3.28084)),
          verticalSpeed: state.verticalSpeed || 0
        }];
    const occupied = [];
    for (const target of aircraftTargets) {
      drawAircraftTrail(ctx, target.trail || [], worldToMap, {
        self: target.isSelf,
        stale: target.connectionStatus === 'stale',
        expanded
      });
    }
    for (const target of aircraftTargets) {
      const p = worldToMap(target.position.x, target.position.z);
      const offset = markerOverlapOffset(p, occupied, expanded);
      occupied.push({ x: p.x + offset.x, y: p.y + offset.y });
      drawAircraftMarker(ctx, {
        x: p.x + offset.x,
        y: p.y + offset.y,
        heading: target.heading ?? headingDeg,
        code: target.isSelf ? 'YOU' : target.aircraftCode,
        subCode: target.isSelf ? target.aircraftCode || 'A20N' : '',
        altitude: target.altitude,
        speed: target.speed,
        bearing: target.bearingFromSelf,
        verticalSpeed: target.verticalSpeed,
        connectionStatus: target.connectionStatus,
        self: target.isSelf,
        expanded
      });
    }

    const ufoContact = state.ufoContact;
    if (ufoContact?.active && ufoContact.position) {
      const p = worldToMap(ufoContact.position.x, ufoContact.position.z);
      const offset = markerOverlapOffset(p, occupied, expanded);
      drawUfoContactMarker(ctx, {
        x: THREE.MathUtils.clamp(p.x + offset.x, left + 10, left + size - 10),
        y: THREE.MathUtils.clamp(p.y + offset.y, top + 10, top + size - 10),
        contact: ufoContact,
        expanded,
        bounds: { left, top, size }
      });
    }
  
    ctx.fillStyle = 'rgba(238, 247, 255, 0.92)';
    ctx.font = `${expanded ? 11 : 9}px ui-sans-serif, system-ui, sans-serif`;
    ctx.textAlign = 'right';
    ctx.fillText(`${headingDeg.toString().padStart(3, '0')} deg`, left + size - 4, top + size - 5);
    if (expanded) {
      const region = closestLandmass(state.position.x, state.position.z);
      const regionName = region.signedDistance > -260 ? region.land?.name || 'Open Sea' : 'Open Sea';
      ctx.textAlign = 'left';
      ctx.fillText(regionName, left + 5, top + size - 5);
      ctx.textAlign = 'right';
      ctx.fillText(`${mapZoom.toFixed(1)}x`, left + size - 4, top + 13);
    }
    ctx.textAlign = 'left';
  }

  function drawAircraftTrail(ctx, trail, worldToMap, options) {
    if (!Array.isArray(trail) || trail.length < 2) return;
    const maxAge = 30000;
    const points = trail.slice(options.expanded ? -60 : -28).map(point => ({
      ...worldToMap(point.x, point.z),
      ageMs: point.ageMs || 0
    }));
    ctx.save();
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.lineWidth = options.expanded ? 2.1 : 1.35;
    for (let i = 1; i < points.length; i++) {
      const ageRatio = THREE.MathUtils.clamp(points[i].ageMs / maxAge, 0, 1);
      const alpha = (1 - ageRatio) * (options.self ? 0.5 : 0.42) * (options.stale ? 0.42 : 1);
      if (alpha <= 0.02) continue;
      ctx.strokeStyle = options.self
        ? `rgba(255, 209, 102, ${alpha})`
        : `rgba(124, 244, 255, ${alpha})`;
      ctx.beginPath();
      ctx.moveTo(points[i - 1].x, points[i - 1].y);
      ctx.lineTo(points[i].x, points[i].y);
      ctx.stroke();
    }
    ctx.restore();
  }

  function markerOverlapOffset(point, occupied, expanded) {
    const threshold = expanded ? 24 : 16;
    let overlap = 0;
    for (const item of occupied) {
      if (Math.hypot(point.x - item.x, point.y - item.y) < threshold) overlap++;
    }
    if (!overlap) return { x: 0, y: 0 };
    const angle = overlap * 2.2;
    const radius = expanded ? 13 : 8;
    return { x: Math.cos(angle) * radius, y: Math.sin(angle) * radius };
  }

  function drawAircraftMarker(ctx, marker) {
    const size = marker.expanded ? 10 : 7;
    const stale = marker.connectionStatus === 'stale';
    const color = stale ? '#91a3a9' : marker.self ? '#ffd166' : '#7cf4ff';
    const outline = marker.self ? '#051015' : '#021a24';
    const headingRad = THREE.MathUtils.degToRad(marker.heading || 0);
    const trailLength = marker.expanded ? 24 : 15;
    const backX = marker.x - Math.sin(headingRad) * trailLength;
    const backY = marker.y + Math.cos(headingRad) * trailLength;

    ctx.save();
    ctx.strokeStyle = stale
      ? 'rgba(145, 163, 169, 0.52)'
      : marker.self ? 'rgba(255, 209, 102, 0.74)' : 'rgba(124, 244, 255, 0.68)';
    ctx.lineWidth = marker.expanded ? 2 : 1.35;
    ctx.beginPath();
    ctx.moveTo(marker.x, marker.y);
    ctx.lineTo(backX, backY);
    ctx.stroke();
    ctx.translate(marker.x, marker.y);
    ctx.rotate(headingRad);
    ctx.fillStyle = color;
    ctx.strokeStyle = outline;
    ctx.lineWidth = marker.expanded ? 1.4 : 1.1;
    ctx.beginPath();
    ctx.moveTo(0, -size);
    ctx.lineTo(size * 0.62, size * 0.86);
    ctx.lineTo(0, size * 0.46);
    ctx.lineTo(-size * 0.62, size * 0.86);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.restore();

    const trend = marker.verticalSpeed > 180 ? 'CLB' : marker.verticalSpeed < -180 ? 'DES' : 'ALT';
    const altitude = Math.max(0, Math.round(marker.altitude || 0));
    const heading = normalizeHeading(marker.heading || 0).toString().padStart(3, '0');
    const bearing = Number.isFinite(marker.bearing) ? normalizeHeading(marker.bearing).toString().padStart(3, '0') : '';
    const labelX = marker.x + (marker.expanded ? 12 : 9);
    const labelY = marker.y - (marker.expanded ? 10 : 7);

    ctx.save();
    ctx.font = marker.expanded
      ? '800 10px ui-monospace, SFMono-Regular, Menlo, monospace'
      : '800 7.5px ui-monospace, SFMono-Regular, Menlo, monospace';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'top';
    const line1 = marker.subCode ? `${marker.code} ${marker.subCode}` : `${marker.code}${stale ? ' LOST' : ''}`;
    const line2 = `${trend} ${altitude}FT`;
    const line3 = marker.expanded
      ? `HDG ${heading}${bearing ? ` BRG ${bearing}` : ''}`
      : `H${heading}${bearing ? ` B${bearing}` : ''}`;
    const width = Math.max(ctx.measureText(line1).width, ctx.measureText(line2).width, ctx.measureText(line3).width) + 8;
    const height = marker.expanded ? 37 : 28;
    ctx.fillStyle = stale ? 'rgba(12, 18, 20, 0.72)' : marker.self ? 'rgba(34, 22, 4, 0.72)' : 'rgba(2, 20, 28, 0.72)';
    ctx.fillRect(labelX - 3, labelY - 2, width, height);
    ctx.strokeStyle = stale ? 'rgba(145, 163, 169, 0.72)' : marker.self ? 'rgba(255, 209, 102, 0.88)' : 'rgba(124, 244, 255, 0.84)';
    ctx.lineWidth = 1;
    ctx.strokeRect(labelX - 3, labelY - 2, width, height);
    ctx.fillStyle = color;
    ctx.fillText(line1, labelX, labelY);
    ctx.fillStyle = marker.self ? '#fff2bd' : '#dffbff';
    ctx.fillText(line2, labelX, labelY + (marker.expanded ? 12 : 9));
    ctx.fillStyle = stale ? '#b8c7cc' : marker.self ? '#ffe7a0' : '#bff8ff';
    ctx.fillText(line3, labelX, labelY + (marker.expanded ? 24 : 18));
    ctx.restore();
  }

  function drawUfoContactMarker(ctx, marker) {
    const { contact } = marker;
    const now = performance.now();
    const blinkDimmed = contact.intermittent && !contact.lost && Math.sin(now * 0.012) < -0.35;
    const size = marker.expanded ? 12 : 8;
    const pulse = 0.5 + 0.5 * Math.sin(now * 0.009);
    const color = contact.lost ? '#9fb7c2' : '#76d9ff';
    const glow = contact.signalDegraded ? '#ffd166' : color;

    ctx.save();
    ctx.globalAlpha = blinkDimmed ? 0.34 : 1;
    ctx.translate(marker.x, marker.y);
    ctx.strokeStyle = contact.lost
      ? 'rgba(159, 183, 194, 0.62)'
      : `rgba(118, 217, 255, ${0.58 + pulse * 0.22})`;
    ctx.fillStyle = contact.lost
      ? 'rgba(10, 17, 20, 0.62)'
      : `rgba(6, 29, 40, ${0.66 + pulse * 0.12})`;
    ctx.lineWidth = marker.expanded ? 1.8 : 1.25;
    ctx.setLineDash(contact.signalDegraded || contact.intermittent ? [4, 4] : []);
    ctx.beginPath();
    ctx.arc(0, 0, size * (1.2 + pulse * 0.25), 0, Math.PI * 2);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.beginPath();
    ctx.moveTo(0, -size);
    ctx.lineTo(size, 0);
    ctx.lineTo(0, size);
    ctx.lineTo(-size, 0);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = glow;
    ctx.stroke();
    if (!contact.lost && contact.fast) {
      ctx.strokeStyle = 'rgba(118, 217, 255, 0.48)';
      ctx.lineWidth = marker.expanded ? 2 : 1.4;
      ctx.beginPath();
      ctx.moveTo(-size * 2.2, size * 1.2);
      ctx.lineTo(size * 1.9, -size * 1.1);
      ctx.stroke();
    }
    ctx.restore();

    const altitude = Number.isFinite(contact.altitude) ? Math.max(0, Math.round(contact.altitude)) : null;
    const speed = contact.speedUnknown ? '---' : contact.fast || contact.speed >= 999 ? '999+' : contact.speed > 0 ? String(Math.round(contact.speed)) : '0';
    const heading = Number.isFinite(contact.heading) ? normalizeHeading(contact.heading).toString().padStart(3, '0') : '---';
    const line1 = contact.lost ? 'CONTACT LOST' : 'UNKNOWN CONTACT';
    const line2 = contact.lost
      ? 'SIGNAL LOST'
      : contact.visualContact ? 'VISUAL CONTACT'
        : contact.signalOffset ? 'SIGNAL OFFSET'
        : contact.hover ? 'HOVER' : `ALT ${altitude == null ? '----' : altitude}`;
    const line3 = contact.lost
      ? ''
      : contact.hover && !contact.speedUnknown ? 'SPD 0  HDG ---' : `SPD ${speed}  HDG ${heading}`;
    const line4 = contact.signalDegraded && !contact.lost ? 'SIGNAL DEGRADED' : '';
    let labelX = marker.x + (marker.expanded ? 15 : 11);
    let labelY = marker.y - (marker.expanded ? 15 : 10);

    ctx.save();
    ctx.globalAlpha = blinkDimmed ? 0.46 : 1;
    ctx.font = marker.expanded
      ? '850 10px ui-monospace, SFMono-Regular, Menlo, monospace'
      : '850 7.5px ui-monospace, SFMono-Regular, Menlo, monospace';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'top';
    const lines = [line1, line2, line3, line4].filter(Boolean);
    const width = Math.max(...lines.map(line => ctx.measureText(line).width)) + 9;
    const lineHeight = marker.expanded ? 12 : 9;
    const height = lines.length * lineHeight + 7;
    if (marker.bounds) {
      const pad = marker.expanded ? 8 : 4;
      const minX = marker.bounds.left + pad;
      const minY = marker.bounds.top + pad;
      const maxX = marker.bounds.left + marker.bounds.size - width - pad;
      const maxY = marker.bounds.top + marker.bounds.size - height - pad;
      if (labelX > maxX) labelX = marker.x - width - (marker.expanded ? 15 : 11);
      labelX = Math.min(Math.max(labelX, minX), Math.max(minX, maxX));
      labelY = Math.min(Math.max(labelY, minY), Math.max(minY, maxY));
    }
    ctx.fillStyle = contact.lost ? 'rgba(8, 13, 16, 0.75)' : 'rgba(1, 18, 27, 0.76)';
    ctx.fillRect(labelX - 3, labelY - 2, width, height);
    ctx.strokeStyle = contact.lost ? 'rgba(159, 183, 194, 0.74)' : 'rgba(118, 217, 255, 0.88)';
    ctx.lineWidth = 1;
    ctx.strokeRect(labelX - 3, labelY - 2, width, height);
    for (let i = 0; i < lines.length; i++) {
      ctx.fillStyle = i === 0 ? color : i === lines.length - 1 && line4 ? '#ffd166' : '#dffbff';
      ctx.fillText(lines[i], labelX, labelY + i * lineHeight);
    }
    ctx.restore();
  }

  function handleMapWheel(event) {
    event.preventDefault();
    const factor = event.deltaY < 0 ? 1.18 : 0.84;
    mapZoom = THREE.MathUtils.clamp(mapZoom * factor, 1, 6);
    clampMapPan();
    drawNavMap();
  }

  function panExpandedMap(deltaX, deltaY, canvas) {
    if (mapZoom <= 1) return;
    const rect = canvas.getBoundingClientRect();
    const viewSpan = MAP_SIZE / mapZoom;
    mapPanX -= deltaX / Math.max(1, rect.width) * viewSpan;
    mapPanZ -= deltaY / Math.max(1, rect.height) * viewSpan;
    clampMapPan();
    drawNavMap();
  }

  function resetMapView() {
    mapZoom = 1;
    mapPanX = 0;
    mapPanZ = 0;
    drawNavMap();
  }

  function clampMapPan() {
    const limit = Math.max(0, MAP_SIZE * 0.5 - MAP_SIZE / mapZoom * 0.5);
    mapPanX = THREE.MathUtils.clamp(mapPanX, -limit, limit);
    mapPanZ = THREE.MathUtils.clamp(mapPanZ, -limit, limit);
  }

  function nearestAirport() {
    let best = AIRPORTS[0];
    let bestDistance = Infinity;
    for (const airport of AIRPORTS) {
      const distance = Math.hypot(state.position.x - airport.x, state.position.z - airport.z);
      if (distance < bestDistance) {
        bestDistance = distance;
        best = airport;
      }
    }
    const name = window.innerWidth < 560 ? best.short || best.name : best.name;
    if (best.airportCategory === 'HIDDEN_REMOTE_AIRFIELD') {
      return { name: 'nothing there', distanceNm: bestDistance / 1852 };
    }
    const classTag = best.runwayClass || (best.tier === 'international' ? 'A' : best.tier === 'regional' ? 'B' : 'C');
    const a320Tag = best.a320Recommended === false ? ' NO A320' : best.a320Recommended === 'challenge' ? ' CHALLENGE' : '';
    const nightTag = best.isNightCapable === false ? ' NO LIGHT' : '';
    return { name: `${name} [${classTag}${a320Tag}${nightTag}]`, distanceNm: bestDistance / 1852 };
  }

  function normalizeHeading(deg) {
    return Math.round((deg % 360 + 360) % 360) % 360;
  }

  function currentHeadingDeg() {
    return normalizeHeading(-THREE.MathUtils.radToDeg(state.yaw));
  }

  return {
    updateHud,
    drawNavMap,
    currentHeadingDeg,
    handleMapWheel,
    panExpandedMap,
    resetMapView
  };
}
