// Generated by tools/buildVirtualSources.js from src/ui/renderDiagnostics/part-*/source.js. Do not edit directly.
const DEFAULT_UPDATE_HZ = 1;
const BYTE_TO_MB = 1 / (1024 * 1024);

export function createRenderDiagnostics({
  scene,
  renderer,
  state,
  qualityPresets,
  getQualityPreset,
  getNetworkDiagnostics = () => ({}),
  getPerformanceSnapshot = () => ({}),
  setQualityPreset,
  container = document.body,
  startVisible = false
}) {
  const panel = document.createElement('section');
  panel.className = `render-diagnostics collapsed${startVisible ? ' visible' : ''}`;
  panel.setAttribute('aria-label', 'Render diagnostics');
  panel.innerHTML = `
    <div class="render-diagnostics-head">
      <span>RENDER</span>
      <button type="button" data-diagnostics-toggle>${startVisible ? 'SHOW' : 'OPEN'}</button>
    </div>
    <div class="quality-switch" data-quality-switch></div>
    <dl class="render-diagnostics-grid" data-diagnostics-grid></dl>
  `;
  container.appendChild(panel);

  const grid = panel.querySelector('[data-diagnostics-grid]');
  const qualitySwitch = panel.querySelector('[data-quality-switch]');
  const toggle = panel.querySelector('[data-diagnostics-toggle]');
  const rows = new Map();
  const counters = createCounters();
  let frameAccumulator = 0;
  let frameCount = 0;
  let lastFrameTimeMs = 0;
  let cachedFps = null;

  for (const preset of Object.values(qualityPresets)) {
    const button = document.createElement('button');
    button.type = 'button';
    button.textContent = preset.label;
    button.dataset.quality = preset.key;
    button.addEventListener('click', event => {
      event.preventDefault();
      event.stopPropagation();
      setQualityPreset(preset.key);
      updateNow();
    });
    qualitySwitch.appendChild(button);
  }

  toggle.addEventListener('click', event => {
    event.preventDefault();
    event.stopPropagation();
    if (!panel.classList.contains('visible')) {
      panel.classList.add('visible');
      panel.classList.remove('collapsed');
      toggle.textContent = 'HIDE';
      updateNow();
      return;
    }
    panel.classList.toggle('collapsed');
    toggle.textContent = panel.classList.contains('collapsed') ? 'SHOW' : 'HIDE';
    if (!panel.classList.contains('collapsed')) updateNow();
  });

  window.addEventListener('keydown', event => {
    if (event.code !== 'F9') return;
    event.preventDefault();
    panel.classList.toggle('visible');
    if (panel.classList.contains('visible')) {
      panel.classList.remove('collapsed');
      toggle.textContent = 'HIDE';
      updateNow();
    }
  });

  function update(dt, frameStats = null) {
    lastFrameTimeMs = Number.isFinite(frameStats?.frameTimeMs) ? frameStats.frameTimeMs : dt * 1000;
    frameAccumulator += dt;
    frameCount++;
    if (!isCollecting()) return;
    const quality = getQualityPreset();
    const interval = 1 / Math.max(0.1, quality?.debugUpdateHz || DEFAULT_UPDATE_HZ);
    if (frameAccumulator < interval) return;
    cachedFps = frameCount / Math.max(0.001, frameAccumulator);
    updateNow(cachedFps, lastFrameTimeMs);
    frameAccumulator = 0;
    frameCount = 0;
  }

  function updateNow(fps = cachedFps, frameTimeMs = lastFrameTimeMs) {
    updateQualityButtons(getQualityPreset()?.key);
    if (!isCollecting()) return;

    resetCounters(counters);
    collectSceneCounters(scene, counters);
    const info = renderer.info;
    const geometryBytes = estimateGeometryBytes(counters.geometries);
    const textureBytes = (info.memory.textures || 0) * 4 * 1024 * 1024;
    const quality = getQualityPreset();
    const network = getNetworkDiagnostics() || {};
    const performanceStats = getPerformanceSnapshot() || {};
    const heapMb = jsHeapEstimateMb(performanceStats);

    setRow('FPS', fps == null ? '--' : fps.toFixed(0));
    setRow('frame time', `${frameTimeMs.toFixed(1)} ms`);
    setRow('max frame time 5s', formatMs(performanceStats.maxFrameTimeLast5sMs));
    setRow('1% low FPS', formatFps(performanceStats.onePercentLowFps));
    setRow('draw calls', info.render.calls.toLocaleString());
    setRow('triangles', info.render.triangles.toLocaleString());
    setRow('active lights', counters.activeLights.toLocaleString());
    setRow('visible chunks', counters.chunks.toLocaleString());
    setRow('JS heap estimate', heapMb == null ? '--' : `${heapMb.toFixed(1)} MB`);
    setRow('GC spike warning', performanceStats.gcSpikeWarning || 'no');
    setRow('long task count', Number(performanceStats.longTaskCount || 0).toLocaleString());
    setRow('visible buildings', counters.buildings.toLocaleString());
    setRow('visible trees', counters.trees.toLocaleString());
    setRow('visible aircraft', Math.max(counters.aircraft, state.multiplayerAircraft?.length || 1).toLocaleString());
    setRow('visible birds', counters.birds.toLocaleString());
    setRow('visible ships', counters.ships.toLocaleString());
    setRow('textures', info.memory.textures.toLocaleString());
    setRow('geometries', info.memory.geometries.toLocaleString());
    setRow('GPU memory est.', `${((geometryBytes + textureBytes) * BYTE_TO_MB).toFixed(1)} MB`);
    setRow('quality preset', `${quality.label}${quality.dynamicLevel ? ` - D${quality.dynamicLevel}` : ''}`);
    setRow('target FPS', quality.targetFPS || '--');
    setRow('pixelRatio', renderer.getPixelRatio().toFixed(2));
    setRow('real light limit', quality.realLightsLimit ?? '--');
    setRow('city lights', quality.cityLightsMode || '--');
    setRow('failed requests', formatCount(network.failedRequestsCount));
    setRow('pending requests', formatCount(network.pendingRequests));
    setRow('world loaded', network.worldLoaded ? 'yes' : 'no');
    setRow('multiplayer mode', network.multiplayerMode || 'local');
    setRow('session status', network.sessionStatus || '--');
    setRow('last API error', network.lastApiError || '--');
    setRow('asset missing', formatCount(network.assetMissingCount));
  }

  function isCollecting() {
    return panel.classList.contains('visible') && !panel.classList.contains('collapsed');
  }

  function setRow(label, value) {
    let row = rows.get(label);
    if (!row) {
      row = {
        term: document.createElement('dt'),
        value: document.createElement('dd')
      };
      row.term.textContent = label;
      grid.append(row.term, row.value);
      rows.set(label, row);
    }
    const text = String(value);
    if (row.value.textContent !== text) row.value.textContent = text;
  }

  function updateQualityButtons(activeKey) {
    for (const button of qualitySwitch.querySelectorAll('button')) {
      button.classList.toggle('active', button.dataset.quality === activeKey);
    }
  }

  updateQualityButtons(getQualityPreset()?.key);
  return { update, updateNow, isCollecting };
}

function createCounters() {
  return {
    activeLights: 0,
    chunks: 0,
    buildings: 0,
    trees: 0,
    birds: 0,
    aircraft: 0,
    ships: 0,
    geometries: new Set()
  };
}

function resetCounters(counters) {
  counters.activeLights = 0;
  counters.chunks = 0;
  counters.buildings = 0;
  counters.trees = 0;
  counters.birds = 0;
  counters.aircraft = 0;
  counters.ships = 0;
  counters.geometries.clear();
}

function collectSceneCounters(scene, counters) {
  scene.traverse(object => {
    if (!isWorldVisible(object)) return;
    if (object.isLight && (object.intensity ?? 0) > 0.001) counters.activeLights++;
    if (object.geometry) counters.geometries.add(object.geometry);
    const type = object.userData?.diagnosticType;
    const count = object.userData?.diagnosticCount || instanceCount(object);
    if (type === 'chunk') counters.chunks += count;
    if (type === 'building') counters.buildings += count;
    if (type === 'tree') counters.trees += count;
    if (type === 'bird') counters.birds += count;
    if (type === 'aircraft') counters.aircraft += count;
    if (type === 'ship') counters.ships += count;
  });
}

function isWorldVisible(object) {
  for (let current = object; current; current = current.parent) {
    if (!current.visible) return false;
  }
  return true;
}

function instanceCount(object) {
  if (object.isInstancedMesh) return object.count || 0;
  if (object.isPoints) return object.geometry?.attributes?.position?.count || 0;
  return 1;
}

function formatCount(value) {
  return Number(value || 0).toLocaleString();
}

function formatMs(value) {
  return Number.isFinite(value) ? `${value.toFixed(1)} ms` : '--';
}

function formatFps(value) {
  return Number.isFinite(value) ? value.toFixed(0) : '--';
}

function jsHeapEstimateMb(performanceStats) {
  if (Number.isFinite(performanceStats.jsHeapUsedMb)) return performanceStats.jsHeapUsedMb;
  const memory = performance.memory;
  if (!memory?.usedJSHeapSize) return null;
  return memory.usedJSHeapSize * BYTE_TO_MB;
}

function estimateGeometryBytes(geometries) {
  let bytes = 0;
  for (const geometry of geometries) {
    for (const attribute of Object.values(geometry.attributes || {})) {
      bytes += attribute.array?.byteLength || 0;
    }
    bytes += geometry.index?.array?.byteLength || 0;
  }
  return bytes;
}
