// Generated by tools/buildVirtualSources.js from src/world/AssetManager/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { RGBELoader } from '../vendor/RGBELoader.js?v=202605050057';
import { PATHS } from '../config/paths.js?v=202605060600';
import { markFailed, requestJson, shouldRetry } from '../utils/networkDiagnostics.js?v=202605060600';

const MAP_TYPES = ['albedo', 'normal', 'roughness', 'ao'];

export class AssetManager {
  constructor({
    manifestUrl = PATHS.assetManifest,
    anisotropy = 1
  } = {}) {
    this.manifestUrl = manifestUrl;
    this.anisotropy = anisotropy;
    this.textures = {};
    this.hdri = null;
    this.manifest = null;
  }

  async loadAll(onProgress = () => {}) {
    onProgress({ loaded: 0, total: 1, label: 'manifest' });
    this.manifest = await requestJson(this.manifestUrl, {}, { label: 'asset manifest', asset: true, retryAfter: 60000 });

    const textureJobs = [];
    for (const [name, entry] of Object.entries(this.manifest.textures || {})) {
      for (const type of MAP_TYPES) {
        const url = entry.maps?.[type];
        if (!url) continue;
        textureJobs.push({ name, type, url });
      }
    }

    const hdriUrl = this.manifest.hdri?.kloofendalPartlyCloudy;
    const total = textureJobs.length + (hdriUrl ? 1 : 0);
    let loaded = 0;
    const report = (label) => onProgress({ loaded, total, label });
    const textureLoader = new THREE.TextureLoader();

    await Promise.all(textureJobs.map(async (job) => {
      if (!shouldRetry(job.url)) {
        loaded++;
        report(`${job.name}/${job.type} skipped`);
        return;
      }
      try {
        const texture = await textureLoader.loadAsync(job.url);
        this.configureTexture(texture, job.type);
        this.textures[job.name] ??= {};
        this.textures[job.name][job.type] = texture;
      } catch {
        markFailed(job.url, { asset: true, retryAfter: 60000 });
      } finally {
        loaded++;
        report(`${job.name}/${job.type}`);
      }
    }));

    if (hdriUrl && shouldRetry(hdriUrl)) {
      const rgbeLoader = new RGBELoader();
      try {
        this.hdri = await rgbeLoader.loadAsync(hdriUrl);
        this.hdri.mapping = THREE.EquirectangularReflectionMapping;
      } catch {
        markFailed(hdriUrl, { asset: true, retryAfter: 60000 });
      }
      loaded++;
      report('hdri');
    } else if (hdriUrl) {
      loaded++;
      report('hdri skipped');
    }

    return {
      manifest: this.manifest,
      textures: this.textures,
      hdri: this.hdri
    };
  }

  configureTexture(texture, type) {
    texture.wrapS = THREE.RepeatWrapping;
    texture.wrapT = THREE.RepeatWrapping;
    texture.anisotropy = this.anisotropy;
    texture.colorSpace = type === 'albedo' ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    texture.needsUpdate = true;
  }

  dispose() {
    for (const pack of Object.values(this.textures)) {
      for (const texture of Object.values(pack)) {
        texture?.dispose?.();
      }
    }
    this.hdri?.dispose?.();
    this.textures = {};
    this.hdri = null;
  }
}
