// Generated by tools/buildVirtualSources.js from src/world/clouds/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { MAP_SIZE } from '../data/worldData.js?v=202605070100';

export function createCloudSystem({ scene, clouds, mulberry32 }) {
  const dummy = new THREE.Object3D();
  let baseMesh = null;
  let puffMesh = null;

  function createClouds() {
    if (baseMesh || puffMesh) return;
    const rng = mulberry32(7781);
    const cloudCount = 52;
    const baseInstances = [];
    const puffInstances = [];

    for (let i = 0; i < cloudCount; i++) {
      const cloud = {
        x: -MAP_SIZE * 0.56 + rng() * MAP_SIZE * 1.12,
        z: -MAP_SIZE * 0.56 + rng() * MAP_SIZE * 1.12,
        y: 820 + rng() * 1180,
        baseY: 0,
        rotationY: rng() * Math.PI * 2,
        driftX: -3.4 + rng() * 6.8,
        driftZ: 5.5 + rng() * 7.5,
        phase: rng() * Math.PI * 2,
        bob: 12 + rng() * 26,
        puffs: []
      };
      cloud.baseY = cloud.y;

      const puffs = 9 + Math.floor(rng() * 9);
      const spanX = 380 + rng() * 780;
      const spanZ = 120 + rng() * 240;
      const baseRadius = 76 + rng() * 48;
      const baseInstance = {
        cloud,
        lx: 0,
        ly: -10,
        lz: 0,
        sx: spanX / 96 * baseRadius,
        sy: (0.13 + rng() * 0.06) * baseRadius,
        sz: spanZ / 84 * baseRadius
      };
      cloud.baseInstance = baseInstance;
      baseInstances.push(baseInstance);

      for (let p = 0; p < puffs; p++) {
        const lane = puffs === 1 ? 0 : p / (puffs - 1) - 0.5;
        const radius = 48 + rng() * 58;
        const instance = {
          cloud,
          lx: lane * spanX + (rng() - 0.5) * 82,
          ly: (rng() - 0.5) * 34,
          lz: (rng() - 0.5) * spanZ,
          sx: radius * (2.1 + rng() * 1.25),
          sy: radius * (0.4 + rng() * 0.2),
          sz: radius * (0.95 + rng() * 0.56)
        };
        cloud.puffs.push(instance);
        puffInstances.push(instance);
      }

      clouds.push(cloud);
    }

    const puffGeometry = new THREE.SphereGeometry(1, 12, 6);
    const baseGeometry = new THREE.SphereGeometry(1, 12, 6);
    const puffMaterial = new THREE.MeshStandardMaterial({
      color: 0xffffff,
      emissive: 0xeaf8ff,
      emissiveIntensity: 0.18,
      transparent: true,
      opacity: 0.62,
      roughness: 0.48
    });
    const shadeMaterial = new THREE.MeshStandardMaterial({
      color: 0xf2fbff,
      emissive: 0xe4f4ff,
      emissiveIntensity: 0.12,
      transparent: true,
      opacity: 0.2,
      roughness: 0.66
    });

    baseMesh = new THREE.InstancedMesh(baseGeometry, shadeMaterial, baseInstances.length);
    puffMesh = new THREE.InstancedMesh(puffGeometry, puffMaterial, puffInstances.length);
    for (const mesh of [baseMesh, puffMesh]) {
      mesh.frustumCulled = false;
      mesh.userData.longRangeVisual = true;
      mesh.userData.diagnosticType = 'chunk';
      mesh.userData.diagnosticCount = 1;
      scene.add(mesh);
    }
    updateCloudMatrices(baseInstances, puffInstances);
  }

  function updateClouds(dt) {
    const wrap = MAP_SIZE / 2 + 820;
    for (const cloud of clouds) {
      cloud.phase += dt * 0.18;
      cloud.x += cloud.driftX * dt;
      cloud.z += cloud.driftZ * dt;
      cloud.y = cloud.baseY + Math.sin(cloud.phase) * cloud.bob;

      if (cloud.x > wrap) cloud.x = -wrap;
      if (cloud.x < -wrap) cloud.x = wrap;
      if (cloud.z > wrap) cloud.z = -wrap;
      if (cloud.z < -wrap) cloud.z = wrap;
    }

    if (!baseMesh || !puffMesh) return;
    updateCloudMatricesFromClouds();
  }

  function updateCloudMatricesFromClouds() {
    let baseIndex = 0;
    let puffIndex = 0;
    for (const cloud of clouds) {
      setCloudMatrix(baseMesh, baseIndex++, cloud.baseInstance);
      for (const puff of cloud.puffs) setCloudMatrix(puffMesh, puffIndex++, puff);
    }
    baseMesh.instanceMatrix.needsUpdate = true;
    puffMesh.instanceMatrix.needsUpdate = true;
  }

  function updateCloudMatrices(baseInstances, puffInstances) {
    for (let i = 0; i < baseInstances.length; i++) setCloudMatrix(baseMesh, i, baseInstances[i]);
    for (let i = 0; i < puffInstances.length; i++) setCloudMatrix(puffMesh, i, puffInstances[i]);
    baseMesh.instanceMatrix.needsUpdate = true;
    puffMesh.instanceMatrix.needsUpdate = true;
  }

  function setCloudMatrix(mesh, index, instance) {
    const cloud = instance.cloud;
    const cos = Math.cos(cloud.rotationY);
    const sin = Math.sin(cloud.rotationY);
    const x = cloud.x + instance.lx * cos + instance.lz * sin;
    const z = cloud.z - instance.lx * sin + instance.lz * cos;
    dummy.position.set(x, cloud.y + instance.ly, z);
    dummy.rotation.set(0, cloud.rotationY, 0);
    dummy.scale.set(instance.sx, instance.sy, instance.sz);
    dummy.updateMatrix();
    mesh.setMatrixAt(index, dummy.matrix);
  }

  return {
    createClouds,
    updateClouds
  };
}
