// Generated by tools/buildVirtualSources.js from src/world/lighting/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { DEFAULT_RENDER_QUALITY } from './visualQuality.js?v=202605070100';

export const DAY_DURATION_SECONDS = 600;

const TWO_PI = Math.PI * 2;
const DAY_COLORS = {
  top: 0x4ca9e8,
  upper: 0x9ad0f1,
  horizon: 0xe6f2f4,
  ground: 0x8dbad2,
  fog: 0xc2ddf2
};
const TWILIGHT_COLORS = {
  top: 0x376fa6,
  upper: 0x7fb0d4,
  horizon: 0xffb66f,
  ground: 0x6d8295,
  fog: 0xcfa982
};
const NIGHT_COLORS = {
  top: 0x071225,
  upper: 0x14213a,
  horizon: 0x1b2a40,
  ground: 0x0b1322,
  fog: 0x111b2b
};
const DAY_COLOR_CACHE = colorCache(DAY_COLORS);
const TWILIGHT_COLOR_CACHE = colorCache(TWILIGHT_COLORS);
const NIGHT_COLOR_CACHE = colorCache(NIGHT_COLORS);
const CYCLE_COLORS = {
  top: new THREE.Color(),
  upper: new THREE.Color(),
  horizon: new THREE.Color(),
  ground: new THREE.Color(),
  fog: new THREE.Color()
};
const SUN_TWILIGHT_COLOR = new THREE.Color(0xffa35d);
const MOON_NIGHT_COLOR = new THREE.Color(0x9fb7ff);
const NIGHT_MATERIAL_WORLD_POSITION = new THREE.Vector3();

export function initLights(scene, quality = DEFAULT_RENDER_QUALITY) {
  const hemi = new THREE.HemisphereLight(0xdff4ff, 0x31533b, 1.9);
  hemi.name = 'ultra-sky-fill';
  scene.add(hemi);

  const sun = new THREE.DirectionalLight(0xfff1d1, 4.15);
  sun.name = 'ultra-sun';
  sun.position.set(-4200, 9200, 2600);
  sun.castShadow = true;
  sun.shadow.bias = -0.00008;
  scene.add(sun);

  const moon = new THREE.DirectionalLight(0xaec8ff, 0.0);
  moon.name = 'ultra-moon-light';
  moon.position.set(3600, 4200, -2600);
  scene.add(moon);

  const horizonFill = new THREE.DirectionalLight(0x9fc9ff, 0.72);
  horizonFill.name = 'ultra-horizon-fill';
  horizonFill.position.set(5200, 2600, -4200);
  scene.add(horizonFill);

  const lights = { hemi, sun, moon, horizonFill };
  applyLightQuality(lights, quality);
  return lights;
}

export function applyLightQuality(lights, quality = DEFAULT_RENDER_QUALITY) {
  if (!lights?.sun) return;
  const size = quality.shadowMapSize ?? DEFAULT_RENDER_QUALITY.shadowMapSize;
  const extent = quality.shadowExtent ?? DEFAULT_RENDER_QUALITY.shadowExtent;
  const shadowFar = quality.shadowFar ?? DEFAULT_RENDER_QUALITY.shadowFar;
  lights.sun.userData.shadowEnabled = size > 0;
  lights.sun.castShadow = size > 0;
  lights.sun.shadow.mapSize.set(Math.max(1, size), Math.max(1, size));
  lights.sun.shadow.camera.left = -extent;
  lights.sun.shadow.camera.right = extent;
  lights.sun.shadow.camera.top = extent;
  lights.sun.shadow.camera.bottom = -extent;
  lights.sun.shadow.camera.near = 30;
  lights.sun.shadow.camera.far = shadowFar;
  lights.sun.shadow.normalBias = quality.shadowNormalBias ?? DEFAULT_RENDER_QUALITY.shadowNormalBias;
  lights.sun.shadow.camera.updateProjectionMatrix();
}

export function createSky(scene) {
  const skyMaterial = new THREE.ShaderMaterial({
    side: THREE.BackSide,
    depthWrite: false,
    depthTest: false,
    fog: false,
    uniforms: {
      topColor: { value: new THREE.Color(DAY_COLORS.top) },
      upperColor: { value: new THREE.Color(DAY_COLORS.upper) },
      horizonColor: { value: new THREE.Color(DAY_COLORS.horizon) },
      groundColor: { value: new THREE.Color(DAY_COLORS.ground) },
      sunDirection: { value: new THREE.Vector3(-0.42, 0.82, -0.24).normalize() },
      moonDirection: { value: new THREE.Vector3(0.42, -0.82, 0.24).normalize() },
      sunColor: { value: new THREE.Color(0xfff0c8) },
      moonColor: { value: new THREE.Color(0xcbd8ff) },
      sunAlpha: { value: 1.0 },
      moonAlpha: { value: 0.0 },
      starAlpha: { value: 0.0 },
      twilightAlpha: { value: 0.0 },
      time: { value: 0.0 }
    },
    vertexShader: `
      varying vec3 vDirection;
      void main() {
        vDirection = normalize(position.xyz);
        vec4 clipPosition = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        clipPosition.z = clipPosition.w;
        gl_Position = clipPosition;
      }
    `,
    fragmentShader: `
      precision highp float;
      varying vec3 vDirection;
      uniform vec3 topColor;
      uniform vec3 upperColor;
      uniform vec3 horizonColor;
      uniform vec3 groundColor;
      uniform vec3 sunDirection;
      uniform vec3 moonDirection;
      uniform vec3 sunColor;
      uniform vec3 moonColor;
      uniform float sunAlpha;
      uniform float moonAlpha;
      uniform float starAlpha;
      uniform float twilightAlpha;
      uniform float time;

      float hash21(vec2 p) {
        p = fract(p * vec2(123.34, 456.21));
        p += dot(p, p + 45.32);
        return fract(p.x * p.y);
      }

      float starField(vec3 dir) {
        float u = atan(dir.z, dir.x) / 6.28318530718 + 0.5;
        float v = asin(clamp(dir.y, -1.0, 1.0)) / 3.14159265359 + 0.5;
        vec2 grid = vec2(u * 280.0, v * 142.0);
        vec2 cell = floor(grid);
        vec2 local = fract(grid) - 0.5;
        float rnd = hash21(cell);
        float density = step(0.985, rnd);
        float size = mix(0.052, 0.018, hash21(cell + 13.7));
        float core = (1.0 - smoothstep(0.0, size, length(local))) * density;
        float twinkle = mix(0.58, 1.0, hash21(cell + floor(time * 0.18)));
        return core * twinkle * smoothstep(-0.02, 0.18, dir.y);
      }

      void main() {
        vec3 dir = normalize(vDirection);
        float h = dir.y;
        float upper = smoothstep(0.05, 0.78, h);
        float horizon = 1.0 - smoothstep(0.0, 0.28, abs(h));
        vec3 color = mix(groundColor, upperColor, smoothstep(-0.24, 0.25, h));
        color = mix(color, topColor, upper);
        color = mix(color, horizonColor, horizon * (0.65 + twilightAlpha * 0.22));

        float sunDot = dot(dir, normalize(sunDirection));
        float sunDisc = smoothstep(0.9998, 0.99996, sunDot);
        float sunGlow = pow(max(sunDot, 0.0), 560.0) * 0.58 + pow(max(sunDot, 0.0), 86.0) * 0.12;
        color += sunColor * (sunDisc * 1.16 + sunGlow) * sunAlpha;

        float moonDot = dot(dir, normalize(moonDirection));
        float moonDisc = smoothstep(0.99962, 0.9999, moonDot);
        float moonGlow = pow(max(moonDot, 0.0), 220.0) * 0.28 + pow(max(moonDot, 0.0), 36.0) * 0.08;
        float moonShade = 0.86 + 0.08 * sin(dir.x * 37.0 + dir.z * 21.0);
        color += moonColor * (moonDisc * moonShade + moonGlow) * moonAlpha;

        float stars = starField(dir) * starAlpha;
        color += vec3(0.72, 0.84, 1.0) * stars;
        gl_FragColor = vec4(color, 1.0);
      }
    `
  });

  const sky = new THREE.Mesh(new THREE.SphereGeometry(118000, 64, 32), skyMaterial);
  sky.name = 'ultra-atmospheric-sky';
  sky.frustumCulled = false;
  sky.renderOrder = -1000;
  sky.userData.backgroundSky = true;
  scene.add(sky);

  return {
    mesh: sky,
    material: skyMaterial,
    update(camera, state) {
      if (camera) sky.position.copy(camera.position);
      const uniforms = skyMaterial.uniforms;
      uniforms.topColor.value.copy(state.colors.top);
      uniforms.upperColor.value.copy(state.colors.upper);
      uniforms.horizonColor.value.copy(state.colors.horizon);
      uniforms.groundColor.value.copy(state.colors.ground);
      uniforms.sunDirection.value.copy(state.sunDirection);
      uniforms.moonDirection.value.copy(state.moonDirection);
      uniforms.sunColor.value.copy(state.sunColor);
      uniforms.moonColor.value.copy(state.moonColor);
      uniforms.sunAlpha.value = state.sunAlpha;
      uniforms.moonAlpha.value = state.moonAlpha;
      uniforms.starAlpha.value = state.starAlpha;
      uniforms.twilightAlpha.value = state.twilightFactor;
      uniforms.time.value = state.elapsedSeconds;
    }
  };
}

export function createDayNightCycle({ scene, renderer, camera, lights, sky, initialMode = 'day', getRenderQuality = null }) {
  let elapsedSeconds = normalizedForMode(initialMode) * DAY_DURATION_SECONDS;
  let nightLightAccumulator = 1;
  let previousNightLightFactor = -1;
  const sunDirection = new THREE.Vector3();
  const moonDirection = new THREE.Vector3();
  const sunColor = new THREE.Color();
  const moonColor = new THREE.Color(0xcbd8ff);

  function update(deltaTime = 0, serverTime = null) {
    if (Number.isFinite(serverTime?.normalized)) {
      const receivedAgoSeconds = Math.max(0, (performance.now() - (serverTime.receivedAtMs || performance.now())) / 1000);
      elapsedSeconds = ((serverTime.normalized + receivedAgoSeconds / DAY_DURATION_SECONDS) % 1) * DAY_DURATION_SECONDS;
    } else {
      elapsedSeconds = (elapsedSeconds + deltaTime) % DAY_DURATION_SECONDS;
    }
    const normalized = elapsedSeconds / DAY_DURATION_SECONDS;
    const state = computeCycleState(normalized, elapsedSeconds, sunDirection, moonDirection, sunColor, moonColor);

    sky.update(camera, state);
    updateLights(lights, state);
    updateAtmosphere(scene, renderer, state, getRenderQuality?.() || DEFAULT_RENDER_QUALITY);

    nightLightAccumulator += deltaTime;
    const quality = getRenderQuality?.() || DEFAULT_RENDER_QUALITY;
    const nightLightUpdateInterval = 1 / Math.max(0.1, quality.cityLightUpdateHz || 1);
    if (nightLightAccumulator >= nightLightUpdateInterval || Math.abs(state.nightLightFactor - previousNightLightFactor) > 0.035 || deltaTime === 0) {
      updateNightLinkedMaterials(scene, state.nightLightFactor, camera);
      previousNightLightFactor = state.nightLightFactor;
      nightLightAccumulator = 0;
    }

    return state;
  }

  return {
    update,
    get normalizedTime() {
      return elapsedSeconds / DAY_DURATION_SECONDS;
    },
    get clock12h() {
      return formatSimClock12h(elapsedSeconds / DAY_DURATION_SECONDS);
    },
    get clock24h() {
      return formatSimClock24h(elapsedSeconds / DAY_DURATION_SECONDS);
    }
  };
}

function computeCycleState(normalized, elapsedSeconds, sunDirection, moonDirection, sunColor, moonColor) {
  const sunAngle = normalized * TWO_PI;
  const sunHeight = Math.sin(sunAngle);
  sunDirection.set(Math.cos(sunAngle) * 0.92, sunHeight, Math.sin(sunAngle * 0.72) * 0.22 - 0.2).normalize();
  moonDirection.copy(sunDirection).multiplyScalar(-1);
  moonDirection.z += 0.18;
  moonDirection.normalize();

  const daylight = smoothstep(-0.05, 0.18, sunHeight);
  const nightFactor = 1 - smoothstep(-0.2, 0.08, sunHeight);
  const horizonSun = (1 - smoothstep(0.02, 0.46, Math.abs(sunHeight))) * smoothstep(-0.22, 0.1, sunHeight);
  const twilightFactor = THREE.MathUtils.clamp(horizonSun * (1 - nightFactor * 0.35), 0, 1);
  const moonHeight = moonDirection.y;

  sunColor.set(0xfff4d2).lerp(SUN_TWILIGHT_COLOR, twilightFactor * 0.82);
  moonColor.set(0xcbd8ff).lerp(MOON_NIGHT_COLOR, nightFactor * 0.32);

  const colors = CYCLE_COLORS;
  blendedSkyColor('top', daylight, nightFactor, twilightFactor, colors.top);
  blendedSkyColor('upper', daylight, nightFactor, twilightFactor, colors.upper);
  blendedSkyColor('horizon', daylight, nightFactor, twilightFactor, colors.horizon);
  blendedSkyColor('ground', daylight, nightFactor, twilightFactor, colors.ground);
  blendedSkyColor('fog', daylight, nightFactor, twilightFactor, colors.fog);

  const sunStrength = THREE.MathUtils.clamp((sunHeight + 0.06) / 1.04, 0, 1);
  const sunAlpha = smoothstep(-0.11, 0.08, sunHeight);
  const moonAlpha = smoothstep(-0.03, 0.15, moonHeight) * THREE.MathUtils.clamp(nightFactor + twilightFactor * 0.25, 0, 1);
  const starAlpha = smoothstep(0.22, 0.72, nightFactor) * (1 - twilightFactor * 0.34);
  const nightLightFactor = THREE.MathUtils.clamp(nightFactor + twilightFactor * 0.48, 0, 1);

  return {
    elapsedSeconds,
    normalized,
    clock12h: formatSimClock12h(normalized),
    clock24h: formatSimClock24h(normalized),
    sunDirection,
    moonDirection,
    sunColor,
    moonColor,
    colors,
    sunHeight,
    moonHeight,
    daylight,
    nightFactor,
    twilightFactor,
    sunStrength,
    sunAlpha,
    moonAlpha,
    starAlpha,
    nightLightFactor
  };
}

function updateLights(lights, state) {
  if (!lights) return;
  if (lights.sun) {
    lights.sun.position.copy(state.sunDirection).multiplyScalar(10000);
    lights.sun.color.copy(state.sunColor);
    lights.sun.intensity = THREE.MathUtils.lerp(0.02, 4.15, Math.pow(state.sunStrength, 0.72)) * (1 - state.nightFactor * 0.96);
    lights.sun.castShadow = lights.sun.userData.shadowEnabled !== false && state.sunStrength > 0.02;
  }
  if (lights.moon) {
    lights.moon.position.copy(state.moonDirection).multiplyScalar(9000);
    lights.moon.color.copy(state.moonColor);
    lights.moon.intensity = 0.36 * state.moonAlpha;
  }
  if (lights.hemi) {
    lights.hemi.color.copy(state.colors.upper);
    lights.hemi.groundColor.copy(state.colors.ground);
    lights.hemi.intensity = THREE.MathUtils.lerp(0.34, 1.92, state.daylight) + state.twilightFactor * 0.18;
  }
  if (lights.horizonFill) {
    lights.horizonFill.color.copy(state.colors.horizon);
    lights.horizonFill.intensity = THREE.MathUtils.lerp(0.12, 0.72, state.daylight) + state.twilightFactor * 0.34;
  }
}

function updateAtmosphere(scene, renderer, state, quality = DEFAULT_RENDER_QUALITY) {
  if (scene.background?.isColor) scene.background.copy(state.colors.upper);
  else scene.background = state.colors.upper.clone();
  if (scene.fog) {
    scene.fog.color.copy(state.colors.fog);
    scene.fog.density = THREE.MathUtils.lerp(quality.fogNightDensity, quality.fogDayDensity, state.daylight) +
      state.twilightFactor * 0.0000012;
  }
  renderer.toneMappingExposure = THREE.MathUtils.lerp(0.78, 1.14, state.daylight) - state.twilightFactor * 0.04;
}

function updateNightLinkedMaterials(scene, nightLightFactor, camera = null) {
  scene.traverse(object => {
    const material = object.material;
    if (!material) return;
    if (Array.isArray(material)) {
      for (const item of material) updateNightMaterial(item, object, nightLightFactor, camera);
      return;
    }
    updateNightMaterial(material, object, nightLightFactor, camera);
  });
}

function updateNightMaterial(material, object, nightLightFactor, camera = null) {
  const nightVisualFactor = smoothstep(0.02, 0.24, nightLightFactor);
  if (material.userData?.nightPbrControlled) {
    if (material.userData.dayRoughness !== undefined && material.userData.nightRoughness !== undefined) {
      material.roughness = THREE.MathUtils.lerp(material.userData.dayRoughness, material.userData.nightRoughness, nightLightFactor);
    }
    if (material.userData.dayEnvMapIntensity !== undefined && material.userData.nightEnvMapIntensity !== undefined) {
      material.envMapIntensity = THREE.MathUtils.lerp(material.userData.dayEnvMapIntensity, material.userData.nightEnvMapIntensity, nightLightFactor);
    }
    if (material.emissive && material.userData.dayEmissiveIntensity !== undefined && material.userData.nightEmissiveIntensity !== undefined) {
      material.emissiveIntensity = THREE.MathUtils.lerp(material.userData.dayEmissiveIntensity, material.userData.nightEmissiveIntensity, nightLightFactor);
    }
    material.needsUpdate = true;
  }
  if (material.userData?.nightControlled) {
    const lodAlpha = material.userData.cityWindowLod === 'near' ? cityNearWindowAlpha(object, material, camera) : 1;
    material.opacity = THREE.MathUtils.lerp(material.userData.baseOpacity, material.userData.nightOpacity, nightVisualFactor) * lodAlpha;
    if (material.userData.nightOnlyVisual && object) object.visible = material.opacity > 0.001;
    material.needsUpdate = true;
  }
  if (object.userData.nightLight) {
    const lodAlpha = object.userData.cityFarWindowLight ? cityFarWindowAlpha(object, camera) : 1;
    material.opacity = object.userData.baseOpacity * THREE.MathUtils.lerp(0, 1.34, nightVisualFactor) * lodAlpha;
    material.size = object.userData.baseSize * THREE.MathUtils.lerp(0.72, 1.18, nightVisualFactor);
    object.visible = material.opacity > 0.001;
    material.needsUpdate = true;
  }
  if (object.userData.nightGlow) {
    material.opacity = THREE.MathUtils.lerp(object.userData.baseOpacity, object.userData.nightOpacity, nightVisualFactor);
    if (object.userData.nightOnlyVisual) object.visible = material.opacity > 0.001;
    material.needsUpdate = true;
  }
}

function cityNearWindowAlpha(object, material, camera) {
  if (!camera || !object?.getWorldPosition) return 1;
  object.getWorldPosition(NIGHT_MATERIAL_WORLD_POSITION);
  const distance = NIGHT_MATERIAL_WORLD_POSITION.distanceTo(camera.position);
  const start = material.userData.nearFadeStart ?? 2600;
  const end = Math.max(start + 1, material.userData.nearFadeEnd ?? 6200);
  return 1 - smoothstep(start, end, distance);
}

function cityFarWindowAlpha(object, camera) {
  if (!camera || !object?.getWorldPosition) return 1;
  object.getWorldPosition(NIGHT_MATERIAL_WORLD_POSITION);
  const distance = NIGHT_MATERIAL_WORLD_POSITION.distanceTo(camera.position);
  const start = object.userData.farFadeStart ?? 2200;
  const end = Math.max(start + 1, object.userData.farFadeEnd ?? 6200);
  return smoothstep(start, end, distance);
}

function blendedSkyColor(key, daylight, nightFactor, twilightFactor, target = new THREE.Color()) {
  target.copy(NIGHT_COLOR_CACHE[key]).lerp(DAY_COLOR_CACHE[key], daylight);
  target.lerp(TWILIGHT_COLOR_CACHE[key], twilightFactor * (1 - nightFactor * 0.4));
  return target;
}

function colorCache(source) {
  const cache = {};
  for (const [key, value] of Object.entries(source)) cache[key] = new THREE.Color(value);
  return cache;
}

function normalizedForMode(mode) {
  const normalized = `${mode || 'day'}`.toLowerCase();
  if (normalized.includes('night')) return 0.75;
  if (normalized.includes('dusk') || normalized.includes('sunset')) return 0.49;
  if (normalized.includes('dawn') || normalized.includes('sunrise')) return 0.99;
  if (normalized.includes('morning')) return 0.08;
  return 0.25;
}

function formatSimClock12h(normalized) {
  const totalMinutes = simClockTotalMinutes(normalized);
  const hour24 = Math.floor(totalMinutes / 60);
  const minute = totalMinutes % 60;
  const suffix = hour24 >= 12 ? 'PM' : 'AM';
  const hour12 = hour24 % 12 || 12;
  return `${String(hour12).padStart(2, '0')}:${String(minute).padStart(2, '0')} ${suffix}`;
}

function formatSimClock24h(normalized) {
  const totalMinutes = simClockTotalMinutes(normalized);
  const hour24 = Math.floor(totalMinutes / 60);
  const minute = totalMinutes % 60;
  return `${String(hour24).padStart(2, '0')}:${String(minute).padStart(2, '0')}`;
}

function simClockTotalMinutes(normalized) {
  return Math.floor((((normalized * 24 + 6) % 24) * 60) + 0.5) % (24 * 60);
}

function smoothstep(edge0, edge1, x) {
  const t = THREE.MathUtils.clamp((x - edge0) / (edge1 - edge0), 0, 1);
  return t * t * (3 - 2 * t);
}
