// Generated by tools/buildVirtualSources.js from src/world/roads/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { BRIDGES, CONNECTING_ROADS, RIVER_SURFACE_Y, RIVER_SYSTEMS, WATER_LEVEL } from '../data/worldData.js?v=202605070100';
import { distanceToRiver, isInAirportExclusionZone, liftSurfaceMaterial, roadSegmentAirportBlocked } from './spatial.js?v=202605056000';

export function createRoadSystem({ scene, terrainHeight, waterBands }) {
  const roadIntegrityReport = {
    totalRoads: 0,
    floatingRoadSegments: 0,
    roadSegmentsInRiversSea: 0,
    roadSegmentsInsideAirportZones: 0,
    roadSegmentsCrossingRunway: 0,
    fixedCount: 0,
    bridgeReport: {
      totalBridgesAdded: 0,
      smallBridgesCount: 0,
      mediumBridgesCount: 0,
      largeBridgesCount: 0,
      bridgesWithValidRamps: 0,
      floatingBridgeCount: 0,
      bridgeRoadMisalignmentCount: 0,
      bridgesOverlappingAirportZones: 0,
      bridgesFixedCount: 0
    },
    riverCrossingReport: {
      riverRoadCrossingsDetected: 0,
      crossingsConvertedToBridges: 0,
      unresolvedCrossings: 0
    }
  };

  function createRoadIntegrityReport() {
    return JSON.parse(JSON.stringify(roadIntegrityReport));
  }

  function createBridge(bridge, bridgeMaterial, roadMaterial, railMaterial, stripeMaterial, underBridgeWaterMaterial) {
    const placement = bridgeRiverPlacement(bridge);
    const group = new THREE.Group();
    const bridgeType = bridge.type || bridgeTypeForProfile(bridge);
    const deckY = Math.max(terrainHeight(placement.x, placement.z) + (bridge.lift || 10), WATER_LEVEL + (bridge.clearance || 24));
    group.name = `${bridge.name || 'regional'}-${bridgeType}-bridge`;
    group.position.set(placement.x, deckY, placement.z);
    group.rotation.y = placement.heading;
    group.userData.bridge = true;
    group.userData.bridgeType = bridgeType;
    group.userData.riverRoadBridge = true;
    group.userData.regionalBridge = true;
    group.userData.deckLength = bridge.length;
    group.userData.rampLength = Math.max(150, bridge.width * 2.45);
    scene.add(group);

    createBridgeUnderflow(bridge, underBridgeWaterMaterial, placement);

    const deck = new THREE.Mesh(new THREE.BoxGeometry(bridge.width, 7.5, bridge.length), bridgeMaterial);
    deck.castShadow = true;
    deck.receiveShadow = true;
    group.add(deck);

    const surface = new THREE.Mesh(new THREE.BoxGeometry(bridge.width - 10, 0.65, bridge.length + 18), roadMaterial);
    surface.position.y = 4.08;
    surface.receiveShadow = true;
    group.add(surface);
    const rampsValid = createBridgeApproaches(group, placement, bridge, roadMaterial, railMaterial, stripeMaterial, 4.08);

    for (const side of [-1, 1]) {
      const rail = new THREE.Mesh(new THREE.BoxGeometry(4.2, 9.5, bridge.length + 26), railMaterial);
      rail.position.set(side * (bridge.width / 2 - 3), 9.2, 0);
      rail.castShadow = true;
      group.add(rail);
    }

    const pierHeight = Math.max(18, deckY - WATER_LEVEL + 3);
    const pierSpacing = bridgeType === 'large' ? 105 : bridgeType === 'medium' ? 132 : bridge.length + 1;
    for (let z = -bridge.length / 2 + 70; z <= bridge.length / 2 - 70; z += pierSpacing) {
      for (const x of [-bridge.width * 0.32, bridge.width * 0.32]) {
        const pier = new THREE.Mesh(
          new THREE.CylinderGeometry(5.8, 7.2, pierHeight, 12),
          new THREE.MeshStandardMaterial({ color: 0x8a9298, roughness: 0.76 })
        );
        pier.position.set(x, WATER_LEVEL - deckY + pierHeight / 2, z);
        pier.castShadow = true;
        group.add(pier);
      }
    }

    if (bridgeType === 'medium') {
      for (const z of [-bridge.length * 0.24, bridge.length * 0.24]) {
        const crossBeam = new THREE.Mesh(new THREE.BoxGeometry(bridge.width + 18, 4.2, 7), railMaterial);
        crossBeam.position.set(0, 6.2, z);
        crossBeam.castShadow = true;
        group.add(crossBeam);
      }
    } else if (bridgeType === 'large') {
      for (const z of [-bridge.length * 0.28, bridge.length * 0.28]) {
        for (const x of [-bridge.width * 0.42, bridge.width * 0.42]) {
          const tower = new THREE.Mesh(
            new THREE.BoxGeometry(9, 42, 11),
            new THREE.MeshStandardMaterial({ color: 0xb5bdc4, roughness: 0.62 })
          );
          tower.position.set(x, 27, z);
          tower.castShadow = true;
          group.add(tower);
        }
        const crossBeam = new THREE.Mesh(new THREE.BoxGeometry(bridge.width + 26, 6, 8), railMaterial);
        crossBeam.position.set(0, 49, z);
        crossBeam.castShadow = true;
        group.add(crossBeam);
      }
    }

    for (let z = -bridge.length / 2 + 48; z < bridge.length / 2; z += 86) {
      const stripe = new THREE.Mesh(new THREE.BoxGeometry(4, 0.12, 30), stripeMaterial);
      stripe.position.set(0, 4.46, z);
      group.add(stripe);
    }

    recordBridge(bridgeType, rampsValid, deckY, bridge.clearance || 24, bridge);
  }

  function createRoadSegment(road, roadMaterial, stripeMaterial) {
    const a = { x: road.x1, z: road.z1 };
    const b = { x: road.x2, z: road.z2 };
    if (roadSegmentAirportBlocked(a, b)) {
      roadIntegrityReport.fixedCount++;
      return;
    }

    const ranges = groundRoadClearRanges(a, b, road.width);
    if (!ranges.length) roadIntegrityReport.fixedCount++;
    for (const range of ranges) {
      const start = pointOnSegment(a, b, range.start);
      const end = pointOnSegment(a, b, range.end);
      createTerrainRoadPiece(start, end, road.width, roadMaterial, stripeMaterial);
    }
  }

  function createBridgesAndRoads() {
    const roadMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({ color: 0x2b3033, roughness: 0.86 }), -1, -1);
    const stripeMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({ color: 0xe4e9ed, roughness: 0.55 }), -2, -2);
    const bridgeMaterial = new THREE.MeshStandardMaterial({ color: 0x65707a, roughness: 0.72, metalness: 0.04 });
    const railMaterial = new THREE.MeshStandardMaterial({ color: 0xd6dde3, roughness: 0.48, metalness: 0.08 });
    const underBridgeWaterMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({
      color: 0x257fa7,
      emissive: 0x0b354e,
      emissiveIntensity: 0.1,
      roughness: 0.16,
      metalness: 0.16,
      depthWrite: true
    }), -5, -5);
  
    for (const road of CONNECTING_ROADS) createRoadSegment(road, roadMaterial, stripeMaterial);
    for (const bridge of BRIDGES) {
      roadIntegrityReport.riverCrossingReport.riverRoadCrossingsDetected++;
      createBridge(bridge, bridgeMaterial, roadMaterial, railMaterial, stripeMaterial, underBridgeWaterMaterial);
      roadIntegrityReport.riverCrossingReport.crossingsConvertedToBridges++;
    }
  }

  function createBridgeApproaches(group, placement, bridge, roadMaterial, railMaterial, stripeMaterial, deckY) {
    const rampLength = Math.max(150, bridge.width * 2.45);
    const roadWidth = bridge.width - 12;
    let rampsValid = true;
  
    for (const end of [-1, 1]) {
      const deckZ = end * (bridge.length / 2 + 8);
      const farZ = end * (bridge.length / 2 + rampLength + 54);
      const farWorld = bridgeLocalToWorld(placement, 0, farZ);
      const groundY = terrainHeight(farWorld.x, farWorld.z) - group.position.y + 1.05;
      const centerZ = end * (bridge.length / 2 + rampLength / 2 + 31);
      const centerY = (deckY + groundY) / 2;
      const slope = Math.atan2(deckY - groundY, rampLength);
      if (Math.abs(deckY - groundY) / Math.max(1, rampLength) > 0.18) rampsValid = false;
  
      const ramp = new THREE.Mesh(new THREE.BoxGeometry(roadWidth, 0.58, rampLength + 48), roadMaterial);
      ramp.position.set(0, centerY, centerZ);
      ramp.rotation.x = end * slope;
      ramp.receiveShadow = true;
      group.add(ramp);
  
      const apron = new THREE.Mesh(new THREE.BoxGeometry(roadWidth + 18, 0.32, 86), roadMaterial);
      apron.position.set(0, groundY, end * (bridge.length / 2 + rampLength + 92));
      apron.rotation.x = end * slope * 0.28;
      apron.receiveShadow = true;
      group.add(apron);
  
      for (const side of [-1, 1]) {
        const curb = new THREE.Mesh(new THREE.BoxGeometry(3.2, 3.8, rampLength + 40), railMaterial);
        curb.position.set(side * (roadWidth / 2 - 1.2), centerY + 1.75, centerZ);
        curb.rotation.x = ramp.rotation.x;
        curb.castShadow = true;
        group.add(curb);
      }
  
      for (let z = deckZ + end * 42; Math.abs(z) < Math.abs(farZ) - 30; z += end * 74) {
        const t = THREE.MathUtils.clamp((Math.abs(z) - bridge.length / 2) / Math.max(1, rampLength), 0, 1);
        const y = THREE.MathUtils.lerp(deckY + 0.34, groundY + 0.22, t);
        const stripe = new THREE.Mesh(new THREE.BoxGeometry(4, 0.08, 26), stripeMaterial);
        stripe.position.set(0, y, z);
        stripe.rotation.x = end * slope;
        group.add(stripe);
      }
    }
    return rampsValid;
  }

  function bridgeTypeForProfile(bridge) {
    if ((bridge.length || 0) >= 620 || (bridge.width || 0) >= 70) return 'large';
    if ((bridge.length || 0) >= 500 || (bridge.width || 0) >= 58) return 'medium';
    return 'small';
  }

  function recordBridge(type, rampsValid, deckY, clearance, bridge) {
    const report = roadIntegrityReport.bridgeReport;
    report.totalBridgesAdded++;
    if (type === 'large') report.largeBridgesCount++;
    else if (type === 'medium') report.mediumBridgesCount++;
    else report.smallBridgesCount++;
    if (rampsValid) report.bridgesWithValidRamps++;
    else report.bridgesFixedCount++;
    if (deckY < WATER_LEVEL + Math.max(10, clearance * 0.55) || deckY > terrainHeight(bridge.x, bridge.z) + 38) report.floatingBridgeCount++;
    if (isInAirportExclusionZone(bridge.x, bridge.z, Math.max(36, (bridge.width || 50) * 0.45), { approach: false, runwaySafety: false, pavement: true })) {
      report.bridgesOverlappingAirportZones++;
    }
  }

  function bridgeLocalToWorld(placement, x, z) {
    const c = Math.cos(placement.heading);
    const s = Math.sin(placement.heading);
    return { x: placement.x + c * x + s * z, z: placement.z - s * x + c * z };
  }

  function bridgeRiverPlacement(bridge) {
    let best = null;
    for (const river of RIVER_SYSTEMS) {
      for (let i = 0; i < river.length - 1; i++) {
        const a = river[i];
        const b = river[i + 1];
        const dx = b.x - a.x;
        const dz = b.z - a.z;
        const lengthSq = dx * dx + dz * dz;
        const t = THREE.MathUtils.clamp(((bridge.x - a.x) * dx + (bridge.z - a.z) * dz) / lengthSq, 0, 1);
        const x = a.x + dx * t;
        const z = a.z + dz * t;
        const distance = Math.hypot(bridge.x - x, bridge.z - z);
        if (!best || distance < best.distance) {
          best = {
            x,
            z,
            distance,
            heading: Math.atan2(-dz, dx)
          };
        }
      }
    }
    return best || { x: bridge.x, z: bridge.z, heading: bridge.heading || 0 };
  }

  function createBridgeUnderflow(bridge, underBridgeWaterMaterial, placement) {
    const group = new THREE.Group();
    group.position.set(placement.x, RIVER_SURFACE_Y + 0.08, placement.z);
    group.rotation.y = placement.heading;
    scene.add(group);
  
    const water = new THREE.Mesh(
      new THREE.BoxGeometry(bridge.length + 170, 0.16, Math.max(150, bridge.width * 2.6)),
      underBridgeWaterMaterial.clone()
    );
    water.receiveShadow = true;
    water.renderOrder = 2;
    group.add(water);
  
    const flowMaterial = liftSurfaceMaterial(new THREE.MeshBasicMaterial({ color: 0xd7fbff, transparent: true, opacity: 0.14, depthWrite: false }), -7, -7);
    for (let i = -3; i <= 3; i++) {
      const flow = new THREE.Mesh(new THREE.BoxGeometry(82, 0.12, 2.6), flowMaterial.clone());
      flow.position.set(i * 82, 0.34, (i % 2) * 18);
      flow.renderOrder = 4;
      group.add(flow);
      waterBands.push({ mesh: flow, baseX: flow.position.x, phase: i * 0.7 + bridge.x * 0.002, speed: 0.42, travel: 12, worldAxis: false });
    }
  }

  function groundRoadClearRanges(a, b, width, samples = 48) {
    const ranges = [];
    let start = null;
    let lastClear = null;

    for (let i = 0; i <= samples; i++) {
      const t = i / samples;
      const point = pointOnSegment(a, b, t);
      const clear = isGroundRoadPointClear(point.x, point.z, width);

      if (clear && start === null) start = t;
      if (clear) lastClear = t;

      if ((!clear || i === samples) && start !== null) {
        const from = Math.max(0, start + 0.5 / samples);
        const to = Math.min(1, lastClear - 0.5 / samples);
        if (to - from > 0.08) ranges.push({ start: from, end: to });
        start = null;
        lastClear = null;
      }
    }

    return ranges;
  }

  function isGroundRoadPointClear(x, z, width) {
    const riverClearance = Math.max(142, width * 2.85);
    if (isInAirportExclusionZone(x, z, Math.max(58, width * 1.5))) return false;
    if (distanceToRiver(x, z) < riverClearance) return false;
    const y = terrainHeight(x, z);
    if (y < WATER_LEVEL + 2.5) return false;
    return true;
  }

  function createTerrainRoadPiece(a, b, width, roadMaterial, stripeMaterial) {
    const dx = b.x - a.x;
    const dz = b.z - a.z;
    const length = Math.hypot(dx, dz);
    if (length < 70) return;
    if (!terrainRoadFits(a, b, width)) {
      roadIntegrityReport.fixedCount++;
      return;
    }

    if (createTerrainRoadStrip(a, b, width, roadMaterial, 1.05, 2)) roadIntegrityReport.totalRoads++;

    const dirX = dx / length;
    const dirZ = dz / length;
    for (let offset = 36; offset < length - 36; offset += 72) {
      const center = { x: a.x + dirX * offset, z: a.z + dirZ * offset };
      if (!isGroundRoadPointClear(center.x, center.z, width)) continue;
      createTerrainRoadStrip(
        { x: center.x - dirX * 13, z: center.z - dirZ * 13 },
        { x: center.x + dirX * 13, z: center.z + dirZ * 13 },
        3.5,
        stripeMaterial,
        1.34,
        3
      );
    }
  }

  function createTerrainRoadStrip(a, b, width, material, lift, renderOrder) {
    const dx = b.x - a.x;
    const dz = b.z - a.z;
    const length = Math.hypot(dx, dz);
    if (length < 1) return null;

    const dirX = dx / length;
    const dirZ = dz / length;
    const normalX = -dirZ;
    const normalZ = dirX;
    const segments = Math.max(2, Math.ceil(length / 80));
    const halfWidth = width / 2;
    const positions = [];
    const indices = [];

    for (let i = 0; i <= segments; i++) {
      const t = i / segments;
      const cx = THREE.MathUtils.lerp(a.x, b.x, t);
      const cz = THREE.MathUtils.lerp(a.z, b.z, t);
      for (const side of [-1, 1]) {
        const x = cx + normalX * halfWidth * side;
        const z = cz + normalZ * halfWidth * side;
        positions.push(x, terrainHeight(x, z) + lift, z);
      }
    }

    for (let i = 0; i < segments; i++) {
      const row = i * 2;
      indices.push(row, row + 2, row + 1, row + 1, row + 2, row + 3);
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geometry.setIndex(indices);
    geometry.computeVertexNormals();
    const mesh = new THREE.Mesh(geometry, material);
    mesh.receiveShadow = true;
    mesh.renderOrder = renderOrder;
    scene.add(mesh);
    return mesh;
  }

  function terrainRoadFits(a, b, width) {
    const length = Math.hypot(b.x - a.x, b.z - a.z);
    const samples = Math.max(3, Math.ceil(length / 95));
    let minY = Infinity;
    let maxY = -Infinity;

    for (let i = 0; i <= samples; i++) {
      const point = pointOnSegment(a, b, i / samples);
      if (!isGroundRoadPointClear(point.x, point.z, width)) return false;
      const y = terrainHeight(point.x, point.z);
      minY = Math.min(minY, y);
      maxY = Math.max(maxY, y);
    }

    return maxY - minY < 46;
  }

  function pointOnSegment(a, b, t) {
    return {
      x: THREE.MathUtils.lerp(a.x, b.x, t),
      z: THREE.MathUtils.lerp(a.z, b.z, t)
    };
  }

  return { createBridgesAndRoads, createRoadIntegrityReport };
}
