// Generated by tools/buildVirtualSources.js from src/world/spatial/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { AIRPORTS, BAYS, EDGE_OCEAN_WIDTH, ISLANDS, LAKES, LANDMASSES, MAP_SIZE, RIVER_SYSTEMS } from '../data/worldData.js?v=202605070100';

export function airportLocal(airport, x, z) {
  const dx = x - airport.x;
  const dz = z - airport.z;
  const c = Math.cos(airport.heading || 0);
  const s = Math.sin(airport.heading || 0);
  return { x: c * dx - s * dz, z: s * dx + c * dz };
}

export function airportPavementRects(airport, margin = 0) {
  const size = airport.size || 1;
  const runwayLength = airport.runwayLength || 1320;
  const runwayWidth = airport.runwayWidth || 98;
  const taxiX = runwayWidth * 1.18 + 70 * size;
  const taxiZ = runwayLength * 0.08;
  const taxiLength = Math.max(430 * size, runwayLength * 0.45);
  const apronW = airport.apronWidth || 420 * size;
  const apronD = airport.apronDepth || 310 * size;
  const apronX = taxiX + apronW * 0.45;
  const apronZ = runwayLength * 0.16;

  return [
    { x: 0, z: 0, halfX: runwayWidth * 1.38 + margin, halfZ: runwayLength / 2 + 158 + margin },
    { x: taxiX, z: taxiZ, halfX: Math.max(54, 66 * size) / 2 + 34 + margin, halfZ: taxiLength / 2 + 104 + margin },
    { x: taxiX * 0.52, z: -runwayLength * 0.16, halfX: taxiX * 0.6 + margin, halfZ: Math.max(34, 42 * size) + margin },
    { x: apronX, z: apronZ, halfX: apronW / 2 + 126 + margin, halfZ: apronD / 2 + 126 + margin }
  ];
}

export function airportWorld(airport, x, z) {
  const c = Math.cos(airport.heading || 0);
  const s = Math.sin(airport.heading || 0);
  return { x: airport.x + c * x + s * z, z: airport.z - s * x + c * z };
}

export function applyChallengeApproachTerrain(height, airport, local) {
  if (!airport.challenge) return height;

  const runwayLength = airport.runwayLength || 1320;
  const runwayWidth = airport.runwayWidth || 98;
  const elevation = airport.elevation || 0;
  const endSign = Math.sign(airport.challenge.end || 1);
  const threshold = runwayLength / 2;
  const along = endSign > 0 ? local.z - threshold : -local.z - threshold;
  if (along <= 80 || along > 1850) return height;
  const world = airportWorld(airport, local.x, local.z);
  if (isNearOtherAirportSafety(airport, world.x, world.z, 280, 980)) return height;

  const cross = local.x;
  const wallDistance = airport.challenge.wallDistance || 560;
  const wallHeight = airport.challenge.wallHeight || 220;
  const wallBand = 1 - smoothstep(240, 820, Math.abs(along - wallDistance));
  const wallWide = 1 - smoothstep(runwayWidth * 2.8, runwayWidth * 12.2, Math.abs(cross));
  const wall = Math.max(0, wallBand * wallWide);
  if (wall > 0) {
    const centerBreak = 0.22 * (1 - smoothstep(runwayWidth * 1.2, runwayWidth * 3.4, Math.abs(cross)));
    const lateralRidges =
      0.62 +
      0.2 * Math.sin(cross * 0.009 + airport.heading * 4) +
      0.18 * Math.sin((cross + along) * 0.005);
    const naturalWall = Math.pow(wall, 1.55) * Math.max(0.45, lateralRidges - centerBreak);
    const ridgeNoise =
      0.84 +
      0.1 * Math.sin(local.x * 0.012 + airport.heading * 3) +
      0.08 * Math.cos(along * 0.014 + airport.heading);
    height = Math.max(height, elevation + 22 + naturalWall * wallHeight * ridgeNoise);
  }

  const side = airport.challenge.gullySide || 1;
  const turn = side * (runwayWidth * 7.4 - along * 0.28 + 150 * Math.sin(along * 0.0048));
  const gullyWidth = 170 + Math.min(145, along * 0.09);
  const gully = (1 - smoothstep(gullyWidth, gullyWidth + 330, Math.abs(cross - turn))) * (1 - smoothstep(1650, 1920, along));
  if (gully > 0) {
    const target = elevation + 14 + along * 0.045 + 8 * Math.sin(along * 0.018);
    height = THREE.MathUtils.lerp(height, Math.min(height, target), gully * 0.82);
  }

  const shoulder = 1 - smoothstep(0, 860, Math.abs(Math.abs(cross) - runwayWidth * 6.2));
  const sideRidge = shoulder * (1 - smoothstep(220, 1720, along));
  if (sideRidge > 0) {
    const noise = 0.78 + 0.18 * Math.sin(cross * 0.011) + 0.14 * Math.cos(along * 0.01);
    height = Math.max(height, elevation + sideRidge * (54 + wallHeight * 0.22) * noise);
  }

  return height;
}

export function closestLakeNormalized(x, z) {
  return closestWaterBodyNormalized(LAKES, x, z);
}

export function closestWaterBodyNormalized(bodies, x, z) {
  let best = Infinity;
  for (const body of bodies) best = Math.min(best, waterBodyNormalized(body, x, z));
  return best;
}

export function coastlineOffset(horizontal, sideSign, along) {
  const side = sideSign >= 0 ? 1 : -1;
  const axisPhase = horizontal ? 0 : 1.37;
  const cornerFade = 1 - smoothstep(MAP_SIZE * 0.36, MAP_SIZE * 0.5, Math.abs(along));
  const cape =
    Math.sin(along * 0.00078 + side * 2.1 + axisPhase * 1.8) * 72 +
    Math.cos(along * 0.00112 - side * 1.45 + axisPhase * 0.9) * 48;
  const wave =
    Math.sin(along * 0.0017 + side * 0.82 + axisPhase) * 118 +
    Math.sin(along * 0.0033 - side * 1.5 + axisPhase * 0.7) * 58 +
    Math.cos(along * 0.0058 + side * 2.4 - axisPhase) * 28;
  return (cape + wave) * (0.38 + cornerFade * 0.62);
}

export function closestLandSignedDistance(x, z) {
  let best = -Infinity;
  for (const land of LANDMASSES) {
    const n = waterBodyNormalized(land, x, z);
    const radius = Math.min(land.rx, land.rz);
    best = Math.max(best, (1 - n) * radius);
  }
  return best;
}

export function closestLandmass(x, z) {
  let best = null;
  let bestSigned = -Infinity;
  for (const land of LANDMASSES) {
    const n = waterBodyNormalized(land, x, z);
    const signed = (1 - n) * Math.min(land.rx, land.rz);
    if (signed > bestSigned) {
      bestSigned = signed;
      best = land;
    }
  }
  return { land: best, signedDistance: bestSigned };
}

export function isOnLand(x, z, margin = 0) {
  return closestLandSignedDistance(x, z) > margin;
}

export function distanceToMapEdge(x, z) {
  return EDGE_OCEAN_WIDTH + closestLandSignedDistance(x, z);
}

export function distanceToRiver(x, z) {
  let best = Infinity;
  for (const river of RIVER_SYSTEMS) {
    for (let i = 0; i < river.length - 1; i++) {
      best = Math.min(best, distanceToSegment(x, z, river[i], river[i + 1]));
    }
  }
  return best;
}

export function distanceToSegment(x, z, a, b) {
  const dx = b.x - a.x;
  const dz = b.z - a.z;
  const lengthSq = dx * dx + dz * dz;
  const t = THREE.MathUtils.clamp(((x - a.x) * dx + (z - a.z) * dz) / lengthSq, 0, 1);
  return Math.hypot(x - (a.x + dx * t), z - (a.z + dz * t));
}

export function isChallengeEnd(airport, endSign) {
  return airport.challenge && Math.sign(airport.challenge.end || 1) === endSign;
}

export function isInAirportPavementLocal(airport, local, margin = 0) {
  return airportPavementRects(airport, margin).some(rect =>
    rectContains(local.x, local.z, rect.x, rect.z, rect.halfX, rect.halfZ)
  );
}

export function isInRunwayApproach(x, z, lateral = 420, extension = 1850) {
  for (const airport of AIRPORTS) {
    const local = airportLocal(airport, x, z);
    const runwayLength = airport.runwayLength || 1320;
    const runwayWidth = airport.runwayWidth || 98;
    const threshold = runwayLength / 2;
    const beyondSouth = local.z - threshold;
    const beyondNorth = -local.z - threshold;
    const beyond = Math.max(beyondSouth, beyondNorth);
    if (beyond <= 0 || beyond > extension) continue;
    const halfWidth = Math.max(lateral, runwayWidth * 2.2) + beyond * 0.18;
    if (Math.abs(local.x) < halfWidth) return true;
  }
  return false;
}

export function isNearOtherAirportSafety(sourceAirport, x, z, lateral = 240, longitudinal = 880) {
  for (const airport of AIRPORTS) {
    if (airport === sourceAirport) continue;
    const local = airportLocal(airport, x, z);
    const runwayWidth = airport.runwayWidth || 98;
    const runwayLength = airport.runwayLength || 1320;
    const safeLateral = Math.max(lateral, runwayWidth * 1.45);
    const safeLongitudinal = Math.max(longitudinal, runwayLength / 2 + 230);
    if (Math.abs(local.x) < safeLateral && Math.abs(local.z) < safeLongitudinal) return true;
    if (isInAirportPavementLocal(airport, local, Math.max(34, lateral * 0.24))) return true;
  }
  return false;
}

export function isNearRunwaySafety(x, z, lateral = 240, longitudinal = 880) {
  for (const airport of AIRPORTS) {
    const local = airportLocal(airport, x, z);
    const runwayWidth = airport.runwayWidth || 98;
    const runwayLength = airport.runwayLength || 1320;
    const safeLateral = Math.max(lateral, runwayWidth * 1.45);
    const safeLongitudinal = Math.max(longitudinal, runwayLength / 2 + 230);
    if (Math.abs(local.x) < safeLateral && Math.abs(local.z) < safeLongitudinal) return true;
    if (isInAirportPavementLocal(airport, local, Math.max(34, lateral * 0.24))) return true;
  }
  return false;
}

export function isInAirportExclusionZone(x, z, margin = 0, options = {}) {
  const includeApproach = options.approach !== false;
  const includePavement = options.pavement !== false;
  const includeRunwaySafety = options.runwaySafety !== false;
  const extra = Math.max(0, margin);

  for (const airport of AIRPORTS) {
    const local = airportLocal(airport, x, z);
    const runwayLength = airport.runwayLength || 1320;
    const runwayWidth = airport.runwayWidth || 98;
    const size = airport.size || 1;

    if (includePavement && isInAirportPavementLocal(airport, local, 190 + extra)) return true;

    if (includeRunwaySafety) {
      const runwaySafetyHalfX = Math.max(runwayWidth * 3.2, 260) + extra;
      const runwaySafetyHalfZ = runwayLength / 2 + Math.max(310, 190 * size) + extra;
      if (Math.abs(local.x) < runwaySafetyHalfX && Math.abs(local.z) < runwaySafetyHalfZ) return true;
    }

    if (includeApproach) {
      const threshold = runwayLength / 2;
      const beyondSouth = local.z - threshold;
      const beyondNorth = -local.z - threshold;
      const beyond = Math.max(beyondSouth, beyondNorth);
      const approachLength = Math.max(2600, runwayLength * 0.82) + extra * 2;
      if (beyond > 0 && beyond < approachLength) {
        const halfWidth = Math.max(620, runwayWidth * 7.4) + beyond * 0.24 + extra;
        if (Math.abs(local.x) < halfWidth) return true;
      }
    }
  }

  return false;
}

export function isInRunwayProtectedArea(x, z, margin = 0) {
  for (const airport of AIRPORTS) {
    const local = airportLocal(airport, x, z);
    const runwayLength = airport.runwayLength || 1320;
    const runwayWidth = airport.runwayWidth || 98;
    const halfX = Math.max(runwayWidth * 1.55, 80) + margin;
    const halfZ = runwayLength / 2 + 170 + margin;
    if (Math.abs(local.x) < halfX && Math.abs(local.z) < halfZ) return true;
  }
  return false;
}

export function isRunwayEndUrbanRoadZone(x, z) {
  return isInAirportExclusionZone(x, z, 0) || isNearRunwaySafety(x, z, 320, 1120) || isInRunwayApproach(x, z, 820, 2850);
}

export function isRiverMouthClearancePoint(x, z, clearance = 220, riverDistance = null) {
  const distance = riverDistance ?? distanceToRiver(x, z);
  if (distance > clearance) return false;
  if (distanceToMapEdge(x, z) < EDGE_OCEAN_WIDTH + 300) return true;
  return closestWaterBodyNormalized(BAYS, x, z) < 1.42;
}

export function lakeLocal(lake, x, z) {
  return waterBodyLocal(lake, x, z);
}

export function lakeNormalized(lake, x, z) {
  return waterBodyNormalized(lake, x, z);
}

export function liftSurfaceMaterial(material, factor = -1, units = -1) {
  material.polygonOffset = true;
  material.polygonOffsetFactor = factor;
  material.polygonOffsetUnits = units;
  return material;
}

export const GROUND_PLACEMENT_TOLERANCES = Object.freeze({
  smallBuilding: 0.5,
  largeBuilding: 1.0,
  airportFacility: 0.2
});

export function sampleFootprintHeights(footprint, terrainHeight, options = {}) {
  const width = Math.max(0, footprint.width ?? footprint.w ?? 0);
  const depth = Math.max(0, footprint.depth ?? footprint.d ?? 0);
  const rotation = footprint.rotation ?? footprint.heading ?? 0;
  const x = footprint.x ?? footprint.cx ?? 0;
  const z = footprint.z ?? footprint.cz ?? 0;
  const c = Math.cos(rotation);
  const s = Math.sin(rotation);
  const samples = options.samples || footprint.samples || defaultFootprintSamples(width, depth);
  const results = [];

  for (const sample of samples) {
    const localX = (Array.isArray(sample) ? sample[0] : sample.x) * width;
    const localZ = (Array.isArray(sample) ? sample[1] : sample.z) * depth;
    const sx = x + c * localX + s * localZ;
    const sz = z - s * localX + c * localZ;
    results.push({ x: sx, z: sz, y: terrainHeight(sx, sz) });
  }

  return results;
}

export function terrainPlacementHeight(footprint, terrainHeight, options = {}) {
  const samples = sampleFootprintHeights(footprint, terrainHeight, options);
  let minH = Infinity;
  let maxH = -Infinity;
  let sum = 0;

  for (const sample of samples) {
    minH = Math.min(minH, sample.y);
    maxH = Math.max(maxH, sample.y);
    sum += sample.y;
  }

  if (!samples.length) {
    const y = terrainHeight(footprint.x ?? footprint.cx ?? 0, footprint.z ?? footprint.cz ?? 0);
    minH = y;
    maxH = y;
    sum = y;
    samples.push({ x: footprint.x ?? 0, z: footprint.z ?? 0, y });
  }

  const avgH = sum / samples.length;
  const slope = maxH - minH;
  const width = Math.max(0, footprint.width ?? footprint.w ?? 0);
  const depth = Math.max(0, footprint.depth ?? footprint.d ?? 0);
  const large = options.large === true || footprint.large === true || Math.max(width, depth) >= 56 || width * depth >= 2800;
  const tolerance = options.slopeTolerance ?? footprint.slopeTolerance ?? (
    options.airportFacility || footprint.airportFacility
      ? GROUND_PLACEMENT_TOLERANCES.airportFacility
      : large
        ? GROUND_PLACEMENT_TOLERANCES.largeBuilding
        : GROUND_PLACEMENT_TOLERANCES.smallBuilding
  );
  const mode = options.mode || footprint.mode || (slope > tolerance ? 'max' : 'average');
  const groundY = mode === 'min'
    ? minH
    : mode === 'max'
      ? maxH
      : avgH;
  const groundOffset = options.groundOffset ?? footprint.groundOffset ?? 0;

  return {
    samples,
    minH,
    maxH,
    avgH,
    slope,
    tolerance,
    mode,
    groundY,
    objectY: groundY + groundOffset,
    needsFoundation: slope > tolerance,
    foundationDepth: Math.max(0.35, slope + Math.max(0.25, tolerance * 0.5))
  };
}

export function placeObjectOnTerrain(object, footprint, terrainHeight, options = {}) {
  const placement = terrainPlacementHeight(footprint, terrainHeight, options);
  const positionSpace = options.positionSpace || 'world';
  const parentWorldY = positionSpace === 'local' && object.parent
    ? object.parent.getWorldPosition(reusableTerrainPlacementVector).y
    : 0;

  object.position.y = positionSpace === 'local'
    ? placement.objectY - parentWorldY
    : placement.objectY;
  markGroundPlacement(object, placement, options);
  return placement;
}

export function placeOnTerrain(object, footprint, terrainHeight, options = {}) {
  return placeObjectOnTerrain(object, footprint, terrainHeight, options);
}

export function markGroundPlacement(object, placement, options = {}) {
  const category = options.category || (options.airportFacility ? 'airportFacility' : 'building');
  object.userData.groundPlacement = {
    category,
    checked: options.checked ?? 1,
    floatingFixed: options.floatingFixed ?? 0,
    buriedFixed: options.buriedFixed ?? 0,
    airportFacility: category === 'airportFacility',
    tolerance: placement.tolerance,
    slope: placement.slope,
    minH: placement.minH,
    maxH: placement.maxH,
    avgH: placement.avgH,
    samplesCount: placement.samples?.length || options.checked || 1,
    groundY: placement.groundY,
    objectY: placement.objectY,
    needsFoundation: placement.needsFoundation,
    foundationDepth: placement.foundationDepth,
    reference: options.reference || 'terrain-footprint',
    name: options.name || object.name || ''
  };
}

export function summarizeGroundPlacement(scene) {
  const report = {
    buildingsChecked: 0,
    floatingBuildingsFixed: 0,
    buriedBuildingsFixed: 0,
    airportFacilitiesChecked: 0,
    floatingAirportObjectsFixed: 0,
    airportObjectsWithFoundation: 0,
    terrainFootprintsSampled: 0
  };

  scene.traverse(object => {
    const summary = object.userData?.groundPlacementSummary;
    if (summary) addGroundSummary(report, summary);

    const placement = object.userData?.groundPlacement;
    if (!placement) return;
    const checked = placement.checked || 1;
    if (placement.category === 'airportFacility' || placement.airportFacility) {
      report.airportFacilitiesChecked += checked;
      report.floatingAirportObjectsFixed += placement.floatingFixed || 0;
      if (placement.needsFoundation) report.airportObjectsWithFoundation += checked;
    } else {
      report.buildingsChecked += checked;
      report.floatingBuildingsFixed += placement.floatingFixed || 0;
      report.buriedBuildingsFixed += placement.buriedFixed || 0;
    }
    report.terrainFootprintsSampled += placement.samplesCount || (checked > 0 ? checked : 0);
  });

  return report;
}

function addGroundSummary(report, summary) {
  report.buildingsChecked += summary.buildingsChecked || 0;
  report.floatingBuildingsFixed += summary.floatingBuildingsFixed || 0;
  report.buriedBuildingsFixed += summary.buriedBuildingsFixed || 0;
  report.airportFacilitiesChecked += summary.airportFacilitiesChecked || 0;
  report.floatingAirportObjectsFixed += summary.floatingAirportObjectsFixed || 0;
  report.airportObjectsWithFoundation += summary.airportObjectsWithFoundation || 0;
  report.terrainFootprintsSampled += summary.terrainFootprintsSampled || 0;
}

function defaultFootprintSamples(width, depth) {
  if (width <= 0 && depth <= 0) return [[0, 0]];
  return [
    [0, 0],
    [-0.5, -0.5],
    [0.5, -0.5],
    [-0.5, 0.5],
    [0.5, 0.5],
    [-0.5, 0],
    [0.5, 0],
    [0, -0.5],
    [0, 0.5]
  ];
}

const reusableTerrainPlacementVector = new THREE.Vector3();

export function rectContains(x, z, cx, cz, halfX, halfZ) {
  return Math.abs(x - cx) <= halfX && Math.abs(z - cz) <= halfZ;
}

export function rectFalloff(x, z, halfX, halfZ, fade) {
  const dx = Math.max(0, Math.abs(x) - halfX);
  const dz = Math.max(0, Math.abs(z) - halfZ);
  return 1 - smoothstep(0, fade, Math.hypot(dx, dz));
}

export function roadSegmentAirportBlocked(a, b, samples = 18) {
  for (let i = 0; i <= samples; i++) {
    const t = i / samples;
    const x = THREE.MathUtils.lerp(a.x, b.x, t);
    const z = THREE.MathUtils.lerp(a.z, b.z, t);
    if (isInAirportExclusionZone(x, z, 80) || isNearRunwaySafety(x, z, 230, 900) || isInRunwayApproach(x, z, 280, 980)) return true;
  }
  return false;
}

export function rotatedPatchOverlapsAirportPavement(cx, cz, width, depth, rotation, margin = 0) {
  const patchC = Math.cos(rotation);
  const patchS = Math.sin(rotation);
  const halfWidth = width / 2;
  const halfDepth = depth / 2;

  for (const airport of AIRPORTS) {
    const center = airportLocal(airport, cx, cz);
    const airportC = Math.cos(airport.heading || 0);
    const airportS = Math.sin(airport.heading || 0);
    const axisX = { x: airportC * patchC + airportS * patchS, z: airportS * patchC - airportC * patchS };
    const axisZ = { x: airportC * patchS - airportS * patchC, z: airportS * patchS + airportC * patchC };

    for (const rect of airportPavementRects(airport, margin)) {
      if (rotatedRectIntersectsAxisRect(center, axisX, axisZ, halfWidth, halfDepth, rect)) return true;
    }
  }

  return false;
}

export function rotatedRectIntersectsAxisRect(center, axisX, axisZ, halfWidth, halfDepth, rect) {
  const dx = center.x - rect.x;
  const dz = center.z - rect.z;
  const axes = [
    { x: 1, z: 0 },
    { x: 0, z: 1 },
    axisX,
    axisZ
  ];

  for (const axis of axes) {
    const distance = Math.abs(dx * axis.x + dz * axis.z);
    const patchRadius =
      halfWidth * Math.abs(axisX.x * axis.x + axisX.z * axis.z) +
      halfDepth * Math.abs(axisZ.x * axis.x + axisZ.z * axis.z);
    const rectRadius = rect.halfX * Math.abs(axis.x) + rect.halfZ * Math.abs(axis.z);
    if (distance > patchRadius + rectRadius) return false;
  }

  return true;
}

export function smoothstep(edge0, edge1, x) {
  const t = THREE.MathUtils.clamp((x - edge0) / (edge1 - edge0), 0, 1);
  return t * t * (3 - 2 * t);
}

export function waterBodyLocal(body, x, z) {
  const dx = x - body.x;
  const dz = z - body.z;
  const c = Math.cos(body.rotation || 0);
  const s = Math.sin(body.rotation || 0);
  return { x: c * dx - s * dz, z: s * dx + c * dz };
}

export function waterBodyNormalized(body, x, z) {
  const local = waterBodyLocal(body, x, z);
  const nx = local.x / body.rx;
  const nz = local.z / body.rz;
  const angle = Math.atan2(nz, nx);
  return Math.sqrt(nx * nx + nz * nz) / waterBodyShoreScale(body, angle);
}

export function waterBodyWorld(body, x, z) {
  const c = Math.cos(body.rotation || 0);
  const s = Math.sin(body.rotation || 0);
  return { x: body.x + c * x + s * z, z: body.z - s * x + c * z };
}

export function waterBodyBoundaryPoint(body, angle, normalizedRadius = 1) {
  const local = waterBodyBoundaryLocal(body, angle, normalizedRadius);
  return waterBodyWorld(body, local.x, local.z);
}

export function waterBodyBoundaryLocal(body, angle, normalizedRadius = 1) {
  const shoreScale = waterBodyShoreScale(body, angle) * normalizedRadius;
  return {
    x: Math.cos(angle) * body.rx * shoreScale,
    z: Math.sin(angle) * body.rz * shoreScale
  };
}

export function waterBodyShoreScale(body, angle) {
  const irregularity = body.shoreIrregularity || 0;
  if (irregularity <= 0) return 1;
  const seed = body.shoreSeed || 0;
  const broad =
    Math.sin(angle * 2 + seed * 0.64) * 0.34 +
    Math.cos(angle * 3 - seed * 0.38) * 0.29;
  const coves =
    Math.sin(angle * 5 + seed * 1.21) * 0.15 +
    Math.cos(angle * 6 - seed * 0.81) * 0.1;
  const rounded = Math.tanh((broad + coves) * 0.86);
  return THREE.MathUtils.clamp(1 + rounded * irregularity, 0.86, 1.16);
}
