// Generated by tools/buildVirtualSources.js from src/world/terrain/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import {
  AIRPORTS,
  BAYS,
  CITY_ZONES,
  EDGE_OCEAN_WIDTH,
  ISLANDS,
  LANDMASSES,
  LAKES,
  MAP_SIZE,
  MOUNTAINS,
  WATER_LEVEL
} from '../data/worldData.js?v=202605070100';
import {
  airportLocal,
  applyChallengeApproachTerrain,
  closestLandSignedDistance,
  closestLakeNormalized,
  closestWaterBodyNormalized,
  distanceToMapEdge,
  distanceToRiver,
  isChallengeEnd,
  isInAirportPavementLocal,
  isNearOtherAirportSafety,
  isRiverMouthClearancePoint,
  lakeNormalized,
  rectFalloff,
  smoothstep,
  waterBodyBoundaryPoint,
  waterBodyNormalized
} from './spatial.js?v=202605056000';
import { isRiverGeometryHiddenByWater } from './water.js?v=202605060300';

const PINE_BASIN_AIRPORT = AIRPORTS.find(airport => airport.short === 'Pine Basin');
const ISLAND_NAME_SET = new Set(ISLANDS.map(island => island.name));
const AIRPORT_ISLAND_NAMES = new Set(AIRPORTS.filter(airport => ISLAND_NAME_SET.has(airport.region)).map(airport => airport.region));
const ISLAND_MOUNTAIN_SET = new Set(MOUNTAINS.filter(mountain => closestWaterBodyNormalized(ISLANDS, mountain.x, mountain.z) < 1.22));
const AIRPORT_ISLAND_MOUNTAIN_SET = new Set(MOUNTAINS.filter(mountain =>
  ISLAND_MOUNTAIN_SET.has(mountain) && AIRPORT_ISLAND_NAMES.has(closestIslandName(mountain.x, mountain.z))
));

export function createTerrain({ scene, waterSystem, quality = null }) {
  const terrainSegments = quality?.terrainLOD === 'high'
    ? (MAP_SIZE > 42000 ? 300 : 360)
    : (MAP_SIZE > 42000 ? 220 : 260);
  const geometry = new THREE.PlaneGeometry(MAP_SIZE, MAP_SIZE, terrainSegments, terrainSegments);
  geometry.rotateX(-Math.PI / 2);

  const positions = geometry.attributes.position;
  const colors = [];
  const grassLow = new THREE.Color(0x3f8546);
  const grassHigh = new THREE.Color(0x7faa5d);
  const denseGrass = new THREE.Color(0x237a46);
  const freshMeadow = new THREE.Color(0x58a845);
  const wildMeadow = new THREE.Color(0x91b94a);
  const dirt = new THREE.Color(0x826d4a);
  const sand = new THREE.Color(0xf0c247);
  const rock = new THREE.Color(0x777b78);
  const snow = new THREE.Color(0xe8edf1);

  for (let i = 0; i < positions.count; i++) {
    const x = positions.getX(i);
    const z = positions.getZ(i);
    const y = terrainHeight(x, z);
    positions.setY(i, y);

    const color = grassLow.clone().lerp(grassHigh, THREE.MathUtils.clamp((y + 18) / 60, 0, 1));
    const lakeN = closestLakeNormalized(x, z);
    if (lakeN < 1.12 && lakeN > 0.82) color.lerp(sand, 0.82);
    const bayN = closestWaterBodyNormalized(BAYS, x, z);
    if (bayN < 1.12 && bayN > 0.82) color.lerp(sand, 0.84);
    const islandN = closestWaterBodyNormalized(ISLANDS, x, z);
    if (islandN < 1.05 && islandN > 0.72) color.lerp(sand, 0.78);
    const riverEdge = distanceToRiver(x, z);
    if (!isRiverGeometryHiddenByWater(x, z, riverEdge) && riverEdge < 220 && riverEdge > 68) color.lerp(sand, 0.76);
    const mapEdge = distanceToMapEdge(x, z);
    if (mapEdge < EDGE_OCEAN_WIDTH + 340 && mapEdge > EDGE_OCEAN_WIDTH - 110) color.lerp(sand, 0.9);
    if (isMeadowColorZone(y, lakeN, bayN, islandN, riverEdge, mapEdge)) {
      const patch = meadowPattern(x, z);
      const meadowMix = smoothstep(-0.18, 0.58, patch) * (1 - smoothstep(118, 180, y));
      const meadowColor = denseGrass.clone()
        .lerp(freshMeadow, smoothstep(-0.1, 0.46, Math.sin(x * 0.0029 + z * 0.0017)))
        .lerp(wildMeadow, smoothstep(0.42, 0.92, patch) * 0.72);
      color.lerp(meadowColor, THREE.MathUtils.clamp(0.18 + meadowMix * 0.38, 0, 0.54));
    }
    if (y > 34) color.lerp(dirt, 0.28);
    if (y > 88) color.lerp(rock, THREE.MathUtils.clamp((y - 88) / 90, 0, 0.75));
    if (y > 175) color.lerp(snow, THREE.MathUtils.clamp((y - 175) / 90, 0, 0.82));
    colors.push(color.r, color.g, color.b);
  }

  geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
  geometry.computeVertexNormals();

  const material = new THREE.MeshStandardMaterial({
    vertexColors: true,
    roughness: 0.92,
    metalness: 0.02,
    dithering: true
  });
  const terrain = new THREE.Mesh(geometry, material);
  terrain.receiveShadow = true;
  terrain.frustumCulled = false;
  scene.add(terrain);

  if (quality?.denseScenery === true) createCoastalCliffs(scene);
  waterSystem.createWaterSystems(quality);
}

function meadowPattern(x, z) {
  return Math.sin(x * 0.00125 + z * 0.00072) * 0.54 +
    Math.cos(x * 0.0021 - z * 0.00155) * 0.34 +
    Math.sin((x - z) * 0.0038) * 0.18;
}

function isMeadowColorZone(y, lakeN, bayN, islandN, riverEdge, mapEdge) {
  if (y < WATER_LEVEL + 5 || y > 188) return false;
  if (lakeN < 1.18) return false;
  if (riverEdge < 250) return false;
  if (mapEdge < EDGE_OCEAN_WIDTH + 210) return false;
  if (bayN < 1.12 && islandN > 1.04) return false;
  if (islandN < 1.08 && islandN > 0.72) return false;
  return true;
}

function createCoastalCliffs(scene) {
  const cross = [1.08, 1.02, 0.94, 0.82];
  const rockMaterial = new THREE.MeshStandardMaterial({
    color: 0x6d7069,
    roughness: 0.94,
    metalness: 0.02,
    vertexColors: true
  });

  for (const land of LANDMASSES) {
    const samples = land.rx > 2500 ? 320 : 176;
    const positions = [];
    const colors = [];
    const indices = [];
    const rock = new THREE.Color(0x6d7069);
    const darkRock = new THREE.Color(0x4f5654);
    const sand = new THREE.Color(0xf0c247);

    for (let i = 0; i <= samples; i++) {
      const angle = i / samples * Math.PI * 2;
      const top = waterBodyBoundaryPoint(land, angle, 0.82);
      const topY = terrainHeight(top.x, top.z);
      const heightGain = Math.max(0, topY - WATER_LEVEL);
      const cliff = smoothstep(12, 58, heightGain);
      const shore = waterBodyBoundaryPoint(land, angle, 1.02);
      const riverGap = 1 - smoothstep(150, 360, distanceToRiver(shore.x, shore.z));
      const openBay = closestWaterBodyNormalized(BAYS, shore.x, shore.z) < 1.08 && closestWaterBodyNormalized(ISLANDS, shore.x, shore.z) > 1.06;
      const gap = Math.max(riverGap, openBay ? 0.7 : 0);

      for (let j = 0; j < cross.length; j++) {
        const normalized = cross[j];
        const point = waterBodyBoundaryPoint(land, angle, normalized);
        const c = 1 - j / (cross.length - 1);
        const shelf = Math.pow(Math.max(0, 1 - normalized), 1.15);
        const rough =
          Math.sin(angle * 9 + land.shoreSeed + j * 1.7) * 1.7 +
          Math.cos((point.x + point.z) * 0.004 + j) * 1.2;
        const beachY = WATER_LEVEL - 1.85 + Math.max(0, 1.08 - normalized) * 18;
        const wallY = THREE.MathUtils.lerp(WATER_LEVEL - 1.2, topY + 0.28, shelf) + rough * cliff * (0.25 + c * 0.75);
        const y = THREE.MathUtils.lerp(wallY, beachY, gap * 0.82);
        positions.push(point.x, y, point.z);

        const beachBand = smoothstep(0.93, 1.06, normalized);
        const rockMix = cliff * (1 - beachBand * 0.86);
        const color = sand.clone()
          .lerp(rock, rockMix)
          .lerp(darkRock, THREE.MathUtils.clamp((topY - 92) / 120, 0, 0.24) * (1 - beachBand));
        if (beachBand > 0) color.lerp(sand, beachBand * 0.92);
        colors.push(color.r, color.g, color.b);
      }
    }

    const row = cross.length;
    for (let i = 0; i < samples; i++) {
      for (let j = 0; j < row - 1; j++) {
        const a = i * row + j;
        indices.push(a, a + row, a + 1, a + 1, a + row, a + row + 1);
      }
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
    geometry.setIndex(indices);
    geometry.computeVertexNormals();
    const cliffMesh = new THREE.Mesh(geometry, rockMaterial);
    cliffMesh.receiveShadow = true;
    cliffMesh.castShadow = true;
    cliffMesh.renderOrder = 0;
    scene.add(cliffMesh);
  }
}

export function terrainHeight(x, z) {
  let height =
    Math.sin(x * 0.00165) * 13 +
    Math.cos(z * 0.00145) * 10 +
    Math.sin((x + z) * 0.00092) * 15 +
    Math.cos(Math.hypot(x + 700, z - 500) * 0.0022) * 6 +
    Math.sin(x * 0.0038 - z * 0.0029) * 10 +
    Math.cos((x - z) * 0.0046) * 7;

  const landSignedDistance = closestLandSignedDistance(x, z);
  if (landSignedDistance < -20) {
    const openWater = smoothstep(80, 1500, -landSignedDistance);
    height = Math.min(height, WATER_LEVEL - 7.8 - openWater * 5.4);
  } else {
    const inland = smoothstep(40, 980, landSignedDistance);
    height = Math.max(height, WATER_LEVEL + 4.8 + inland * 12.8);
  }

  height = applyMountainRelief(height, x, z, false);

  for (const zone of CITY_ZONES) {
    const d = Math.hypot(x - zone.x, z - zone.z);
    height *= smoothstep(zone.radius * 0.78, zone.radius, d);
  }

  for (const lake of LAKES) {
    const n = lakeNormalized(lake, x, z);
    if (n < 1.14) {
      const shore = smoothstep(0.74, 1.14, n);
      const basin = lake.level - 8 + n * 3.8;
      height = THREE.MathUtils.lerp(basin, height, shore);
    }
  }

  const riverDistance = distanceToRiver(x, z);
  const riverMouthClearance = isRiverMouthClearancePoint(x, z, 210, riverDistance);

  for (const bay of BAYS) {
    const n = waterBodyNormalized(bay, x, z);
    if (n < 1.66 && (closestWaterBodyNormalized(ISLANDS, x, z) > 1.08 || riverMouthClearance)) {
      const shore = smoothstep(0.78, 1.66, n);
      const basin = bay.level - 7 + Math.min(n, 1.12) * 3.1;
      height = THREE.MathUtils.lerp(basin, height, shore);
    }
  }

  if (!isRiverGeometryHiddenByWater(x, z, riverDistance) && riverDistance < 230) {
    const shore = smoothstep(86, 230, riverDistance);
    height = THREE.MathUtils.lerp(WATER_LEVEL - 7.2, height, shore);
  }

  const mapEdge = distanceToMapEdge(x, z);
  if (mapEdge < EDGE_OCEAN_WIDTH + 1480) {
    const shore = smoothstep(EDGE_OCEAN_WIDTH - 90, EDGE_OCEAN_WIDTH + 1420, mapEdge);
    const coastalShelf = WATER_LEVEL - 7.8 + Math.max(0, mapEdge - EDGE_OCEAN_WIDTH) * 0.004;
    const coastalCap = WATER_LEVEL + 12 + Math.max(0, mapEdge - EDGE_OCEAN_WIDTH) * 0.074;
    height = Math.min(height, coastalCap);
    height = THREE.MathUtils.lerp(coastalShelf, height, shore);
  }

  for (const island of ISLANDS) {
    const n = waterBodyNormalized(island, x, z);
    if (n < 1.12 && !riverMouthClearance) {
      const shore = smoothstep(0.78, 1.12, n);
      const islandGround = islandBaseHeight(island, x, z, n);
      height = THREE.MathUtils.lerp(islandGround, height, shore);
    }
  }

  height = applyMountainRelief(height, x, z, true);

  for (const airport of AIRPORTS) {
    const d = Math.hypot(x - airport.x, z - airport.z);
    const runwayLength = airport.runwayLength || 1320;
    const runwayWidth = airport.runwayWidth || 98;
    const size = airport.size || 1;
    const local = airportLocal(airport, x, z);
    const flattenInner = airport.flattenInner || Math.max(620, runwayLength * 0.52);
    const flattenOuter = airport.flattenOuter || Math.max(1120, runwayLength * 0.95);
    const taxiX = runwayWidth * 1.18 + 70 * size;
    const taxiZ = runwayLength * 0.08;
    const taxiLength = Math.max(430 * size, runwayLength * 0.45);
    const apronW = airport.apronWidth || 420 * size;
    const apronD = airport.apronDepth || 310 * size;
    const apronX = taxiX + apronW * 0.45;
    const apronZ = runwayLength * 0.16;

    const radialFlatten = 1 - smoothstep(flattenInner, flattenOuter, d);
    const runwayFlatten = rectFalloff(local.x, local.z, runwayWidth * 0.95, runwayLength / 2 + 96, 230);
    const taxiFlatten = rectFalloff(local.x - taxiX, local.z - taxiZ, Math.max(42, 50 * size), taxiLength / 2 + 85, 150);
    const apronFlatten = rectFalloff(local.x - apronX, local.z - apronZ, apronW / 2 + 95, apronD / 2 + 95, 170);
    const connectorFlatten = rectFalloff(local.x - taxiX * 0.52, local.z + runwayLength * 0.16, taxiX * 0.72, Math.max(55, 60 * size), 140);
    const flatten = Math.max(radialFlatten, runwayFlatten, taxiFlatten, apronFlatten, connectorFlatten);
    height = THREE.MathUtils.lerp(height, airport.elevation || 0, flatten);
    height = applyHiddenIslandAirportSlopeRing(height, airport, local);
    if (
      flatten > 0 &&
      !isRiverGeometryHiddenByWater(x, z) &&
      riverDistance < 230 &&
      !isInAirportPavementLocal(airport, local, 24)
    ) {
      const shore = smoothstep(86, 230, riverDistance);
      height = THREE.MathUtils.lerp(WATER_LEVEL - 7.2, height, shore);
    }

    const approachDistance = runwayLength * 1.15;
    const threshold = runwayLength / 2;
    const beyondSouth = local.z - threshold;
    const beyondNorth = -local.z - threshold;
    const beyond = Math.max(beyondSouth, beyondNorth);
    const endSign = beyondSouth > beyondNorth ? 1 : -1;
    if (beyond > 0 && beyond < approachDistance && !isChallengeEnd(airport, endSign) && !isNearOtherAirportSafety(airport, x, z, 280, 980)) {
      const halfWidth = (airport.runwayWidth || 98) * 1.8 + beyond * 0.18;
      const corridor = 1 - smoothstep(halfWidth, halfWidth + 280, Math.abs(local.x));
      const fade = 1 - smoothstep(approachDistance * 0.72, approachDistance, beyond);
      const protect = corridor * fade * 0.62;
      const target = (airport.elevation || 0) + 10 + beyond * 0.035;
      if (protect > 0) height = THREE.MathUtils.lerp(height, Math.min(height, target), protect);
    }

    height = applyAirportApproachClearance(height, airport, local, false);
    height = applyChallengeApproachTerrain(height, airport, local);
    height = applyAirportApproachClearance(height, airport, local, true);
  }

  height = applyPostAirportIslandRelief(height, x, z);

  return height;
}

function applyAirportApproachClearance(height, airport, local, postChallenge) {
  const runwayLength = airport.runwayLength || 1320;
  const runwayWidth = airport.runwayWidth || 98;
  const threshold = runwayLength / 2;
  const beyondSouth = local.z - threshold;
  const beyondNorth = -local.z - threshold;
  const beyond = Math.max(beyondSouth, beyondNorth);
  if (beyond <= 0) return height;

  const endSign = beyondSouth > beyondNorth ? 1 : -1;
  const classTag = airport.runwayClass || (airport.tier === 'international' ? 'A' : airport.tier === 'regional' ? 'B' : 'C');
  const challengeEnd = isChallengeEnd(airport, endSign);
  const remoteHiddenAirport = airport.airportCategory === 'REMOTE_AIRSTRIP' || airport.airportCategory === 'HIDDEN_REMOTE_AIRFIELD';
  const normalAirport = classTag !== 'D' && !remoteHiddenAirport;
  const extension = classTag === 'A'
    ? 15000
    : classTag === 'B'
      ? 11500
      : classTag === 'C'
        ? 8200
        : 5200;
  if (beyond > extension) return height;

  const baseHalfWidth = classTag === 'A'
    ? 980
    : classTag === 'B'
      ? 760
      : classTag === 'C'
        ? 520
        : 260;
  const widening = normalAirport ? beyond * 0.06 : beyond * 0.03;
  const halfWidth = Math.max(runwayWidth * 3.6, baseHalfWidth + widening);
  const corridor = 1 - smoothstep(halfWidth, halfWidth + (normalAirport ? 520 : 240), Math.abs(local.x));
  if (corridor <= 0) return height;

  const fade = 1 - smoothstep(extension * 0.72, extension, beyond);
  const elevation = airport.elevation || 0;
  const slope = normalAirport ? 0.047 : 0.054;
  const target = elevation + (normalAirport ? 14 : 22) + beyond * slope + Math.abs(local.x) * 0.025;
  const strength = postChallenge
    ? (challengeEnd ? 0.86 : 0.68)
    : (normalAirport ? 0.78 : 0.38);

  if (challengeEnd && !postChallenge) return height;
  const cleared = THREE.MathUtils.lerp(height, Math.min(height, target), corridor * fade * strength);
  if (normalAirport && corridor * fade > 0.42) return Math.min(cleared, target + 2.5);
  return cleared;
}

function islandBaseHeight(island, x, z, n) {
  const center = Math.max(0, 1 - n);
  const size = Math.sqrt(island.rx * island.rz);
  const lowlandRise = Math.max(0, 1 - n / 1.06) * (8 + Math.min(18, size * 0.006));
  const shoulder = Math.pow(Math.max(0, 1 - n / 0.88), 1.55) * (size > 1100 ? 20 : size > 780 ? 12 : 6);
  const rolling =
    Math.sin((x + z) * 0.004 + island.shoreSeed) * 1.6 +
    Math.cos(x * 0.006 - z * 0.003 + island.rotation) * 1.2;
  return WATER_LEVEL + 4.6 + lowlandRise + shoulder + rolling * (0.35 + center * 0.65);
}

function applyMountainRelief(height, x, z, islandPass) {
  let result = height;
  for (const mountain of MOUNTAINS) {
    if (ISLAND_MOUNTAIN_SET.has(mountain) !== islandPass) continue;
    const dx = (x - mountain.x) / mountain.rx;
    const dz = (z - mountain.z) / mountain.rz;
    const d = dx * dx + dz * dz;
    if (d >= 1.7) continue;

    const coastalTaper = islandPass ? islandMountainTaper(x, z) : mountainCoastalTaper(x, z);
    if (coastalTaper <= 0.02) continue;

    const ridge = Math.max(0, 1 - d / 1.7);
    const ridgeAxis = Math.sin((x - mountain.x) * 0.0034 + mountain.ridge) * 0.36 +
      Math.cos((z - mountain.z) * 0.0042 - mountain.ridge) * 0.28;
    const detail =
      1 +
      0.24 * Math.sin(x * 0.006 + mountain.ridge) +
      0.21 * Math.cos(z * 0.007 - mountain.ridge) +
      0.12 * Math.sin((x - z) * 0.012 + mountain.ridge * 2);
    const crags = Math.max(0, Math.sin(x * 0.011 + z * 0.009 + mountain.ridge)) * ridge * (islandPass ? 11 : 18);
    const relief = Math.pow(ridge, islandPass ? 1.48 : 1.35) * mountain.height * (detail + ridgeAxis * ridge) + crags;
    result += relief * coastalTaper;
  }
  return result;
}

function applyPostAirportIslandRelief(height, x, z) {
  let result = height;
  for (const mountain of AIRPORT_ISLAND_MOUNTAIN_SET) {
    const dx = (x - mountain.x) / mountain.rx;
    const dz = (z - mountain.z) / mountain.rz;
    const d = dx * dx + dz * dz;
    if (d >= 1.7) continue;
    const clear = airportIslandReliefClearance(x, z);
    if (clear <= 0.02) continue;
    const coastalTaper = islandMountainTaper(x, z);
    if (coastalTaper <= 0.02) continue;

    const ridge = Math.max(0, 1 - d / 1.7);
    const detail =
      1 +
      0.24 * Math.sin(x * 0.006 + mountain.ridge) +
      0.21 * Math.cos(z * 0.007 - mountain.ridge) +
      0.12 * Math.sin((x - z) * 0.012 + mountain.ridge * 2);
    const broadRelief = Math.pow(ridge, 1.5) * mountain.height * detail;
    const restoreStrength = mountain.hiddenIslandMountain ? 0.28 : 0.86;
    result += broadRelief * coastalTaper * clear * restoreStrength;
  }
  return result;
}

function airportIslandReliefClearance(x, z) {
  let clearance = 1;
  for (const airport of AIRPORTS) {
    if (!AIRPORT_ISLAND_NAMES.has(airport.region)) continue;
    const local = airportLocal(airport, x, z);
    const runwayLength = airport.runwayLength || 1320;
    const runwayWidth = airport.runwayWidth || 98;
    if (isInAirportPavementLocal(airport, local, 150)) return 0;
    const runwayGuard = rectFalloff(local.x, local.z, runwayWidth * 1.6, runwayLength / 2 + 230, 360);
    const approachGuard = islandRunwayApproachGuard(airport, local);
    clearance *= 1 - Math.max(runwayGuard, approachGuard) * 0.68;
  }
  return THREE.MathUtils.clamp(clearance, 0, 1);
}

function islandRunwayApproachGuard(airport, local) {
  const runwayLength = airport.runwayLength || 1320;
  const runwayWidth = airport.runwayWidth || 98;
  const threshold = runwayLength / 2;
  const beyondSouth = local.z - threshold;
  const beyondNorth = -local.z - threshold;
  const beyond = Math.max(beyondSouth, beyondNorth);
  if (beyond <= 0 || beyond > 900) return 0;
  const halfWidth = runwayWidth * 2.8 + beyond * 0.22;
  return (1 - smoothstep(halfWidth, halfWidth + 260, Math.abs(local.x))) * (1 - smoothstep(620, 900, beyond));
}

function closestIslandName(x, z) {
  let best = null;
  let bestN = Infinity;
  for (const island of ISLANDS) {
    const n = waterBodyNormalized(island, x, z);
    if (n < bestN) {
      bestN = n;
      best = island;

    }
  }
  return best?.name || '';
}

function islandMountainTaper(x, z) {
  let best = Infinity;
  for (const island of ISLANDS) best = Math.min(best, waterBodyNormalized(island, x, z));
  const shoreFade = 1 - smoothstep(0.72, 1.02, best);
  return THREE.MathUtils.clamp(shoreFade, 0, 1);
}

function applyPineBasinSouthSlopeRepair(height, x, z) {
  const airport = PINE_BASIN_AIRPORT;
  if (!airport) return height;

  const local = airportLocal(airport, x, z);
  if (isInAirportPavementLocal(airport, local, 56)) return height;

  const sideBand = smoothstep(180, 520, local.x) * (1 - smoothstep(1430, 1740, local.x));
  const lengthBand = smoothstep(-460, -120, local.z) * (1 - smoothstep(1120, 1520, local.z));
  const lakeN = closestLakeNormalized(x, z);
  const lakeClearance = smoothstep(0.9, 1.14, lakeN);
  const sideRepair = sideBand * lengthBand * lakeClearance;

  const uphill = smoothstep(2520, 3350, z);
  const naturalBreakup =
    Math.sin((x + z) * 0.006) * 4.5 +
    Math.cos(local.x * 0.01 + local.z * 0.003) * 3.2;
  const slopeTarget = WATER_LEVEL + 18 + uphill * ((airport.elevation || 146) - WATER_LEVEL - 28) + naturalBreakup * (0.35 + uphill * 0.65);
  let repairedHeight = THREE.MathUtils.lerp(height, Math.max(height, slopeTarget), sideRepair * 0.74);

  const outerShoulderBand = (1 - smoothstep(360, 640, Math.abs(local.x))) *
    smoothstep(820, 980, local.z) *
    (1 - smoothstep(1420, 1660, local.z)) *
    lakeClearance;
  if (outerShoulderBand <= 0) return repairedHeight;

  const shoulderDescent = smoothstep(1120, 1450, local.z);
  const shoreProgress = smoothstep(1.02, 1.72, lakeN);
  const shoulderTarget = WATER_LEVEL + 52 + shoreProgress * 72 + (1 - shoulderDescent) * 18 + naturalBreakup * 0.56;
  repairedHeight = THREE.MathUtils.lerp(repairedHeight, Math.max(repairedHeight, shoulderTarget), outerShoulderBand * 0.72);
  return repairedHeight;
}

function applyHiddenIslandAirportSlopeRing(height, airport, local) {
  if (airport.airportCategory !== 'HIDDEN_REMOTE_AIRFIELD') return height;
  if (isInAirportPavementLocal(airport, local, 92)) return height;

  const runwayLength = airport.runwayLength || 1320;
  const runwayWidth = airport.runwayWidth || 98;
  const size = airport.size || 1;
  const taxiX = runwayWidth * 1.18 + 70 * size;
  const taxiZ = runwayLength * 0.08;
  const taxiLength = Math.max(430 * size, runwayLength * 0.45);
  const apronW = airport.apronWidth || 420 * size;
  const apronD = airport.apronDepth || 310 * size;
  const apronX = taxiX + apronW * 0.45;
  const apronZ = runwayLength * 0.16;

  const runwayGuard = rectFalloff(local.x, local.z, runwayWidth * 3.1 + 84, runwayLength * 0.5 + 210, 170);
  const taxiGuard = rectFalloff(local.x - taxiX, local.z - taxiZ, Math.max(80, 92 * size), taxiLength * 0.5 + 126, 140);
  const apronGuard = rectFalloff(local.x - apronX, local.z - apronZ, apronW * 0.5 + 118, apronD * 0.5 + 126, 145);
  const clearCore = Math.max(runwayGuard, taxiGuard, apronGuard);
  if (clearCore > 0.64) return height;

  const radial = Math.hypot(local.x * 1.06, local.z * 0.82);
  const inner = runwayLength * 0.5 + 92;
  const outer = runwayLength * 0.5 + 520;
  const ring = smoothstep(inner, inner + 220, radial) * (1 - smoothstep(outer - 180, outer + 170, radial));
  if (ring <= 0) return height;

  const sideBias = smoothstep(runwayWidth * 3.8, runwayWidth * 10.5, Math.abs(local.x)) * (1 - smoothstep(930, 1250, Math.abs(local.x)));
  const endBias = smoothstep(runwayLength * 0.46, runwayLength * 0.68, Math.abs(local.z)) * (1 - smoothstep(runwayLength * 0.75, runwayLength * 0.95, Math.abs(local.z)));
  const irregular =
    Math.sin(local.x * 0.011 + local.z * 0.006 + 1.7) * 2.8 +
    Math.cos(local.x * 0.005 - local.z * 0.012) * 2.1;
  const slopeHeight = 8 + sideBias * 18 + endBias * 9 + irregular;
  const target = (airport.elevation || 0) + Math.max(5, slopeHeight);
  const strength = ring * (1 - clearCore * 0.78) * 0.72;
  return THREE.MathUtils.lerp(height, Math.max(height, target), strength);
}

function applyPineHighValleyCoastalRepair(height, x, z, mapEdge) {
  const xBand = smoothstep(350, 850, x) * (1 - smoothstep(3200, 3800, x));
  const zBand = smoothstep(4480, 4880, z);
  if (xBand <= 0 || zBand <= 0) return height;

  for (const airport of AIRPORTS) {
    if (airport.short !== 'High Valley' && airport.short !== 'Pine Basin') continue;
    if (isInAirportPavementLocal(airport, airportLocal(airport, x, z), 42)) return height;
  }

  const oceanDrop = 1 - smoothstep(EDGE_OCEAN_WIDTH - 120, EDGE_OCEAN_WIDTH + 45, mapEdge);
  if (oceanDrop <= 0) return height;

  const coastalShelf = WATER_LEVEL - 9 + Math.max(0, mapEdge) * 0.013;
  const repair = xBand * zBand * oceanDrop;
  return THREE.MathUtils.lerp(height, Math.min(height, coastalShelf), repair);
}

function mountainCoastalTaper(x, z) {
  const edgeTaper = smoothstep(EDGE_OCEAN_WIDTH + 70, EDGE_OCEAN_WIDTH + 1220, distanceToMapEdge(x, z));
  const onIsland = closestWaterBodyNormalized(ISLANDS, x, z) < 1.16;
  const bayTaper = onIsland ? 1 : smoothstep(1.06, 1.92, closestWaterBodyNormalized(BAYS, x, z));
  return edgeTaper * bayTaper;
}
