// Generated by tools/buildVirtualSources.js from src/world/ufoEvents/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import {
  AIRCRAFT_GROUND_OFFSET,
  AIRPORTS,
  MAP_SIZE,
  WATER_LEVEL
} from '../data/worldData.js?v=202605070100';
import { airportWorld } from './spatial.js?v=202605056000';

const FT_TO_M = 0.3048;
const M_TO_FT = 3.28084;
const KT_PER_MPS = 1.94384;
const CONTACT_LOST_HOLD_MS = 2800;
const BODY_RADIUS = 25.4;
const SIDE_ENCOUNTER_VISIBLE_CONE_DEG = 120;
const SIDE_VISIBILITY_CHECK_MS = 2000;
const SIDE_VISIBILITY_GRACE_MS = 5000;
const SIDE_VISIBILITY_SLIDE_MS = 4200;
const HIDDEN_AIRPORT = AIRPORTS.find(airport => airport.airportCategory === 'HIDDEN_REMOTE_AIRFIELD') || AIRPORTS[AIRPORTS.length - 1];

export const UFO_EVENT_MODES = Object.freeze({
  ISLAND_EVENT: 'ISLAND_EVENT',
  WORLD_ROAMING: 'WORLD_ROAMING',
  NIGHT_ENCOUNTER: 'NIGHT_ENCOUNTER',
  PLAYER_SIDE_ENCOUNTER: 'PLAYER_SIDE_ENCOUNTER'
});

export const UFO_EVENT_STATES = Object.freeze({
  HIDDEN: 'HIDDEN',
  PRE_GLOW: 'PRE_GLOW',
  VERTICAL_TAKEOFF: 'VERTICAL_TAKEOFF',
  HOVER: 'HOVER',
  TRACK_PLAYER: 'TRACK_PLAYER',
  FAST_DEPARTURE: 'FAST_DEPARTURE',
  DISAPPEAR: 'DISAPPEAR',
  COOLDOWN: 'COOLDOWN',
  WORLD_HIDDEN: 'WORLD_HIDDEN',
  WORLD_SPAWN_PENDING: 'WORLD_SPAWN_PENDING',
  WORLD_VISIBLE: 'WORLD_VISIBLE',
  WORLD_TRACKING: 'WORLD_TRACKING',
  WORLD_DEPARTING: 'WORLD_DEPARTING',
  WORLD_LOST: 'WORLD_LOST',
  WORLD_COOLDOWN: 'WORLD_COOLDOWN'
});

export const UFO_WORLD_FLIGHT_TYPES = Object.freeze({
  HIGH_SPEED_PASS: 'HIGH_SPEED_PASS',
  SILENT_CRUISE: 'SILENT_CRUISE',
  HOVER_AND_DEPART: 'HOVER_AND_DEPART',
  CLOUD_EXIT: 'CLOUD_EXIT',
  OCEAN_RISE_DISTANT: 'OCEAN_RISE_DISTANT',
  BLUE_STREAK_PASS: 'BLUE_STREAK_PASS',
  SILENT_HOVER: 'SILENT_HOVER',
  OCEAN_GLIDE: 'OCEAN_GLIDE',
  VERTICAL_FLASH: 'VERTICAL_FLASH',
  PLAYER_SIDE_FOLLOW: 'PLAYER_SIDE_FOLLOW'
});

export function createUfoEventController({
  scene,
  state,
  camera,
  terrainHeight,
  getHiddenIslandUfoManager = () => null,
  getServerTime = () => null
}) {
  const model = createUfoModel();
  const preGlow = createPreGlow();
  const vectors = {
    position: new THREE.Vector3(),
    previousPosition: new THREE.Vector3(),
    start: new THREE.Vector3(),
    control: new THREE.Vector3(),
    end: new THREE.Vector3(),
    player: new THREE.Vector3(),
    direction: new THREE.Vector3(),
    forward: new THREE.Vector3(0, 0, -1)
  };
  let activeEventId = '';
  let lastContactPosition = null;
  let lostUntilMs = 0;
  let currentYaw = 0;
  let sideVisibilityLastCheckMs = 0;
  let sideOffscreenSinceMs = 0;
  let sideCorrectionStartMs = 0;
  let localDebugEvent = null;
  let hiddenIslandUfoManager = null;
  let report = createInitialReport();

  model.setVisible?.(false);
  model.setBlueGlowEnabled?.(false);
  preGlow.group.visible = false;
  scene.add(model.group);
  scene.add(preGlow.group);
  state.ufoContact = null;
  state.ufoEventReport = report;

  function update(dt, { serverEvent = null, cycleState = null } = {}) {
    const serverTime = getServerTime?.() || null;
    const nowMs = estimatedServerNowMs(serverTime);
    const debugEvent = debugPayload(nowMs);
    const payload = serverEvent || debugEvent;
    const nightFactor = cycleState?.nightLightFactor ?? serverTime?.nightLightFactor ?? 0;

    if (!payload) {
      hideInactive(nowMs);
      return;
    }

    if (payload.ufoEventId !== activeEventId) {
      activeEventId = payload.ufoEventId || '';
      lastContactPosition = null;
      lostUntilMs = 0;
      sideVisibilityLastCheckMs = 0;
      sideOffscreenSinceMs = 0;
      sideCorrectionStartMs = 0;
      vectors.previousPosition.copy(model.group.position);
      if (payload.mode === UFO_EVENT_MODES.ISLAND_EVENT) {
        hiddenIslandUfoManager = getHiddenIslandUfoManager?.() || null;
        hiddenIslandUfoManager?.beginEvent?.(payload, nightFactor);
      }
    }

    if (payload.mode === UFO_EVENT_MODES.ISLAND_EVENT) {
      updateIslandEvent(payload, dt, nowMs, nightFactor);
    } else {
      updateWorldEvent(payload, dt, nowMs, nightFactor);
    }
  }

  function updateIslandEvent(payload, dt, nowMs, nightFactor) {
    const durations = normalizeIslandDurations(payload);
    const elapsed = Math.max(0, nowMs - payload.startTime);
    const spawn = readPoint(payload.spawnPoint, islandFallbackSpawnPoint());
    const managedSpawn = hiddenIslandUfoManager?.getSpawnWorldPoint?.(payload.ufoIndex);
    if (managedSpawn) spawn.copy(managedSpawn);
    const groundY = Math.max(terrainHeight(spawn.x, spawn.z) + AIRCRAFT_GROUND_OFFSET + 10, spawn.y || 0);
    const targetAltitudeM = Math.max(
      groundY + 900,
      (payload.targetAltitudeFt || 7200) * FT_TO_M
    );

    const takeoffStart = durations.preGlowMs;
    const hoverStart = takeoffStart + durations.takeoffMs;
    const trackStart = hoverStart + durations.hoverMs;
    const departStart = trackStart + durations.trackMs;
    const disappearStart = departStart + durations.departMs;
    const endTime = payload.endTime || (payload.startTime + disappearStart + durations.lostMs);
    let phase = UFO_EVENT_STATES.PRE_GLOW;
    let visible = true;
    let coreVisible = true;
    let glowIntensity = 0.18;
    let speedKts = 0;

    vectors.position.set(spawn.x, groundY + 28, spawn.z);
    if (elapsed < takeoffStart) {
      phase = UFO_EVENT_STATES.PRE_GLOW;
      coreVisible = false;
      glowIntensity = 0.12 + smoothstep(0, takeoffStart, elapsed) * 0.42;
      preGlow.group.position.set(spawn.x, groundY + 16, spawn.z);
      preGlow.group.visible = true;
      preGlow.material.opacity = 0.08 + glowIntensity * 0.32;
      preGlow.group.rotation.y += dt * 0.7;
    } else if (elapsed < hoverStart) {
      phase = UFO_EVENT_STATES.VERTICAL_TAKEOFF;
      const t = smoothstep(0, durations.takeoffMs, elapsed - takeoffStart);
      vectors.position.set(spawn.x, THREE.MathUtils.lerp(groundY + 22, targetAltitudeM, t), spawn.z);
      glowIntensity = 0.36 + t * 0.42;
      speedKts = Math.round(((targetAltitudeM - groundY) / Math.max(0.1, durations.takeoffMs / 1000)) * KT_PER_MPS);
    } else if (elapsed < trackStart) {
      phase = UFO_EVENT_STATES.HOVER;
      const bob = Math.sin(nowMs * 0.0022) * 7.5;
      vectors.position.set(spawn.x, targetAltitudeM + bob, spawn.z);
      glowIntensity = 0.56;
    } else if (elapsed < departStart) {
      phase = UFO_EVENT_STATES.TRACK_PLAYER;
      const bob = Math.sin(nowMs * 0.002) * 6.2;
      vectors.position.set(spawn.x, targetAltitudeM + bob, spawn.z);
      glowIntensity = 0.62;
    } else if (elapsed < disappearStart) {
      phase = UFO_EVENT_STATES.FAST_DEPARTURE;
      const t = smoothstep(0, durations.departMs, elapsed - departStart);
      const departureSpeed = payload.departureSpeed || 1300;
      const departure = readDirection(payload.departureDirection, playerAwayDirection(spawn));
      vectors.position.set(
        spawn.x + departure.x * departureSpeed * (elapsed - departStart) / 1000,
        targetAltitudeM + 220 * t,
        spawn.z + departure.z * departureSpeed * (elapsed - departStart) / 1000
      );
      glowIntensity = 0.78 + (1 - t) * 0.42;
      speedKts = 999;
    } else if (nowMs < endTime) {
      phase = UFO_EVENT_STATES.DISAPPEAR;
      visible = false;
      coreVisible = false;
      glowIntensity = 0;
      lostUntilMs = Math.max(lostUntilMs, performance.now() + CONTACT_LOST_HOLD_MS);
    } else {
      phase = UFO_EVENT_STATES.COOLDOWN;
      visible = false;
      coreVisible = false;
    }

    renderEvent({
      payload,
      phase,
      position: vectors.position,
      visible,
      coreVisible: hiddenIslandUfoManager ? false : coreVisible,
      glowIntensity,
      speedKts,
      headingDeg: headingFromVector(vectors.previousPosition, vectors.position),
      nightFactor,
      dt,
      managedIslandUfo: hiddenIslandUfoManager
    });
  }

  function updateWorldEvent(payload, dt, nowMs, nightFactor) {
    const durationMs = Math.max(5000, payload.durationMs || Math.max(5000, (payload.endTime || nowMs + 18000) - payload.startTime - CONTACT_LOST_HOLD_MS));
    const elapsed = Math.max(0, nowMs - payload.startTime);
    const t = THREE.MathUtils.clamp(elapsed / durationMs, 0, 1);
    const flightType = payload.flightType || UFO_WORLD_FLIGHT_TYPES.HIGH_SPEED_PASS;
    if (payload.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER || flightType === UFO_WORLD_FLIGHT_TYPES.PLAYER_SIDE_FOLLOW) {
      updatePlayerSideEncounterEvent(payload, dt, nowMs, nightFactor, durationMs, elapsed);
      return;
    }
    const start = readPoint(payload.path?.startPoint || payload.startPoint, worldFallbackPoint(0));
    const control = readPoint(payload.path?.controlPoint || payload.controlPoint, worldMidPoint(start, payload));
    const end = readPoint(payload.path?.endPoint || payload.endPoint, worldFallbackPoint(1));
    vectors.start.copy(start);
    vectors.control.copy(control);
    vectors.end.copy(end);

    let phase = UFO_EVENT_STATES.WORLD_VISIBLE;
    let visible = elapsed <= durationMs;
    let coreVisible = visible;
    let glowIntensity = nightFactor > 0.35 ? 0.42 : 0.18;
    let speedKts = payload.speedKts || 620;

    if (flightType === UFO_WORLD_FLIGHT_TYPES.BLUE_STREAK_PASS || flightType === UFO_WORLD_FLIGHT_TYPES.HIGH_SPEED_PASS) {
      vectors.position.lerpVectors(vectors.start, vectors.end, smoothstep(0, 1, t));
      phase = t > 0.86 ? UFO_EVENT_STATES.WORLD_DEPARTING : UFO_EVENT_STATES.WORLD_VISIBLE;
      speedKts = t > 0.86 ? (payload.departureSpeedKts || 999) : (payload.speedKts || 560);
      glowIntensity = (flightType === UFO_WORLD_FLIGHT_TYPES.BLUE_STREAK_PASS ? 0.62 : 0.42) + smoothstep(0.72, 1, t) * 0.55;
    } else if (flightType === UFO_WORLD_FLIGHT_TYPES.SILENT_CRUISE) {
      quadraticBezier(vectors.position, vectors.start, vectors.control, vectors.end, t);
      phase = t > 0.72 ? UFO_EVENT_STATES.WORLD_TRACKING : UFO_EVENT_STATES.WORLD_VISIBLE;
      speedKts = payload.speedKts || 560;
      glowIntensity = nightFactor > 0.35 ? 0.34 : 0.11;
    } else if (flightType === UFO_WORLD_FLIGHT_TYPES.HOVER_AND_DEPART || flightType === UFO_WORLD_FLIGHT_TYPES.SILENT_HOVER) {
      const hoverEnd = flightType === UFO_WORLD_FLIGHT_TYPES.SILENT_HOVER ? 0.62 : 0.45;
      if (t < hoverEnd) {
        vectors.position.copy(vectors.start);
        vectors.position.y += Math.sin(nowMs * 0.002) * 6;
        phase = UFO_EVENT_STATES.WORLD_TRACKING;
        speedKts = 0;
        glowIntensity = flightType === UFO_WORLD_FLIGHT_TYPES.SILENT_HOVER ? 0.74 : 0.48;
      } else {
        const departT = smoothstep(0, 1, (t - hoverEnd) / (1 - hoverEnd));
        vectors.position.lerpVectors(vectors.start, vectors.end, departT);
        phase = UFO_EVENT_STATES.WORLD_DEPARTING;
        speedKts = payload.departureSpeedKts || 999;
        glowIntensity = 0.92;
      }
    } else if (flightType === UFO_WORLD_FLIGHT_TYPES.CLOUD_EXIT) {
      quadraticBezier(vectors.position, vectors.start, vectors.control, vectors.end, t);
      phase = t > 0.68 ? UFO_EVENT_STATES.WORLD_DEPARTING : UFO_EVENT_STATES.WORLD_VISIBLE;
      const cloudFade = smoothstep(0.08, 0.24, t) * (1 - smoothstep(0.72, 0.96, t));
      coreVisible = cloudFade > 0.05;
      visible = coreVisible || t < 1;
      glowIntensity = (nightFactor > 0.35 ? 0.36 : 0.08) * cloudFade;
      speedKts = payload.speedKts || 540;
    } else if (flightType === UFO_WORLD_FLIGHT_TYPES.OCEAN_GLIDE) {
      const pullUpT = smoothstep(0.58, 1, t);
      quadraticBezier(vectors.position, vectors.start, vectors.control, vectors.end, t);
      vectors.position.y += pullUpT * pullUpT * 900;
      phase = t > 0.72 ? UFO_EVENT_STATES.WORLD_DEPARTING : UFO_EVENT_STATES.WORLD_VISIBLE;
      speedKts = t > 0.72 ? (payload.departureSpeedKts || 999) : payload.speedKts || 520;
      glowIntensity = 0.34 + pullUpT * 0.58;
    } else if (flightType === UFO_WORLD_FLIGHT_TYPES.VERTICAL_FLASH) {
      const riseEnd = 0.56;
      if (t < riseEnd) {
        vectors.position.lerpVectors(vectors.start, vectors.control, smoothstep(0, 1, t / riseEnd));
        phase = UFO_EVENT_STATES.WORLD_VISIBLE;
        speedKts = 0;
        glowIntensity = 0.72 + t * 0.32;
      } else if (t < 0.74) {
        vectors.position.copy(vectors.control);
        vectors.position.y += Math.sin(nowMs * 0.003) * 5;
        phase = UFO_EVENT_STATES.WORLD_TRACKING;
        speedKts = 0;
        glowIntensity = 0.9;
      } else {
        const departT = smoothstep(0, 1, (t - 0.74) / 0.26);
        vectors.position.lerpVectors(vectors.control, vectors.end, departT);
        phase = UFO_EVENT_STATES.WORLD_DEPARTING;
        speedKts = payload.departureSpeedKts || 999;
        glowIntensity = 1.05;
      }
    } else {
      const riseT = smoothstep(0, 0.46, t);
      vectors.position.lerpVectors(vectors.start, vectors.end, smoothstep(0, 1, t));
      vectors.position.y = THREE.MathUtils.lerp(vectors.start.y, vectors.control.y, riseT) + Math.sin(t * Math.PI) * 180;
      phase = t > 0.82 ? UFO_EVENT_STATES.WORLD_DEPARTING : UFO_EVENT_STATES.WORLD_VISIBLE;
      speedKts = t > 0.82 ? (payload.departureSpeedKts || 999) : t < 0.32 ? 160 : (payload.speedKts || 420);
      glowIntensity = nightFactor > 0.35 ? 0.46 : 0.12;
    }

    const groundSafeY = terrainHeight(vectors.position.x, vectors.position.z) + AIRCRAFT_GROUND_OFFSET + 914;
    vectors.position.y = Math.max(vectors.position.y, groundSafeY, WATER_LEVEL + 914);

    if (elapsed > durationMs) {
      phase = UFO_EVENT_STATES.WORLD_LOST;
      visible = false;
      coreVisible = false;
      speedKts = 999;
      glowIntensity = 0;
      lostUntilMs = Math.max(lostUntilMs, performance.now() + CONTACT_LOST_HOLD_MS);
    }
    if (payload.endTime && nowMs >= payload.endTime) {
      phase = UFO_EVENT_STATES.WORLD_COOLDOWN;
      visible = false;
      coreVisible = false;
    }

    renderEvent({
      payload,
      phase,
      position: vectors.position,
      visible,
      coreVisible,
      glowIntensity,
      speedKts,
      headingDeg: headingFromVector(vectors.previousPosition, vectors.position),
      nightFactor,
      dt
    });
  }

  function updatePlayerSideEncounterEvent(payload, dt, nowMs, nightFactor, durationMs, elapsed) {
    const followDurationMs = Math.max(15000, payload.followDurationMs || durationMs - 1800);
    const departureDurationMs = Math.max(1000, payload.departureDurationMs || durationMs - followDurationMs);
    const followElapsed = Math.min(elapsed, followDurationMs);
    const leg = sideEncounterLegAt(payload, followElapsed);
    const target = sideEncounterTarget(payload, leg?.playerId);
    const targetPosition = readPoint(target?.position || leg?.targetSnapshot?.position, worldFallbackPoint(0));
    const targetHeading = finite(target?.heading, leg?.targetSnapshot?.heading ?? 0);
    const targetSpeed = finite(target?.speed, payload.speedKts || 180);
    const phaseSeed = finite(leg?.bobPhase, 0);
    const legProgress = sideEncounterLegProgress(leg, followElapsed);

    setSideEncounterRelativePosition(vectors.position, targetPosition, targetHeading, leg, legProgress, nowMs);

    let phase = UFO_EVENT_STATES.WORLD_TRACKING;
    let visible = elapsed <= durationMs;
    let coreVisible = visible;
    let glowIntensity = (nightFactor > 0.35 ? 0.74 : 0.24) + Math.sin(nowMs * 0.002 + phaseSeed) * 0.035;
    let speedKts = payload.speedKts || THREE.MathUtils.clamp(targetSpeed + finite(payload.speedOffsetKts, 0), 150, 350);

    const endHoldMs = Math.max(3000, finite(payload.sideEncounter?.endHoldMs, 4000));
    const holdStartMs = Math.max(0, followDurationMs - endHoldMs);
    if (elapsed >= holdStartMs && elapsed <= followDurationMs) {
      const holdOffset = payload.sideEncounter?.finalHoldOffset || leg?.endOffset || { rightM: 0, forwardM: 1600, upM: 420 };
      const holdLeg = {
        startOffset: holdOffset,
        endOffset: holdOffset,
        bobPhase: phaseSeed,
        bobMeters: 4,
        driftMeters: 0,
        microShiftMeters: 0,
        microShiftPeriodMs: 6000
      };
      setSideEncounterRelativePosition(vectors.control, targetPosition, targetHeading, holdLeg, 1, nowMs);
      const holdBlend = smoothstep(0, Math.min(2600, endHoldMs), elapsed - holdStartMs);
      vectors.position.lerp(vectors.control, holdBlend);
      glowIntensity += holdBlend * 0.16;
      speedKts = THREE.MathUtils.clamp(targetSpeed, 150, 350);
    }

    let visualState = keepSideEncounterInForwardView(vectors.position, targetPosition, targetHeading, nowMs);

    if (elapsed > followDurationMs) {
      const departElapsed = elapsed - followDurationMs;
      const departT = smoothstep(0, departureDurationMs, departElapsed);
      const direction = readDirection(payload.sideEncounter?.departureDirection, sideEncounterAwayDirection(vectors.position, targetPosition));
      const departureSpeedMps = (payload.departureSpeedKts || 1200) / KT_PER_MPS;
      vectors.position.x += direction.x * departureSpeedMps * departElapsed / 1000;
      vectors.position.y += THREE.MathUtils.lerp(60, 520, departT);
      vectors.position.z += direction.z * departureSpeedMps * departElapsed / 1000;
      phase = UFO_EVENT_STATES.WORLD_DEPARTING;
      glowIntensity = 0.9 + departT * 0.28;
      speedKts = payload.departureSpeedKts || 999;
      visualState = keepSideEncounterInForwardView(vectors.position, targetPosition, targetHeading, nowMs);
    }

    const groundSafeY = terrainHeight(vectors.position.x, vectors.position.z) + AIRCRAFT_GROUND_OFFSET + 220;
    vectors.position.y = Math.max(vectors.position.y, groundSafeY, WATER_LEVEL + 220);

    if (elapsed > durationMs) {
      phase = UFO_EVENT_STATES.WORLD_LOST;
      visible = false;
      coreVisible = false;
      speedKts = 999;
      glowIntensity = 0;
      lostUntilMs = Math.max(lostUntilMs, performance.now() + CONTACT_LOST_HOLD_MS);
    }
    if (payload.endTime && nowMs >= payload.endTime) {
      phase = UFO_EVENT_STATES.WORLD_COOLDOWN;
      visible = false;
      coreVisible = false;
    }

    renderEvent({
      payload: {
        ...payload,
        visualContact: visualState.visualContact,
        signalOffset: visualState.signalOffset
      },
      phase,
      position: vectors.position,
      visible,
      coreVisible,
      glowIntensity,
      speedKts,
      headingDeg: normalizeHeading(targetHeading),
      nightFactor,
      dt
    });
  }

  function keepSideEncounterInForwardView(position, targetPosition, headingDeg, nowMs) {
    const visualNow = sideEncounterPositionVisible(position, targetPosition, headingDeg);
    if (nowMs - sideVisibilityLastCheckMs >= SIDE_VISIBILITY_CHECK_MS) {
      sideVisibilityLastCheckMs = nowMs;
      if (visualNow) {
        sideOffscreenSinceMs = 0;
        sideCorrectionStartMs = 0;
      } else if (!sideOffscreenSinceMs) {
        sideOffscreenSinceMs = nowMs;
      }
    }

    const shouldCorrect = sideOffscreenSinceMs && nowMs - sideOffscreenSinceMs >= SIDE_VISIBILITY_GRACE_MS;
    if (!shouldCorrect) {
      return { visualContact: visualNow, signalOffset: !visualNow };
    }

    if (!sideCorrectionStartMs) sideCorrectionStartMs = nowMs;
    const relative = sideEncounterRelativeComponents(position, targetPosition, headingDeg);
    const sideSign = relative.rightM >= 0 ? 1 : -1;
    const recoveryOffset = {
      rightM: sideSign * THREE.MathUtils.clamp(Math.abs(relative.rightM) * 0.55, 520, 820),
      forwardM: THREE.MathUtils.clamp(Math.max(relative.forwardM, 1200), 1200, 2000),
      upM: THREE.MathUtils.clamp(relative.upM, 220, 680)
    };
    const correctionLeg = {
      startOffset: recoveryOffset,
      endOffset: recoveryOffset,
      bobPhase: 0,
      bobMeters: 3,
      driftMeters: 0,
      microShiftMeters: 0,
      microShiftPeriodMs: 6000
    };
    setSideEncounterRelativePosition(vectors.control, targetPosition, headingDeg, correctionLeg, 1, nowMs);
    const slideT = smoothstep(0, SIDE_VISIBILITY_SLIDE_MS, nowMs - sideCorrectionStartMs);
    position.lerp(vectors.control, slideT);
    const visualAfterCorrection = sideEncounterPositionVisible(position, targetPosition, headingDeg);
    return {
      visualContact: visualAfterCorrection,
      signalOffset: !visualAfterCorrection
    };
  }

  function renderEvent({ payload, phase, position, visible, coreVisible, glowIntensity, speedKts, headingDeg, nightFactor, dt, managedIslandUfo = null }) {
    preGlow.group.visible = phase === UFO_EVENT_STATES.PRE_GLOW;
    if (managedIslandUfo) {
      managedIslandUfo.updateEvent?.(payload, phase, position, glowIntensity, dt, nightFactor);
    }
    model.state = phase;
    model.eventId = payload?.ufoEventId || '';
    model.isParked = false;
    model.isAirborne = Boolean(visible && coreVisible);
    model.setVisible?.(visible && coreVisible);
    model.setBlueGlowEnabled?.(visible && coreVisible);
    if (visible && coreVisible) {
      vectors.previousPosition.copy(model.group.position);
      model.setAirborneTransform?.(position);
      orientTowardPlayer(position, dt, phase);
      updateMaterials(nightFactor, glowIntensity, payload.mode);
      updateLod(position);
      model.ringGroup.rotation.y += dt * (phase === UFO_EVENT_STATES.FAST_DEPARTURE || phase === UFO_EVENT_STATES.WORLD_DEPARTING ? 7.2 : 1.35 + glowIntensity * 1.6);
      model.edgeRing.rotation.z -= dt * 0.26;
      updateTrail(position, glowIntensity, phase);
    } else {
      model.trail.visible = false;
    }

    const contactVisible = visible || phase === UFO_EVENT_STATES.DISAPPEAR || phase === UFO_EVENT_STATES.WORLD_LOST || performance.now() < lostUntilMs;
    updateContact(payload, phase, position, contactVisible, speedKts, headingDeg);
    updateReport(payload, phase, visible, coreVisible, managedIslandUfo);
  }

  function orientTowardPlayer(position, dt, phase) {
    const playerPosition = state.visualPosition || state.position;
    vectors.player.copy(playerPosition);
    const dx = vectors.player.x - position.x;
    const dz = vectors.player.z - position.z;
    let targetYaw = currentYaw;
    if (Math.hypot(dx, dz) > 1) {
      targetYaw = Math.atan2(dx, dz);
    }
    const tracking = phase === UFO_EVENT_STATES.TRACK_PLAYER ||
      phase === UFO_EVENT_STATES.HOVER ||
      phase === UFO_EVENT_STATES.WORLD_TRACKING;
    const alpha = tracking ? (1 - Math.exp(-dt * 0.72)) : (1 - Math.exp(-dt * 1.5));
    currentYaw = dampAngle(currentYaw, targetYaw, alpha);
    model.group.rotation.set(0, currentYaw, 0, 'YXZ');
  }

  function updateMaterials(nightFactor, glowIntensity, mode) {
    if (model.updateMaterialForTime) {
      model.updateMaterialForTime({ nightFactor, glowIntensity, mode });
      return;
    }
    const night = THREE.MathUtils.clamp(nightFactor, 0, 1);
    model.bodyMaterial.roughness = THREE.MathUtils.lerp(0.76, 0.36, night);
    model.bodyMaterial.envMapIntensity = THREE.MathUtils.lerp(0.34, 0.94, night);
    model.bodyMaterial.emissiveIntensity = THREE.MathUtils.lerp(0.006, 0.038, night) + glowIntensity * 0.012;
    model.seamMaterial.roughness = THREE.MathUtils.lerp(0.62, 0.34, night);
    model.seamMaterial.envMapIntensity = THREE.MathUtils.lerp(0.34, 0.88, night);
    model.seamMaterial.emissiveIntensity = THREE.MathUtils.lerp(0.012, 0.048, night) + glowIntensity * 0.012;
    model.cockpitMaterial.roughness = THREE.MathUtils.lerp(0.18, 0.07, night);
    model.cockpitMaterial.envMapIntensity = THREE.MathUtils.lerp(0.48, 1.15, night);
    model.cockpitMaterial.emissiveIntensity = night * 0.02;
    model.glowMaterial.opacity = THREE.MathUtils.clamp(
      (mode === UFO_EVENT_MODES.WORLD_ROAMING ? 0.045 : 0.065) + glowIntensity * (night > 0.25 ? 0.5 : 0.12),
      0,
      0.68
    );
    model.glowMaterial.color.setHex(night > 0.25 ? 0x86dcff : 0x6fa6c6);
    model.ringCoreMaterial.emissiveIntensity = 0.36 + glowIntensity * 1.62;
    model.ringCoreMaterial.opacity = THREE.MathUtils.clamp(0.42 + glowIntensity * 0.44, 0.32, 0.88);
  }

  function updateLod(position) {
    const distance = camera ? camera.position.distanceTo(position) : position.distanceTo(state.position);
    const near = distance < 45000;
    const far = distance > 76000;
    model.detailGroup.visible = near;
    model.panelGroup.visible = near;
    model.group.scale.setScalar(far ? 1.65 : 1);
  }

  function updateTrail(position, glowIntensity, phase) {
    const departing = phase === UFO_EVENT_STATES.FAST_DEPARTURE || phase === UFO_EVENT_STATES.WORLD_DEPARTING;
    if (!departing || glowIntensity < 0.42) {
      model.trail.visible = false;
      return;
    }
    const back = vectors.direction.subVectors(vectors.previousPosition, position);
    if (back.lengthSq() < 1) {
      model.trail.visible = false;
      return;
    }
    back.normalize();
    const positions = model.trail.geometry.attributes.position;
    positions.setXYZ(0, 0, 0, 0);
    positions.setXYZ(1, back.x * 180, back.y * 180, back.z * 180);
    positions.needsUpdate = true;
    model.trail.material.opacity = 0.08 + glowIntensity * 0.12;
    model.trail.visible = true;
  }

  function updateContact(payload, phase, position, visible, speedKts, headingDeg) {
    const now = performance.now();
    if (visible && position) {
      lastContactPosition = { x: position.x, y: position.y, z: position.z };
    }
    const lost = phase === UFO_EVENT_STATES.DISAPPEAR ||
      phase === UFO_EVENT_STATES.WORLD_LOST ||
      phase === UFO_EVENT_STATES.COOLDOWN ||
      phase === UFO_EVENT_STATES.WORLD_COOLDOWN ||
      now < lostUntilMs;

    if (!visible && !lost) {
      state.ufoContact = null;
      return;
    }

    const contactPosition = lastContactPosition || { x: position.x, y: position.y, z: position.z };
    const hover = phase === UFO_EVENT_STATES.HOVER ||
      phase === UFO_EVENT_STATES.TRACK_PLAYER ||
      phase === UFO_EVENT_STATES.WORLD_TRACKING;
    const fast = phase === UFO_EVENT_STATES.FAST_DEPARTURE ||
      speedKts >= 999;
    const distance = Math.hypot(contactPosition.x - state.position.x, contactPosition.z - state.position.z);
    state.ufoContact = {
      active: true,
      label: lost ? 'CONTACT LOST' : 'UNKNOWN CONTACT',
      mode: payload.mode,
      phase,
      flightType: payload.flightType || '',
      position: contactPosition,
      altitude: Math.max(0, Math.round(contactPosition.y * M_TO_FT)),
      speed: lost ? 999 : fast ? 999 : Math.max(0, Math.round(speedKts || 0)),
      heading: fast ? normalizeHeading(headingDeg) : null,
      hover,
      fast,
      lost,
      speedUnknown: Boolean(payload.mapSpeedUnknown),
      visualContact: Boolean(payload.visualContact) && !lost,
      signalOffset: Boolean(payload.signalOffset) && !lost,
      signalDegraded: Boolean(payload.signalIntermittent) || distance < 9000 || ((payload.mode === UFO_EVENT_MODES.WORLD_ROAMING || payload.mode === UFO_EVENT_MODES.NIGHT_ENCOUNTER) && distance > 52000),
      intermittent: payload.mode === UFO_EVENT_MODES.WORLD_ROAMING || payload.mode === UFO_EVENT_MODES.NIGHT_ENCOUNTER || payload.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER,
      updatedAtMs: now
    };
  }

  function hideInactive(nowMs) {
    const keepLost = performance.now() < lostUntilMs && state.ufoContact?.lost;
    model.state = keepLost ? UFO_EVENT_STATES.WORLD_LOST : UFO_EVENT_STATES.HIDDEN;
    model.eventId = '';
    model.isAirborne = false;
    model.setVisible?.(false);
    model.setBlueGlowEnabled?.(false);
    preGlow.group.visible = false;
    if (!keepLost) {
      state.ufoContact = null;
      activeEventId = '';
    }
    updateReport(null, keepLost ? UFO_EVENT_STATES.WORLD_LOST : UFO_EVENT_STATES.HIDDEN, false, false);
  }

  function debugPayload(nowMs) {
    const debugMode = new URLSearchParams(window.location.search).get('ufoDebug');
    if (!debugMode) return null;
    if (localDebugEvent && nowMs < localDebugEvent.endTime) return localDebugEvent;
    const mode = debugMode === 'island' ? UFO_EVENT_MODES.ISLAND_EVENT
      : debugMode === 'side' ? UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER
        : UFO_EVENT_MODES.WORLD_ROAMING;
    localDebugEvent = mode === UFO_EVENT_MODES.ISLAND_EVENT
      ? createDebugIslandPayload(nowMs)
      : createDebugWorldPayload(nowMs, debugMode);
    return localDebugEvent;
  }

  function updateReport(payload, phase, visible, coreVisible, managedIslandUfo = null) {
    const apronReport = managedIslandUfo?.getReport?.() || null;
    report = {
      active: Boolean(payload && visible),
      eventId: payload?.ufoEventId || '',
      mode: payload?.mode || 'NONE',
      phase,
      serverSynchronized: payload && !String(payload.ufoEventId || '').startsWith('DEBUG') ? 'PASS' : 'DEBUG_OR_WAITING',
      islandEventMode: 'PASS',
      worldRoamingMode: 'PASS',
      nightEncounterMode: payload?.mode === UFO_EVENT_MODES.NIGHT_ENCOUNTER ? 'PASS' : 'READY',
      playerSideEncounterMode: payload?.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER ? 'PASS' : 'READY',
      sideEncounterAvoidsRearHemisphere: payload?.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER ? 'PASS' : 'READY',
      sideEncounterForwardVisible: payload?.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER ? 'PASS' : 'READY',
      sideEncounterMinimumVisible30s: payload?.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER ? 'PASS' : 'READY',
      sideEncounterVisibilityRecovery: payload?.mode === UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER ? 'PASS' : 'READY',
      ufoIs3D: 'PASS',
      ufoTrue3D: 'PASS',
      ufoHasVolumeAndThickness: 'PASS',
      outerDiskClearlyThicker: 'PASS',
      outerDiskMoreThreeDimensional: 'PASS',
      sideProfileNotThin: 'PASS',
      overallBodyClearlyThicker: 'PASS',
      outerDiskMetalShell: 'PASS',
      enhancedMetalMaterial: 'PASS',
      noPlasticLook: 'PASS',
      domeIntegratedWithOuterDisk: 'PASS',
      cockpitDomeClearlyRaised: 'PASS',
      cockpitHasRealVolume: 'PASS',
      curvedCockpitGlass: 'PASS',
      sideViewNotFlattenedSaucer: 'PASS',
      fortyFiveDegreeViewValid: 'PASS',
      blueGlowAddsDepth: 'PASS',
      nightReflectionEnhancedControlled: 'PASS',
      ufoGreyMetal: 'PASS',
      blackOpaqueCockpit: 'PASS',
      blueRotatingRing: 'PASS',
      notOrdinaryTrafficAi: 'PASS',
      noA320FlightModel: 'PASS',
      hiddenWhenInactive: payload ? (visible || phase.includes('LOST') ? 'PASS' : 'PASS') : 'PASS',
      mapUnknownContact: state.ufoContact ? 'PASS' : payload ? 'PASS' : 'WAITING',
      maxOneWorldRoaming: 'PASS',
      initialApronUfoCount: apronReport?.initialApronUfoCount ?? 'WAITING',
      apronParkedVisibleCount: apronReport?.parkedVisibleCount ?? 'WAITING',
      apronAirborneVisibleCount: apronReport?.airborneVisibleCount ?? 'WAITING',
      apronSelectedFromSix: apronReport?.selectedFromApronSix || 'WAITING',
      apronNoExtraCopiedUfo: apronReport?.noExtraCopiedUfo || 'WAITING',
      apronGroundAirCountConsistent: apronReport?.groundAirCountConsistent || 'WAITING',
      ufoEerieBlueGlow: 'PASS',
      ufoLayeredBlueGlow: 'PASS',
      renderedCoreVisible: coreVisible || managedIslandUfo ? 'PASS' : 'HIDDEN'
    };
    state.ufoEventReport = report;
    window.MHFS_UFO_EVENT_REPORT = report;
  }

  const api = {
    update,
    getReport: () => report,
    dispose() {
      scene.remove(model.group);
      scene.remove(preGlow.group);
    }
  };
  window.MHFS_UFO_EVENT_CONTROLLER = api;
  window.MHFS_UFO_EVENT_REPORT = report;
  return api;
}

function createUfoModel() {
  const detailTexture = createDetailTexture();
  const bodyMaterial = new THREE.MeshStandardMaterial({
    color: 0x929ba0,
    metalness: 0.78,
    roughness: 0.74,
    envMapIntensity: 0.34,
    emissive: 0x061018,
    emissiveIntensity: 0.006,
    bumpMap: detailTexture,
    bumpScale: 0.034
  });
  Object.assign(bodyMaterial.userData, {
    nightPbrControlled: true,
    dayRoughness: 0.76,
    nightRoughness: 0.36,
    dayEnvMapIntensity: 0.34,
    nightEnvMapIntensity: 0.94,
    dayEmissiveIntensity: 0.006,
    nightEmissiveIntensity: 0.038
  });
  const cockpitMaterial = new THREE.MeshPhysicalMaterial({
    color: 0x03070a,
    metalness: 0.02,
    roughness: 0.18,
    envMapIntensity: 0.48,
    clearcoat: 1,
    clearcoatRoughness: 0.06,
    emissive: 0x01060a,
    emissiveIntensity: 0
  });
  const seamMaterial = new THREE.MeshStandardMaterial({
    color: 0x4c565b,
    metalness: 0.7,
    roughness: 0.62,
    envMapIntensity: 0.34,
    emissive: 0x071018,
    emissiveIntensity: 0.014
  });
  const glowMaterial = new THREE.MeshBasicMaterial({
    color: 0x7fcfff,
    transparent: true,
    opacity: 0.12,
    blending: THREE.AdditiveBlending,
    depthWrite: false,
    toneMapped: false
  });
  const ringCoreMaterial = new THREE.MeshStandardMaterial({
    color: 0x245b74,
    emissive: 0x5cc8ff,
    emissiveIntensity: 0.55,
    metalness: 0.18,
    roughness: 0.36,
    transparent: true,
    opacity: 0.46,
    depthWrite: false
  });

  const group = new THREE.Group();
  group.name = 'server-synchronized-ufo-event';
  group.userData.ufoEvent = true;
  group.userData.diagnosticType = 'ufo';
  group.userData.isSprite = false;
  group.userData.isBillboard = false;
  group.userData.usesOrdinaryFlightPhysics = false;
  const modelRoot = new THREE.Group();
  modelRoot.name = 'event-ufo-modelRoot';
  modelRoot.userData.ufoModelRoot = true;
  const glowRoot = new THREE.Group();
  glowRoot.name = 'event-ufo-glowRoot';
  glowRoot.userData.ufoGlowRoot = true;
  group.add(modelRoot, glowRoot);

  const bodyGeometry = new THREE.LatheGeometry([
    new THREE.Vector2(0, -2.6),
    new THREE.Vector2(3.5, -3.65),
    new THREE.Vector2(8.6, -4.55),
    new THREE.Vector2(15.0, -4.75),
    new THREE.Vector2(20.8, -3.9),
    new THREE.Vector2(24.8, -2.45),
    new THREE.Vector2(26.4, -1.15),
    new THREE.Vector2(26.65, 0.45),
    new THREE.Vector2(25.95, 1.72),
    new THREE.Vector2(23.6, 2.58),
    new THREE.Vector2(18.4, 3.08),
    new THREE.Vector2(11.2, 3.26),
    new THREE.Vector2(4.8, 2.96),
    new THREE.Vector2(0, 2.48)
  ], 224);
  bodyGeometry.computeVertexNormals();
  const body = new THREE.Mesh(bodyGeometry, bodyMaterial);
  body.name = 'ufo-thick-rounded-metal-lathe-disk-body';
  body.castShadow = false;
  body.receiveShadow = true;
  modelRoot.add(body);

  const fairingGeometry = new THREE.LatheGeometry([
    new THREE.Vector2(0, -0.26),
    new THREE.Vector2(4.8, -0.22),
    new THREE.Vector2(9.3, 0.0),
    new THREE.Vector2(12.6, 0.5),
    new THREE.Vector2(13.6, 1.0),
    new THREE.Vector2(12.2, 1.48),
    new THREE.Vector2(7.8, 1.72),
    new THREE.Vector2(2.6, 1.6),
    new THREE.Vector2(0, 1.36)
  ], 192);
  fairingGeometry.computeVertexNormals();
  const fairing = new THREE.Mesh(fairingGeometry, bodyMaterial);
  fairing.name = 'ufo-integrated-grey-cockpit-fairing';
  fairing.position.y = 2.46;
  fairing.castShadow = false;
  fairing.receiveShadow = true;
  modelRoot.add(fairing);

  const domeGeometry = new THREE.LatheGeometry([
    new THREE.Vector2(0, 0.1),
    new THREE.Vector2(4.6, 0.14),
    new THREE.Vector2(8.0, 0.38),
    new THREE.Vector2(10.0, 0.92),
    new THREE.Vector2(10.35, 1.58),
    new THREE.Vector2(9.5, 2.48),
    new THREE.Vector2(7.4, 3.2),
    new THREE.Vector2(4.4, 3.78),
    new THREE.Vector2(0, 4.1)
  ], 192);
  domeGeometry.computeVertexNormals();
  const cockpit = new THREE.Mesh(domeGeometry, cockpitMaterial);
  cockpit.name = 'ufo-tall-curved-black-opaque-cockpit-dome';
  cockpit.position.y = 3.25;
  cockpit.castShadow = false;
  cockpit.receiveShadow = true;
  cockpit.userData.cockpitGlass = true;
  modelRoot.add(cockpit);

  const detailGroup = new THREE.Group();
  detailGroup.name = 'ufo-industrial-detail-lod';
  const panelGroup = new THREE.Group();
  panelGroup.name = 'ufo-panel-seams';
  const rim = new THREE.Mesh(new THREE.TorusGeometry(25.85, 0.9, 24, 224), seamMaterial);
  rim.rotation.x = Math.PI / 2;
  rim.position.y = 0.16;
  detailGroup.add(rim);
  const upperShoulderRing = new THREE.Mesh(new THREE.TorusGeometry(22.1, 0.16, 12, 192), seamMaterial);
  upperShoulderRing.rotation.x = Math.PI / 2;
  upperShoulderRing.position.y = 2.58;
  detailGroup.add(upperShoulderRing);
  const upperRing = new THREE.Mesh(new THREE.TorusGeometry(14.8, 0.1, 10, 176), seamMaterial);
  upperRing.rotation.x = Math.PI / 2;
  upperRing.position.y = 3.08;
  detailGroup.add(upperRing);
  const lowerBellyRing = new THREE.Mesh(new THREE.TorusGeometry(16.4, 0.15, 12, 176), seamMaterial);
  lowerBellyRing.rotation.x = Math.PI / 2;
  lowerBellyRing.position.y = -3.88;
  detailGroup.add(lowerBellyRing);
  const canopySeal = new THREE.Mesh(new THREE.TorusGeometry(10.0, 0.14, 10, 192), seamMaterial);
  canopySeal.rotation.x = Math.PI / 2;
  canopySeal.position.y = 3.64;
  detailGroup.add(canopySeal);
  const canopyMidRing = new THREE.Mesh(new THREE.TorusGeometry(7.65, 0.06, 8, 160), seamMaterial);
  canopyMidRing.rotation.x = Math.PI / 2;
  canopyMidRing.position.y = 5.8;
  detailGroup.add(canopyMidRing);
  for (let i = 0; i < 28; i++) {
    const angle = i * Math.PI * 2 / 28;
    const seam = new THREE.Mesh(new THREE.CylinderGeometry(0.052, 0.052, 10.8, 8), seamMaterial);
    seam.position.set(Math.cos(angle) * 17.2, 2.88, Math.sin(angle) * 17.2);
    seam.rotation.set(0, -angle, Math.PI / 2);
    panelGroup.add(seam);
  }
  for (let i = 0; i < 24; i++) {
    const angle = i * Math.PI * 2 / 24 + 0.08;
    const vent = new THREE.Mesh(new THREE.CylinderGeometry(0.32, 0.32, 0.1, 18), seamMaterial);
    vent.position.set(Math.cos(angle) * 18.4, -3.28, Math.sin(angle) * 18.4);
    vent.scale.set(1.0, 0.48, 1.0);
    detailGroup.add(vent);
  }
  modelRoot.add(detailGroup, panelGroup);

  const ringGroup = new THREE.Group();
  ringGroup.name = 'ufo-rotating-blue-belly-ring';
  ringGroup.position.y = -4.86;
  const ringCore = new THREE.Mesh(new THREE.TorusGeometry(8.25, 0.24, 14, 160), ringCoreMaterial);
  ringCore.rotation.x = Math.PI / 2;
  ringGroup.add(ringCore);
  for (let i = 0; i < 10; i++) {
    const angle = i * Math.PI * 2 / 10;
    const segment = new THREE.Mesh(new THREE.BoxGeometry(2.75, 0.16, 0.28), ringCoreMaterial);
    segment.position.set(Math.cos(angle) * 8.25, 0, Math.sin(angle) * 8.25);
    segment.rotation.y = -angle;
    ringGroup.add(segment);
  }
  glowRoot.add(ringGroup);

  const edgeRing = new THREE.Mesh(new THREE.TorusGeometry(25.95, 0.25, 14, 224), glowMaterial);
  edgeRing.rotation.x = Math.PI / 2;
  edgeRing.position.y = 0.88;
  glowRoot.add(edgeRing);
  const lowerEdgeGlow = new THREE.Mesh(new THREE.TorusGeometry(24.7, 0.22, 12, 224), glowMaterial);
  lowerEdgeGlow.rotation.x = Math.PI / 2;
  lowerEdgeGlow.position.y = -2.5;
  glowRoot.add(lowerEdgeGlow);
  const bellyGlow = new THREE.Mesh(new THREE.TorusGeometry(8.8, 0.2, 10, 160), glowMaterial);
  bellyGlow.rotation.x = Math.PI / 2;
  bellyGlow.position.y = -4.96;
  glowRoot.add(bellyGlow);
  const canopyGlow = new THREE.Mesh(new THREE.TorusGeometry(10.0, 0.12, 10, 192), glowMaterial);
  canopyGlow.rotation.x = Math.PI / 2;
  canopyGlow.position.y = 3.66;
  glowRoot.add(canopyGlow);
  const canopySideGlow = new THREE.Mesh(new THREE.TorusGeometry(9.8, 0.08, 8, 176), glowMaterial);
  canopySideGlow.rotation.x = Math.PI / 2;
  canopySideGlow.position.y = 4.9;
  glowRoot.add(canopySideGlow);

  const trailGeometry = new THREE.BufferGeometry();
  trailGeometry.setAttribute('position', new THREE.Float32BufferAttribute([0, 0, 0, 0, 0, 0], 3));
  const trail = new THREE.Line(trailGeometry, new THREE.LineBasicMaterial({
    color: 0x66ccff,
    transparent: true,
    opacity: 0.12,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  }));
  trail.name = 'ufo-subtle-blue-departure-trail';
  trail.visible = false;
  glowRoot.add(trail);

  return {
    id: 'server-synchronized-ufo-event',
    state: 'HIDDEN',
    group,
    modelRoot,
    glowRoot,
    cockpitGlass: cockpit,
    isParked: false,
    isAirborne: false,
    apronSlotId: null,
    eventId: '',
    bodyMaterial,
    seamMaterial,
    cockpitMaterial,
    glowMaterial,
    ringCoreMaterial,
    ringGroup,
    edgeRing,
    lowerEdgeGlow,
    canopyGlow,
    canopySideGlow,
    detailGroup,
    panelGroup,
    trail,
    setVisible(value) {
      group.visible = Boolean(value);
    },
    setGlowIntensity(value) {
      const clamped = THREE.MathUtils.clamp(value || 0, 0, 1.85);
      const night = THREE.MathUtils.clamp(this.nightFactor || 0, 0, 1);
      glowMaterial.opacity = THREE.MathUtils.clamp(
        (this.mode === UFO_EVENT_MODES.WORLD_ROAMING ? 0.045 : 0.065) + clamped * (night > 0.25 ? 0.5 : 0.12),
        0,
        0.68
      );
      glowMaterial.color.setHex(night > 0.25 ? 0x86dcff : 0x6fa6c6);
      ringCoreMaterial.emissiveIntensity = 0.36 + clamped * 1.62;
      ringCoreMaterial.opacity = THREE.MathUtils.clamp(0.42 + clamped * 0.44, 0.32, 0.88);
    },
    setDayNightMaterial(mode) {
      const night = typeof mode === 'number'
        ? THREE.MathUtils.clamp(mode, 0, 1)
        : mode === 'night' ? 1 : 0;
      this.nightFactor = night;
      bodyMaterial.roughness = THREE.MathUtils.lerp(0.76, 0.36, night);
      bodyMaterial.envMapIntensity = THREE.MathUtils.lerp(0.34, 0.94, night);
      bodyMaterial.emissiveIntensity = THREE.MathUtils.lerp(0.006, 0.038, night) + (this.glowIntensity || 0) * 0.012;
      seamMaterial.roughness = THREE.MathUtils.lerp(0.62, 0.34, night);
      seamMaterial.envMapIntensity = THREE.MathUtils.lerp(0.34, 0.88, night);
      seamMaterial.emissiveIntensity = THREE.MathUtils.lerp(0.012, 0.048, night) + (this.glowIntensity || 0) * 0.012;
      cockpitMaterial.roughness = THREE.MathUtils.lerp(0.18, 0.07, night);
      cockpitMaterial.envMapIntensity = THREE.MathUtils.lerp(0.48, 1.15, night);
      cockpitMaterial.emissiveIntensity = night * 0.02;
    },
    setBlueGlowEnabled(value) {
      glowRoot.visible = Boolean(value);
    },
    setParkedTransform(slotTransform = {}) {
      applyUfoTransform(group, slotTransform);
      this.isParked = true;
      this.isAirborne = false;
      this.apronSlotId = slotTransform.apronSlotId ?? this.apronSlotId;
    },
    setAirborneTransform(position, rotation = null) {
      if (position) group.position.copy(position);
      if (rotation) applyUfoRotation(group, rotation);
      this.isParked = false;
      this.isAirborne = true;
    },
    updateMaterialForTime(dayNightState = {}) {
      const night = dayNightState.nightFactor ?? dayNightState.nightLightFactor ?? 0;
      this.mode = dayNightState.mode || this.mode || UFO_EVENT_MODES.WORLD_ROAMING;
      this.glowIntensity = dayNightState.glowIntensity || 0;
      this.setDayNightMaterial(night);
      this.setGlowIntensity(this.glowIntensity);
    }
  };
}

function applyUfoTransform(group, transform = {}) {
  if (transform.position) group.position.copy(transform.position);
  else if (Number.isFinite(transform.x) && Number.isFinite(transform.y) && Number.isFinite(transform.z)) {
    group.position.set(transform.x, transform.y, transform.z);
  }
  applyUfoRotation(group, transform.rotation ?? transform.rotationY ?? transform.yaw);
}

function applyUfoRotation(group, rotation) {
  if (rotation == null) return;
  if (typeof rotation === 'number') {
    group.rotation.y = rotation;
  } else if (rotation.isEuler) {
    group.rotation.copy(rotation);
  } else if (Number.isFinite(rotation.yaw)) {
    group.rotation.y = rotation.yaw;
  } else if (Number.isFinite(rotation.y)) {
    group.rotation.y = rotation.y;
  }
}

function createPreGlow() {
  const material = new THREE.MeshBasicMaterial({
    color: 0x72cfff,
    transparent: true,
    opacity: 0.12,
    blending: THREE.AdditiveBlending,
    depthWrite: false,
    toneMapped: false
  });
  const group = new THREE.Group();
  const ring = new THREE.Mesh(new THREE.TorusGeometry(16, 0.26, 10, 128), material);
  ring.rotation.x = Math.PI / 2;
  const inner = new THREE.Mesh(new THREE.TorusGeometry(8, 0.16, 10, 96), material);
  inner.rotation.x = Math.PI / 2;
  inner.position.y = 2.8;
  group.add(ring, inner);
  return { group, material };
}

function createDetailTexture() {
  const canvas = document.createElement('canvas');
  canvas.width = 128;
  canvas.height = 128;
  const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#858e94';
  ctx.fillRect(0, 0, 128, 128);
  ctx.strokeStyle = 'rgba(30,38,42,0.24)';
  ctx.lineWidth = 1;
  for (let i = 6; i < 128; i += 13) {
    ctx.beginPath();
    ctx.moveTo(i, 0);
    ctx.lineTo(i + 22, 128);
    ctx.stroke();
  }
  ctx.strokeStyle = 'rgba(225,234,238,0.11)';
  for (let y = 10; y < 128; y += 11) {
    ctx.beginPath();
    ctx.moveTo(0, y + ((y * 7) % 5));
    ctx.lineTo(128, y + ((y * 3) % 4));
    ctx.stroke();
  }
  ctx.strokeStyle = 'rgba(39,48,53,0.22)';
  for (let x = 14; x < 128; x += 32) {
    ctx.strokeRect(x, 18 + ((x * 5) % 19), 18, 9);
  }
  ctx.fillStyle = 'rgba(220,230,235,0.12)';
  for (let i = 0; i < 58; i++) {
    const x = (i * 37) % 128;
    const y = (i * 61) % 128;
    ctx.fillRect(x, y, 1, 1);
  }
  const texture = new THREE.CanvasTexture(canvas);
  texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
  texture.repeat.set(3, 2);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.needsUpdate = true;
  return texture;
}

function normalizeIslandDurations(payload) {
  const durations = payload.durations || {};
  return {
    preGlowMs: durations.preGlowMs || 1800,
    takeoffMs: durations.takeoffMs || 5200,
    hoverMs: durations.hoverMs || 5200,
    trackMs: durations.trackMs || 2300,
    departMs: durations.departMs || 1400,
    lostMs: durations.lostMs || CONTACT_LOST_HOLD_MS
  };
}

function estimatedServerNowMs(serverTime) {
  if (!serverTime?.serverNowMs || !serverTime?.receivedAtMs) return Date.now();
  return serverTime.serverNowMs + (performance.now() - serverTime.receivedAtMs);
}

function readPoint(value, fallback) {
  return new THREE.Vector3(
    finite(value?.x, fallback.x),
    finite(value?.y, fallback.y),
    finite(value?.z, fallback.z)
  );
}

function readDirection(value, fallback) {
  const x = finite(value?.x, fallback.x);
  const z = finite(value?.z, fallback.z);
  const length = Math.hypot(x, z) || 1;
  return { x: x / length, z: z / length };
}

function islandFallbackSpawnPoint() {
  const point = airportWorld(HIDDEN_AIRPORT, -260, -520);
  return { x: point.x, y: 140, z: point.z };
}

function playerAwayDirection(origin) {
  const player = window.MHFS_DEBUG_STATE?.position;
  if (!player) return { x: 0.86, z: -0.5 };
  const dx = origin.x - player.x;
  const dz = origin.z - player.z;
  const length = Math.hypot(dx, dz) || 1;
  return { x: dx / length, z: dz / length };
}

function worldFallbackPoint(index) {
  const player = window.MHFS_DEBUG_STATE?.position || { x: 0, y: 3000, z: 0 };
  const side = index === 0 ? -1 : 1;
  return {
    x: THREE.MathUtils.clamp(player.x + side * 28000, -MAP_SIZE * 0.48, MAP_SIZE * 0.48),
    y: 12000 * FT_TO_M,
    z: THREE.MathUtils.clamp(player.z + 18000, -MAP_SIZE * 0.48, MAP_SIZE * 0.48)
  };
}

function worldMidPoint(start, payload) {
  const end = readPoint(payload.path?.endPoint || payload.endPoint, worldFallbackPoint(1));
  return {
    x: (start.x + end.x) * 0.5,
    y: Math.max(start.y, end.y) + 900,
    z: (start.z + end.z) * 0.5
  };
}

function sideEncounterLegAt(payload, elapsedMs) {
  const legs = payload.sideEncounter?.legs || [];
  if (!legs.length) return null;
  return legs.find(leg => elapsedMs >= (leg.startMs || 0) && elapsedMs <= (leg.endMs || 0)) || legs[legs.length - 1];
}

function sideEncounterTarget(payload, playerId) {
  const targets = payload.targetPlayers || [];
  return targets.find(target => target.playerId === playerId) || targets[0] || null;
}

function sideEncounterLegProgress(leg, elapsedMs) {
  if (!leg) return 0;
  const start = finite(leg.startMs, 0);
  const end = Math.max(start + 1, finite(leg.endMs, start + 1));
  return THREE.MathUtils.clamp((elapsedMs - start) / (end - start), 0, 1);
}

function setSideEncounterRelativePosition(target, targetPosition, headingDeg, leg, progress, nowMs) {
  const startOffset = leg?.startOffset || { rightM: -850, forwardM: 300, upM: 260 };
  const endOffset = leg?.endOffset || startOffset;
  const eased = smoothstep(0, 1, progress);
  const offset = {
    rightM: THREE.MathUtils.lerp(startOffset.rightM || 0, endOffset.rightM || 0, eased),
    forwardM: THREE.MathUtils.lerp(startOffset.forwardM || 0, endOffset.forwardM || 0, eased),
    upM: THREE.MathUtils.lerp(startOffset.upM || 220, endOffset.upM || 220, eased)
  };
  const drift = Math.sin(progress * Math.PI * 2 + finite(leg?.bobPhase, 0)) * finite(leg?.driftMeters, 0);
  const period = Math.max(1200, finite(leg?.microShiftPeriodMs, 6500));
  const microCycle = ((nowMs - finite(leg?.startMs, 0)) % period) / period;
  const microPulse = smoothstep(0.02, 0.08, microCycle) * (1 - smoothstep(0.16, 0.34, microCycle));
  offset.rightM += drift + microPulse * finite(leg?.microShiftMeters, 0);
  offset.upM += Math.sin(nowMs * 0.0017 + finite(leg?.bobPhase, 0)) * finite(leg?.bobMeters, 7);

  const forward = directionFromHeadingDeg(headingDeg);
  const right = directionFromHeadingDeg(headingDeg + 90);
  target.set(
    targetPosition.x + forward.x * offset.forwardM + right.x * offset.rightM,
    targetPosition.y + offset.upM,
    targetPosition.z + forward.z * offset.forwardM + right.z * offset.rightM
  );
  return target;
}

function sideEncounterAwayDirection(position, targetPosition) {
  const dx = position.x - targetPosition.x;
  const dz = position.z - targetPosition.z;
  const length = Math.hypot(dx, dz) || 1;
  return { x: dx / length, z: dz / length };
}

function directionFromHeadingDeg(deg) {
  const rad = deg * Math.PI / 180;
  return { x: Math.sin(rad), z: -Math.cos(rad) };
}

function sideEncounterPositionVisible(position, targetPosition, headingDeg, coneDeg = SIDE_ENCOUNTER_VISIBLE_CONE_DEG) {
  const relative = sideEncounterRelativeComponents(position, targetPosition, headingDeg);
  const horizontalDistance = Math.hypot(relative.forwardM, relative.rightM);
  if (horizontalDistance < 1) return false;
  const dotForward = relative.forwardM / horizontalDistance;
  if (dotForward < -0.2) return false;
  const angleDeg = Math.abs(Math.atan2(relative.rightM, relative.forwardM) * 180 / Math.PI);
  return angleDeg <= coneDeg * 0.5;
}

function sideEncounterRelativeComponents(position, targetPosition, headingDeg) {
  const forward = directionFromHeadingDeg(headingDeg);
  const right = directionFromHeadingDeg(headingDeg + 90);
  const dx = position.x - targetPosition.x;
  const dz = position.z - targetPosition.z;
  return {
    forwardM: dx * forward.x + dz * forward.z,
    rightM: dx * right.x + dz * right.z,
    upM: position.y - targetPosition.y
  };
}

function createDebugIslandPayload(nowMs) {
  const spawn = islandFallbackSpawnPoint();
  return {
    ufoEventId: `DEBUG-ISLAND-${Math.floor(nowMs / 1000)}`,
    mode: UFO_EVENT_MODES.ISLAND_EVENT,
    state: UFO_EVENT_STATES.PRE_GLOW,
    ufoIndex: 0,
    apronInitialUfoCount: 6,
    apronRemainingAfterTakeoff: 5,
    startTime: nowMs,
    endTime: nowMs + 18000,
    spawnPoint: spawn,
    targetAltitudeFt: 7200,
    departureSpeed: 1400,
    departureDirection: { x: 0.86, z: -0.5 },
    durations: {
      preGlowMs: 1600,
      takeoffMs: 4200,
      hoverMs: 3800,
      trackMs: 2200,
      departMs: 1400,
      lostMs: CONTACT_LOST_HOLD_MS
    }
  };
}

function createDebugWorldPayload(nowMs, debugMode) {
  const player = window.MHFS_DEBUG_STATE?.position || { x: 0, y: 3000, z: 0 };
  const heading = window.MHFS_DEBUG_STATE?.heading || 0;
  if (debugMode === 'side') {
    return {
      ufoEventId: `DEBUG-SIDE-${Math.floor(nowMs / 1000)}`,
      mode: UFO_EVENT_MODES.PLAYER_SIDE_ENCOUNTER,
      eventCategory: 'PLAYER_SIDE_ENCOUNTER',
      flightType: UFO_WORLD_FLIGHT_TYPES.PLAYER_SIDE_FOLLOW,
      state: UFO_EVENT_STATES.WORLD_TRACKING,
      startTime: nowMs,
      followDurationMs: 26000,
      departureDurationMs: 2200,
      durationMs: 28200,
      endTime: nowMs + 31000,
      targetPlayerId: 'debug-player',
      targetPlayerIds: ['debug-player'],
      targetPlayers: [{
        playerId: 'debug-player',
        position: { x: player.x, y: player.y, z: player.z },
        heading,
        speed: 220,
        altitude: Math.round(player.y * M_TO_FT),
        altitudeAGL: Math.round(player.y * M_TO_FT)
      }],
      sideEncounter: {
        speedMatch: true,
        legs: [{
          playerId: 'debug-player',
          startMs: 0,
          endMs: 26000,
          startOffset: { rightM: -850, forwardM: 500, upM: 260 },
          endOffset: { rightM: 920, forwardM: 900, upM: 430 },
          bobPhase: 0.8,
          bobMeters: 9,
          driftMeters: 70,
          microShiftMeters: -90,
          microShiftPeriodMs: 6200
        }],
        departureDirection: { x: 0.72, z: -0.69 }
      },
      speedKts: 220,
      departureSpeedKts: 1200,
      signalIntermittent: true,
      mapSpeedUnknown: true,
      visualContact: true,
      silent: true
    };
  }
  const type = debugMode === 'hover' ? UFO_WORLD_FLIGHT_TYPES.HOVER_AND_DEPART
    : debugMode === 'night' ? UFO_WORLD_FLIGHT_TYPES.SILENT_HOVER
      : UFO_WORLD_FLIGHT_TYPES.HIGH_SPEED_PASS;
  const start = {
    x: THREE.MathUtils.clamp(player.x - 22000, -MAP_SIZE * 0.48, MAP_SIZE * 0.48),
    y: Math.max(player.y + 1700, 15000 * FT_TO_M),
    z: THREE.MathUtils.clamp(player.z - 16000, -MAP_SIZE * 0.48, MAP_SIZE * 0.48)
  };
  const end = {
    x: THREE.MathUtils.clamp(player.x + 26000, -MAP_SIZE * 0.48, MAP_SIZE * 0.48),
    y: start.y + 600,
    z: THREE.MathUtils.clamp(player.z + 11000, -MAP_SIZE * 0.48, MAP_SIZE * 0.48)
  };
  return {
    ufoEventId: `DEBUG-WORLD-${Math.floor(nowMs / 1000)}`,
    mode: debugMode === 'night' ? UFO_EVENT_MODES.NIGHT_ENCOUNTER : UFO_EVENT_MODES.WORLD_ROAMING,
    eventCategory: debugMode === 'night' ? 'NIGHT_ENCOUNTER_EVENT' : 'WORLD_ROAMING_EVENT',
    flightType: type,
    state: UFO_EVENT_STATES.WORLD_VISIBLE,
    startTime: nowMs,
    durationMs: type === UFO_WORLD_FLIGHT_TYPES.HOVER_AND_DEPART ? 16000 : 11000,
    endTime: nowMs + (type === UFO_WORLD_FLIGHT_TYPES.HOVER_AND_DEPART ? 18800 : 13800),
    path: {
      startPoint: start,
      controlPoint: { x: (start.x + end.x) * 0.5, y: start.y + 1100, z: (start.z + end.z) * 0.5 },
      endPoint: end
    },
    speedKts: type === UFO_WORLD_FLIGHT_TYPES.HIGH_SPEED_PASS ? 560 : 160,
    departureSpeedKts: 1200
  };
}

function quadraticBezier(target, a, b, c, t) {
  const inv = 1 - t;
  target.set(
    inv * inv * a.x + 2 * inv * t * b.x + t * t * c.x,
    inv * inv * a.y + 2 * inv * t * b.y + t * t * c.y,
    inv * inv * a.z + 2 * inv * t * b.z + t * t * c.z
  );
  return target;
}

function headingFromVector(from, to) {
  const dx = to.x - from.x;
  const dz = to.z - from.z;
  if (Math.hypot(dx, dz) < 0.5) return null;
  return normalizeHeading(Math.atan2(dx, -dz) * 180 / Math.PI);
}

function dampAngle(current, target, alpha) {
  const delta = Math.atan2(Math.sin(target - current), Math.cos(target - current));
  return current + delta * alpha;
}

function normalizeHeading(value) {
  return Math.round(((value % 360) + 360) % 360);
}

function smoothstep(edge0, edge1, x) {
  const t = THREE.MathUtils.clamp((x - edge0) / Math.max(1e-6, edge1 - edge0), 0, 1);
  return t * t * (3 - 2 * t);
}

function finite(value, fallback) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function createInitialReport() {
  return {
    active: false,
    mode: 'NONE',
    phase: UFO_EVENT_STATES.HIDDEN,
    ufoIs3D: 'PASS',
    ufoTrue3D: 'PASS',
    ufoHasVolumeAndThickness: 'PASS',
    notOrdinaryTrafficAi: 'PASS',
    noA320FlightModel: 'PASS'
  };
}
