// Generated by tools/buildVirtualSources.js from src/world/water/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import {
  BAYS,
  EDGE_OCEAN_EXTENT,
  EDGE_OCEAN_WIDTH,
  ISLANDS,
  LANDMASSES,
  LAKES,
  MAP_SIZE,
  RIVER_FOAM_Y,
  RIVER_SHORE_Y,
  RIVER_SURFACE_Y,
  RIVER_SYSTEMS,
  WATER_LEVEL
} from '../data/worldData.js?v=202605070100';
import {
  coastlineOffset,
  closestLakeNormalized,
  closestWaterBodyNormalized,
  distanceToMapEdge,
  distanceToRiver,
  isRiverMouthClearancePoint,
  liftSurfaceMaterial,
  smoothstep,
  waterBodyBoundaryLocal,
  waterBodyBoundaryPoint,
  waterBodyNormalized
} from './spatial.js?v=202605056000';

let glossFalloffTexture = null;

export function isRiverGeometryHiddenByWater(x, z, riverDistance = null) {
  if (closestLakeNormalized(x, z) < 0.94) return true;
  if (isRiverMouthClearancePoint(x, z, 230, riverDistance)) return true;
  if (distanceToMapEdge(x, z) < EDGE_OCEAN_WIDTH - 12) return true;
  const inBay = closestWaterBodyNormalized(BAYS, x, z) < 1.04;
  const onIsland = closestWaterBodyNormalized(ISLANDS, x, z) < 1.04;
  return inBay && !onIsland;
}

export function createWaterSystem({ scene, waterBands, mulberry32 }) {
  function createWaterSystems(quality = null) {
    const denseScenery = quality?.denseScenery === true;
    const rng = mulberry32(61830);
    const shoreMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({ color: 0xe8d68a, roughness: 0.9, metalness: 0.01 }), -1, -1);
    const waterMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({
      color: 0x2f93bf,
      emissive: 0x0a334d,
      emissiveIntensity: 0.15,
      roughness: 0.13,
      metalness: 0.24,
      dithering: true,
      depthWrite: true
    }), -4, -4);
    const glossMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({
      color: 0xb6efff,
      roughness: 0.05,
      metalness: 0.08,
      transparent: true,
      opacity: 0.075,
      alphaMap: createGlossFalloffTexture(),
      depthWrite: false
    }), -3, -3);
  
    for (const lake of LAKES) {
      const group = new THREE.Group();
      group.position.set(lake.x, lake.level, lake.z);
      group.rotation.y = lake.rotation;
      scene.add(group);
  
      const shore = createOpenWaterBodyShore(lake, shoreMaterial, 0.88, 1.1, 160);
      shore.receiveShadow = true;
      shore.renderOrder = 1;
      group.add(shore);
  
      const water = new THREE.Mesh(new THREE.CircleGeometry(1, 128), waterMaterial.clone());
      water.rotation.x = -Math.PI / 2;
      water.position.y = 0.08;
      water.scale.set(lake.rx * 0.96, lake.rz * 0.96, 1);
      water.renderOrder = 2;
      group.add(water);
  
      const gloss = new THREE.Mesh(new THREE.CircleGeometry(1, 96), glossMaterial.clone());
      gloss.rotation.x = -Math.PI / 2;
      gloss.position.set(-lake.rx * 0.16, 0.1, -lake.rz * 0.08);
      gloss.scale.set(lake.rx * 0.44, lake.rz * 0.2, 1);
      gloss.renderOrder = 3;
      group.add(gloss);
  
      if (denseScenery) {
        const waveMaterial = new THREE.MeshBasicMaterial({ color: 0xc8f6ff, transparent: true, opacity: 0.18, depthWrite: false });
        for (let i = 0; i < 34; i++) {
          let lx = 0;
          let lz = 0;
          for (let attempt = 0; attempt < 12; attempt++) {
            lx = (rng() - 0.5) * lake.rx * 1.55;
            lz = (rng() - 0.5) * lake.rz * 1.55;
            if ((lx / lake.rx) ** 2 + (lz / lake.rz) ** 2 < 0.78) break;
          }
          const width = lake.rx * (0.22 + rng() * 0.48);
          const band = new THREE.Mesh(new THREE.PlaneGeometry(width, 3 + rng() * 5), waveMaterial.clone());
          band.rotation.x = -Math.PI / 2;
          band.rotation.z = (rng() - 0.5) * 0.18;
          band.position.set(lx, 0.14, lz);
          group.add(band);
          waterBands.push({ mesh: band, baseX: lx, phase: rng() * Math.PI * 2, speed: 0.45 + rng() * 0.75, travel: 10 + rng() * 18 });
        }
      }
    }
  
    createWorldOceanWater(rng, waterMaterial, glossMaterial, denseScenery);
    createBayWater(rng, shoreMaterial, waterMaterial, glossMaterial, denseScenery);
    createLandmassShores(shoreMaterial);
    if (denseScenery) {
      for (const river of RIVER_SYSTEMS) createRiverSegments(river, rng, shoreMaterial, waterMaterial);
      createRiverMouths(rng, shoreMaterial, waterMaterial);
      createLakeRiverConfluences(rng, waterMaterial);
    }
  }

  function createWorldOceanWater(rng, waterMaterial, glossMaterial, denseScenery = true) {
    const span = MAP_SIZE + EDGE_OCEAN_EXTENT * 1.74;
    const oceanMaterial = waterMaterial.clone();
    oceanMaterial.color.setHex(0x226f98);
    oceanMaterial.emissive.setHex(0x062d44);
    oceanMaterial.emissiveIntensity = 0.16;
    oceanMaterial.roughness = 0.18;
    oceanMaterial.metalness = 0.28;

    const ocean = new THREE.Mesh(new THREE.BoxGeometry(span, 0.14, span), oceanMaterial);
    ocean.position.set(0, WATER_LEVEL + 0.08, 0);
    ocean.receiveShadow = false;
    ocean.renderOrder = -2;
    ocean.frustumCulled = false;
    scene.add(ocean);

    const horizonMaterial = glossMaterial.clone();
    horizonMaterial.alphaMap = null;
    horizonMaterial.opacity = 0.045;
    const horizon = new THREE.Mesh(new THREE.PlaneGeometry(span * 1.08, span * 1.08, 1, 1), horizonMaterial);
    horizon.rotation.x = -Math.PI / 2;
    horizon.position.set(0, WATER_LEVEL + 0.19, 0);
    horizon.renderOrder = -1;
    horizon.frustumCulled = false;
    scene.add(horizon);

    const farSheenMaterial = glossMaterial.clone();
    farSheenMaterial.alphaMap = null;
    farSheenMaterial.opacity = 0.035;
    const farSheen = new THREE.Mesh(new THREE.PlaneGeometry(span * 0.76, span * 0.76, 1, 1), farSheenMaterial);
    farSheen.rotation.x = -Math.PI / 2;
    farSheen.position.set(-span * 0.05, WATER_LEVEL + 0.24, -span * 0.04);
    farSheen.renderOrder = 0;
    farSheen.frustumCulled = false;
    scene.add(farSheen);

    if (!denseScenery) return;

    const waveMaterial = new THREE.MeshBasicMaterial({
      color: 0xd6fbff,
      transparent: true,
      opacity: 0.105,
      depthWrite: false
    });

    const offshoreBands = [];
    for (const land of LANDMASSES) {
      const count = land.rx > 2500 ? 58 : 24;
      for (let i = 0; i < count; i++) {
        const angle = rng() * Math.PI * 2;
        const radius = 1.055 + rng() * 0.32;
        const point = waterBodyBoundaryPoint(land, angle, radius);
        const tangent = angle + Math.PI / 2 + (land.rotation || 0);
        offshoreBands.push({ point, tangent, length: 130 + rng() * 290 });
      }
    }

    for (const item of offshoreBands) {
      const band = new THREE.Mesh(new THREE.PlaneGeometry(item.length, 3 + rng() * 4.5), waveMaterial.clone());
      band.rotation.x = -Math.PI / 2;
      band.rotation.z = -item.tangent + (rng() - 0.5) * 0.18;
      band.position.set(item.point.x, WATER_LEVEL + 0.22, item.point.z);
      band.renderOrder = 0;
      scene.add(band);
      waterBands.push({
        mesh: band,
        baseX: band.position.x,
        phase: rng() * Math.PI * 2,
        speed: 0.22 + rng() * 0.34,
        travel: 5 + rng() * 15,
        worldAxis: true
      });
    }
  }

  function createLandmassShores(shoreMaterial) {
    for (const land of LANDMASSES) {
      const group = new THREE.Group();
      group.position.set(land.x, WATER_LEVEL + 0.11, land.z);
      group.rotation.y = land.rotation || 0;
      scene.add(group);

      const segments = land.rx > 2500 ? 256 : 128;
      const shore = createLandmassShoreRing(land, shoreMaterial, 0.94, 1.055, segments);
      shore.receiveShadow = true;
      shore.renderOrder = 1;
      group.add(shore);
    }
  }

  function createLandmassShoreRing(body, material, innerScale, outerScale, segments) {
    const positions = [];
    const indices = [];
    let vertex = 0;

    for (let i = 0; i < segments; i++) {
      const a0 = (i / segments) * Math.PI * 2;
      const a1 = ((i + 1) / segments) * Math.PI * 2;
      const mid = (a0 + a1) * 0.5;
      const midWorld = waterBodyBoundaryPoint(body, mid, 1.0);
      if (distanceToRiver(midWorld.x, midWorld.z) < 210) continue;

      const inner0 = waterBodyBoundaryLocal(body, a0, innerScale);
      const outer0 = waterBodyBoundaryLocal(body, a0, outerScale);
      const outer1 = waterBodyBoundaryLocal(body, a1, outerScale);
      const inner1 = waterBodyBoundaryLocal(body, a1, innerScale);
      const points = [
        [inner0.x, 0, inner0.z],
        [outer0.x, 0, outer0.z],
        [outer1.x, 0, outer1.z],
        [inner1.x, 0, inner1.z]
      ];
      for (const point of points) positions.push(...point);
      indices.push(vertex, vertex + 2, vertex + 1, vertex, vertex + 3, vertex + 2);
      vertex += 4;
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geometry.setIndex(indices);
    geometry.computeVertexNormals();
    return new THREE.Mesh(geometry, material);
  }

  function createEdgeOceanWater(rng, shoreMaterial, waterMaterial, glossMaterial) {
    const half = MAP_SIZE / 2;
    const oceanMaterial = waterMaterial.clone();
    oceanMaterial.opacity = 0.86;
    const outer = EDGE_OCEAN_EXTENT;
    const middleSpan = MAP_SIZE - EDGE_OCEAN_WIDTH * 2;
    const strips = [
      { x: 0, z: -half + EDGE_OCEAN_WIDTH / 2 - outer / 2, w: MAP_SIZE + outer * 2, d: EDGE_OCEAN_WIDTH + outer, shoreZ: -half + EDGE_OCEAN_WIDTH + 8 },
      { x: 0, z: half - EDGE_OCEAN_WIDTH / 2 + outer / 2, w: MAP_SIZE + outer * 2, d: EDGE_OCEAN_WIDTH + outer, shoreZ: half - EDGE_OCEAN_WIDTH - 8 },
      { x: -half + EDGE_OCEAN_WIDTH / 2 - outer / 2, z: 0, w: EDGE_OCEAN_WIDTH + outer, d: middleSpan, shoreX: -half + EDGE_OCEAN_WIDTH + 8 },
      { x: half - EDGE_OCEAN_WIDTH / 2 + outer / 2, z: 0, w: EDGE_OCEAN_WIDTH + outer, d: middleSpan, shoreX: half - EDGE_OCEAN_WIDTH - 8 }
    ];
  
    for (const strip of strips) {
      const water = new THREE.Mesh(new THREE.BoxGeometry(strip.w, 0.12, strip.d), oceanMaterial.clone());
      water.position.set(strip.x, WATER_LEVEL + 0.12, strip.z);
      scene.add(water);
  
      createSegmentedEdgeShore(strip, shoreMaterial);
    }
  
    const waveMaterial = new THREE.MeshBasicMaterial({ color: 0xd6fbff, transparent: true, opacity: 0.09, depthWrite: false });
    const visibleOffshore = Math.min(14000, EDGE_OCEAN_EXTENT * 0.24);
    for (let i = 0; i < 120; i++) {
      const vertical = rng() > 0.5;
      const edgeSign = rng() > 0.5 ? 1 : -1;
      const offshore = rng() < 0.58
        ? rng() * EDGE_OCEAN_WIDTH * 0.86
        : EDGE_OCEAN_WIDTH * 0.7 + Math.pow(rng(), 1.75) * visibleOffshore;
      const length = 160 + rng() * 260;
      const band = new THREE.Mesh(new THREE.PlaneGeometry(length, 3 + rng() * 4), waveMaterial.clone());
      band.rotation.x = -Math.PI / 2;
      if (vertical) {
        band.rotation.z = Math.PI / 2 + (rng() - 0.5) * 0.16;
        band.position.set(edgeSign * (half - EDGE_OCEAN_WIDTH + offshore), WATER_LEVEL + 0.18, (rng() - 0.5) * middleSpan);
      } else {
        band.rotation.z = (rng() - 0.5) * 0.16;
        band.position.set((rng() - 0.5) * (MAP_SIZE + visibleOffshore * 1.4), WATER_LEVEL + 0.18, edgeSign * (half - EDGE_OCEAN_WIDTH + offshore));
      }
      scene.add(band);
      waterBands.push({ mesh: band, baseX: band.position.x, phase: rng() * Math.PI * 2, speed: 0.24 + rng() * 0.42, travel: 8 + rng() * 18, worldAxis: true });
    }
  }

  function createBayWater(rng, shoreMaterial, waterMaterial, glossMaterial, denseScenery = true) {
    for (const bay of BAYS) {
      const group = new THREE.Group();
      group.position.set(bay.x, bay.level, bay.z);
      group.rotation.y = bay.rotation;
      scene.add(group);
  
      const shore = createOpenWaterBodyShore(bay, shoreMaterial, 0.91, 1.05, 192);
      shore.receiveShadow = true;
      shore.renderOrder = 1;
      group.add(shore);
  
      const water = new THREE.Mesh(new THREE.CircleGeometry(1, 160), waterMaterial.clone());
      water.rotation.x = -Math.PI / 2;
      water.position.y = 0.08;
      water.scale.set(bay.rx * 0.98, bay.rz * 0.98, 1);
      water.renderOrder = 2;
      group.add(water);
  
      const gloss = new THREE.Mesh(new THREE.CircleGeometry(1, 96), glossMaterial.clone());
      gloss.rotation.x = -Math.PI / 2;
      gloss.position.set(-bay.rx * 0.18, 0.12, -bay.rz * 0.12);
      gloss.scale.set(bay.rx * 0.48, bay.rz * 0.18, 1);
      gloss.renderOrder = 3;
      group.add(gloss);
  
      if (denseScenery) {
        const waveMaterial = new THREE.MeshBasicMaterial({ color: 0xc8f6ff, transparent: true, opacity: 0.14, depthWrite: false });
        for (let i = 0; i < 56; i++) {
          let lx = 0;
          let lz = 0;
          for (let attempt = 0; attempt < 16; attempt++) {
            lx = (rng() - 0.5) * bay.rx * 1.55;
            lz = (rng() - 0.5) * bay.rz * 1.55;
            if ((lx / bay.rx) ** 2 + (lz / bay.rz) ** 2 < 0.82) break;
          }
          const band = new THREE.Mesh(new THREE.PlaneGeometry(90 + rng() * 190, 3 + rng() * 5), waveMaterial.clone());
          band.rotation.x = -Math.PI / 2;
          band.rotation.z = (rng() - 0.5) * 0.22;
          band.position.set(lx, 0.16, lz);
          group.add(band);
          waterBands.push({ mesh: band, baseX: lx, phase: rng() * Math.PI * 2, speed: 0.32 + rng() * 0.55, travel: 12 + rng() * 24 });
        }
      }
    }
  }

  function createIslandShores(shoreMaterial) {
    for (const island of ISLANDS) {
      const group = new THREE.Group();
      group.position.set(island.x, WATER_LEVEL + 0.1, island.z);
      group.rotation.y = island.rotation || 0;
      scene.add(group);

      const shore = createOpenWaterBodyShore(island, shoreMaterial, 0.88, 1.12, 224);
      shore.receiveShadow = true;
      shore.renderOrder = 1;
      group.add(shore);
    }
  }

  function createSegmentedEdgeShore(strip, shoreMaterial) {
    const half = MAP_SIZE / 2;
    const horizontal = strip.shoreX === undefined;
    const samples = 220;
    const sign = Math.sign(horizontal ? strip.shoreZ : strip.shoreX) || 1;
    const segmentLength = MAP_SIZE / samples;
  
    for (let i = 0; i < samples; i++) {
      const t = (i + 0.5) / samples;
      const coord = THREE.MathUtils.lerp(-half, half, t);
      const fixed = sign * (half - EDGE_OCEAN_WIDTH + 8 + coastlineOffset(horizontal, sign, coord));
      const x = horizontal ? coord : fixed;
      const z = horizontal ? fixed : coord;
      if (isEdgeShoreOpening(x, z)) continue;

      const shore = new THREE.Mesh(
        new THREE.BoxGeometry(horizontal ? segmentLength * 1.12 : 42, 0.1, horizontal ? 42 : segmentLength * 1.12),
        shoreMaterial
      );
      shore.position.set(x, WATER_LEVEL + 0.08, z);
      shore.receiveShadow = true;
      shore.renderOrder = 1;
      scene.add(shore);
    }
  }

  function createOpenWaterBodyShore(body, material, innerScale, outerScale, segments) {
    const positions = [];
    const indices = [];
    let vertex = 0;
  
    for (let i = 0; i < segments; i++) {
      const a0 = (i / segments) * Math.PI * 2;
      const a1 = ((i + 1) / segments) * Math.PI * 2;
      const mid = (a0 + a1) * 0.5;
      const midWorld = waterBodyBoundaryPoint(body, mid, (innerScale + outerScale) * 0.5);
      if (isOpenWaterBodyShoreGap(midWorld.x, midWorld.z)) continue;
  
      const inner0 = waterBodyBoundaryLocal(body, a0, innerScale);
      const outer0 = waterBodyBoundaryLocal(body, a0, outerScale);
      const outer1 = waterBodyBoundaryLocal(body, a1, outerScale);
      const inner1 = waterBodyBoundaryLocal(body, a1, innerScale);
      const points = [
        [inner0.x, 0, inner0.z],
        [outer0.x, 0, outer0.z],
        [outer1.x, 0, outer1.z],
        [inner1.x, 0, inner1.z]
      ];
      for (const point of points) positions.push(...point);
      indices.push(vertex, vertex + 2, vertex + 1, vertex, vertex + 3, vertex + 2);
      vertex += 4;
    }
  
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geometry.setIndex(indices);
    geometry.computeVertexNormals();
    return new THREE.Mesh(geometry, material);
  }

  function isEdgeShoreOpening(x, z) {
    if (distanceToRiver(x, z) < 260) return true;
    const inBay = closestWaterBodyNormalized(BAYS, x, z) < 1.12;
    const onIsland = closestWaterBodyNormalized(ISLANDS, x, z) < 1.05;
    return inBay && !onIsland;
  }

  function isOpenWaterBodyShoreGap(x, z) {
    if (distanceToMapEdge(x, z) < EDGE_OCEAN_WIDTH + 105) return true;
    return distanceToRiver(x, z) < 230;
  }

  function createRiverSegments(points, rng, shoreMaterial, waterMaterial) {
    const riverWaterMaterial = waterMaterial.clone();
    riverWaterMaterial.color.setHex(0x2f93ba);
    riverWaterMaterial.transparent = false;
    riverWaterMaterial.opacity = 1;
    riverWaterMaterial.depthWrite = true;
    riverWaterMaterial.polygonOffset = true;
    riverWaterMaterial.polygonOffsetFactor = -5;

    riverWaterMaterial.polygonOffsetUnits = -5;
    const riverFoamMaterial = liftSurfaceMaterial(new THREE.MeshBasicMaterial({ color: 0xc8f6ff, transparent: true, opacity: 0.12, depthWrite: false }), -7, -7);
    const samples = sampleRiverCurve(points, 12);
    let run = [];
    for (const sample of samples) {
      if (!isRiverGeometryHiddenByWater(sample.x, sample.z)) {
        run.push(sample);
        continue;
      }
      createRiverRibbonRun(run, rng, shoreMaterial, riverWaterMaterial, riverFoamMaterial);
      run = [];
    }
    createRiverRibbonRun(run, rng, shoreMaterial, riverWaterMaterial, riverFoamMaterial);
  }

  function createRiverRibbonRun(run, rng, shoreMaterial, waterMaterial, foamMaterial) {
    if (run.length < 2) return;
    createRiverRibbonMesh(run, sample => sample.width + 92, RIVER_SHORE_Y, shoreMaterial, 1);
    createRiverRibbonMesh(run, sample => sample.width, RIVER_SURFACE_Y, waterMaterial.clone(), 2);

    for (let i = 2; i < run.length - 2; i += 5) {
      const sample = run[i];
      const next = run[Math.min(run.length - 1, i + 1)];
      const angle = Math.atan2(-(next.z - sample.z), next.x - sample.x);
      const band = new THREE.Mesh(new THREE.BoxGeometry(62 + rng() * 92, 0.12, 2.6), foamMaterial.clone());
      band.position.set(sample.x, RIVER_FOAM_Y, sample.z);
      band.rotation.y = angle + (rng() - 0.5) * 0.11;
      band.translateZ((rng() - 0.5) * sample.width * 0.44);
      band.renderOrder = 4;
      scene.add(band);
      waterBands.push({
        mesh: band,
        baseX: band.position.x,
        phase: rng() * Math.PI * 2,
        speed: 0.32 + rng() * 0.48,
        travel: 4 + rng() * 7,
        worldAxis: true
      });
    }
  }

  function createRiverRibbonMesh(samples, widthForSample, y, material, renderOrder) {
    const positions = [];
    const indices = [];

    for (let i = 0; i < samples.length; i++) {
      const prev = samples[Math.max(0, i - 1)];
      const current = samples[i];
      const next = samples[Math.min(samples.length - 1, i + 1)];
      const tangentX = next.x - prev.x;
      const tangentZ = next.z - prev.z;
      const length = Math.max(0.001, Math.hypot(tangentX, tangentZ));
      const normalX = -tangentZ / length;
      const normalZ = tangentX / length;
      const halfWidth = widthForSample(current, i, samples.length) * 0.5;
      positions.push(
        current.x - normalX * halfWidth,
        y,
        current.z - normalZ * halfWidth,
        current.x + normalX * halfWidth,
        y,
        current.z + normalZ * halfWidth
      );
    }

    for (let i = 0; i < samples.length - 1; i++) {
      const row = i * 2;
      indices.push(row, row + 2, row + 1, row + 1, row + 2, row + 3);
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geometry.setIndex(indices);
    geometry.computeVertexNormals();
    const mesh = new THREE.Mesh(geometry, material);
    mesh.receiveShadow = true;
    mesh.renderOrder = renderOrder;
    scene.add(mesh);
  }

  function sampleRiverCurve(points, samplesPerSegment) {
    const samples = [];
    const segmentCount = Math.max(1, points.length - 1);

    for (let i = 0; i < points.length - 1; i++) {
      const p0 = points[Math.max(0, i - 1)];
      const p1 = points[i];
      const p2 = points[i + 1];
      const p3 = points[Math.min(points.length - 1, i + 2)];
      const steps = samplesPerSegment;
      for (let step = 0; step < steps; step++) {
        if (i > 0 && step === 0) continue;
        const t = step / steps;
        const globalT = (i + t) / segmentCount;
        const point = catmullRom2(p0, p1, p2, p3, t);
        samples.push({
          x: point.x,
          z: point.z,
          t: globalT,
          width: riverWidthAt(globalT, point.x, point.z)
        });
      }
    }

    const end = points[points.length - 1];
    samples.push({ x: end.x, z: end.z, t: 1, width: riverWidthAt(1, end.x, end.z) });
    return samples;
  }

  function catmullRom2(p0, p1, p2, p3, t) {
    const t2 = t * t;
    const t3 = t2 * t;
    return {
      x: 0.5 * ((2 * p1.x) + (-p0.x + p2.x) * t + (2 * p0.x - 5 * p1.x + 4 * p2.x - p3.x) * t2 + (-p0.x + 3 * p1.x - 3 * p2.x + p3.x) * t3),
      z: 0.5 * ((2 * p1.z) + (-p0.z + p2.z) * t + (2 * p0.z - 5 * p1.z + 4 * p2.z - p3.z) * t2 + (-p0.z + 3 * p1.z - 3 * p2.z + p3.z) * t3)
    };
  }

  function riverWidthAt(t, x, z) {
    const mouth = Math.max(1 - smoothstep(0.04, 0.18, t), smoothstep(0.82, 0.98, t));
    const lakeBlend = smoothstep(1.18, 0.96, closestLakeNormalized(x, z));
    const texture = 0.5 + 0.5 * Math.sin(x * 0.0021 + z * 0.0017 + t * 7.4);
    return 116 + mouth * 96 + lakeBlend * 54 + texture * 18;
  }

  function createRiverSpan(a, b, rng, shoreMaterial, riverWaterMaterial, riverFoamMaterial) {
      const dx = b.x - a.x;
      const dz = b.z - a.z;
      const length = Math.hypot(dx, dz);
    if (length < 44) return;
      const angle = Math.atan2(-dz, dx);
  
      const shore = new THREE.Mesh(new THREE.BoxGeometry(length + 92, 0.08, 238), shoreMaterial);
      shore.position.set((a.x + b.x) / 2, RIVER_SHORE_Y, (a.z + b.z) / 2);
      shore.rotation.y = angle;
      shore.receiveShadow = true;
      shore.renderOrder = 1;
      scene.add(shore);
  
      const water = new THREE.Mesh(new THREE.BoxGeometry(length + 86, 0.16, 154), riverWaterMaterial.clone());
      water.position.set((a.x + b.x) / 2, RIVER_SURFACE_Y, (a.z + b.z) / 2);
      water.rotation.y = angle;
      water.renderOrder = 2;
      scene.add(water);
  
      for (let w = 0; w < 7; w++) {
        const band = new THREE.Mesh(
          new THREE.BoxGeometry(56 + rng() * 86, 0.12, 2.5),
          riverFoamMaterial.clone()
        );
        band.position.set((a.x + b.x) / 2, RIVER_FOAM_Y, (a.z + b.z) / 2);
        band.rotation.y = angle + (rng() - 0.5) * 0.08;
        band.translateX((rng() - 0.5) * length * 0.82);
        band.translateZ((rng() - 0.5) * 74);
        band.renderOrder = 4;
        scene.add(band);
        waterBands.push({ mesh: band, baseX: band.position.x, phase: rng() * Math.PI * 2, speed: 0.35 + rng() * 0.55, travel: 4 + rng() * 7, worldAxis: true });
      }
    }

  function riverVisibleSpans(a, b, samples = 34) {
    const spans = [];
    let start = null;
  
    for (let i = 0; i <= samples; i++) {
      const t = i / samples;
      const x = THREE.MathUtils.lerp(a.x, b.x, t);
      const z = THREE.MathUtils.lerp(a.z, b.z, t);
      const visible = !isRiverGeometryHiddenByWater(x, z);
  
      if (visible && start === null) start = t;
      if ((!visible || i === samples) && start !== null) {
        const end = visible && i === samples ? t : (i - 1) / samples;
        if (end - start > 0.028) {
          spans.push({
            a: {
              x: THREE.MathUtils.lerp(a.x, b.x, start),
              z: THREE.MathUtils.lerp(a.z, b.z, start)
            },
            b: {
              x: THREE.MathUtils.lerp(a.x, b.x, end),
              z: THREE.MathUtils.lerp(a.z, b.z, end)
            }
          });
        }
        start = null;
      }
    }
  
    return spans;
  }

  function createRiverBends(points, shoreMaterial, waterMaterial) {
    for (let i = 1; i < points.length - 1; i++) {
      const point = points[i];
      if (isRiverGeometryHiddenByWater(point.x, point.z)) continue;
      const mouthZone = isRiverMouthZone(point.x, point.z);
      if (mouthZone) continue;

      const prev = points[i - 1];
      const next = points[i + 1];
      createRiverBendPatch(prev, point, next, 130, 126, RIVER_SHORE_Y + 0.03, shoreMaterial, 1);
      createRiverBendPatch(prev, point, next, 84, 112, RIVER_SURFACE_Y + 0.08, waterMaterial.clone(), 2);
    }
  }

  function createRiverBendPatch(prev, point, next, halfWidth, length, y, material, renderOrder) {
    const inDir = normalized2(point.x - prev.x, point.z - prev.z);
    const outDir = normalized2(next.x - point.x, next.z - point.z);
    if (!inDir || !outDir) return;

    const inNormal = { x: -inDir.z, z: inDir.x };
    const outNormal = { x: -outDir.z, z: outDir.x };
    const candidates = [
      offsetPoint(point, -inDir.x * length + inNormal.x * halfWidth, -inDir.z * length + inNormal.z * halfWidth),
      offsetPoint(point, -inDir.x * length - inNormal.x * halfWidth, -inDir.z * length - inNormal.z * halfWidth),
      offsetPoint(point, inNormal.x * halfWidth, inNormal.z * halfWidth),
      offsetPoint(point, -inNormal.x * halfWidth, -inNormal.z * halfWidth),
      offsetPoint(point, outDir.x * length + outNormal.x * halfWidth, outDir.z * length + outNormal.z * halfWidth),
      offsetPoint(point, outDir.x * length - outNormal.x * halfWidth, outDir.z * length - outNormal.z * halfWidth),
      offsetPoint(point, outNormal.x * halfWidth, outNormal.z * halfWidth),
      offsetPoint(point, -outNormal.x * halfWidth, -outNormal.z * halfWidth)
    ];
    const hull = convexHull2(candidates);
    if (hull.length < 3) return;

    const center = hull.reduce((sum, item) => ({ x: sum.x + item.x, z: sum.z + item.z }), { x: 0, z: 0 });
    center.x /= hull.length;
    center.z /= hull.length;

    const positions = [center.x, y, center.z];
    for (const item of hull) positions.push(item.x, y, item.z);

    const indices = [];
    for (let i = 0; i < hull.length; i++) {
      indices.push(0, i + 1, ((i + 1) % hull.length) + 1);
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geometry.setIndex(indices);
    geometry.computeVertexNormals();
    const patch = new THREE.Mesh(geometry, material);
    patch.receiveShadow = true;
    patch.renderOrder = renderOrder;
    scene.add(patch);
  }

  function normalized2(x, z) {
    const length = Math.hypot(x, z);
    if (length < 0.001) return null;
    return { x: x / length, z: z / length };
  }

  function offsetPoint(point, x, z) {
    return { x: point.x + x, z: point.z + z };
  }

  function convexHull2(points) {
    const unique = [];
    for (const point of points) {
      if (!unique.some(item => Math.hypot(item.x - point.x, item.z - point.z) < 0.01)) unique.push(point);
    }
    unique.sort((a, b) => a.x === b.x ? a.z - b.z : a.x - b.x);
    if (unique.length <= 3) return unique;

    const lower = [];
    for (const point of unique) {
      while (lower.length >= 2 && cross2(lower[lower.length - 2], lower[lower.length - 1], point) <= 0) lower.pop();
      lower.push(point);
    }

    const upper = [];
    for (let i = unique.length - 1; i >= 0; i--) {
      const point = unique[i];
      while (upper.length >= 2 && cross2(upper[upper.length - 2], upper[upper.length - 1], point) <= 0) upper.pop();
      upper.push(point);
    }

    lower.pop();
    upper.pop();
    return lower.concat(upper);
  }

  function cross2(a, b, c) {
    return (b.x - a.x) * (c.z - a.z) - (b.z - a.z) * (c.x - a.x);
  }

  function isRiverMouthZone(x, z) {
    if (distanceToMapEdge(x, z) < EDGE_OCEAN_WIDTH + 460) return true;
    const inBay = closestWaterBodyNormalized(BAYS, x, z) < 1.38;
    const onIsland = closestWaterBodyNormalized(ISLANDS, x, z) < 1.08;
    return inBay && !onIsland;
  }

  function createRiverMouths(rng, shoreMaterial, waterMaterial) {
    const mouthWaterMaterial = waterMaterial.clone();
    mouthWaterMaterial.color.setHex(0x319fc3);
    mouthWaterMaterial.roughness = 0.14;
    mouthWaterMaterial.metalness = 0.16;
    const wetSandMaterial = liftSurfaceMaterial(new THREE.MeshStandardMaterial({
      color: 0xded79f,
      roughness: 0.9,
      metalness: 0.02,
      transparent: true,
      opacity: 0.44,
      depthWrite: false
    }), -3, -3);
    const foamMaterial = liftSurfaceMaterial(new THREE.MeshBasicMaterial({
      color: 0xd8fbff,
      transparent: true,
      opacity: 0.16,
      depthWrite: false
    }), -8, -8);
  
    for (const river of RIVER_SYSTEMS) {
      if (river.length < 2) continue;
      addMouth(river[0], river[1]);
      addMouth(river[river.length - 1], river[river.length - 2]);
    }
  
    function addMouth(endpoint, inside) {
      const edgeMouth = distanceToMapEdge(endpoint.x, endpoint.z) < EDGE_OCEAN_WIDTH + 280;
      const bayMouth = closestWaterBodyNormalized(BAYS, endpoint.x, endpoint.z) < 1.38 &&
        (closestWaterBodyNormalized(ISLANDS, endpoint.x, endpoint.z) > 1.08 ||
          isRiverMouthClearancePoint(endpoint.x, endpoint.z, 160));
      if (!edgeMouth && !bayMouth) return;
  
      const outward = new THREE.Vector2(endpoint.x - inside.x, endpoint.z - inside.z);
      if (outward.lengthSq() < 0.001) outward.set(1, 0);
      outward.normalize();
      const center = bayMouth
        ? { x: endpoint.x + outward.x * 130, z: endpoint.z + outward.y * 130 }
        : { x: endpoint.x + outward.x * 210, z: endpoint.z + outward.y * 210 };
      const heading = Math.atan2(-outward.y, outward.x);
      const width = bayMouth ? 720 : 640;
      const length = bayMouth ? 980 : 1060;
      if (edgeMouth) createEdgeMouthConnector(endpoint, inside, shoreMaterial, mouthWaterMaterial);
  
      const group = new THREE.Group();
      group.position.set(center.x, RIVER_SHORE_Y + 0.04, center.z);
      group.rotation.y = heading;
      scene.add(group);
  
      for (const side of [-1, 1]) {
        const sandbar = new THREE.Mesh(new THREE.CircleGeometry(1, 72), wetSandMaterial.clone());
        sandbar.rotation.x = -Math.PI / 2;
        sandbar.position.set(length * 0.02, 0.06, side * width * 0.38);
        sandbar.rotation.z = side * 0.18;
        sandbar.scale.set(length * 0.34, width * 0.13, 1);
        sandbar.receiveShadow = true;
        sandbar.renderOrder = 1;
        group.add(sandbar);
      }
  
      const channel = new THREE.Mesh(new THREE.CircleGeometry(1, 128), mouthWaterMaterial.clone());
      channel.rotation.x = -Math.PI / 2;
      channel.position.set(length * 0.04, RIVER_SURFACE_Y - RIVER_SHORE_Y + 0.12, 0);
      channel.scale.set(length * 0.72, width * 0.43, 1);
      channel.renderOrder = 2;
      group.add(channel);
  
      for (let i = 0; i < 9; i++) {
        const band = new THREE.Mesh(new THREE.BoxGeometry(62 + rng() * 90, 0.12, 2.6), foamMaterial.clone());
        band.position.set(
          -length * 0.25 + i * length * 0.065 + (rng() - 0.5) * 22,
          RIVER_FOAM_Y - RIVER_SHORE_Y + 0.12,
          (rng() - 0.5) * width * 0.44
        );
        band.rotation.y = (rng() - 0.5) * 0.2;
        band.renderOrder = 4;
        group.add(band);
        waterBands.push({
          mesh: band,
          baseX: band.position.x,
          phase: rng() * Math.PI * 2,
          speed: 0.34 + rng() * 0.4,
          travel: 6 + rng() * 10
        });
      }
    }

    function createEdgeMouthConnector(endpoint, inside, shoreMaterial, waterMaterial) {
      const anchor = riverPointAt(inside, endpoint, 0.18);
      const length = Math.hypot(endpoint.x - anchor.x, endpoint.z - anchor.z);
      if (length < 120) return;
      const angle = Math.atan2(-(endpoint.z - anchor.z), endpoint.x - anchor.x);
      const center = {
        x: (anchor.x + endpoint.x) / 2,
        z: (anchor.z + endpoint.z) / 2
      };

      const normalX = -(endpoint.z - anchor.z) / length;
      const normalZ = (endpoint.x - anchor.x) / length;

      for (const side of [-1, 1]) {
        const sediment = new THREE.Mesh(new THREE.CircleGeometry(1, 64), shoreMaterial.clone());
        sediment.rotation.x = -Math.PI / 2;
        sediment.rotation.z = -angle + side * 0.18;
        sediment.position.set(center.x + normalX * side * 126, RIVER_SHORE_Y + 0.08, center.z + normalZ * side * 126);
        sediment.scale.set(length * 0.42, 86, 1);
        sediment.receiveShadow = true;
        sediment.renderOrder = 1;
        scene.add(sediment);
      }

      const water = new THREE.Mesh(new THREE.CircleGeometry(1, 96), waterMaterial.clone());
      water.rotation.x = -Math.PI / 2;
      water.rotation.z = -angle;
      water.position.set(center.x, RIVER_SURFACE_Y + 0.14, center.z);
      water.scale.set(length * 0.68 + 120, 118, 1);
      water.renderOrder = 5;
      scene.add(water);
    }
  }

  function createLakeRiverConfluences(rng, waterMaterial) {
    const confluenceMaterial = waterMaterial.clone();
    confluenceMaterial.color.setHex(0x2f93ba);
    confluenceMaterial.roughness = 0.14;

    confluenceMaterial.metalness = 0.14;
    confluenceMaterial.depthWrite = true;
    confluenceMaterial.polygonOffset = true;
    confluenceMaterial.polygonOffsetFactor = -8;
    confluenceMaterial.polygonOffsetUnits = -8;

    const rippleMaterial = liftSurfaceMaterial(new THREE.MeshBasicMaterial({
      color: 0xcaf7ff,
      transparent: true,
      opacity: 0.15,
      depthWrite: false
    }), -9, -9);

    const placed = [];
    for (const lake of LAKES) {
      for (const river of RIVER_SYSTEMS) {
        for (let i = 0; i < river.length - 1; i++) {
          const a = river[i];
          const b = river[i + 1];
          for (const crossing of lakeRiverCrossings(lake, a, b)) {
            if (placed.some(point => Math.hypot(point.x - crossing.x, point.z - crossing.z) < 145)) continue;
            placed.push(crossing);
            createLakeRiverConfluence(lake, crossing, a, b, rng, confluenceMaterial, rippleMaterial);
          }
        }
      }
    }
  }

  function createLakeRiverConfluence(lake, crossing, a, b, rng, confluenceMaterial, rippleMaterial) {
    const dx = b.x - a.x;
    const dz = b.z - a.z;
    const angle = Math.atan2(-dz, dx);
    const y = Math.max(lake.level + 0.18, RIVER_SURFACE_Y + 0.18);
    const major = Math.max(230, Math.min(360, lake.rx * 0.72));
    const minor = Math.max(134, Math.min(220, lake.rz * 0.72));

    const blend = new THREE.Mesh(new THREE.CircleGeometry(1, 128), confluenceMaterial.clone());
    blend.rotation.x = -Math.PI / 2;
    blend.rotation.z = -angle;
    blend.position.set(crossing.x, y, crossing.z);
    blend.scale.set(major, minor, 1);
    blend.renderOrder = 5;
    scene.add(blend);

    for (let i = 0; i < 4; i++) {
      const ripple = new THREE.Mesh(new THREE.BoxGeometry(70 + rng() * 90, 0.08, 2.4), rippleMaterial.clone());
      ripple.position.set(crossing.x, y + 0.08, crossing.z);
      ripple.rotation.y = angle + (rng() - 0.5) * 0.16;
      ripple.translateX((rng() - 0.5) * major * 0.38);
      ripple.translateZ((rng() - 0.5) * minor * 0.38);
      ripple.renderOrder = 6;
      scene.add(ripple);
      waterBands.push({
        mesh: ripple,
        baseX: ripple.position.x,
        phase: rng() * Math.PI * 2,
        speed: 0.28 + rng() * 0.38,
        travel: 3 + rng() * 6,
        worldAxis: true
      });
    }
  }

  function lakeRiverCrossings(lake, a, b, threshold = 1.02) {
    const crossings = [];
    const samples = 76;
    let prevT = 0;
    let prevN = waterBodyNormalized(lake, a.x, a.z) - threshold;

    for (let i = 1; i <= samples; i++) {
      const t = i / samples;
      const point = riverPointAt(a, b, t);
      const n = waterBodyNormalized(lake, point.x, point.z) - threshold;

      if ((prevN <= 0 && n > 0) || (prevN > 0 && n <= 0)) {
        const hitT = refineLakeCrossing(lake, a, b, prevT, t, threshold, prevN <= 0);
        const hit = riverPointAt(a, b, hitT);
        if (!crossings.some(point => Math.hypot(point.x - hit.x, point.z - hit.z) < 90)) crossings.push(hit);
      }

      prevT = t;
      prevN = n;
    }

    return crossings;
  }

  function refineLakeCrossing(lake, a, b, lo, hi, threshold, loInside) {
    for (let i = 0; i < 12; i++) {
      const mid = (lo + hi) * 0.5;
      const point = riverPointAt(a, b, mid);
      const inside = waterBodyNormalized(lake, point.x, point.z) <= threshold;
      if (inside === loInside) {
        lo = mid;
      } else {
        hi = mid;
      }
    }
    return (lo + hi) * 0.5;
  }

  function riverPointAt(a, b, t) {
    return {
      x: THREE.MathUtils.lerp(a.x, b.x, t),
      z: THREE.MathUtils.lerp(a.z, b.z, t)
    };
  }

  function edgeRiverMouthPoint(endpoint, inside) {
    const half = MAP_SIZE / 2;
    const coast = half - EDGE_OCEAN_WIDTH - 18;
    const dx = endpoint.x - inside.x;
    const dz = endpoint.z - inside.z;
    let t = 0.72;
  
    if (Math.abs(endpoint.x) > Math.abs(endpoint.z) && Math.abs(dx) > 0.001) {
      const sign = Math.sign(endpoint.x || dx);
      const targetX = sign * (coast + coastlineOffset(false, sign, endpoint.z));
      t = THREE.MathUtils.clamp((targetX - inside.x) / dx, 0, 1);
    } else if (Math.abs(dz) > 0.001) {
      const sign = Math.sign(endpoint.z || dz);
      const targetZ = sign * (coast + coastlineOffset(true, sign, endpoint.x));
      t = THREE.MathUtils.clamp((targetZ - inside.z) / dz, 0, 1);
    }
  
    return {
      x: THREE.MathUtils.lerp(inside.x, endpoint.x, t),
      z: THREE.MathUtils.lerp(inside.z, endpoint.z, t)
    };
  }

  function updateWater(dt) {
    for (const band of waterBands) {
      band.phase += dt * band.speed;
      const drift = Math.sin(band.phase) * band.travel;
      if (band.worldAxis) {
        band.mesh.position.x = band.baseX + drift;
      } else {
        band.mesh.position.x = band.baseX + drift;
      }
      band.mesh.material.opacity = 0.12 + Math.max(0, Math.sin(band.phase + 1.4)) * 0.14;
    }
  }

  return {
    createWaterSystems,
    updateWater
  };
}

function createGlossFalloffTexture() {
  if (glossFalloffTexture) return glossFalloffTexture;
  const canvas = document.createElement('canvas');
  canvas.width = 128;
  canvas.height = 128;
  const ctx = canvas.getContext('2d');
  const gradient = ctx.createRadialGradient(64, 64, 0, 64, 64, 64);
  gradient.addColorStop(0, 'rgba(255,255,255,1)');
  gradient.addColorStop(0.42, 'rgba(255,255,255,0.46)');
  gradient.addColorStop(0.78, 'rgba(255,255,255,0.12)');
  gradient.addColorStop(1, 'rgba(255,255,255,0)');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 128, 128);
  glossFalloffTexture = new THREE.CanvasTexture(canvas);
  glossFalloffTexture.needsUpdate = true;
  return glossFalloffTexture;
}
