import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const SOURCE_EXTENSIONS = ['.js', '.css'];

const generated = [];

for (const directory of sourceDirectories(join(ROOT, 'src'))) {
  const chunkDirectories = readdirSync(directory, { withFileTypes: true })
    .filter(entry => entry.isDirectory() && /^part-\d+$/.test(entry.name))
    .map(entry => entry.name)
    .sort();

  if (!chunkDirectories.length) continue;

  for (const extension of SOURCE_EXTENSIONS) {
    const sourceName = `source${extension}`;
    if (!existsSync(join(directory, chunkDirectories[0], sourceName))) continue;

    const output = join(dirname(directory), `${basename(directory)}${extension}`);
    const body = chunkDirectories
      .map(chunkDirectory => readFileSync(join(directory, chunkDirectory, sourceName), 'utf8').trimEnd())
      .join('\n\n');
    writeFileSync(output, `${generatedBanner(extension, directory)}${body}\n`);
    generated.push(relative(ROOT, output));
  }
}

function generatedBanner(extension, directory) {
  const sourcePath = relative(ROOT, directory);
  if (extension === '.css') {
    return `/* Generated by tools/buildVirtualSources.js from ${sourcePath} part source.css files. Do not edit directly. */\n`;
  }
  return `// Generated by tools/buildVirtualSources.js from ${sourcePath}/part-*/source.js. Do not edit directly.\n`;
}

for (const file of generated.sort()) {
  console.log(file);
}

function sourceDirectories(root) {
  const pending = [root];
  const directories = [];

  while (pending.length) {
    const directory = pending.pop();
    if (!directory || !existsSync(directory) || !statSync(directory).isDirectory()) continue;
    directories.push(directory);

    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      pending.push(join(directory, entry.name));
    }
  }

  return directories;
}
