import { readdirSync, readFileSync } from 'node:fs';
import { extname, join } from 'node:path';

const CODE_EXTENSIONS = new Set(['.js', '.css', '.html', '.json']);
const LIMIT = Number(process.argv[2] || 500);
const root = process.cwd();
const counts = [];

function countDirectLines(directory) {
  let total = 0;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      countDirectLines(fullPath);
      continue;
    }
    if (!CODE_EXTENSIONS.has(extname(entry.name))) continue;
    const source = readFileSync(fullPath, 'utf8');
    if (source.startsWith('// Generated by tools/buildVirtualSources.js') || source.startsWith('/* Generated by tools/buildVirtualSources.js')) continue;
    total += source.split(/\r?\n/).length;
  }
  counts.push({
    directory,
    relative: directory === root ? '.' : directory.slice(root.length + 1),
    total
  });
}

countDirectLines(root);

const offenders = counts
  .filter(entry => entry.total > LIMIT)
  .sort((a, b) => b.total - a.total);

for (const entry of counts.filter(entry => entry.total > 0).sort((a, b) => b.total - a.total)) {
  console.log(`${String(entry.total).padStart(5)} ${entry.relative}`);
}

if (offenders.length) {
  console.error(`\nFolder line limit failed: ${offenders.length} folder(s) exceed ${LIMIT} direct code lines.`);
  process.exit(1);
}

console.log(`\nFolder line limit passed: every folder is <= ${LIMIT} direct code lines.`);
