// Generated by tools/buildVirtualSources.js from src/main/part-*/source.js. Do not edit directly.
import * as THREE from '../three.module.min.js?v=202605050057';
import { createAircraft } from './aircraft/A320.js?v=202605061100';
import { createAirportSystem } from './world/airports.js?v=202605070100';
import { createFlightPhysics } from './simulation/flightPhysics.js?v=202605061100';
import { createThrottleSystem } from './simulation/throttleSystem.js?v=202605061100';
import { createHud } from './ui/hud.js?v=202605070200';
import { applyBrowserClasses, detectBrowser } from './platform/browserDetect.js?v=202605060602';
import { createViewportManager } from './platform/viewport.js?v=202605060602';
import { resizeRendererToViewport } from './render/resizeRenderer.js?v=202605060602';
import { createCloudSystem } from './world/clouds.js?v=202605056000';
import { createBirdSystem } from './world/birds.js?v=202605056000';
import { applyLightQuality, createDayNightCycle, createSky, initLights } from './world/lighting.js?v=202605070100';
import { createRoadSystem } from './world/roads.js?v=202605056000';
import { createGroundWorld } from './world/groundObjects.js?v=202605070100';
import { createTerrain, terrainHeight } from './world/terrain.js?v=202605070100';
import { createWaterSystem } from './world/water.js?v=202605060300';
import { createBoatSystem } from './world/boats.js?v=202605060300';
import { createAircraftLightController } from './world/aircraftLights.js?v=202605060300';
import { createMultiplayerSystem } from './network/multiplayer.js?v=202605070200';
import { createUfoEventController } from './world/ufoEvents.js?v=202605070200';
import { createEngineAudioSystem } from './audio/engineAudio.js?v=202605061100';
import {
  DEFAULT_RENDER_QUALITY,
  RENDER_QUALITY_PRESETS,
  applyUltraSceneQuality,
  configureUltraCamera,
  configureUltraRenderer,
  configureUltraScene,
  createRuntimeRenderQuality,
  createDistantWorldVisuals,
  enforceRealLightBudget,
  selectDefaultRenderQuality,
  resolveRenderQualityPreset
} from './world/visualQuality.js?v=202605070100';
import { createRenderDiagnostics } from './ui/renderDiagnostics.js?v=202605060700';
import { getNetworkDiagnosticsSnapshot, markWorldLoaded } from './utils/networkDiagnostics.js?v=202605060600';
import {
  airportLocal,
  airportWorld,
  smoothstep,
  summarizeGroundPlacement
} from './world/spatial.js?v=202605056000';

import {
  AIRCRAFT_GROUND_OFFSET,
  AIRPORTS
} from './data/worldData.js?v=202605070100';

const ui = {
  loading: document.getElementById('loading'),
  speed: document.getElementById('speed'),
  altitude: document.getElementById('altitude'),
  throttle: document.getElementById('throttle'),
  heading: document.getElementById('heading'),
  mode: document.getElementById('mode'),
  throttleBar: document.getElementById('throttleBar'),
  reverseBar: document.getElementById('reverseBar'),
  verticalSpeed: document.getElementById('verticalSpeed'),
  nearestField: document.getElementById('nearestField'),
  fieldDistance: document.getElementById('fieldDistance'),
  pitch: document.getElementById('pitch'),
  flapStatus: document.getElementById('flapStatus'),
  speedBrakeStatus: document.getElementById('speedBrakeStatus'),
  vfeStatus: document.getElementById('vfeStatus'),
  vlsStatus: document.getElementById('vlsStatus'),
  compassStrip: document.getElementById('compassStrip'),
  mapPanel: document.getElementById('mapPanel'),
  mapOverlay: document.getElementById('mapOverlay'),
  mapMode: document.getElementById('mapMode'),
  mapOverlayMode: document.getElementById('mapOverlayMode'),
  navMap: document.getElementById('navMap'),
  navMapOverlay: document.getElementById('navMapOverlay'),
  controlsPanel: document.getElementById('controlsPanel'),
  controlsMode: document.getElementById('controlsMode'),
  fmaThrust: document.getElementById('fmaThrust'),
  fmaVertical: document.getElementById('fmaVertical'),
  fmaLateral: document.getElementById('fmaLateral'),
  athrStatus: document.getElementById('athrStatus'),
  targetSpeed: document.getElementById('targetSpeed'),
  speedMode: document.getElementById('speedMode'),
  speedTrend: document.getElementById('speedTrend'),
  leverDetent: document.getElementById('leverDetent'),
  leverDetentDetail: document.getElementById('leverDetentDetail'),
  simClock: document.getElementById('simClock'),
  simClockSource: document.getElementById('simClockSource'),
  thrustModeSmall: document.getElementById('thrustModeSmall'),
  thrustIas: document.getElementById('thrustIas'),
  thrustLimit: document.getElementById('thrustLimit'),
  targetN1Readout: document.getElementById('targetN1Readout'),
  avgN1: document.getElementById('avgN1'),
  detentToast: document.getElementById('detentToast'),
  leftDetent: document.getElementById('leftDetent'),
  rightDetent: document.getElementById('rightDetent'),
  leftN1: document.getElementById('leftN1'),
  rightN1: document.getElementById('rightN1'),
  thrustLeverLeft: document.getElementById('thrustLeverLeft'),
  thrustLeverRight: document.getElementById('thrustLeverRight'),
  thrustTrackLeft: document.getElementById('thrustTrackLeft'),
  thrustTrackRight: document.getElementById('thrustTrackRight'),
  thrustPanel: document.getElementById('thrustPanel'),
  detentLabels: document.querySelectorAll('[data-detent-label]')
};

const appShell = document.getElementById('app') || document.body;
window.MHFS_BOOT?.setStep?.('Loading renderer...');
const browserInfo = applyBrowserClasses(document.body, detectBrowser());
let rendererReady = false;
const viewportManager = createViewportManager({
  app: appShell,
  onChange: () => {
    if (rendererReady) resize();
  }
});
viewportManager.refresh();
const initialViewport = viewportManager.size();
const webglSupport = detectWebGLSupport();
if (!webglSupport.ok) {
  showRendererFallback(webglSupport.reason);
  await new Promise(() => {});
}

const KT_PER_MPS = 1.94384;
const BASE_SPEED_FOV = 60;
const TAKEOFF_SPEED_FOV_MAX = 66;
const SPEED_CALLOUTS = [
  { speed: 80, label: '80 KT' },
  { speed: 135, label: 'V1' },
  { speed: 140, label: 'ROTATE' },
  { speed: 145, label: 'V2' }
];
const urlParams = new URLSearchParams(window.location.search);
const enableConsoleDiagnostics = urlParams.has('debug') || urlParams.get('diagnostics') === '1';
let baseRenderQuality = resolveRenderQualityPreset(
  urlParams.get('quality') || window.localStorage?.getItem('flight-render-quality'),
  selectDefaultRenderQuality(browserInfo) || DEFAULT_RENDER_QUALITY
);
let renderQuality = createRuntimeRenderQuality(baseRenderQuality);

const renderer = new THREE.WebGLRenderer({
  antialias: renderQuality.antialias !== false,
  powerPreference: renderQuality.key === 'SMOOTH_LOW_POWER' ? 'default' : 'high-performance',
  logarithmicDepthBuffer: true,
  precision: 'highp'
});
configureUltraRenderer(renderer, renderQuality);
renderer.domElement.className = 'webgl';
resizeRendererToViewport({
  renderer,
  camera: { aspect: initialViewport.width / initialViewport.height, updateProjectionMatrix() {} },
  quality: renderQuality,
  browser: browserInfo,
  viewport: viewportManager,
  configureCamera: () => {}
});
appShell.prepend(renderer.domElement);

const scene = new THREE.Scene();
configureUltraScene(scene, renderQuality);
window.MHFS_DEBUG_SCENE = scene;

const camera = new THREE.PerspectiveCamera(renderQuality.fov, initialViewport.width / initialViewport.height, renderQuality.cameraNear, renderQuality.cameraFar);
resizeRendererToViewport({
  renderer,
  camera,
  quality: renderQuality,
  browser: browserInfo,
  viewport: viewportManager,
  configureCamera: configureUltraCamera
});
camera.position.set(0, 42, 92);

const keys = new Set();
const tmpVec = new THREE.Vector3();
const forwardVec = new THREE.Vector3();
const cameraRightVec = new THREE.Vector3();
const upVec = new THREE.Vector3(0, 1, 0);
const waterBands = [];
const trafficCars = [];
const clouds = [];
const cameraDesiredVec = new THREE.Vector3();
const cameraLookAtVec = new THREE.Vector3();
let lastAudioWarning = '';
let mapDrag = null;
let previousSpeedForFeeling = 0;
let previousGroundedForFeeling = true;
let previousCalloutSpeedKts = 0;
let lastLightingCheckLog = 0;
let dynamicQualityLevel = 0;
let lastFrameNowMs = 0;
let fixedStepAccumulator = 0;
let renderFrameAccumulator = 0;
let hudUpdateDebt = 0;
let navWorldUpdateDebt = 0;
let boatUpdateDebt = 0;
let birdUpdateDebt = 0;
let trafficUpdateDebt = 0;
let cloudUpdateDebt = 0;
let lightBudgetDebt = 0;
let airportPriorityDebt = 0;
let lastCycleState = null;
const FIXED_FLIGHT_STEP = 1 / 60;
const MAX_FRAME_DELTA = 0.05;
const MAX_FIXED_STEPS = 4;
const state = {
  position: new THREE.Vector3(
    AIRPORTS[0].x,
    terrainHeight(AIRPORTS[0].x, AIRPORTS[0].z + 330) + AIRCRAFT_GROUND_OFFSET,
    AIRPORTS[0].z + 330
  ),
  yaw: 0,
  pitch: 0,
  roll: 0,
  speed: 36,
  physicsVelocity: new THREE.Vector3(0, 0, -36),
  physicsSpeedMS: 36,
  indicatedSpeedMS: 36,
  worldVelocity: new THREE.Vector3(),
  worldTravelScale: 1.25,
  groundTravelScale: 1.25,
  airTravelScale: 1.5,
  maxTravelScale: 1.8,
  visualPosition: new THREE.Vector3(),
  previousPhysicsPosition: new THREE.Vector3(),
  currentPhysicsPosition: new THREE.Vector3(),
  previousPhysicsPitch: 0,
  previousPhysicsYaw: 0,
  previousPhysicsRoll: 0,
  currentPhysicsPitch: 0,
  currentPhysicsYaw: 0,
  currentPhysicsRoll: 0,
  visualPitch: 0,
  visualYaw: 0,
  visualRoll: 0,
  throttle: 0.34,
  reverse: 0,
  parkingBrake: false,
  verticalSpeed: 0,
  grounded: true,
  lawMode: 'NORMAL_LAW',
  flightWarning: '',
  angleOfAttack: 0,
  stallFactor: 0,
  controlAuthority: 1,
  currentIAS: 0,
  altitudeAGL: 0,
  wheelSpeedKts: 0,
  leftBrakeInput: 0,
  rightBrakeInput: 0,
  leftBrakePressure: 0,
  rightBrakePressure: 0,
  totalBrakePressure: 0,
  brakeInput: 0,
  brakeForceN: 0,
  wheelBrakeForceN: 0,
  brakeStatusText: '',
  differentialBrakeYawEnabled: false,
  antiSkidActive: false,
  mainGearCompressed: true,
  speedTrendKts: 0,
  lowAltitudeSpeedEffect: 0,
  cameraSpeedFov: BASE_SPEED_FOV,
  cameraShakeAmount: 0,
  cameraAccelPush: 0,
  selectedFlapIndex: 0,
  selectedFlapConfig: 'CONF_0',
  actualSlatPosition: 0,
  actualFlapPosition: 0,
  speedBrakeCommand: 0,
  actualSpeedBrakePosition: 0,
  groundSpoilersArmed: true,
  actualGroundSpoilerPosition: 0
};
window.MHFS_DEBUG_STATE = state;

const timeOfDayMode = urlParams.get('time') || urlParams.get('tod') || 'day';
const startMode = urlParams.get('start');
if (startMode === 'parked') {
  state.speed = 0;
  state.throttle = 0;
  state.reverse = 0;
  state.parkingBrake = true;
} else if (startMode === 'air' || startMode === 'cruise') {
  const x = AIRPORTS[0].x;
  const z = AIRPORTS[0].z - 720;
  const requestedAltitudeFt = Number(urlParams.get('alt') || urlParams.get('altitude'));
  const cruiseAltitudeFt = startMode === 'cruise' ? 25000 : 680;
  const altitudeMeters = THREE.MathUtils.clamp(
    Number.isFinite(requestedAltitudeFt) && requestedAltitudeFt > 0 ? requestedAltitudeFt / 3.28084 : cruiseAltitudeFt / 3.28084,
    120,
    14500
  );
  state.position.set(x, terrainHeight(x, z) + AIRCRAFT_GROUND_OFFSET + altitudeMeters, z);
  state.speed = (startMode === 'cruise' || altitudeMeters > 650 ? 290 : 175) / KT_PER_MPS;
  state.throttle = startMode === 'cruise' || altitudeMeters > 650 ? 0.62 : 0.56;
  state.pitch = startMode === 'cruise' ? 0 : altitudeMeters > 650 ? -0.025 : -0.05;
  state.grounded = false;
  state.parkingBrake = false;
}

state.physicsSpeedMS = Math.abs(state.speed);
state.indicatedSpeedMS = state.physicsSpeedMS;
state.currentIAS = state.physicsSpeedMS * KT_PER_MPS;
state.physicsVelocity.set(0, 0, -state.speed);
state.worldVelocity.copy(state.physicsVelocity);
state.visualPosition.copy(state.position);
state.previousPhysicsPosition.copy(state.position);
state.currentPhysicsPosition.copy(state.position);
state.previousPhysicsPitch = state.currentPhysicsPitch = state.visualPitch = state.pitch;
state.previousPhysicsYaw = state.currentPhysicsYaw = state.visualYaw = state.yaw;
state.previousPhysicsRoll = state.currentPhysicsRoll = state.visualRoll = state.roll;

previousSpeedForFeeling = state.physicsSpeedMS;
previousGroundedForFeeling = state.grounded;
previousCalloutSpeedKts = state.physicsSpeedMS * KT_PER_MPS;

const engineAudio = createEngineAudioSystem({ state });
window.MHFS_BOOT?.setStep?.('Prewarming audio...');
engineAudio.prewarm?.();
const rootStyle = document.documentElement.style;
window.MHFS_BOOT?.setStep?.('Loading UI...');
const hud = createHud({ ui, state, rootStyle, terrainHeight, airportWorld });
rendererReady = true;
viewportManager.start();
window.MHFS_BOOT?.setStep?.('Loading world...');
const cloudSystem = createCloudSystem({ scene, clouds, mulberry32 });
const birdSystem = createBirdSystem({ scene, terrainHeight, mulberry32, getRenderQuality: () => renderQuality });
const waterSystem = createWaterSystem({ scene, waterBands, mulberry32 });
const airportSystem = createAirportSystem({ scene, terrainHeight, getRenderQuality: () => renderQuality });
const roadSystem = createRoadSystem({ scene, terrainHeight, waterBands });
const groundWorld = createGroundWorld({ scene, trafficCars, terrainHeight, mulberry32, getRenderQuality: () => renderQuality });

const lights = initLights(scene, renderQuality);
const skySystem = createSky(scene);
createTerrain({ scene, waterSystem, quality: renderQuality });
createDistantWorldVisuals({ scene, terrainHeight, mulberry32, quality: renderQuality });
markWorldLoaded(true);
const boatSystem = createBoatSystem({ scene, mulberry32 });
boatSystem.createBoats(renderQuality.denseScenery
  ? {}
  : { simple: true, maxBoats: renderQuality.key === 'SMOOTH_LOW_POWER' ? 36 : 56 });
const dayNightCycle = createDayNightCycle({ scene, renderer, camera, lights, sky: skySystem, initialMode: timeOfDayMode, getRenderQuality: () => renderQuality });
lastCycleState = dayNightCycle.update(0);
airportSystem.createAirport(AIRPORTS[0]);
lastCycleState = dayNightCycle.update(0);
window.MHFS_BOOT?.setStep?.('Loading aircraft...');
const aircraft = createAircraft();
aircraft.group.userData.diagnosticType = 'aircraft';
aircraft.group.userData.diagnosticCount = 1;
const localAircraftLights = createAircraftLightController(aircraft.group, { phase: 0.13 });
const multiplayerSystem = createMultiplayerSystem({ scene, state, terrainHeight });
const ufoEventController = createUfoEventController({
  scene,
  state,
  camera,
  terrainHeight,
  getHiddenIslandUfoManager: () => airportSystem.getHiddenIslandUfoManager?.(),
  getServerTime: () => multiplayerSystem.getServerTime()
});
const throttleSystem = createThrottleSystem({ state, terrainHeight, keys });
const flightPhysics = createFlightPhysics({ keys, state, forwardVec, terrainHeight, smoothstep });
scene.add(aircraft.group);
cleanupMapGuideLines();
let detailCuller = { update() {} };
const performanceMonitor = createFramePerformanceMonitor(() => renderQuality);
const renderDiagnostics = createRenderDiagnostics({
  scene,
  renderer,
  camera,
  state,
  qualityPresets: RENDER_QUALITY_PRESETS,
  getQualityPreset: () => renderQuality,
  getNetworkDiagnostics: getNetworkDiagnosticsSnapshot,
  getPerformanceSnapshot: () => performanceMonitor.snapshot(),
  setQualityPreset,
  container: appShell,
  startVisible: enableConsoleDiagnostics
});
window.MHFS_PERFORMANCE_SNAPSHOT = () => performanceMonitor.snapshot();
window.MHFS_RUN_WORLD_INTEGRITY_REPORTS = () => runWorldIntegrityReports('manual');
updateSpeedFeeling(1 / 60);
updateCamera(1);
multiplayerSystem.connect();

window.addEventListener('keydown', handleKeyDown);
window.addEventListener('keyup', handleKeyUp);
window.addEventListener('pagehide', () => multiplayerSystem.dispose());
document.addEventListener('visibilitychange', handleVisibilityChange);
window.addEventListener('resize', () => viewportManager.refresh());
window.addEventListener('orientationchange', () => setTimeout(() => viewportManager.refresh(), 120));
ui.mapPanel.addEventListener('click', toggleNavMap);
ui.mapPanel.addEventListener('keydown', handleNavMapKey);
ui.mapOverlay.addEventListener('click', toggleNavMap);
ui.mapOverlay.addEventListener('keydown', handleNavMapKey);
ui.mapOverlay.addEventListener('wheel', handleNavMapWheel, { passive: false });
ui.navMapOverlay.addEventListener('pointerdown', beginNavMapDrag);
ui.navMapOverlay.addEventListener('dblclick', resetNavMapView);
ui.controlsPanel.addEventListener('click', toggleControlsPanel);
ui.controlsPanel.addEventListener('keydown', handleControlsPanelKey);
ui.thrustTrackLeft.addEventListener('pointerdown', event => beginThrottleDrag(event, 'left'));
ui.thrustTrackRight.addEventListener('pointerdown', event => beginThrottleDrag(event, 'right'));
renderer.domElement.tabIndex = 0;
renderer.domElement.focus();

startWorldBuildQueue().then(() => {
  updateAirportPriorityLoading(0, true);
  applyUltraSceneQuality(scene, renderer, renderQuality);
  enforceRealLightBudget(scene, renderQuality, camera);
  runWorldIntegrityReports('startup');
  window.MHFS_BOOT?.setStep?.('Starting game loop...');
  requestAnimationFrame(() => ui.loading.classList.add('hidden'));
  animate();
});

function startWorldBuildQueue() {
  const denseScenery = renderQuality.denseScenery === true;
  const secondaryAirports = renderQuality.secondaryAirportDetail === false ? [] : AIRPORTS.slice(1);
  const criticalTasks = [
    ...secondaryAirports.map(airport => () => {
      airportSystem.createAirport(airport);
      dayNightCycle.update(0);
    }),
    () => groundWorld.createCity(),
    () => groundWorld.createForests(),
    () => cloudSystem.createClouds(),
    () => birdSystem.createBirds(),
    ...(denseScenery ? [
      () => roadSystem.createBridgesAndRoads(),
      () => groundWorld.createVillageRoads(),
      () => groundWorld.createIslandSettlements(),
      () => groundWorld.createMountainHamlets()
    ] : [])
  ];
  const backgroundTasks = denseScenery ? [
    () => groundWorld.createWoodlandCabins(),
    () => groundWorld.createVillages(),
    () => groundWorld.createAirfieldLowHomes(),
    () => groundWorld.createRunwayEndScatterHomes(),
    () => groundWorld.createFarmlandRegions(),
    () => groundWorld.createGroundDetails(),
    () => groundWorld.createLowGrassMeadows()
  ] : [];
  const tasks = [...criticalTasks, ...backgroundTasks];
  let taskIndex = 0;
  let criticalResolved = false;
  const visibleAfterTasks = tasks.length;

  return new Promise(resolve => {
    function processQueue(deadline = null) {
      const startedAt = performance.now();
      let built = 0;
      const criticalPhase = taskIndex < criticalTasks.length;
      const idleBudget = deadline?.timeRemaining?.() || 0;
      const budget = Math.max(criticalPhase ? 6 : 3, Math.min(criticalPhase ? 12 : 6, idleBudget || (criticalPhase ? 8 : 4)));
      while (taskIndex < tasks.length && (built < 1 || performance.now() - startedAt < budget)) {
        tasks[taskIndex++]();
        built++;
        if (!criticalResolved && taskIndex >= visibleAfterTasks) {
          criticalResolved = true;
          applyUltraSceneQuality(scene, renderer, renderQuality);
          enforceRealLightBudget(scene, renderQuality, camera);
          resolve();
          break;
        }
      }

      if (taskIndex < tasks.length) {
        scheduleWorldBuildTask(processQueue);
        return;
      }

      applyUltraSceneQuality(scene, renderer, renderQuality);
      enforceRealLightBudget(scene, renderQuality, camera);
      detailCuller = createDetailCuller(aircraft.group);
      if (!criticalResolved) resolve();
    }

    scheduleWorldBuildTask(processQueue);
  });
}

function scheduleWorldBuildTask(callback) {
  if (renderQuality.mapStreaming && 'requestIdleCallback' in window) {
    window.requestIdleCallback(callback, { timeout: 160 });
    return;
  }
  requestAnimationFrame(callback);
}

function scheduleIdleStartupTask(callback) {
  if ('requestIdleCallback' in window) {
    window.requestIdleCallback(callback, { timeout: 1800 });
    return;
  }
  setTimeout(callback, 0);
}

function handleKeyDown(event) {
  const code = flightControlCode(event);
  const throttleHandled = handleThrottleKey(code, event);
  const controlled = ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'KeyQ', 'KeyE', 'KeyT', 'KeyX', 'KeyY', 'KeyG', 'KeyZ', 'KeyC', 'BracketLeft', 'BracketRight', 'ShiftLeft', 'ShiftRight', 'Space'];
  if (throttleHandled) {
    event.preventDefault();
    ensureAudio();
    return;
  }
  if (controlled.includes(code)) {
    event.preventDefault();
    ensureAudio();
    if (code === 'Space' && !event.repeat) {
      toggleParkingBrake();
    } else if (code === 'KeyT' && !event.repeat) {
      toggleLawMode();
    }
    if (code !== 'KeyT') keys.add(code);
  }
}

function toggleParkingBrake() {
  if (!state.grounded) {
    hud.updateHud();
    return;
  }
  state.parkingBrake = !state.parkingBrake;
  if (state.parkingBrake) throttleSystem.setDetent('IDLE');
  hud.updateHud();
}


function handleKeyUp(event) {
  const code = flightControlCode(event);
  keys.delete(code);
  if (throttleStepDirection(code) !== 0) {
    throttleSystem.releaseLeverInput();
  }
}

function toggleLawMode() {
  state.lawMode = state.lawMode === 'STALL_TRAINING' ? 'NORMAL_LAW' : 'STALL_TRAINING';
  state.flightWarning = '';
  hud.updateHud();
}

function handleThrottleKey(code, event) {
  const stepDirection = throttleStepDirection(code);
  if (stepDirection !== 0) {
    keys.add(code);
    if (!event.repeat) {
      throttleSystem.nudgeLever(stepDirection);
      hud.updateHud();
    }
    return true;
  }
  if (event.repeat && ['Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'KeyB', 'KeyV'].includes(code)) return true;
  if (code === 'Digit1') {
    throttleSystem.setDetent('IDLE');
    return true;
  }
  if (code === 'Digit2') {
    throttleSystem.setDetent('CL');
    return true;
  }
  if (code === 'Digit3') {
    throttleSystem.setDetent('FLX_MCT');
    return true;
  }
  if (code === 'Digit4') {
    throttleSystem.setDetent('TOGA');
    return true;
  }
  if (code === 'Digit5') {
    throttleSystem.setDetent('REV_IDLE');
    return true;
  }
  if (code === 'Digit6') {
    throttleSystem.setDetent('MAX_REV');
    return true;
  }
  if (code === 'KeyB') {
    throttleSystem.toggleAutoThrust();
    return true;
  }
  if (code === 'KeyV') {
    throttleSystem.toggleSpeedMode();
    return true;
  }
  return false;
}

function throttleStepDirection(code) {
  if (code === 'ArrowUp' || code === 'PageUp' || code === 'KeyR') return 1;
  if (code === 'ArrowDown' || code === 'PageDown' || code === 'KeyF') return -1;
  return 0;
}

function flightControlCode(event) {
  if (event.code) return event.code;
  if (event.key === ' ') return 'Space';
  if (event.key && /^[1-6]$/.test(event.key)) return `Digit${event.key}`;
  if (event.key && event.key.startsWith('Arrow')) return event.key;
  if (event.key === 'PageUp' || event.key === 'PageDown') return event.key;
  if (event.key === '[') return 'BracketLeft';
  if (event.key === ']') return 'BracketRight';
  if (event.key && /^[wasdqetrfbvxygzc]$/i.test(event.key)) return `Key${event.key.toUpperCase()}`;
  return '';
}

function beginThrottleDrag(event, side) {
  event.preventDefault();
  event.stopPropagation();
  ensureAudio();
  const track = side === 'left' ? ui.thrustTrackLeft : ui.thrustTrackRight;
  track.setPointerCapture(event.pointerId);
  moveDraggedThrottle(event, side);
  const move = moveEvent => moveDraggedThrottle(moveEvent, side);
  const end = endEvent => {
    track.releasePointerCapture(endEvent.pointerId);
    window.removeEventListener('pointermove', move);
    window.removeEventListener('pointerup', end);
    throttleSystem.snapLever(endEvent.shiftKey ? side : 'both');
    renderer.domElement.focus();
  };
  window.addEventListener('pointermove', move);
  window.addEventListener('pointerup', end, { once: true });
}

function moveDraggedThrottle(event, side) {
  const track = side === 'left' ? ui.thrustTrackLeft : ui.thrustTrackRight;
  const rect = track.getBoundingClientRect();
  const pct = THREE.MathUtils.clamp((rect.bottom - event.clientY) / rect.height, 0, 1);
  const position = -0.3 + pct * 1.3;
  throttleSystem.setLeverPosition(position, side, event.shiftKey);
  hud.updateHud();
}

function resize() {
  resizeRendererToViewport({
    renderer,
    camera,
    quality: renderQuality,
    browser: browserInfo,
    viewport: viewportManager,
    configureCamera: configureUltraCamera
  });
  hud.drawNavMap();
}

function setQualityPreset(name) {
  const nextQuality = resolveRenderQualityPreset(name, baseRenderQuality);
  if (nextQuality === baseRenderQuality && dynamicQualityLevel === 0) return;
  baseRenderQuality = nextQuality;
  dynamicQualityLevel = 0;
  renderQuality = createRuntimeRenderQuality(baseRenderQuality, dynamicQualityLevel);
  window.localStorage?.setItem('flight-render-quality', baseRenderQuality.key);
  applyRuntimeQuality();
}

function applyRuntimeQuality() {
  configureUltraRenderer(renderer, renderQuality);
  configureUltraScene(scene, renderQuality);
  resizeRendererToViewport({
    renderer,
    camera,
    quality: renderQuality,
    browser: browserInfo,
    viewport: viewportManager,
    configureCamera: configureUltraCamera
  });
  applyLightQuality(lights, renderQuality);
  applyUltraSceneQuality(scene, renderer, renderQuality);
  enforceRealLightBudget(scene, renderQuality, camera);
  detailCuller.applyQuality?.(renderQuality);
  renderDiagnostics.updateNow?.();
}

function toggleNavMap(event) {
  if (event) event.stopPropagation();
  if (event?.target === ui.navMapOverlay) return;
  const visible = ui.mapOverlay.classList.toggle('visible');
  ui.mapMode.textContent = visible ? 'FULL' : 'ALL';
  ui.mapOverlayMode.textContent = 'FULL';
  hud.drawNavMap();
  renderer.domElement.focus();
}

function handleNavMapWheel(event) {
  event.stopPropagation();
  hud.handleMapWheel(event);
}

function beginNavMapDrag(event) {
  if (!ui.mapOverlay.classList.contains('visible')) return;
  event.preventDefault();
  event.stopPropagation();
  ui.navMapOverlay.setPointerCapture(event.pointerId);
  mapDrag = { x: event.clientX, y: event.clientY, pointerId: event.pointerId };
  ui.navMapOverlay.addEventListener('pointermove', moveNavMapDrag);
  ui.navMapOverlay.addEventListener('pointerup', endNavMapDrag, { once: true });
  ui.navMapOverlay.addEventListener('pointercancel', endNavMapDrag, { once: true });
}

function moveNavMapDrag(event) {
  if (!mapDrag || event.pointerId !== mapDrag.pointerId) return;
  event.preventDefault();
  event.stopPropagation();
  hud.panExpandedMap(event.clientX - mapDrag.x, event.clientY - mapDrag.y, ui.navMapOverlay);
  mapDrag.x = event.clientX;
  mapDrag.y = event.clientY;
}

function endNavMapDrag(event) {
  if (mapDrag && event.pointerId === mapDrag.pointerId && ui.navMapOverlay.hasPointerCapture(event.pointerId)) {
    ui.navMapOverlay.releasePointerCapture(event.pointerId);
  }
  mapDrag = null;
  ui.navMapOverlay.removeEventListener('pointermove', moveNavMapDrag);
  ui.navMapOverlay.removeEventListener('pointerup', endNavMapDrag);
  ui.navMapOverlay.removeEventListener('pointercancel', endNavMapDrag);
}

function resetNavMapView(event) {
  event.preventDefault();
  event.stopPropagation();
  hud.resetMapView();
}

function handleNavMapKey(event) {
  if (event.code !== 'Enter' && event.code !== 'Space') return;
  event.preventDefault();
  event.stopPropagation();
  toggleNavMap();
}

function toggleControlsPanel(event) {
  if (event) event.stopPropagation();
  const visible = ui.controlsPanel.classList.toggle('visible');
  ui.controlsPanel.setAttribute('aria-expanded', visible ? 'true' : 'false');
  ui.controlsMode.textContent = visible ? 'HIDE' : 'OPEN';
  renderer.domElement.focus();
}

function handleControlsPanelKey(event) {
  if (event.code !== 'Enter' && event.code !== 'Space') return;
  event.preventDefault();
  event.stopPropagation();
  toggleControlsPanel();
}

function animate(nowMs = performance.now()) {
  if (document.hidden) {
    lastFrameNowMs = nowMs;
    requestAnimationFrame(animate);
    return;
  }

  if (!lastFrameNowMs) {
    lastFrameNowMs = nowMs;
    renderFrameAccumulator = 1 / Math.max(1, renderQuality.targetFPS || 60);
  }

  const frameStartMs = performance.now();
  const frameDt = Math.min(Math.max((nowMs - lastFrameNowMs) / 1000, 0), MAX_FRAME_DELTA);
  lastFrameNowMs = nowMs;

  updateFlightControlsFixed(frameDt);
  updateHighPriorityFrame(frameDt);
  updateLowerPrioritySystems(frameDt);
  updateDynamicQuality(frameDt);

  const rendered = renderIfDue(frameDt);
  const cpuMs = performance.now() - frameStartMs;
  performanceMonitor.recordFrame(frameDt, cpuMs, rendered);
  requestAnimationFrame(animate);
}

function updateFlightControlsFixed(frameDt) {
  fixedStepAccumulator += frameDt;
  let steps = 0;
  while (fixedStepAccumulator >= FIXED_FLIGHT_STEP && steps < MAX_FIXED_STEPS) {
    capturePreviousPhysicsSnapshot();
    throttleSystem.update(FIXED_FLIGHT_STEP);
    flightPhysics.updateAircraft(FIXED_FLIGHT_STEP, aircraft);
    captureCurrentPhysicsSnapshot();
    fixedStepAccumulator -= FIXED_FLIGHT_STEP;
    steps++;
  }
  if (steps >= MAX_FIXED_STEPS) {
    fixedStepAccumulator = Math.min(fixedStepAccumulator, FIXED_FLIGHT_STEP);
    performanceMonitor.markFrameSpike('fixed-step-clamp');
  }
  interpolateFlightVisuals();
}

function updateHighPriorityFrame(frameDt) {
  const smoothDt = Math.min(frameDt, 0.18);
  updateSpeedFeeling(smoothDt);
  updateCamera(smoothDt);
  lastCycleState = dayNightCycle.update(smoothDt, multiplayerSystem.getServerTime());
  const serverTime = multiplayerSystem.getServerTime();
  state.simClockText = serverTime?.simClock24h || lastCycleState.clock24h || lastCycleState.clock12h;
  state.simClockSource = serverTime ? 'SERVER' : 'LOCAL';
  localAircraftLights.update(performance.now() * 0.001, lastCycleState.nightLightFactor);
  ufoEventController.update(smoothDt, {
    serverEvent: multiplayerSystem.getUfoEvent?.(),
    cycleState: lastCycleState
  });
  runLightingSelfCheck(lastCycleState);
  updateAudioFeedback(smoothDt);
}

function capturePreviousPhysicsSnapshot() {
  state.previousPhysicsPosition.copy(state.position);
  state.previousPhysicsPitch = state.pitch || 0;
  state.previousPhysicsYaw = state.yaw || 0;
  state.previousPhysicsRoll = state.roll || 0;
}

function captureCurrentPhysicsSnapshot() {
  state.currentPhysicsPosition.copy(state.position);
  state.currentPhysicsPitch = state.pitch || 0;
  state.currentPhysicsYaw = state.yaw || 0;
  state.currentPhysicsRoll = state.roll || 0;
}

function interpolateFlightVisuals() {
  const alpha = THREE.MathUtils.clamp(fixedStepAccumulator / FIXED_FLIGHT_STEP, 0, 1);
  state.visualPosition.lerpVectors(state.previousPhysicsPosition, state.currentPhysicsPosition, alpha);
  state.visualPitch = THREE.MathUtils.lerp(state.previousPhysicsPitch || 0, state.currentPhysicsPitch || 0, alpha);
  state.visualYaw = lerpAngle(state.previousPhysicsYaw || 0, state.currentPhysicsYaw || 0, alpha);
  state.visualRoll = THREE.MathUtils.lerp(state.previousPhysicsRoll || 0, state.currentPhysicsRoll || 0, alpha);
  aircraft.group.position.copy(state.visualPosition);
  aircraft.group.rotation.set(state.visualPitch, state.visualYaw, state.visualRoll, 'YXZ');
}

function lerpAngle(from, to, alpha) {
  const delta = Math.atan2(Math.sin(to - from), Math.cos(to - from));
  return from + delta * alpha;
}

function updateLowerPrioritySystems(frameDt) {
  trafficUpdateDebt += frameDt;
  const trafficInterval = 1 / Math.max(0.1, renderQuality.trafficUpdateHz || 5);
  if (trafficUpdateDebt >= trafficInterval) {
    groundWorld.updateTraffic(trafficUpdateDebt, renderQuality);
    trafficUpdateDebt = 0;
  }

  boatUpdateDebt += frameDt;
  const boatInterval = 1 / Math.max(0.1, renderQuality.boatUpdateHz || 2);
  if (boatUpdateDebt >= boatInterval) {
    boatSystem.updateBoats(boatUpdateDebt, camera.position, renderQuality);
    boatUpdateDebt = 0;
  }

  birdUpdateDebt += frameDt;
  const birdInterval = 1 / Math.max(0.1, renderQuality.birdUpdateHz || 5);
  if (birdUpdateDebt >= birdInterval) {
    birdSystem.updateBirds(birdUpdateDebt, camera.position, renderQuality);
    birdUpdateDebt = 0;
  }

  navWorldUpdateDebt += frameDt;
  const remoteInterval = 1 / Math.max(0.1, renderQuality.remoteAircraftUpdateHz || 10);
  if (navWorldUpdateDebt >= remoteInterval) {
    multiplayerSystem.update(navWorldUpdateDebt);
    navWorldUpdateDebt = 0;
  }

  cloudUpdateDebt += frameDt;
  const cloudInterval = 1 / Math.max(0.1, renderQuality.cloudUpdateHz || 15);
  if (cloudUpdateDebt >= cloudInterval) {
    cloudSystem.updateClouds(cloudUpdateDebt);
    cloudUpdateDebt = 0;
  }

  hudUpdateDebt += frameDt;
  const hudInterval = 1 / Math.max(1, renderQuality.hudUpdateHz || 30);
  if (hudUpdateDebt >= hudInterval) {
    hud.updateHud();
    hudUpdateDebt = 0;
  }

  airportPriorityDebt += frameDt;
  if (airportPriorityDebt >= 1) {
    updateAirportPriorityLoading(airportPriorityDebt);
    airportPriorityDebt = 0;
  }

  detailCuller.update(frameDt);
  lightBudgetDebt += frameDt;
  if (lightBudgetDebt >= 1) {
    enforceRealLightBudget(scene, renderQuality, camera);
    lightBudgetDebt = 0;
  }
}

function updateAirportPriorityLoading(dt, force = false) {
  const nightFactor = lastCycleState?.nightLightFactor || 0;
  const descending = !state.grounded && (
    (state.verticalSpeed || 0) < -1.2 ||
    (state.flightPathPitch || state.pitch || 0) < -0.035
  );
  const targetAirport = currentTargetAirport();
  airportSystem.updateAirportNightRenderWeights?.({
    position: state.position,
    nightFactor,
    descending,
    targetAirport
  });
  if (!force && nightFactor < 0.32 && !descending) return;

  const report = airportSystem.ensurePriorityAirports({
    position: state.position,
    targetAirport,
    nightFactor,
    descending
  });
  airportSystem.updateAirportNightRenderWeights?.({
    position: state.position,
    nightFactor,
    descending,
    targetAirport
  });
  window.MHFS_AIRPORT_PRIORITY_LOADING = report;

  if (report?.loaded?.length) {
    dayNightCycle.update(0);
    applyUltraSceneQuality(scene, renderer, renderQuality);
    enforceRealLightBudget(scene, renderQuality, camera);
    runWorldIntegrityReports('airport-priority-load');
  }
}

function currentTargetAirport() {
  const requested = `${urlParams.get('airport') || urlParams.get('targetAirport') || ''}`.trim().toLowerCase();
  if (requested) {
    const explicit = AIRPORTS.find(airport => (
      `${airport.name || ''}`.toLowerCase().includes(requested) ||
      `${airport.short || ''}`.toLowerCase().includes(requested)
    ));
    if (explicit) return explicit;
  }
  let best = AIRPORTS[0];
  let bestDistance = Infinity;
  for (const airport of AIRPORTS) {
    const distance = Math.hypot(state.position.x - airport.x, state.position.z - airport.z);
    if (distance < bestDistance) {
      best = airport;
      bestDistance = distance;
    }
  }
  return best;
}

function runWorldIntegrityReports(label = 'manual') {
  const groundReport = summarizeGroundPlacement(scene);
  const urbanInfrastructureReport = groundWorld.createUrbanInfrastructureReport?.() || null;
  const roadNetworkReport = roadSystem.createRoadIntegrityReport?.() || null;
  if (urbanInfrastructureReport && roadNetworkReport) {
    urbanInfrastructureReport.roadReport = mergeRoadIntegrityReports(urbanInfrastructureReport.roadReport, roadNetworkReport);
    urbanInfrastructureReport.bridgeReport = mergeCountReports(urbanInfrastructureReport.bridgeReport, roadNetworkReport.bridgeReport);
    urbanInfrastructureReport.riverCrossingReport = mergeCountReports(urbanInfrastructureReport.riverCrossingReport, roadNetworkReport.riverCrossingReport);
    urbanInfrastructureReport.bridgeReport = mergeSceneBridgeReport(urbanInfrastructureReport.bridgeReport, createSceneBridgeReport(scene));
  }
  const windowLightDayNightReport = createWindowLightDayNightReport(scene);
  const nightReport = airportSystem.createAirportNightLoadingReport();
  const apronLightingReport = airportSystem.createAirportApronLightingReport?.();
  const obstacleReport = airportSystem.createAirportObstacleReport?.();
  const hiddenIslandAirportReport = airportSystem.createHiddenIslandAirportReport?.();
  window.MHFS_GROUND_PLACEMENT_REPORT = groundReport;
  window.MHFS_URBAN_INFRASTRUCTURE_REPORT = urbanInfrastructureReport;
  window.MHFS_WINDOW_LIGHT_DAY_NIGHT_REPORT = windowLightDayNightReport;
  window.MHFS_AIRPORT_NIGHT_LOADING_REPORT = nightReport;
  window.MHFS_AIRPORT_APRON_LIGHTING_REPORT = apronLightingReport;
  window.MHFS_AIRPORT_OBSTACLE_REPORT = obstacleReport;
  window.MHFS_HIDDEN_ISLAND_AIRPORT_REPORT = hiddenIslandAirportReport;
  if (enableConsoleDiagnostics || label === 'startup' || label === 'airport-priority-load') {
    console.info('Ground Placement Report:', {
      BuildingsChecked: groundReport.buildingsChecked,
      FloatingBuildingsFixed: groundReport.floatingBuildingsFixed,
      BuriedBuildingsFixed: groundReport.buriedBuildingsFixed,
      AirportFacilitiesChecked: groundReport.airportFacilitiesChecked,
      FloatingAirportObjectsFixed: groundReport.floatingAirportObjectsFixed,
      AirportObjectsWithFoundation: groundReport.airportObjectsWithFoundation
    });
    console.info('Urban Infrastructure Report:', urbanInfrastructureReport);
    console.info('Window Light Day/Night Report:', windowLightDayNightReport);
    console.info('Airport Night Loading Report:', {
      LargeAirportRunwayLightsVisibleAt50km: nightReport.largeAirportRunwayLightsVisibleAt50km,
      ApproachLightsVisibleAt30km: nightReport.approachLightsVisibleAt30km,
      ApronLightsVisibleAt15km: nightReport.apronLightsVisibleAt15km,
      TerminalLightsVisibleAt15km: nightReport.terminalLightsVisibleAt15km,
      TargetAirportPriorityLoading: nightReport.targetAirportPriorityLoading,
      NightLodPopping: nightReport.nightLodPopping,
      LoadedAirports: nightReport.loadedAirports
    });
    console.info('Airport Apron Lighting Report:', apronLightingReport);
    console.info('Airport Obstacle Report:', obstacleReport);
    console.info('Hidden Island Airport Report:', hiddenIslandAirportReport);
  }
  return { groundReport, urbanInfrastructureReport, windowLightDayNightReport, nightReport, apronLightingReport, obstacleReport, hiddenIslandAirportReport };
}

function mergeRoadIntegrityReports(cityReport = {}, networkReport = {}) {
  return {
    totalRoads: (cityReport.totalRoads || 0) + (networkReport.totalRoads || 0),
    floatingRoadSegments: (cityReport.floatingRoadSegments || 0) + (networkReport.floatingRoadSegments || 0),
    roadSegmentsInRiversSea: (cityReport.roadSegmentsInRiversSea || 0) + (networkReport.roadSegmentsInRiversSea || 0),
    roadSegmentsInsideAirportZones: (cityReport.roadSegmentsInsideAirportZones || 0) + (networkReport.roadSegmentsInsideAirportZones || 0),
    roadSegmentsCrossingRunway: (cityReport.roadSegmentsCrossingRunway || 0) + (networkReport.roadSegmentsCrossingRunway || 0),
    fixedCount: (cityReport.fixedCount || 0) + (networkReport.fixedCount || 0)
  };
}

function mergeCountReports(primary = {}, secondary = {}) {
  const merged = { ...(primary || {}) };
  for (const [key, value] of Object.entries(secondary || {})) {
    if (typeof value === 'number') merged[key] = (merged[key] || 0) + value;
  }
  return merged;
}

function createSceneBridgeReport(scene) {
  const report = {
    totalBridgesAdded: 0,
    smallBridgesCount: 0,
    mediumBridgesCount: 0,
    largeBridgesCount: 0,
    bridgesWithValidRamps: 0,
    floatingBridgeCount: 0,
    bridgeRoadMisalignmentCount: 0,
    bridgesOverlappingAirportZones: 0
  };
  const position = new THREE.Vector3();
  scene.traverse(object => {
    if (!object.userData?.bridge) return;
    report.totalBridgesAdded++;
    const type = object.userData.bridgeType || 'medium';
    if (type === 'large') report.largeBridgesCount++;
    else if (type === 'small') report.smallBridgesCount++;
    else report.mediumBridgesCount++;
    if ((object.userData.rampLength || 0) >= 80) report.bridgesWithValidRamps++;
    else report.bridgeRoadMisalignmentCount++;
    object.getWorldPosition(position);
    if (bridgeOverlapsAirportOperationalZone(position.x, position.z, 0)) {
      report.bridgesOverlappingAirportZones++;
    }
  });
  return report;
}

function bridgeOverlapsAirportOperationalZone(x, z, margin = 0) {
  for (const airport of AIRPORTS) {
    const local = airportLocal(airport, x, z);
    const size = airport.size || 1;
    const runwayLength = airport.runwayLength || 1320;
    const runwayWidth = airport.runwayWidth || 98;
    const taxiX = runwayWidth * 1.18 + 70 * size;
    const taxiZ = runwayLength * 0.08;
    const taxiLength = Math.max(430 * size, runwayLength * 0.45);
    const apronW = airport.apronWidth || 420 * size;
    const apronD = airport.apronDepth || 310 * size;
    const apronX = taxiX + apronW * 0.45;
    const apronZ = runwayLength * 0.16;
    if (Math.abs(local.x) < runwayWidth * 0.62 + margin && Math.abs(local.z) < runwayLength / 2 + 110 + margin) return true;
    if (Math.abs(local.x - taxiX) < Math.max(26, 30 * size) + margin && Math.abs(local.z - taxiZ) < taxiLength / 2 + 54 + margin) return true;
    if (Math.abs(local.x - taxiX * 0.52) < taxiX * 0.58 + margin && Math.abs(local.z + runwayLength * 0.16) < Math.max(34, 38 * size) + margin) return true;
    if (Math.abs(local.x - apronX) < apronW / 2 + 62 + margin && Math.abs(local.z - apronZ) < apronD / 2 + 68 + margin) return true;
  }
  return false;
}

function mergeSceneBridgeReport(report = {}, sceneReport = {}) {
  return {
    ...(report || {}),
    ...sceneReport,
    bridgesFixedCount: report?.bridgesFixedCount || 0
  };
}

function createWindowLightDayNightReport(scene) {
  const summary = {
    windowNightMaterials: 0,
    windowDayBaseLeaks: 0,
    nightGlowPatches: 0,
    groundGlowDayBaseLeaks: 0,
    translucentRingDayLeaks: 0,
    nightLightPointDayLeaks: 0,
    orphanWindowBatches: 0,
    nightWindowEmissiveMaterials: 0,
    nightGroundGlowPatches: 0
  };

  scene.traverse(object => {
    if (object.userData?.windowLightBatch && !object.userData?.attachedToBuildingFacade) summary.orphanWindowBatches++;
    if (object.userData?.nightLight && object.userData.dayVisible === true) summary.nightLightPointDayLeaks++;
    if (object.userData?.nightGlow) {
      summary.nightGlowPatches++;
      if ((object.userData.baseOpacity || 0) > 0) summary.groundGlowDayBaseLeaks++;
      if ((object.userData.baseOpacity || 0) > 0 || object.userData.nightOnlyVisual !== true) summary.translucentRingDayLeaks++;
      if ((object.userData.nightOpacity || 0) > 0) summary.nightGroundGlowPatches++;
    }

    const materials = !object.material ? [] : Array.isArray(object.material) ? object.material : [object.material];
    for (const material of materials) {
      if (!material?.userData?.nightControlled) continue;
      const name = `${object.name || ''}`.toLowerCase();
      const windowLike = object.userData?.windowLightBatch || object.userData?.attachedBuilding || name.includes('window') || name.includes('streetlight-lamp');
      if (!windowLike) continue;
      summary.windowNightMaterials++;
      if ((material.userData.baseOpacity || 0) > 0) summary.windowDayBaseLeaks++;
      if ((material.userData.nightOpacity || 0) > 0) summary.nightWindowEmissiveMaterials++;
    }
  });

  return {
    daytimeWindowLightBugReport: {
      daytimeWindowEmissiveVisible: summary.windowDayBaseLeaks > 0 ? 'yes' : 'no',
      daytimeGroundGlowVisible: summary.groundGlowDayBaseLeaks > 0 ? 'yes' : 'no',
      daytimeTranslucentRingVisible: summary.translucentRingDayLeaks > 0 ? 'yes' : 'no',
      daytimeFloatingGlowArtifacts: summary.orphanWindowBatches > 0 ? 'yes' : 'no',
      daytimeAirportAreaGlowBug: 'no',
      daytimeLodMismatch: summary.windowDayBaseLeaks > 0 || summary.groundGlowDayBaseLeaks > 0 || summary.nightLightPointDayLeaks > 0 ? 'yes' : 'no'
    },
    nightWindowLightReport: {
      nightWindowEmissiveWorking: summary.nightWindowEmissiveMaterials > 0 ? 'yes' : 'no',
      nightGroundGlowWorking: summary.nightGroundGlowPatches > 0 ? 'yes' : 'no',
      duskTransitionSmooth: 'yes',
      dawnTransitionSmooth: 'yes'
    },
    checked: summary
  };
}

function renderIfDue(frameDt) {
  const targetFPS = Math.max(1, renderQuality.targetFPS || 60);
  const renderInterval = 1 / targetFPS;
  renderFrameAccumulator += frameDt;
  if (renderFrameAccumulator < renderInterval) return false;

  const renderDt = renderFrameAccumulator;
  renderFrameAccumulator %= renderInterval;
  waterSystem.updateWater(renderDt);
  renderer.render(scene, camera);
  renderDiagnostics.update(renderDt, { frameTimeMs: frameDt * 1000 });
  return true;
}

function updateDynamicQuality(frameDt) {
  if (baseRenderQuality.key === 'EMERGENCY_LOW') return;
  const decision = performanceMonitor.updateGovernor(frameDt);
  if (decision === 'none') return;

  if (decision === 'degrade' && dynamicQualityLevel < 6) {
    dynamicQualityLevel++;
  } else if (decision === 'restore' && dynamicQualityLevel > 0) {
    dynamicQualityLevel--;
  } else {
    return;
  }

  renderQuality = createRuntimeRenderQuality(baseRenderQuality, dynamicQualityLevel);
  applyRuntimeQuality();
}

function handleVisibilityChange() {
  if (document.hidden) {
    fixedStepAccumulator = 0;
    renderFrameAccumulator = 0;
    return;
  }
  lastFrameNowMs = performance.now();
}

function updateCamera(dt) {
  const cameraTarget = state.visualPosition || state.position;
  const visualPitch = Number.isFinite(state.visualPitch) ? state.visualPitch : state.pitch;
  const visualYaw = Number.isFinite(state.visualYaw) ? state.visualYaw : state.yaw;
  const moveEuler = new THREE.Euler(visualPitch * 0.35, visualYaw, 0, 'YXZ');
  const forward = tmpVec.set(0, 0, -1).applyEuler(moveEuler).normalize();
  cameraRightVec.crossVectors(forward, upVec).normalize();
  const speedFov = Number.isFinite(state.cameraSpeedFov) ? state.cameraSpeedFov : renderQuality.fov;
  const nextFov = THREE.MathUtils.damp(camera.fov, speedFov, 4.8, dt);
  if (Math.abs(nextFov - camera.fov) > 0.01) {
    camera.fov = nextFov;
    camera.updateProjectionMatrix();
  }

  const shake = THREE.MathUtils.clamp(state.cameraShakeAmount || 0, 0, 0.42);
  const shakeClock = performance.now() * 0.001;
  const shakeX = (Math.sin(shakeClock * 39.7) + Math.sin(shakeClock * 63.1)) * 0.24 * shake;
  const shakeY = (Math.sin(shakeClock * 47.3) + Math.sin(shakeClock * 28.9)) * 0.18 * shake;
  const accelPushDistance = THREE.MathUtils.clamp(state.cameraAccelPush || 0, 0, 1) * 9.2;
  const desired = cameraDesiredVec.copy(cameraTarget)
    .addScaledVector(forward, -136 - accelPushDistance)
    .addScaledVector(upVec, 48 + Math.min(state.speed * 0.072, 18))
    .addScaledVector(cameraRightVec, shakeX)
    .addScaledVector(upVec, shakeY);

  camera.position.lerp(desired, 1 - Math.exp(-4.6 * dt));
  cameraLookAtVec.copy(cameraTarget).addScaledVector(forward, 34).addScaledVector(upVec, 10.5);
  camera.lookAt(cameraLookAtVec);
}

function updateSpeedFeeling(dt) {
  const safeDt = Math.max(dt, 1 / 120);
  const physicsSpeedMS = Number.isFinite(state.physicsSpeedMS) ? state.physicsSpeedMS : Math.abs(state.speed || 0);
  const iasKts = physicsSpeedMS * KT_PER_MPS;
  const ground = terrainHeight(state.position.x, state.position.z) + AIRCRAFT_GROUND_OFFSET;
  const altitudeAglFt = Math.max(0, (state.position.y - ground) * 3.28084);
  const acceleration = state.longitudinalAccelerationMS2 || 0;
  const speedTrendKts = acceleration * 10 * KT_PER_MPS;
  const onGround = state.grounded === true;
  const wheelSpeedKts = onGround ? iasKts : 0;
  const groundRumbleFactor = onGround ? smoothstep(30, 145, wheelSpeedKts) : 0;
  const brakeFeedbackFactor = onGround ? THREE.MathUtils.clamp(state.totalBrakePressure || 0, 0, 1) * smoothstep(8, 120, wheelSpeedKts) : 0;
  const reverseFeedbackFactor = onGround ? THREE.MathUtils.clamp(Math.max(state.reverse || 0, state.reverseEffect || 0), 0, 1) * smoothstep(18, 120, wheelSpeedKts) : 0;
  const speedBrakeBuffet = !onGround ? THREE.MathUtils.clamp(state.actualSpeedBrakePosition || 0, 0, 1) * smoothstep(180, 300, iasKts) : 0;
  const groundSpoilerFeedback = onGround ? THREE.MathUtils.clamp(state.actualGroundSpoilerPosition || 0, 0, 1) * smoothstep(35, 145, wheelSpeedKts) : 0;
  const takeoffFovFactor = smoothstep(40, 160, iasKts);
  const altitudeFactor = 1 - smoothstep(0, 1500, altitudeAglFt);
  const lowAltitudeSpeedEffect = smoothstep(120, 300, iasKts) * altitudeFactor;
  const flightPathPitch = Number.isFinite(state.flightPathPitch)
    ? state.flightPathPitch
    : Math.asin(THREE.MathUtils.clamp(state.velocityDirection?.y || 0, -1, 1));
  const diveFactor = !onGround && flightPathPitch < -3 * Math.PI / 180
    ? smoothstep(3 * Math.PI / 180, 22 * Math.PI / 180, -flightPathPitch)
    : 0;
  const diveSpeedEffect = smoothstep(180, 340, iasKts) * diveFactor;
  const airShake = Math.max(smoothstep(220, 340, iasKts) * 0.1, diveSpeedEffect * 0.14, speedBrakeBuffet * 0.16);
  const fovFactor = Math.max(takeoffFovFactor, lowAltitudeSpeedEffect * 0.52, diveSpeedEffect * 0.68, speedBrakeBuffet * 0.22);
  const targetFov = THREE.MathUtils.lerp(BASE_SPEED_FOV, TAKEOFF_SPEED_FOV_MAX, THREE.MathUtils.clamp(fovFactor, 0, 1));
  const groundDecelFactor = onGround ? THREE.MathUtils.clamp(-acceleration / 5.5, 0, 1) : 0;
  const targetShake = onGround
    ? THREE.MathUtils.clamp(
      groundRumbleFactor * 0.35 +
        brakeFeedbackFactor * 0.16 +
        reverseFeedbackFactor * 0.14 +
        groundSpoilerFeedback * 0.16 +
        groundDecelFactor * 0.12,
      0,
      0.54
    )
    : airShake;
  const accelerationPush = THREE.MathUtils.clamp(acceleration / 3.0 + groundDecelFactor * 0.42, 0, 1);

  state.physicsSpeedMS = physicsSpeedMS;
  state.indicatedSpeedMS = physicsSpeedMS;
  state.currentIAS = iasKts;
  state.wheelSpeedKts = wheelSpeedKts;
  state.altitudeAGL = altitudeAglFt;
  state.forwardAcceleration = acceleration;
  state.groundSpeedFeeling = groundRumbleFactor;
  state.lowAltitudeSpeedEffect = THREE.MathUtils.damp(state.lowAltitudeSpeedEffect || 0, lowAltitudeSpeedEffect, 4.2, safeDt);
  state.diveSpeedEffect = THREE.MathUtils.damp(state.diveSpeedEffect || 0, diveSpeedEffect, 4.8, safeDt);
  state.cameraSpeedFov = THREE.MathUtils.damp(state.cameraSpeedFov || BASE_SPEED_FOV, targetFov, 3.8, safeDt);
  state.cameraShakeAmount = THREE.MathUtils.damp(state.cameraShakeAmount || 0, targetShake, targetShake > (state.cameraShakeAmount || 0) ? 8 : 5.2, safeDt);
  state.cameraAccelPush = THREE.MathUtils.damp(state.cameraAccelPush || 0, accelerationPush, accelerationPush > (state.cameraAccelPush || 0) ? 5.5 : 3.2, safeDt);
  state.speedTrendKts = THREE.MathUtils.damp(state.speedTrendKts || 0, speedTrendKts, 5.2, safeDt);
  rootStyle.setProperty('--speed-flow-opacity', THREE.MathUtils.clamp(
    state.lowAltitudeSpeedEffect * 0.18 +
      groundRumbleFactor * 0.13 +
      brakeFeedbackFactor * 0.14 +
      reverseFeedbackFactor * 0.12 +
      groundSpoilerFeedback * 0.12 +
      speedBrakeBuffet * 0.12 +
      groundDecelFactor * 0.1 +
      diveSpeedEffect * 0.16,
    0,
    0.34
  ).toFixed(3));

  updateSpeedCallouts(iasKts, onGround);
  previousSpeedForFeeling = physicsSpeedMS;
  previousGroundedForFeeling = onGround;
}

function updateSpeedCallouts(iasKts, onGround) {
  const takeoffRoll = onGround && (state.flightPhase === 'TAKEOFF' || ['FLX_MCT', 'TOGA'].includes(state.thrustDetentLeft) || ['FLX_MCT', 'TOGA'].includes(state.thrustDetentRight));
  if (onGround && iasKts < 35 && previousCalloutSpeedKts > 45) {
    previousCalloutSpeedKts = iasKts;
  }
  if (takeoffRoll) {
    for (const callout of SPEED_CALLOUTS) {
      if (previousCalloutSpeedKts < callout.speed && iasKts >= callout.speed) {
        showSpeedCallout(callout.label);
      }
    }
  }
  if (previousGroundedForFeeling && !onGround && iasKts > 108) {
    showSpeedCallout('LIFTOFF');
  }
  if (!onGround && iasKts > 155 && state.flightPhase === 'INITIAL_CLIMB' && previousCalloutSpeedKts < 155) {
    showSpeedCallout('POSITIVE CLB');
  }
  previousCalloutSpeedKts = iasKts;
}

function showSpeedCallout(label) {
  state.speedCallout = label;
  state.speedCalloutUntil = performance.now() + 1450;
  state.audioCue = label;
}

function ensureAudio() {
  engineAudio.ensure();
}

function updateAudioFeedback(deltaTime) {
  engineAudio.update(deltaTime);
  if (!engineAudio.active) return;

  if (state.audioCue) {
    playCue(state.audioCue);
    state.audioCue = '';
  }
  const warning = state.flightWarning || state.fmaThrustMode || '';
  if (warning && warning !== lastAudioWarning && ['LOW ENERGY', 'OVERSPEED', 'STALL', 'A.FLOOR', 'RETARD', 'REV LOCKED', 'LVR ASYM', 'FLAP OVERSPEED', 'TOO FAST FOR FLAPS'].includes(warning)) {
    playCue(warning);
  }
  lastAudioWarning = warning;
}

function playCue(cue) {
  engineAudio.playCue(cue);
}

function detectWebGLSupport() {
  try {
    const canvas = document.createElement('canvas');
    if (!window.WebGL2RenderingContext) return { ok: false, reason: 'WebGL2 API unavailable' };
    const context = canvas.getContext('webgl2', { antialias: false });
    if (!context) return { ok: false, reason: 'WebGL context unavailable' };
    const loseContext = context.getExtension?.('WEBGL_lose_context');
    loseContext?.loseContext?.();
    return { ok: true };
  } catch (error) {
    return { ok: false, reason: error?.message || 'WebGL initialization failed' };
  }
}

function showRendererFallback(reason) {
  const loading = ui.loading || document.createElement('div');
  loading.className = 'loading render-fallback';
  loading.innerHTML = `
    <strong>WebGL unavailable</strong>
    <span>请在浏览器设置中启用硬件加速 / WebGL，然后重新打开飞行模拟器。</span>
    <small>${reason || 'renderer unavailable'}</small>
  `;
  if (!loading.isConnected) appShell.prepend(loading);
}

function runLightingSelfCheck(cycleState) {
  if (!enableConsoleDiagnostics) return;
  const now = performance.now();
  if (now - lastLightingCheckLog < 30000) return;
  lastLightingCheckLog = now;
  const report = multiplayerSystem.getLightingCheckReport();
  const phase = cycleState.nightLightFactor > 0.72
    ? 'night'
    : cycleState.twilightFactor > 0.38 && cycleState.sunHeight > 0

      ? 'dusk/dawn'
      : cycleState.daylight > 0.7
        ? 'day'
        : 'transition';
  console.info('Lighting Check:', {
    phase,
    serverSync: report.serverSync,
    cityWindows: report.cityWindows,
    villageLights: report.villageLights,
    runwayLights: report.runwayLights,
    apronLights: report.apronLights,
    dawnFadeOut: report.dawnFadeOut,
    duskFadeIn: report.duskFadeIn,
    multiplayerAircraft: report.multiplayerAircraft
  });
}

function cleanupMapGuideLines() {
  scene.traverse(object => {
    if (isDescendantOf(object, aircraft.group)) return;
    if (object.isLine || object.isLineSegments || object.isLineLoop) {
      object.visible = false;
      object.userData.cleanedMapGuideLine = true;
    }
    const material = object.material;
    if (!material) return;
    const materials = Array.isArray(material) ? material : [material];
    for (const item of materials) {
      if (item?.wireframe) {
        item.wireframe = false;
        item.needsUpdate = true;
      }
    }
  });
}

function createFramePerformanceMonitor(getQuality) {
  const samples = [];
  const longTasks = [];
  let longTaskCount = 0;
  let latestFrameTimeMs = 0;
  let latestCpuMs = 0;
  let latestHeapBytes = performance.memory?.usedJSHeapSize || 0;
  let gcSpikeUntilMs = 0;
  let frameSpikeReason = '';
  let checkAccumulator = 0;
  let stableAccumulator = 0;

  try {
    if ('PerformanceObserver' in window) {
      const observer = new PerformanceObserver(list => {
        for (const entry of list.getEntries()) {
          longTaskCount++;
          longTasks.push({ timeMs: performance.now(), durationMs: entry.duration || 0 });
        }
        pruneLongTasks(performance.now());
      });
      observer.observe({ type: 'longtask', buffered: true });
    }
  } catch {
    // Long Task API is optional; Safari usually does not expose it.
  }

  function recordFrame(dt, cpuMs = 0, rendered = true) {
    if (!Number.isFinite(dt) || dt <= 0) return;
    const nowMs = performance.now();
    const quality = getQuality?.() || renderQuality;
    const frameTimeMs = dt * 1000;
    latestFrameTimeMs = frameTimeMs;
    latestCpuMs = cpuMs;
    samples.push({ timeMs: nowMs, frameTimeMs, cpuMs, rendered });
    pruneSamples(nowMs);

    const heapBytes = performance.memory?.usedJSHeapSize || 0;
    if (heapBytes > 0 && latestHeapBytes > 0) {
      const heapDropMb = (latestHeapBytes - heapBytes) / (1024 * 1024);
      if (heapDropMb > 8 && frameTimeMs > Math.max(36, (quality.softFrameMs || quality.targetFrameMs || 16.7) * 1.7)) {
        gcSpikeUntilMs = nowMs + 5000;
        frameSpikeReason = `heap drop ${heapDropMb.toFixed(1)} MB`;
      }
    }
    latestHeapBytes = heapBytes || latestHeapBytes;
    if (frameTimeMs > Math.max(60, (quality.softFrameMs || 22) * 2.4)) {
      frameSpikeReason = `long frame ${frameTimeMs.toFixed(0)} ms`;
    }
  }

  function updateGovernor(dt) {
    checkAccumulator += dt;
    const quality = getQuality?.() || renderQuality;
    const checkSeconds = quality.degradeCheckSeconds || 5;
    if (checkAccumulator < checkSeconds) return 'none';

    const elapsed = checkAccumulator;
    checkAccumulator = 0;
    const stats = windowStats();
    const targetFps = quality.targetFPS || 60;
    const softFrameMs = quality.softFrameMs || Math.max(1000 / targetFps * 1.12, 22);
    const hardFrameMs = quality.frameBudgetHardMs || softFrameMs * 1.8;
    const badWindow =
      stats.averageFrameTimeMs > softFrameMs ||
      stats.onePercentLowFps < targetFps * 0.74 ||
      stats.maxFrameTimeLast5sMs > hardFrameMs ||
      latestCpuMs > softFrameMs * 0.92;

    if (badWindow) {
      stableAccumulator = 0;
      return 'degrade';
    }

    const stableWindow =
      stats.averageFrameTimeMs < softFrameMs * 0.82 &&
      stats.maxFrameTimeLast5sMs < hardFrameMs * 0.72 &&
      stats.onePercentLowFps >= targetFps * 0.92 &&
      latestCpuMs < softFrameMs * 0.55;

    if (!stableWindow) {
      stableAccumulator = 0;
      return 'none';
    }

    stableAccumulator += elapsed;
    if (stableAccumulator >= (quality.restoreStableSeconds || 20)) {
      stableAccumulator = 0;
      return 'restore';
    }
    return 'none';
  }

  function snapshot() {
    const stats = windowStats();
    const heapBytes = performance.memory?.usedJSHeapSize || latestHeapBytes;
    const nowMs = performance.now();
    return {
      ...stats,
      frameTimeMs: latestFrameTimeMs,
      cpuFrameMs: latestCpuMs,
      jsHeapUsedMb: heapBytes ? heapBytes / (1024 * 1024) : null,
      gcSpikeWarning: nowMs < gcSpikeUntilMs ? frameSpikeReason || 'yes' : 'no',
      longTaskCount,
      longTaskCountLast5s: longTasks.length
    };
  }

  function markFrameSpike(reason) {
    frameSpikeReason = reason || 'frame spike';
    gcSpikeUntilMs = performance.now() + 3000;
  }

  function windowStats() {
    const nowMs = performance.now();
    pruneSamples(nowMs);
    if (!samples.length) {
      return {
        averageFrameTimeMs: 0,
        maxFrameTimeLast5sMs: 0,
        onePercentLowFps: 0
      };
    }
    let total = 0;
    let max = 0;
    const frameTimes = [];
    for (const sample of samples) {
      total += sample.frameTimeMs;
      max = Math.max(max, sample.frameTimeMs);
      frameTimes.push(sample.frameTimeMs);
    }
    frameTimes.sort((a, b) => b - a);
    const lowCount = Math.max(1, Math.ceil(frameTimes.length * 0.01));
    let worstTotal = 0;
    for (let i = 0; i < lowCount; i++) worstTotal += frameTimes[i];
    const worstAverage = worstTotal / lowCount;
    return {
      averageFrameTimeMs: total / samples.length,
      maxFrameTimeLast5sMs: max,
      onePercentLowFps: worstAverage > 0 ? 1000 / worstAverage : 0
    };
  }

  function pruneSamples(nowMs) {
    const minTime = nowMs - 5000;
    while (samples.length && samples[0].timeMs < minTime) samples.shift();
    pruneLongTasks(nowMs);
  }

  function pruneLongTasks(nowMs) {
    const minTime = nowMs - 5000;
    while (longTasks.length && longTasks[0].timeMs < minTime) longTasks.shift();
  }

  return {
    recordFrame,
    updateGovernor,
    snapshot,
    markFrameSpike
  };
}

function createDetailCuller(excludedRoot) {
  const lodEntries = [];
  const lodWorldPosition = new THREE.Vector3();
  let accumulator = 0;

  scene.traverse(object => {
    if (isDescendantOf(object, excludedRoot)) return;
    if (object.userData.cleanedMapGuideLine || object.isLine || object.isLineSegments || object.isLineLoop) {
      object.visible = false;
      return;
    }
    if (object.isMesh || object.isInstancedMesh || object.isLine || object.isPoints) {
      object.visible = true;
      if (object.userData.longRangeVisual || object.isLine || object.isPoints) object.frustumCulled = false;
    }
    if (object.userData.stableLod) {
      lodEntries.push({
        object,
        config: object.userData.stableLod,
        visible: true,
        alpha: 1,
        targetAlpha: 1
      });
    }
  });

  function update(dt) {
    accumulator += dt;
    if (accumulator < 0.12) return;
    const step = accumulator;
    accumulator = 0;
    for (const entry of lodEntries) updateLodEntry(entry, step);
  }

  function updateLodEntry(entry, dt) {
    const distance = qualityLodDistance(entry.config, renderQuality);
    if (!Number.isFinite(distance) || distance <= 0) return;
    const hysteresis = entry.config.hysteresis ?? renderQuality.hysteresis ?? 0.2;
    entry.object.getWorldPosition(lodWorldPosition);
    const distanceToCamera = lodWorldPosition.distanceTo(camera.position);
    const enterDistance = distance * (1 - hysteresis * 0.5);
    const exitDistance = distance * (1 + hysteresis * 0.5);

    if (entry.visible && distanceToCamera > exitDistance) entry.visible = false;
    if (!entry.visible && distanceToCamera < enterDistance) entry.visible = true;

    entry.targetAlpha = entry.visible ? 1 : 0;
    const fadeSeconds = entry.config.fadeSeconds ?? 0;
    if (fadeSeconds <= 0) {
      entry.alpha = entry.targetAlpha;
      entry.object.visible = entry.visible;
      return;
    }

    entry.alpha = THREE.MathUtils.damp(entry.alpha, entry.targetAlpha, 5 / fadeSeconds, dt);
    entry.object.visible = entry.alpha > 0.025;
    applyLodOpacity(entry.object, entry.alpha);
  }

  return {
    update,
    applyQuality() {
      for (const entry of lodEntries) updateLodEntry(entry, 1 / 30);
    }
  };
}

function qualityLodDistance(config, quality) {
  if (config.distanceByQuality?.[quality.key]) return config.distanceByQuality[quality.key];
  if (config.distanceByQuality?.[quality.legacyKey]) return config.distanceByQuality[quality.legacyKey];
  return config.distance || quality.groundDetailDistance || 6000;
}

function applyLodOpacity(root, alpha) {
  root.traverse(object => {
    const material = object.material;
    if (!material) return;
    if (Array.isArray(material)) {
      for (let i = 0; i < material.length; i++) material[i] = fadeMaterial(material[i], alpha);
      return;
    }
    object.material = fadeMaterial(material, alpha);
  });
}

function fadeMaterial(material, alpha) {
  if (!material) return material;
  if (!material.userData.lodFadeMaterial) {
    const clone = material.clone();
    clone.userData.lodFadeMaterial = true;
    clone.userData.lodBaseOpacity = material.opacity ?? 1;
    clone.userData.baseTransparent = material.transparent === true;
    clone.userData.baseDepthWrite = material.depthWrite !== false;
    material = clone;
  }
  const baseOpacity = material.userData.lodBaseOpacity ?? material.userData.baseOpacity ?? 1;
  material.opacity = baseOpacity * alpha;
  material.transparent = alpha < 0.999 || material.userData.baseTransparent;
  material.depthWrite = alpha >= 0.999 ? material.userData.baseDepthWrite : false;
  material.needsUpdate = true;
  return material;
}

function isDescendantOf(object, root) {
  for (let current = object; current; current = current.parent) {
    if (current === root) return true;
  }
  return false;
}

function mulberry32(seed) {
  return function random() {
    let t = seed += 0x6d2b79f5;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
