// Generated by tools/buildVirtualSources.js from src/network/multiplayer/part-*/source.js. Do not edit directly.
import * as THREE from '../../three.module.min.js?v=202605050057';
import { AIRCRAFT_GROUND_OFFSET } from '../data/worldData.js?v=202605070100';
import { createAircraft } from '../aircraft/A320.js?v=202605061100';
import { createAircraftLightController } from '../world/aircraftLights.js?v=202605060300';
import { FEATURE_FLAGS, PATHS, apiUrl } from '../config/paths.js?v=202605070200';
import { logOnce } from '../utils/log.js?v=202605060600';
import { HttpError, requestJson, setMultiplayerNetworkState } from '../utils/networkDiagnostics.js?v=202605060600';

const SEND_INTERVAL_SECONDS = 0.1;
const REMOTE_INTERPOLATION_SECONDS = 0.18;
const STALE_REMOTE_SECONDS = 9.5;
const MAP_TRAIL_INTERVAL_MS = 500;
const MAP_TRAIL_MAX_AGE_MS = 30000;
const MAP_TRAIL_MAX_POINTS = 60;
const MAP_TRAIL_MIN_DISTANCE = 18;
const KT_PER_MPS = 1.94384;
const INITIAL_RECONNECT_DELAY_MS = 10000;
const MAX_RECONNECT_DELAY_MS = 60000;

export function createMultiplayerSystem({ scene, state, terrainHeight }) {
  const remotes = new Map();
  const localTrail = [];
  let localTrailLastMs = 0;
  let playerId = '';
  let aircraftCode = 'A20N-LOCAL';
  let callsign = aircraftCode;
  let sessionReady = false;
  let offline = false;
  let apiUnavailable = false;
  let reconnectDelayMs = INITIAL_RECONNECT_DELAY_MS;
  let nextReconnectAtMs = 0;
  let sendAccumulator = SEND_INTERVAL_SECONDS;
  let pendingRequest = false;
  let serverTime = null;
  let lastLightingCheck = null;

  state.localAircraftCode = aircraftCode;
  state.multiplayerAircraft = [];
  state.serverUfoEvent = null;
  state.ufoSyncSource = FEATURE_FLAGS.multiplayerEnabled ? 'server-pending' : 'standalone';
  state.multiplayerMode = FEATURE_FLAGS.multiplayerEnabled ? 'offline' : 'local';
  state.sessionStatus = FEATURE_FLAGS.multiplayerEnabled ? 'idle' : 'disabled';
  state.lastApiError = '';
  setMultiplayerNetworkState({
    mode: state.multiplayerMode,
    sessionStatus: state.sessionStatus,
    lastApiError: ''
  });

  async function connect() {
    if (!FEATURE_FLAGS.multiplayerEnabled) {
      enterLocalOnlyMode('disabled');
      return;
    }
    await requestSession();
  }

  async function requestSession() {
    if (pendingRequest || apiUnavailable) return;
    try {
      pendingRequest = true;
      setConnectionState('offline', 'connecting', '');
      const payload = await postJson(apiUrl(PATHS.apiSession), {
        aircraftType: 'A20N',
        callsign: state.preferredCallsign || '',
        state: localStatePayload()
      }, { label: 'session', retryAfter: reconnectDelayMs });
      if (!payload?.ok) throw new Error('session failed');
      playerId = payload.playerId || payload.sessionId;
      if (!playerId) throw new Error('session response missing playerId');
      aircraftCode = payload.aircraftCode || aircraftCode;
      callsign = payload.callsign || aircraftCode;
      sessionReady = true;
      offline = false;
      apiUnavailable = false;
      reconnectDelayMs = INITIAL_RECONNECT_DELAY_MS;
      nextReconnectAtMs = 0;
      state.localPlayerId = playerId;
      state.localAircraftCode = aircraftCode;
      setConnectionState('online', 'online', '');
      ingestServerPayload(payload);
    } catch (error) {
      handleConnectionFailure(error);
    } finally {
      pendingRequest = false;
    }
  }

  function update(dt) {
    if (!sessionReady) return;
    updateRemoteAircraft(dt);
    updateMapAircraft();

    if (offline) {
      retryConnectionIfDue();
      return;
    }

    if (pendingRequest || !playerId) {
      return;
    }

    sendAccumulator += dt;
    if (sendAccumulator >= SEND_INTERVAL_SECONDS) {
      sendAccumulator = 0;
      sendState();
    }
  }

  function getServerTime() {
    return serverTime;
  }

  function getUfoEvent() {
    return state.serverUfoEvent || null;
  }

  function getLightingCheckReport() {
    if (lastLightingCheck && performance.now() - lastLightingCheck.generatedAt < 2500) return lastLightingCheck;
    const factor = serverTime?.nightLightFactor ?? 0;
    lastLightingCheck = {
      generatedAt: performance.now(),
      serverSync: serverTime ? 'OK' : 'FALLBACK',
      cityWindows: factor > 0.55 || factor < 0.35 ? 'OK' : 'TRANSITION',
      villageLights: factor > 0.55 || factor < 0.35 ? 'OK' : 'TRANSITION',
      runwayLights: factor > 0.55 || factor < 0.35 ? 'OK' : 'TRANSITION',
      apronLights: factor > 0.55 || factor < 0.35 ? 'OK' : 'TRANSITION',
      duskFadeIn: 'OK',
      dawnFadeOut: 'OK',
      multiplayerAircraft: `${state.multiplayerAircraft?.length || 1}`
    };
    return lastLightingCheck;
  }

  function dispose() {
    if (!FEATURE_FLAGS.multiplayerEnabled || !playerId || offline) return;
    try {
      navigator.sendBeacon?.(apiUrl(PATHS.apiLeave), new Blob([JSON.stringify({ playerId })], { type: 'application/json' }));
    } catch {
      // Best-effort disconnect notice.
    }
  }

  async function sendState() {
    if (!FEATURE_FLAGS.multiplayerEnabled || offline || !playerId) return;
    pendingRequest = true;
    try {
      const payload = await postJson(apiUrl(PATHS.apiState), {
        playerId,
        state: localStatePayload()
      }, { label: 'state sync', retryAfter: 30000 });
      setConnectionState('online', 'online', '');
      ingestServerPayload(payload);
    } catch (error) {
      logOnce('multiplayer-state-sync-failed', 'warn', 'Multiplayer state sync failed; switching to local mode with retry backoff.');
      handleConnectionFailure(error);
    } finally {
      pendingRequest = false;
    }
  }

  function retryConnectionIfDue() {
    if (!FEATURE_FLAGS.multiplayerEnabled || apiUnavailable || pendingRequest) return;
    if (performance.now() < nextReconnectAtMs) return;
    requestSession();
  }

  function handleConnectionFailure(error) {
    const status = error instanceof HttpError ? Number(error.status) : Number(error?.status);
    const message = error?.message || 'Multiplayer server unavailable';
    if (status === 404) {
      apiUnavailable = true;
      enterLocalOnlyMode('api-unavailable', message);
      logOnce('multiplayer-api-404', 'warn', 'Multiplayer API unavailable; using local-only mode without repeated /api/session retries.');
      return;
    }

    const retryInMs = scheduleReconnect();
    enterLocalOnlyMode('offline', message);
    logOnce('multiplayer-fallback', 'warn', `Multiplayer unavailable, using local-only mode. Retrying in ${Math.round(retryInMs / 1000)}s.`);
  }

  function enterLocalOnlyMode(sessionStatus = 'disabled', error = '') {
    sessionReady = true;
    offline = true;
    playerId = sessionStatus === 'disabled' ? 'local-only' : 'offline-local';
    serverTime = null;
    state.serverUfoEvent = null;
    state.ufoSyncSource = sessionStatus === 'api-unavailable' ? 'standalone-api-unavailable' : 'standalone';
    state.localPlayerId = playerId;
    state.localAircraftCode = aircraftCode;
    clearRemoteAircraft();
    setConnectionState('local', sessionStatus, error);
  }

  function setConnectionState(mode, sessionStatus, lastApiError = state.lastApiError || '') {
    state.multiplayerMode = mode;
    state.sessionStatus = sessionStatus;
    state.lastApiError = lastApiError || '';
    setMultiplayerNetworkState({
      mode,
      sessionStatus,
      lastApiError: state.lastApiError
    });
  }

  function scheduleReconnect() {
    const delayMs = reconnectDelayMs;
    nextReconnectAtMs = performance.now() + delayMs;
    reconnectDelayMs = Math.min(MAX_RECONNECT_DELAY_MS, Math.max(INITIAL_RECONNECT_DELAY_MS, reconnectDelayMs * 2));
    return delayMs;
  }

  function clearRemoteAircraft() {
    for (const remote of remotes.values()) scene.remove(remote.group);
    remotes.clear();
  }

  function ingestServerPayload(payload) {
    if (!payload) return;
    serverTime = {
      normalized: payload.serverDayTimeNormalized,
      simClock12h: payload.serverSimClock12h,
      simClock24h: payload.serverSimClock24h,
      receivedAtMs: performance.now(),
      serverNowMs: payload.serverNowMs,
      dayDurationSeconds: payload.dayDurationSeconds,
      sunDirection: payload.sunDirection,
      moonVisibility: payload.moonVisibility,
      starVisibility: payload.starVisibility,
      nightLightFactor: payload.nightLightFactor,
      duskFactor: payload.duskFactor,
      dawnFactor: payload.dawnFactor
    };
    state.simClockText = payload.serverSimClock24h || payload.serverSimClock12h;
    state.serverDayTimeNormalized = payload.serverDayTimeNormalized;
    state.serverUfoEvent = payload.ufoEvent || null;
    state.ufoSyncSource = payload.ufoEvent ? 'server-authoritative' : 'server-authoritative-idle';

    const seen = new Set();
    for (const player of payload.players || []) {
      seen.add(player.playerId);
      if (player.playerId === playerId) {
        aircraftCode = player.aircraftCode || aircraftCode;
        callsign = player.callsign || callsign;
        state.localAircraftCode = aircraftCode;
        continue;
      }
      ingestRemotePlayer(player);
    }

    for (const [remoteId, remote] of remotes) {
      if (!seen.has(remoteId) || performance.now() - remote.lastSeenMs > STALE_REMOTE_SECONDS * 1000) {
        scene.remove(remote.group);
        remotes.delete(remoteId);
      }
    }
  }

  function ingestRemotePlayer(player) {
    let remote = remotes.get(player.playerId);
    if (!remote) {
      const model = createAircraft();
      model.group.name = `remote-aircraft-${player.aircraftCode || player.playerId}`;
      model.group.userData.remoteAircraft = true;
      model.group.userData.aircraftCode = player.aircraftCode;
      model.group.userData.diagnosticType = 'aircraft';
      model.group.userData.diagnosticCount = 1;
      tintRemoteAircraft(model.group, remotes.size);
      const lightController = createAircraftLightController(model.group, {
        phase: hashPhase(player.playerId),
        remote: true
      });
      const label = createAircraftLabel(player.aircraftCode || 'A20N');
      model.group.add(label);
      scene.add(model.group);
      remote = {
        playerId: player.playerId,
        group: model.group,
        lightController,
        label,
        current: new THREE.Vector3(),
        target: new THREE.Vector3(),
        currentRotation: { yaw: 0, pitch: 0, roll: 0 },
        targetRotation: { yaw: 0, pitch: 0, roll: 0 },
        trail: [],
        lastTrailMs: 0,
        display: player,
        lastSeenMs: performance.now()
      };
      remotes.set(player.playerId, remote);
    }

    const position = player.position || {};
    remote.target.set(Number(position.x) || 0, Number(position.y) || 0, Number(position.z) || 0);
    if (!remote.initialized) {
      remote.current.copy(remote.target);
      remote.group.position.copy(remote.current);
      remote.initialized = true;
    }
    const rotation = player.rotation || {};
    remote.targetRotation = {
      yaw: Number(rotation.yaw) || 0,
      pitch: Number(rotation.pitch) || 0,
      roll: Number(rotation.roll) || 0
    };
    remote.display = player;
    remote.lastSeenMs = performance.now();
    if (!remote.trail.length) pushTrailPoint(remote.trail, remote.target, player.altitude, player.heading, performance.now(), true);
    updateAircraftLabel(remote.label, player);
  }

  function updateRemoteAircraft(dt) {
    const alpha = 1 - Math.exp(-dt / REMOTE_INTERPOLATION_SECONDS);
    const nowSeconds = performance.now() * 0.001;
    const nowMs = performance.now();
    for (const remote of remotes.values()) {
      remote.current.lerp(remote.target, alpha);
      remote.currentRotation.yaw = dampAngle(remote.currentRotation.yaw, remote.targetRotation.yaw, alpha);
      remote.currentRotation.pitch = THREE.MathUtils.lerp(remote.currentRotation.pitch, remote.targetRotation.pitch, alpha);
      remote.currentRotation.roll = THREE.MathUtils.lerp(remote.currentRotation.roll, remote.targetRotation.roll, alpha);
      remote.group.position.copy(remote.current);
      remote.group.rotation.set(remote.currentRotation.pitch, remote.currentRotation.yaw, remote.currentRotation.roll, 'YXZ');
      remote.lightController.update(nowSeconds, serverTime?.nightLightFactor ?? 0);
      if (remote.label) remote.label.position.set(0, 55, 0);
      if (nowMs - remote.lastTrailMs >= MAP_TRAIL_INTERVAL_MS) {
        remote.lastTrailMs = nowMs;
        pushTrailPoint(remote.trail, remote.current, remote.display?.altitude, remote.display?.heading, nowMs);
      }
    }
  }

  function updateMapAircraft() {
    const ownAltitude = Math.max(0, Math.round((state.position.y - terrainHeight(state.position.x, state.position.z) - AIRCRAFT_GROUND_OFFSET) * 3.28084));
    const nowMs = performance.now();
    if (nowMs - localTrailLastMs >= MAP_TRAIL_INTERVAL_MS) {
      localTrailLastMs = nowMs;
      pushTrailPoint(localTrail, state.position, ownAltitude, normalizeHeading(-THREE.MathUtils.radToDeg(state.yaw)), nowMs);
    }
    const aircraft = [{
      playerId: playerId || 'local',
      aircraftCode,
      callsign,
      isSelf: true,
      position: { x: state.position.x, y: state.position.y, z: state.position.z },
      latitude: state.position.z / 111000,
      longitude: state.position.x / 111000,
      heading: normalizeHeading(-THREE.MathUtils.radToDeg(state.yaw)),
      pitch: state.pitch || 0,
      roll: state.roll || 0,
      altitude: ownAltitude,
      speed: Math.round((state.currentIAS || Math.abs(state.speed || 0) * KT_PER_MPS)),
      altitudeAGL: Math.round(state.altitudeAGL ?? ownAltitude),
      groundSpeedKts: Math.round(state.groundSpeedKts || state.currentIAS || Math.abs(state.speed || 0) * KT_PER_MPS),
      wheelSpeedKts: Math.round(state.wheelSpeedKts || 0),
      verticalSpeed: Math.round(state.verticalSpeed || 0),
      onGround: Boolean(state.grounded),
      flightPhase: state.flightPhase || '',
      connectionStatus: offline ? 'local' : 'online',
      lastUpdateTime: Date.now(),
      trail: trailForMap(localTrail)
    }];

    for (const remote of remotes.values()) {
      const display = remote.display || {};
      const heading = normalizeHeading(-THREE.MathUtils.radToDeg(remote.currentRotation.yaw));
      aircraft.push({
        playerId: remote.playerId,
        aircraftCode: display.aircraftCode || 'A20N',
        callsign: display.callsign || display.aircraftCode || 'A20N',
        isSelf: false,
        position: { x: remote.current.x, y: remote.current.y, z: remote.current.z },
        latitude: display.latitude,
        longitude: display.longitude,
        heading,
        pitch: remote.currentRotation.pitch,
        roll: remote.currentRotation.roll,
        altitude: Math.round(display.altitude || 0),
        speed: Math.round(display.speed || 0),
        verticalSpeed: Math.round(display.verticalSpeed || 0),
        onGround: Boolean(display.onGround),
        connectionStatus: display.connectionStatus || 'online',
        lastUpdateTime: display.lastUpdateTime || 0,
        serverAgeMs: display.serverAgeMs || 0,
        bearingFromSelf: bearingFromSelf(state.position.x, state.position.z, remote.current.x, remote.current.z),
        distanceNm: Math.hypot(remote.current.x - state.position.x, remote.current.z - state.position.z) / 1852,
        trail: trailForMap(remote.trail)
      });
    }
    state.multiplayerAircraft = aircraft;
  }

  function localStatePayload() {
    const altitude = Math.max(0, Math.round((state.position.y - terrainHeight(state.position.x, state.position.z) - AIRCRAFT_GROUND_OFFSET) * 3.28084));
    return {
      position: { x: state.position.x, y: state.position.y, z: state.position.z },
      rotation: { yaw: state.yaw, pitch: state.pitch, roll: state.roll },
      latitude: state.position.z / 111000,
      longitude: state.position.x / 111000,
      heading: normalizeHeading(-THREE.MathUtils.radToDeg(state.yaw)),
      pitch: state.pitch || 0,
      roll: state.roll || 0,
      altitude,
      speed: Math.round(state.currentIAS || Math.abs(state.speed || 0) * KT_PER_MPS),
      altitudeAGL: Math.round(state.altitudeAGL ?? altitude),
      groundSpeedKts: Math.round(state.groundSpeedKts || state.currentIAS || Math.abs(state.speed || 0) * KT_PER_MPS),
      wheelSpeedKts: Math.round(state.wheelSpeedKts || 0),
      verticalSpeed: Math.round(state.verticalSpeed || 0),
      onGround: Boolean(state.grounded),
      flightPhase: state.flightPhase || '',
      stallFactor: state.stallFactor || 0,
      gearState: state.grounded ? 'down' : 'up',
      flapState: 'managed',
      lightsState: {
        navigation: true,
        antiCollision: true,
        landing: state.grounded || altitude < 2500
      },
      antiCollisionLightState: true,
      throttle: state.throttle || 0,
      engineState: state.engineN1Average > 12 || state.throttle > 0.05 ? 'running' : 'idle'
    };
  }

  return {
    connect,
    update,
    dispose,
    getServerTime,
    getUfoEvent,
    getLightingCheckReport,
    get playerId() {
      return playerId;
    },
    get aircraftCode() {
      return aircraftCode;
    }
  };
}

async function postJson(url, payload, metadata = {}) {

  return requestJson(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
    cache: 'no-store'
  }, metadata);
}

function tintRemoteAircraft(group, index) {
  const accents = [0x4b8ed6, 0xe0a145, 0x65b76a, 0xd86464, 0x8e7bd8, 0xd7c456];
  const accent = accents[index % accents.length];
  group.traverse(object => {
    if (!object.isMesh || !object.material?.color) return;
    if (object.name.includes('cheatline') || object.name.includes('tail') || object.name.includes('livery')) {
      object.material = object.material.clone();
      object.material.color.setHex(accent);
      object.material.needsUpdate = true;
    }
  });
}

function createAircraftLabel(text) {
  const texture = createLabelTexture(text, 'ALT ----');
  const material = new THREE.SpriteMaterial({
    map: texture,
    transparent: true,
    depthWrite: false,
    depthTest: false,
    toneMapped: false
  });
  const sprite = new THREE.Sprite(material);
  sprite.scale.set(86, 28, 1);
  sprite.renderOrder = 80;
  sprite.userData.labelTexture = texture;
  return sprite;
}

function updateAircraftLabel(sprite, player) {
  const altitude = Math.round(player.altitude || 0);
  const trend = verticalTrendSymbol(player.verticalSpeed || 0);
  const stale = player.connectionStatus === 'stale';
  const line2 = stale ? 'LOST' : `${trend ? `${trend} ` : ''}ALT ${altitude} FT`;
  const line1 = `${player.aircraftCode || 'A20N'}${stale ? ' STALE' : ''}`;
  const key = `${line1}|${line2}`;
  if (sprite.userData.labelText === key) return;
  sprite.userData.labelText = key;
  sprite.material.map?.dispose?.();
  sprite.material.map = createLabelTexture(line1, line2);
  sprite.material.needsUpdate = true;
}

function createLabelTexture(line1, line2) {
  const canvas = document.createElement('canvas');
  canvas.width = 256;
  canvas.height = 80;
  const ctx = canvas.getContext('2d');
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = 'rgba(3, 10, 14, 0.74)';
  roundRect(ctx, 8, 8, 240, 64, 10);
  ctx.fill();
  ctx.strokeStyle = 'rgba(116, 218, 255, 0.86)';
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.fillStyle = '#dff7ff';
  ctx.font = '800 25px ui-monospace, SFMono-Regular, Menlo, monospace';
  ctx.fillText(line1, 20, 36);
  ctx.fillStyle = '#ffd166';
  ctx.font = '760 18px ui-monospace, SFMono-Regular, Menlo, monospace';
  ctx.fillText(line2, 20, 59);
  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.needsUpdate = true;
  return texture;
}

function roundRect(ctx, x, y, width, height, radius) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + width, y, x + width, y + height, radius);
  ctx.arcTo(x + width, y + height, x, y + height, radius);
  ctx.arcTo(x, y + height, x, y, radius);
  ctx.arcTo(x, y, x + width, y, radius);
  ctx.closePath();
}

function dampAngle(current, target, alpha) {
  const delta = Math.atan2(Math.sin(target - current), Math.cos(target - current));
  return current + delta * alpha;
}

function normalizeHeading(value) {
  return ((value % 360) + 360) % 360;
}

function verticalTrendSymbol(verticalSpeed) {
  if (verticalSpeed > 180) return 'UP';
  if (verticalSpeed < -180) return 'DN';
  return '';
}

function pushTrailPoint(trail, position, altitude = 0, heading = 0, nowMs = performance.now(), force = false) {
  const last = trail[trail.length - 1];
  if (
    !force &&
    last &&
    nowMs - last.timeMs < MAP_TRAIL_INTERVAL_MS &&
    Math.hypot(position.x - last.x, position.z - last.z) < MAP_TRAIL_MIN_DISTANCE
  ) {
    return;
  }
  trail.push({
    x: position.x,
    y: position.y,
    z: position.z,
    altitude: Math.round(altitude || 0),
    heading: normalizeHeading(heading || 0),
    timeMs: nowMs
  });
  pruneTrail(trail, nowMs);
}

function pruneTrail(trail, nowMs = performance.now()) {
  while (trail.length > MAP_TRAIL_MAX_POINTS) trail.shift();
  while (trail.length && nowMs - trail[0].timeMs > MAP_TRAIL_MAX_AGE_MS) trail.shift();
}

function trailForMap(trail) {
  const nowMs = performance.now();
  pruneTrail(trail, nowMs);
  return trail.map(point => ({
    x: point.x,
    y: point.y,
    z: point.z,
    altitude: point.altitude,
    heading: point.heading,
    ageMs: nowMs - point.timeMs
  }));
}

function bearingFromSelf(selfX, selfZ, targetX, targetZ) {
  return normalizeHeading(THREE.MathUtils.radToDeg(Math.atan2(targetX - selfX, -(targetZ - selfZ))));
}

function hashPhase(text) {
  let hash = 0;
  for (let i = 0; i < text.length; i++) hash = (hash * 31 + text.charCodeAt(i)) | 0;
  return Math.abs(hash % 1000) / 1000;
}
